codeunit 135161 "Cloud Mig Country Tables"
{
    procedure GetTablesThatShouldBeCloudMigrated(var ListOfTablesToMigrate: List of [Integer])
    begin
        ListOfTablesToMigrate.Add(18686); // Database::"Act Applicable"
        ListOfTablesToMigrate.Add(20156); // Database::"Action Comment" 
        ListOfTablesToMigrate.Add(20158); // Database::"Action Concatenate Line" 
        ListOfTablesToMigrate.Add(20157); // Database::"Action Concatenate" 
        ListOfTablesToMigrate.Add(20159); // Database::"Action Container" 
        ListOfTablesToMigrate.Add(20160); // Database::"Action Convert Case" 
        ListOfTablesToMigrate.Add(20161); // Database::"Action Date Calculation" 
        ListOfTablesToMigrate.Add(20162); // Database::"Action Date To DateTime" 
        ListOfTablesToMigrate.Add(20165); // Database::"Action Ext. Substr. From Index" 
        ListOfTablesToMigrate.Add(20166); // Database::"Action Ext. Substr. From Pos." 
        ListOfTablesToMigrate.Add(20163); // Database::"Action Extract Date Part" 
        ListOfTablesToMigrate.Add(20164); // Database::"Action Extract DateTime Part" 
        ListOfTablesToMigrate.Add(20167); // Database::"Action Find Date Interval" 
        ListOfTablesToMigrate.Add(20168); // Database::"Action Find Substring" 
        ListOfTablesToMigrate.Add(20171); // Database::"Action If Statement" 
        ListOfTablesToMigrate.Add(20172); // Database::"Action Length Of String" 
        ListOfTablesToMigrate.Add(20173); // Database::"Action Loop N Times" 
        ListOfTablesToMigrate.Add(20174); // Database::"Action Loop Through Rec. Field" 
        ListOfTablesToMigrate.Add(20175); // Database::"Action Loop Through Records" 
        ListOfTablesToMigrate.Add(20176); // Database::"Action Loop With Condition" 
        ListOfTablesToMigrate.Add(20177); // Database::"Action Message" 
        ListOfTablesToMigrate.Add(20178); // Database::"Action Number Calculation" 
        ListOfTablesToMigrate.Add(20180); // Database::"Action Number Expr. Token" 
        ListOfTablesToMigrate.Add(20179); // Database::"Action Number Expression" 
        ListOfTablesToMigrate.Add(20181); // Database::"Action Replace Substring"
        ListOfTablesToMigrate.Add(20182); // Database::"Action Round Number"
        ListOfTablesToMigrate.Add(20183); // Database::"Action Set Variable"
        ListOfTablesToMigrate.Add(20185); // Database::"Action String Expr. Token"
        ListOfTablesToMigrate.Add(20184); // Database::"Action String Expression"
        ListOfTablesToMigrate.Add(18807); // Database::"Allowed NOC"
        ListOfTablesToMigrate.Add(18687); // Database::"Allowed Sections"
        ListOfTablesToMigrate.Add(18466); // Database::"Applied Delivery Challan Entry"
        ListOfTablesToMigrate.Add(18467); // Database::"Applied Delivery Challan"
        ListOfTablesToMigrate.Add(18543); // Database::"Assessee Code"
        ListOfTablesToMigrate.Add(18244); // Database::"Bank Charge Deemed Value Setup"
        ListOfTablesToMigrate.Add(18243); // Database::"Bank Charge"
        ListOfTablesToMigrate.Add(18544); // Database::"Concessional Code"
        ListOfTablesToMigrate.Add(18661); // Database::"Customer Allowed Sections"
        ListOfTablesToMigrate.Add(18808); // Database::"Customer Concessional Code"
        ListOfTablesToMigrate.Add(18545); // Database::"Deductor Category"
        ListOfTablesToMigrate.Add(18468); // Database::"Delivery Challan Header"
        ListOfTablesToMigrate.Add(18469); // Database::"Delivery Challan Line"
        ListOfTablesToMigrate.Add(18317); // Database::"Detailed Cr. Adjstmnt. Entry"
        ListOfTablesToMigrate.Add(18200); // Database::"Detailed GST Dist. Entry"
        ListOfTablesToMigrate.Add(18000); // Database::"Detailed GST Entry Buffer"
        ListOfTablesToMigrate.Add(18016); // Database::"Detailed GST Ledger Entry Info"
        ListOfTablesToMigrate.Add(18001); // Database::"Detailed GST Ledger Entry"
        ListOfTablesToMigrate.Add(18201); // Database::"Dist. Component Amount"
        ListOfTablesToMigrate.Add(18017); // Database::"E-Comm. Merchant"
        ListOfTablesToMigrate.Add(18015); // Database::"E-Commerce Merchant"
        ListOfTablesToMigrate.Add(20232); // Database::"Entity Attribute Mapping"
        ListOfTablesToMigrate.Add(18631); // Database::"FA Accounting Period Inc. Tax"
        ListOfTablesToMigrate.Add(18632); // Database::"Fixed Asset Block"
        ListOfTablesToMigrate.Add(18633); // Database::"Fixed Asset Shift"
        ListOfTablesToMigrate.Add(18601); // Database::"Gate Entry Attachment"
        ListOfTablesToMigrate.Add(18602); // Database::"Gate Entry Comment Line"
        ListOfTablesToMigrate.Add(18603); // Database::"Gate Entry Header"
        ListOfTablesToMigrate.Add(18604); // Database::"Gate Entry Line"
        ListOfTablesToMigrate.Add(18550); // Database::"Gen. Journal Narration"
        ListOfTablesToMigrate.Add(18326); // Database::"GST Adjustment Buffer"
        ListOfTablesToMigrate.Add(18430); // Database::"GST Application Buffer"
        ListOfTablesToMigrate.Add(18002); // Database::"GST Claim Setoff"
        ListOfTablesToMigrate.Add(18202); // Database::"GST Component Distribution"
        ListOfTablesToMigrate.Add(18318); // Database::"GST Credit Adjustment Journal"
        ListOfTablesToMigrate.Add(18203); // Database::"GST Distribution Header"
        ListOfTablesToMigrate.Add(18204); // Database::"GST Distribution Line"
        ListOfTablesToMigrate.Add(18004); // Database::"GST Group"
        ListOfTablesToMigrate.Add(18324); // Database::"GST Journal Batch" 
        ListOfTablesToMigrate.Add(18325); // Database::"GST Journal Line"
        ListOfTablesToMigrate.Add(18323); // Database::"GST Journal Template"
        ListOfTablesToMigrate.Add(18005); // Database::"GST Ledger Entry"
        ListOfTablesToMigrate.Add(18319); // Database::"GST Liability Adjustment"
        ListOfTablesToMigrate.Add(18320); // Database::"GST Liability Buffer"
        ListOfTablesToMigrate.Add(18470); // Database::"GST Liability Line"
        ListOfTablesToMigrate.Add(18322); // Database::"GST Payment Buffer Details"
        ListOfTablesToMigrate.Add(18205); // Database::"GST Payment Buffer"
        ListOfTablesToMigrate.Add(18006); // Database::"GST Posting Buffer" 
        ListOfTablesToMigrate.Add(18007); // Database::"GST Posting Setup"
        ListOfTablesToMigrate.Add(18282); // Database::"GST Recon. Mapping"
        ListOfTablesToMigrate.Add(18281); // Database::"GST Reconcilation Line"
        ListOfTablesToMigrate.Add(18280); // Database::"GST Reconcilation"
        ListOfTablesToMigrate.Add(18008); // Database::"GST Registration Nos."
        ListOfTablesToMigrate.Add(18013); // Database::"GST Setup"
        ListOfTablesToMigrate.Add(18245); // Database::"GST TDS/TCS Entry"
        ListOfTablesToMigrate.Add(18390); // Database::"GST Tracking Entry"
        ListOfTablesToMigrate.Add(18009); // Database::"HSN/SAC"
        ListOfTablesToMigrate.Add(18206); // Database::"ISD Ledger"
        ListOfTablesToMigrate.Add(18247); // Database::"Journal Bank Charges"
        ListOfTablesToMigrate.Add(18546); // Database::"Ministry"
        ListOfTablesToMigrate.Add(18930); // Database::"Journal Voucher Posting Setup"
        ListOfTablesToMigrate.Add(20140); // Database::"Lookup Field Filter"
        ListOfTablesToMigrate.Add(20141); // Database::"Lookup Field Sorting"
        ListOfTablesToMigrate.Add(20142); // Database::"Lookup Table Filter"
        ListOfTablesToMigrate.Add(20143); // Database::"Lookup Table Sorting"
        ListOfTablesToMigrate.Add(20186); // Database::"Script Action"
        ListOfTablesToMigrate.Add(18815); // Database::"Sales Line Buffer TCS On Pmt."
        ListOfTablesToMigrate.Add(18471); // Database::"Multiple Subcon. Order Details"
        ListOfTablesToMigrate.Add(18551); // Database::Party
        ListOfTablesToMigrate.Add(18207); // "Posted GST Distribution Header"
        ListOfTablesToMigrate.Add(18208); // "Posted GST Distribution Line"
        ListOfTablesToMigrate.Add(18283); // "Periodic GSTR-2A Data"
        ListOfTablesToMigrate.Add(18284); // "Posted GST Reconciliation"
        ListOfTablesToMigrate.Add(18321); // "Posted GST Liability Adj."
        ListOfTablesToMigrate.Add(18472); // "Posted Applied DeliveryChallan"
        ListOfTablesToMigrate.Add(18473); // "Posted GST Liability Line"
        ListOfTablesToMigrate.Add(18248); // "Posted Jnl. Bank Charges"
        ListOfTablesToMigrate.Add(18552); // "Posting No. Series"
        ListOfTablesToMigrate.Add(18605); // "Posted Gate Entry Attachment"
        ListOfTablesToMigrate.Add(18606); // "Posted Gate Entry Header"
        ListOfTablesToMigrate.Add(18607); // "Posted Gate Entry Line"
        ListOfTablesToMigrate.Add(18933); // "Posted Narration"
        ListOfTablesToMigrate.Add(18209); // "Posted Settlement Entries"
        ListOfTablesToMigrate.Add(18011); // "Reference Invoice No."
        ListOfTablesToMigrate.Add(18012); // "Retrun & Reco. Components"
        ListOfTablesToMigrate.Add(20233); // "Record Attribute Mapping"
        ListOfTablesToMigrate.Add(18608); // "Service Entity Type"
        ListOfTablesToMigrate.Add(18350); // "Service Transfer Header"
        ListOfTablesToMigrate.Add(18351); // "Service Transfer Line"
        ListOfTablesToMigrate.Add(18352); // "Service Transfer Rcpt. Header"
        ListOfTablesToMigrate.Add(18353); // "Service Transfer Rcpt. Line"
        ListOfTablesToMigrate.Add(18354); // "Service Transfer Shpt. Header"
        ListOfTablesToMigrate.Add(18355); // "Service Transfer Shpt. Line"
        ListOfTablesToMigrate.Add(18547); // "State"
        ListOfTablesToMigrate.Add(18474); // "Sub. Comp. Rcpt. Header"
        ListOfTablesToMigrate.Add(18475); // "Sub. Comp. Rcpt. Line"
        ListOfTablesToMigrate.Add(18476); // "Subcon. Delivery Challan Line"
        ListOfTablesToMigrate.Add(18477); // "Subcontractor Delivery Challan"
        ListOfTablesToMigrate.Add(18478); // "Sub Order Comp. List Vend"
        ListOfTablesToMigrate.Add(18479); // "Sub Order Component List"
        ListOfTablesToMigrate.Add(18809); // "T.C.A.N. No."
        ListOfTablesToMigrate.Add(18548); // "TAN Nos."
        ListOfTablesToMigrate.Add(18549); // "Tax Accounting Period"
        ListOfTablesToMigrate.Add(20234); // "Tax Attribute Value Mapping"
        ListOfTablesToMigrate.Add(18810); // "TCS Entry"
        ListOfTablesToMigrate.Add(18811); // "TCS Nature Of Collection"
        ListOfTablesToMigrate.Add(18813); // "TCS Posting Setup"
        ListOfTablesToMigrate.Add(18814); // "TCS Setup"
        ListOfTablesToMigrate.Add(18872); // "TCS Challan Register"
        ListOfTablesToMigrate.Add(18685); // "Acknowledgement Setup"
        ListOfTablesToMigrate.Add(18688); // "TDS Concessional Code"
        ListOfTablesToMigrate.Add(18689); // "TDS Entry"
        ListOfTablesToMigrate.Add(18690); // "TDS Nature Of Remittance"
        ListOfTablesToMigrate.Add(18691); // "TDS Posting Setup"
        ListOfTablesToMigrate.Add(18692); // "TDS Section"
        ListOfTablesToMigrate.Add(18693); // "TDS Setup"
        ListOfTablesToMigrate.Add(18662); // "TDS Customer Concessional Code"
        ListOfTablesToMigrate.Add(18014); // "Transfer Buffer"
        ListOfTablesToMigrate.Add(18932); // "Voucher Posting Credit Account"
        ListOfTablesToMigrate.Add(18929); // "Voucher Posting Debit Account"
        ListOfTablesToMigrate.Add(20144); // "Script Symbol Lookup"
        ListOfTablesToMigrate.Add(18766); // Database::"Provisional Entry"
        ListOfTablesToMigrate.Add(20200); // Database::"Script Context"
        ListOfTablesToMigrate.Add(20201); // Database::"Script Editor Line"
        ListOfTablesToMigrate.Add(20202); // Database::"Script Record Variable"
        ListOfTablesToMigrate.Add(20131); // Database::"Script Symbol Member Value"
        ListOfTablesToMigrate.Add(20132); // Database::"Script Symbol Value"
        ListOfTablesToMigrate.Add(20130); // Database::"Script Symbol"
        ListOfTablesToMigrate.Add(20203); // Database::"Script Variable"
        ListOfTablesToMigrate.Add(20283); // Database::"Switch Case"
        ListOfTablesToMigrate.Add(20284); // Database::"Switch Statement"
        ListOfTablesToMigrate.Add(20256); // Database::"Tax Acc. Period Setup"
        ListOfTablesToMigrate.Add(20242); // Database::"Tax Attribute Value"
        ListOfTablesToMigrate.Add(20241); // Database::"Tax Attribute"
        ListOfTablesToMigrate.Add(20286); // Database::"Tax Component Expr. Token"
        ListOfTablesToMigrate.Add(20285); // Database::"Tax Component Expression"
        ListOfTablesToMigrate.Add(20248); // Database::"Tax Component Formula Token"
        ListOfTablesToMigrate.Add(20247); // Database::"Tax Component Formula"
        ListOfTablesToMigrate.Add(20301); // Database::"Tax Component Summary"
        ListOfTablesToMigrate.Add(20246); // Database::"Tax Component"
        ListOfTablesToMigrate.Add(20364); // Database::"Tax Engine Notification"
        ListOfTablesToMigrate.Add(20257); // Database::"Tax Entity"
        ListOfTablesToMigrate.Add(20335); // Database::"Tax Insert Record Field"
        ListOfTablesToMigrate.Add(20334); // Database::"Tax Insert Record"
        ListOfTablesToMigrate.Add(20337); // Database::"Tax Posting Keys Buffer"
        ListOfTablesToMigrate.Add(20338); // Database::"Tax Posting Setup"
        ListOfTablesToMigrate.Add(20252); // Database::"Tax Rate Column Setup"
        ListOfTablesToMigrate.Add(20254); // Database::"Tax Rate Filter"
        ListOfTablesToMigrate.Add(20253); // Database::"Tax Rate Value"
        ListOfTablesToMigrate.Add(20251); // Database::"Tax Rate"
        ListOfTablesToMigrate.Add(20258); // Database::"Tax Type"
        ListOfTablesToMigrate.Add(20287); // Database::"Tax Table Relation"
        ListOfTablesToMigrate.Add(20191); // Database::"Tax Test Condition Item"
        ListOfTablesToMigrate.Add(20190); // Database::"Tax Test Condition"
        ListOfTablesToMigrate.Add(20261); // Database::"Tax Transaction Value"
        ListOfTablesToMigrate.Add(20362); // Database::"Tax Type Archival Log Entry"
        ListOfTablesToMigrate.Add(20257); // Database::"Tax Type"
        ListOfTablesToMigrate.Add(20306); // Database::"Tax Use Case"
        ListOfTablesToMigrate.Add(18869); // Database::"TCS Journal Batch"
        ListOfTablesToMigrate.Add(18870); // Database::"TCS Journal Line"
        ListOfTablesToMigrate.Add(18871); // Database::"TCS Journal Template"
        ListOfTablesToMigrate.Add(18749); // Database::"TDS Challan Register"
        ListOfTablesToMigrate.Add(18746); // Database::"TDS Journal Batch"
        ListOfTablesToMigrate.Add(18747); // Database::"TDS Journal Line"
        ListOfTablesToMigrate.Add(18748); // Database::"TDS Journal Template"
        ListOfTablesToMigrate.Add(20363); // Database::"Upgraded Tax Types"
        ListOfTablesToMigrate.Add(20361); // Database::"Upgraded Use Cases"
        ListOfTablesToMigrate.Add(20360); // Database::"Use Case Archival Log Entry"
        ListOfTablesToMigrate.Add(20307); // Database::"Use Case Attribute Mapping"
        ListOfTablesToMigrate.Add(20308); // Database::"Use Case Component Calculation"
        ListOfTablesToMigrate.Add(20309); // Database::"Use Case Rate Column Relation"
        ListOfTablesToMigrate.Add(20295); // Database::"Use Case Tree Node"
        ListOfTablesToMigrate.Add(18510); // Database::"Charge Group Header"
        ListOfTablesToMigrate.Add(18511); // Database::"Charge Group Line"
    end;
}