table COMPANY
	isHidden
	lineageTag: 8393b496-4c4d-4006-b681-5f1e5ccf11d2

	measure 'Company Label' = VALUES(COMPANY[COMPANY])
		isHidden
		lineageTag: 4a9fbcfd-107e-4ae1-8b28-36e726b7fe4a

		changedProperty = IsHidden

	column COMPANY
		dataType: string
		isHidden
		lineageTag: 3cb6db28-dc23-4604-a250-de0532c610fe
		summarizeBy: none
		sourceColumn: COMPANY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition COMPANY = m
		mode: import
		queryGroup: 'Parameters and Functions'
		source = "Cronus" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Text

