table Items
	lineageTag: cf3c7b76-12cc-42e5-95b9-91b471b42ef1

	column 'Item No.'
		dataType: string
		lineageTag: 5923f93a-32dd-412d-9c20-f905e1b654ff
		summarizeBy: none
		sourceColumn: Item No.

		annotation SummarizationSetBy = Automatic

	column 'Item Description'
		dataType: string
		lineageTag: ef6ff404-792b-4346-aba5-e61ad681336e
		summarizeBy: none
		sourceColumn: Item Description

		annotation SummarizationSetBy = Automatic

	column 'Item Base Unit of Measure'
		dataType: string
		lineageTag: f218117c-ec1b-414f-b883-e7ddf7929661
		summarizeBy: none
		sourceColumn: Item Base Unit of Measure

		annotation SummarizationSetBy = Automatic

	column 'Item Unit Cost (LCY)'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: b0fefbe3-c1db-4b6b-a0ea-95eeec492032
		summarizeBy: sum
		sourceColumn: Item Unit Cost (LCY)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-AU"}

	column 'Item Inventory Posting Group'
		dataType: string
		lineageTag: a41be338-13df-4168-b859-4d3a12681519
		summarizeBy: none
		sourceColumn: Item Inventory Posting Group

		annotation SummarizationSetBy = Automatic

	column 'Item Routing No.'
		dataType: string
		isHidden
		lineageTag: 896289da-7a17-43f3-8d2c-591f08e523bd
		summarizeBy: none
		sourceColumn: Item Routing No.

		annotation SummarizationSetBy = Automatic

	column 'Item Production BOM No.'
		dataType: string
		isHidden
		lineageTag: 42cf03b3-77af-4e82-bb1a-bb9ee66c3c01
		summarizeBy: none
		sourceColumn: Item Production BOM No.

		annotation SummarizationSetBy = Automatic

	column 'Item Replenishment System'
		dataType: string
		isHidden
		lineageTag: c744183c-de54-4e0d-a17e-869f50d74724
		summarizeBy: none
		sourceColumn: Item Replenishment System

		annotation SummarizationSetBy = Automatic

	column 'Item Single-Level Cap. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 01b58fac-291f-4fa9-8de1-c07131174d5c
		summarizeBy: sum
		sourceColumn: Item Single-Level Cap. Ovhd Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Capacity Cost'
		dataType: double
		isHidden
		lineageTag: b55eae15-ff45-4080-8018-6d4963d0a258
		summarizeBy: sum
		sourceColumn: Item Single-Level Capacity Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Material Cost'
		dataType: double
		isHidden
		lineageTag: 9e4d9a6c-f91c-4511-b708-6c69ebb95b9a
		summarizeBy: sum
		sourceColumn: Item Single-Level Material Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Mfg. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 5fbfe6aa-d449-4c17-9295-9e225b43dde2
		summarizeBy: sum
		sourceColumn: Item Single-Level Mfg. Ovhd Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Subcontrd. Cost'
		dataType: double
		isHidden
		lineageTag: a40935f8-c04d-4041-9100-36e9367d0d26
		summarizeBy: sum
		sourceColumn: Item Single-Level Subcontrd. Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Lvl Mat. Non-Invt. Cost'
		dataType: double
		isHidden
		lineageTag: e02d889e-fa08-4bc5-8030-357f262a1bde
		summarizeBy: sum
		sourceColumn: Item Single-Lvl Mat. Non-Invt. Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Cap. Overhead Cost'
		dataType: double
		isHidden
		lineageTag: 7645a22a-8c6f-4bb6-bb1f-6feafa8c263c
		summarizeBy: sum
		sourceColumn: Item Rolled-up Cap. Overhead Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Capacity Cost'
		dataType: double
		isHidden
		lineageTag: 74b49137-1ba8-4d8b-957f-dc042d3dbef5
		summarizeBy: sum
		sourceColumn: Item Rolled-up Capacity Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mat. Non-Invt. Cost'
		dataType: double
		isHidden
		lineageTag: dd0194a9-44cd-4b98-803e-4e977d0447ad
		summarizeBy: sum
		sourceColumn: Item Rolled-up Mat. Non-Invt. Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Material Cost'
		dataType: double
		isHidden
		lineageTag: 747f0638-610c-46af-aa58-556b043239f4
		summarizeBy: sum
		sourceColumn: Item Rolled-up Material Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mfg. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 4d729ec7-18e4-4cef-8bde-8f1dc80db59c
		summarizeBy: sum
		sourceColumn: Item Rolled-up Mfg. Ovhd Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Subcontracted Cost'
		dataType: double
		isHidden
		lineageTag: 6fc525ef-e648-4057-9784-fc5a6341ddbf
		summarizeBy: sum
		sourceColumn: Item Rolled-up Subcontracted Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Scrap %'
		dataType: double
		isHidden
		lineageTag: 64d051c3-dce4-4c0f-a563-1670dbba4f32
		summarizeBy: sum
		sourceColumn: Item Scrap %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Category Code'
		dataType: string
		lineageTag: 22ebda4e-b3a3-4fd6-a6aa-cc56cb470d41
		summarizeBy: none
		sourceColumn: Item Category Code

		annotation SummarizationSetBy = Automatic

	column 'Item Category Description'
		dataType: string
		lineageTag: 16a0b937-74ae-4d39-b244-a3c022a36fa9
		summarizeBy: none
		sourceColumn: Item Category Description

		annotation SummarizationSetBy = Automatic

	column 'Item No. & Description'
		dataType: string
		lineageTag: 582f9e71-4550-4788-844f-1032004ac612
		summarizeBy: none
		sourceColumn: Item No. & Description

		annotation SummarizationSetBy = Automatic

	column 'Type Key'
		dataType: string
		isHidden
		isKey
		lineageTag: d609fbcf-001a-44c8-a630-f976ce12a58e
		summarizeBy: none
		sourceColumn: Type Key

		annotation SummarizationSetBy = Automatic

	partition Items = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY, API_ENDPOINT, []),
				    TableData = Source{[Name = "items", Signature = "table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(
				        TableData,
				        {
				            {"itemNo", "Item No."},
				            {"unitCost", "Item Unit Cost (LCY)"},
				            {"itemCategoryCode", "Item Category Code"},
				            {"itemCategoryDescription", "Item Category Description"},
				            {"baseUnitofMeasure", "Item Base Unit of Measure"},
				            {"itemDescription", "Item Description"},
				            {"inventoryPostingGroup", "Item Inventory Posting Group"},
				            {"routingNo", "Item Routing No."},
				            {"productionBomNo", "Item Production BOM No."},
				            {"replenishmentSystem", "Item Replenishment System"},
				            {"singleLevelCapOvhdCost", "Item Single-Level Cap. Ovhd Cost"},
				            {"singleLevelCapacityCost", "Item Single-Level Capacity Cost"},
				            {"singleLevelMaterialCost", "Item Single-Level Material Cost"},
				            {"singleLevelMfgOvhdCost", "Item Single-Level Mfg. Ovhd Cost"},
				            {"singleLevelSubcontrdCost", "Item Single-Level Subcontrd. Cost"},
				            {"singleLvlMatNonInvtCost", "Item Single-Lvl Mat. Non-Invt. Cost"},
				            {"rolledUpCapacityCost", "Item Rolled-up Capacity Cost"},
				            {"rolledUpCapOverheadCost", "Item Rolled-up Cap. Overhead Cost"},
				            {"rolledUpMatNonInvtCost", "Item Rolled-up Mat. Non-Invt. Cost"},
				            {"rolledUpMaterialCost", "Item Rolled-up Material Cost"},
				            {"rolledUpMfgOvhdCost", "Item Rolled-up Mfg. Ovhd Cost"},
				            {"rolledUpSubcontractedCost", "Item Rolled-up Subcontracted Cost"},
				            {"scrapPrc", "Item Scrap %"}
				        }
				    ),
				    #"Added Custom" = Table.AddColumn(
				        #"Renamed Columns", "Item No. & Description", each [#"Item No."] & " " & [Item Description], type text
				    ),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom", {"ETag"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns", {{"Item Unit Cost (LCY)", Currency.Type}}),
				    #"Added Type Key" = Table.AddColumn(#"Changed Type", "Type Key", each "Item" & " " & [#"Item No."], type text)
				in
				    #"Added Type Key"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

