codeunit 103347 "WMS Reserv. Entry Ref. Mgmt"
{
    // Unsupported version tags:
    // NA: Skipped for Execution
    // ES: Skipped for Execution
    // DE: Skipped for Execution
    // 
    // ******************************************************************************************
    // *** This code has been generated by REPORT::"Create Reference Mgmt" to contain
    // *** the reference data hardcoded for every iteration.
    // *** All modifications to this codeunit have to be done in that report, not here !
    // ***
    // *** Source company for reference data: CRONUS International Ltd.
    // ***
    // ******************************************************************************************


    trigger OnRun()
    begin
    end;

    var
        TestScriptMgmt: Codeunit "WMS TestscriptManagement";
        UseCaseNo: Integer;
        TestCaseNo: Integer;
        IterationNo: Integer;
        Offset: Integer;
        TableID: Integer;
        NoOfRecords: Integer;
        NoOfFields: Integer;

    [Scope('OnPrem')]
    procedure Verify(NewUseCaseNo: Integer; NewTestCaseNo: Integer; NewIterationNo: Integer; NewOffset: Integer)
    var
        Sequence: Text;
    begin
        UseCaseNo := NewUseCaseNo;
        TestCaseNo := NewTestCaseNo;
        IterationNo := NewIterationNo;
        Offset := NewOffset;
        TableID := DATABASE::"Reservation Entry";
        Sequence := StrSubstNo('%1-%2-%3', UseCaseNo, TestCaseNo, IterationNo);

        case Sequence of
            '21-12-7':
                begin
                    Test(1, 'WHITE', 20011125D, 37, '1001', 10000, '80002', '', -40, -40, -40, -40, 0, '', '', 'No');
                    Test(1, 'WHITE', 20011125D, 32, '', 1, '80002', '', 40, 40, 40, 40, 0, '', 'LOTNUMBER01', 'Yes');
                    Test(2, 'WHITE', 20011125D, 37, '1001', 10000, '80002', '', -40, -40, -40, -40, 0, '', '', 'No');
                    Test(2, 'WHITE', 20011125D, 32, '', 2, '80002', '', 40, 40, 40, 40, 0, '', 'LOTNUMBER02', 'Yes');
                    Test(3, 'WHITE', 20011125D, 37, '1001', 20000, 'A_TEST', '12', -30, -30, -30, -30, 0, '', '', 'No');
                    Test(3, 'WHITE', 20011125D, 32, '', 6, 'A_TEST', '12', 30, 30, 30, 30, 0, '', '', 'Yes');
                    Test(4, 'WHITE', 20011125D, 37, '1001', 40000, 'T_TEST', 'T1', -1, -1, -1, -1, 0, '', '', 'No');
                    Test(4, 'WHITE', 20011125D, 32, '', 7, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SERIALN0001', '', 'Yes');
                    Test(5, 'WHITE', 20011125D, 37, '1001', 40000, 'T_TEST', 'T1', -1, -1, -1, -1, 0, '', '', 'No');
                    Test(5, 'WHITE', 20011125D, 32, '', 8, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SERIALN0002', '', 'Yes');
                end;
            '21-12-9':
                begin
                    Test(4, 'WHITE', 20011125D, 37, '1001', 40000, 'T_TEST', 'T1', -1, -1, -1, -1, 0, 'SERIALN0001', '', 'No');
                    Test(4, 'WHITE', 20011125D, 32, '', 7, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SERIALN0001', '', 'Yes');
                    Test(5, 'WHITE', 20011125D, 37, '1001', 40000, 'T_TEST', 'T1', -1, -1, -1, -1, 0, 'SERIALN0002', '', 'No');
                    Test(5, 'WHITE', 20011125D, 32, '', 8, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SERIALN0002', '', 'Yes');
                end;
            '21-13-3':
                begin
                    Test(4, 'WHITE', 0D, 39, '106001', 20000, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN02', 'X1', 'Yes');
                    Test(7, 'WHITE', 0D, 39, '106001', 20000, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN04', 'X1', 'Yes');
                    Test(8, 'WHITE', 0D, 39, '106001', 20000, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN03', 'X1', 'Yes');
                    Test(9, 'WHITE', 0D, 39, '106001', 10000, '80002', '', 10, 10, 10, 10, 0, '', 'LOT01', 'Yes');
                    Test(10, 'WHITE', 20011125D, 37, '1001', 10000, 'T_TEST', 'T1', -1, -1, -1, -1, 0, '', '', 'No');
                    Test(10, 'WHITE', 20011125D, 39, '106001', 20000, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN01', 'X1', 'Yes');
                    Test(11, 'WHITE', 20011125D, 37, '1001', 10000, 'T_TEST', 'T1', -1, -1, -1, -1, 0, '', '', 'No');
                    Test(11, 'WHITE', 20011125D, 39, '106001', 20000, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN05', 'X1', 'Yes');
                    Test(12, 'WHITE', 20011125D, 37, '1001', 20000, '80002', '', -10, -10, -10, -10, 0, '', '', 'No');
                    Test(12, 'WHITE', 20011125D, 39, '106001', 10000, '80002', '', 10, 10, 10, 10, 0, '', 'LOT01', 'Yes');
                end;
            '21-13-5':
                begin
                    Test(15, 'WHITE', 0D, 32, '', 5, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN04', 'X1', 'Yes');
                    Test(16, 'WHITE', 0D, 32, '', 6, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN03', 'X1', 'Yes');
                    Test(17, 'WHITE', 20011125D, 32, '', 3, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN05', 'X1', 'Yes');
                    Test(18, 'WHITE', 0D, 32, '', 1, '80002', '', 10, 10, 10, 10, 0, '', 'LOT01', 'Yes');
                end;
            '21-13-7':
                begin
                    Test(21, 'WHITE', 0D, 32, '', 5, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN04', 'X1', 'Yes');
                    Test(24, 'WHITE', 20011125D, 32, '', 3, 'T_TEST', 'T1', 1, 1, 1, 1, 0, 'SN05', 'X1', 'Yes');
                    Test(25, 'WHITE', 0D, 32, '', 1, '80002', '', 9, 9, 9, 9, 0, '', 'LOT01', 'Yes');
                end;
            '22-8-3':
                begin
                    Test(1, 'WHITE', 20011125D, 5407, '101001', 20000, 'A_TEST', '12', -13, -13, -13, -13, 0, '', 'LOT01A', 'No');
                    Test(2, 'WHITE', 20011125D, 5407, '101001', 30000, 'B_TEST', '', -13, -13, -13, -13, 0, '', 'LOT02B', 'No');
                    Test(3, 'WHITE', 20011125D, 5407, '101001', 10000, 'D_PROD', '', -15, -15, -15, -15, 0, '', 'LOT01D', 'No');
                end;
            '28-1-3':
                begin
                    Test(7, 'WHITE', 20011125D, 37, '1001', 10000, '80002', '', -3, -3, -3, -3, 0, '', '', 'No');
                    Test(7, 'WHITE', 20011125D, 5741, '1001', 40000, '80002', '', 3, 3, 3, 3, 0, '', 'LN01', 'Yes');
                    Test(8, 'WHITE', 20011125D, 37, '1001', 20000, '80100', '', -0.6, -0.6, -0.6, -0.6, 0, '', '', 'No');
                    Test(8, 'WHITE', 20011125D, 5741, '1001', 60000, '80100', '', 3, 0.6, 0.6, 0.6, 0, '', 'LT01', 'Yes');
                    Test(9, 'WHITE', 20011125D, 37, '1001', 20000, '80100', '', -2.4, -2.4, -2.4, -2.4, 0, '', '', 'No');
                    Test(9, 'WHITE', 20011125D, 5741, '1001', 50000, '80100', '', 2.4, 2.4, 2.4, 2.4, 0, '', 'LT01', 'Yes');
                    Test(10, 'WHITE', 20011125D, 37, '1001', 30000, '80100', '', -3, -0.6, -0.6, -0.6, 0, '', '', 'No');
                    Test(10, 'WHITE', 20011125D, 5741, '1001', 50000, '80100', '', 0.6, 0.6, 0.6, 0.6, 0, '', 'LT01', 'Yes');
                end;
            '28-1-9':
                Test(1, 'WHITE', 20011125D, 37, '1003', 10000, '80002', '', -3, -3, -3, -3, 0, '', 'LN03', 'No');
            '28-1-11':
                begin
                    Test(2, 'WHITE', 20011125D, 37, '1003', 20000, '80100', '', -17, -3.4, -3.4, -3.4, 0, '', 'LT03', 'No');
                    Test(3, 'WHITE', 20011125D, 37, '1003', 30000, '80100', '', -1, -32, -32, -32, 0, '', 'LT04', 'No');
                end;
            '28-1-15':
                begin
                    Test(4, 'WHITE', 0D, 39, '106003', 20000, '80100', '', 2, 64, 64, 64, 0, '', 'LT04', 'Yes');
                    Test(5, 'WHITE', 0D, 39, '106003', 10000, '80002', '', 1, 35, 35, 35, 0, '', 'LN06', 'Yes');
                end;
            '28-1-17':
                begin
                    Test(4, 'WHITE', 0D, 39, '106003', 20000, '80100', '', 2, 64, 64, 64, 0, '', 'LT04', 'Yes');
                    Test(5, 'WHITE', 0D, 39, '106003', 10000, '80002', '', 1, 35, 35, 35, 0, '', 'LN06', 'Yes');
                end;
            '28-4-3':
                begin
                    Test(1, 'WHITE', 0D, 5406, '101001', 0, 'E_PROD', '', 5, 45, 45, 45, 0, '', 'LE01', 'Yes');
                    Test(2, 'WHITE', 20011124D, 5407, '101001', 20000, 'A_TEST', '12', -5, -65, -65, -65, 0, '', 'LT02', 'No');
                    Test(3, 'WHITE', 20011124D, 5407, '101001', 30000, 'B_TEST', '', -5, -50, -50, -50, 0, '', 'LN01', 'No');
                    Test(4, 'WHITE', 20011124D, 5407, '101001', 10000, 'D_PROD', '', -5, -55, -55, -55, 0, '', 'LS01', 'No');
                end;
            else
                exit;
        end;
    end;

    [Scope('OnPrem')]
    procedure Test(EntryNo: Integer; LocationCode: Code[10]; ShptDate: Date; SrcType: Integer; SourceID: Code[20]; SrcRefNo: Integer; ItemNo: Code[20]; VariantCode: Code[10]; Quantity: Decimal; QuantityBase: Decimal; QtyToHandleBase: Decimal; QtyToInvoiceBase: Decimal; QtyInvoicedBase: Decimal; SerialNo: Code[20]; LotNo: Code[20]; Positive: Text[3])
    var
        ReservationEntry: Record "Reservation Entry";
        Positiv: Boolean;
    begin
        Evaluate(Positiv, Positive);
        ReservationEntry.SetFilter("Entry No.", '>' + Format(Offset));
        ReservationEntry.SetFilter(Positive, Positive);
        ReservationEntry.SetRange("Location Code", LocationCode);
        ReservationEntry.SetRange("Shipment Date", ShptDate);
        ReservationEntry.SetRange("Source Type", SrcType);
        ReservationEntry.SetRange("Source ID", SourceID);
        ReservationEntry.SetRange("Source Ref. No.", SrcRefNo);
        ReservationEntry.SetRange("Item No.", ItemNo);
        ReservationEntry.SetRange("Variant Code", VariantCode);
        ReservationEntry.SetRange(Quantity, Quantity);
        ReservationEntry.SetRange("Quantity (Base)", QuantityBase);
        ReservationEntry.SetRange("Qty. to Handle (Base)", QtyToHandleBase);
        ReservationEntry.SetRange("Qty. to Invoice (Base)", QtyToInvoiceBase);
        ReservationEntry.SetRange("Quantity Invoiced (Base)", QtyInvoicedBase);
        ReservationEntry.SetRange("Serial No.", SerialNo);
        ReservationEntry.SetRange("Lot No.", LotNo);
        // EntryNo := EntryNo + Offset;
        // IF NOT ReservationEntry.GET(EntryNo,Positiv) THEN
        if not ReservationEntry.FindFirst() then
            TestScriptMgmt.TestTextValue('', 'NOT FOUND', 'EXIST', UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo)
        else begin
            EntryNo := ReservationEntry."Entry No.";

            TestScriptMgmt.Increase(NoOfRecords);
            TestScriptMgmt.TestTextValue(ReservationEntry.FieldName("Location Code"), ReservationEntry."Location Code", LocationCode,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestDateValue(ReservationEntry.FieldName("Shipment Date"), ReservationEntry."Shipment Date", ShptDate,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestNumberValue(ReservationEntry.FieldName("Source Type"), ReservationEntry."Source Type", SrcType,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestTextValue(ReservationEntry.FieldName("Source ID"), ReservationEntry."Source ID", SourceID,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestNumberValue(ReservationEntry.FieldName("Source Ref. No."), ReservationEntry."Source Ref. No.", SrcRefNo,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestTextValue(ReservationEntry.FieldName("Item No."), ReservationEntry."Item No.", ItemNo,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestTextValue(ReservationEntry.FieldName("Variant Code"), ReservationEntry."Variant Code", VariantCode,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestNumberValue(ReservationEntry.FieldName(Quantity), ReservationEntry.Quantity, Quantity,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestNumberValue(ReservationEntry.FieldName("Quantity (Base)"), ReservationEntry."Quantity (Base)", QuantityBase,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestNumberValue(ReservationEntry.FieldName("Qty. to Handle (Base)"), ReservationEntry."Qty. to Handle (Base)",
              QtyToHandleBase, UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestNumberValue(ReservationEntry.FieldName("Qty. to Invoice (Base)"), ReservationEntry."Qty. to Invoice (Base)",
              QtyToInvoiceBase, UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestNumberValue(ReservationEntry.FieldName("Quantity Invoiced (Base)"), ReservationEntry."Quantity Invoiced (Base)",
              QtyInvoicedBase, UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestTextValue(ReservationEntry.FieldName("Serial No."), ReservationEntry."Serial No.", SerialNo,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
            TestScriptMgmt.TestTextValue(ReservationEntry.FieldName("Lot No."), ReservationEntry."Lot No.", LotNo,
              UseCaseNo, TestCaseNo, EntryNo, TableID, IterationNo);
            TestScriptMgmt.Increase(NoOfFields);
        end;
    end;

    [Scope('OnPrem')]
    procedure SetNumbers(NewNoOfRecords: Integer; NewNoOfFields: Integer)
    begin
        NoOfRecords := NewNoOfRecords;
        NoOfFields := NewNoOfFields;
    end;

    [Scope('OnPrem')]
    procedure GetNumbers(var NewNoOfRecords: Integer; var NewNoOfFields: Integer)
    begin
        NewNoOfRecords := NoOfRecords;
        NewNoOfFields := NoOfFields;
    end;
}

