codeunit 101009 "Create Country/Region"
{

    trigger OnRun()
    begin
        InsertData('AT', XAustriaLbl, '040', 'AT', 'AT', 3, 1, '0007', '');
        InsertVATRegNoFormat('AT', 10000, 'ATU########');
        InsertData('AU', XAustraliaLbl, '036', '', '', 5, 1, '', '');
        InsertData('BE', XBelgiumLbl, '056', 'BE', 'BE', 0, 1, '9925', '');
        InsertVATRegNoFormat('BE', 10000, 'BE#########');
        InsertVATRegNoFormat('BE', 20000, 'BE #########');
        InsertVATRegNoFormat('BE', 30000, 'BE ###.###.###');
        InsertVATRegNoFormat('BE', 40000, 'BE ### ### ###');
        InsertVATRegNoFormat('BE', 50000, '#########');
        InsertVATRegNoFormat('BE', 60000, '###.###.###');
        InsertVATRegNoFormat('BE', 70000, '### ### ###');
        InsertData('BG', XBulgariaLbl, '100', 'BG', 'BG', 2, 1, '9926', '');
        InsertVATRegNoFormat('BG', 10000, 'BG##########');
        InsertVATRegNoFormat('BG', 20000, 'BG#########');
        InsertData('BR', XBrazilLbl, '076', '', '', 1, 0, '', '');
        InsertData('CA', XCanadaLbl, '124', '', '', 2, 1, '', XProvinceLbl);
        InsertData('CH', XSwitzerlandLbl, '756', '', '', 0, 1, '', '');
        InsertVATRegNoFormat('CH', 10000, 'CHE-###.###.###MWST');
        InsertVATRegNoFormat('CH', 20000, 'CHE-###.###.### TVA');
        InsertVATRegNoFormat('CH', 30000, 'CHE-###.###.### IVA');
        InsertVATRegNoFormat('CH', 40000, '### ###');
        InsertData('CZ', XCzechiaLbl, '203', 'CZ', 'CZ', 0, 1, '9929', '');
        InsertVATRegNoFormat('CZ', 10000, 'CZ########');
        InsertVATRegNoFormat('CZ', 20000, 'CZ#########');
        InsertVATRegNoFormat('CZ', 30000, 'CZ##########');
        InsertData('DE', XGermanyLbl, '276', 'DE', 'DE', 3, 1, '9930', '');
        InsertVATRegNoFormat('DE', 10000, 'DE#########');
        InsertVATRegNoFormat('DE', 20000, '#########');
        InsertData('DK', XDenmarkLbl, '208', 'DK', 'DK', 0, 1, '0184', '');
        InsertVATRegNoFormat('DK', 10000, 'DK########');
        InsertVATRegNoFormat('DK', 20000, '########');
        InsertData('ES', XSpainLbl, '724', 'ES', 'ES', 0, 1, '9920', '');
        InsertVATRegNoFormat('ES', 10000, 'ES########@');
        InsertVATRegNoFormat('ES', 20000, '########@');
        InsertVATRegNoFormat('ES', 30000, 'ES@########');
        InsertVATRegNoFormat('ES', 40000, '@########');
        InsertVATRegNoFormat('ES', 50000, 'ES@#######@');
        InsertVATRegNoFormat('ES', 60000, '@#######@');
        InsertVATRegNoFormat('ES', 70000, '@########@');
        InsertVATRegNoFormat('ES', 80000, '@######@');
        InsertVATRegNoFormat('ES', 90000, '@#####@');
        InsertVATRegNoFormat('ES', 100000, '#######@');
        InsertVATRegNoFormat('ES', 110000, '######@');
        InsertVATRegNoFormat('ES', 120000, '#####@');
        InsertVATRegNoFormat('ES', 130000, '@#######');
        InsertVATRegNoFormat('ES', 140000, '@######');
        InsertVATRegNoFormat('ES', 150000, '@#####');
        InsertData('EE', XEstoniaLbl, '233', 'EE', 'EE', 0, 1, '9931', '');
        InsertVATRegNoFormat('EE', 10000, 'EE#########');
        InsertVATRegNoFormat('EE', 20000, '#########');
        InsertData('FR', XFranceLbl, '250', 'FR', 'FR', 0, 1, '0009', '');
        InsertVATRegNoFormat('FR', 10000, 'FR###########');
        InsertVATRegNoFormat('FR', 20000, '###########');
        InsertData('GB', XGreatBritainLbl, '826', '', 'GB', 2, 1, '9932', '');
        InsertVATRegNoFormat('GB', 10000, 'GB#########');
        InsertVATRegNoFormat('GB', 20000, 'GB###-####-##');
        InsertVATRegNoFormat('GB', 30000, 'GB### #### ##');
        InsertVATRegNoFormat('GB', 40000, '###-####-##');
        InsertVATRegNoFormat('GB', 50000, '### #### ##');
        InsertVATRegNoFormat('GB', 60000, '#########');
        InsertData('ID', XIndonesiaLbl, '360', '', '', 0, 1, '', '');
        InsertData('IN', XIndiaLbl, '356', '', '', 1, 0, '', '');
        InsertData('IS', XIcelandLbl, '352', '', '', 0, 1, '', '');
        InsertData('IT', XItalyLbl, '380', 'IT', 'IT', 0, 1, '0097', '');
        InsertData('LU', XLuxembourgLbl, '442', 'LU', 'LU', 0, 1, '9938', '');
        InsertVATRegNoFormat('LU', 10000, 'LU########');
        InsertVATRegNoFormat('LU', 20000, '########');
        InsertData('LT', XLithuaniaLbl, '440', 'LT', 'LT', 0, 1, '0200', '');
        InsertVATRegNoFormat('LT', 10000, 'LT#########');
        InsertVATRegNoFormat('LT', 20000, 'LT############');
        InsertVATRegNoFormat('LT', 30000, '#########');
        InsertVATRegNoFormat('LT', 40000, '############');
        InsertData('LV', XLatviaLbl, '428', 'LV', 'LV', 0, 1, '9939', '');
        InsertVATRegNoFormat('LV', 10000, 'LV###########');
        InsertVATRegNoFormat('LV', 20000, '###########');
        InsertData('MY', XMalaysiaLbl, '458', '', '', 0, 1, '', '');
        InsertData('MX', XMexicoLbl, '484', '', '', 2, 1, '', '');
        InsertDataExtended('NI', XNothernIrelandLbl, 'GB', '826', 'GBN', 'GBN', 2, 1, '9932', '');
        InsertData('NL', XNetherlandsLbl, '528', 'NL', 'NL', 0, 1, '9944', '');
        InsertVATRegNoFormat('NL', 10000, 'NL#########B##');
        InsertVATRegNoFormat('NL', 20000, '#########B##');
        InsertData('NO', XNorwayLbl, '578', '', '', 0, 1, '0192', '');
        InsertVATRegNoFormat('NO', 10000, 'NO ### ### ### MVA');
        InsertVATRegNoFormat('NO', 20000, '### ### ### MVA');
        InsertVATRegNoFormat('NO', 30000, 'NO ### ### ###');
        InsertVATRegNoFormat('NO', 40000, '#########');
        InsertData('NZ', XNewZealandLbl, '554', '', '', 1, 1, '', '');
        InsertData('PL', XPolandLbl, '616', 'PL', 'PL', 0, 1, '9945', '');
        InsertVATRegNoFormat('PL', 10000, 'PL##########');
        InsertVATRegNoFormat('PL', 20000, '##########');
        InsertData('PT', XPortugalLbl, '620', 'PT', 'PT', 0, 1, '9946', '');
        InsertData('RU', XRussiaLbl, '643', '', '', 1, 2, '', XRegionLbl);
        InsertData('SG', XSingaporeLbl, '702', '', '', 1, 1, '', '');
        InsertVATRegNoFormat('SG', 10000, '##-#######-?');
        InsertData('SE', XSwedenLbl, '752', 'SE', 'SE', 0, 1, '9955', '');
        InsertVATRegNoFormat('SE', 10000, 'SE##########01');
        InsertVATRegNoFormat('SE', 20000, '##########01');
        InsertData('SI', XSloveniaLbl, '705', 'SI', 'SI', 0, 1, '9949', '');
        InsertVATRegNoFormat('SI', 10000, 'SI########');
        InsertVATRegNoFormat('SI', 20000, '########');
        InsertData('TH', XThailandLbl, '764', '', '', 0, 1, '', '');
        InsertData('TR', XTurkeyLbl, '792', '', '', 0, 0, '9952', '');
        InsertData('US', XUSALbl, '840', '', '', 2, 1, '', XStateLbl);
        InsertData('ZA', XSouthAfricaLbl, '710', '', '', 1, 0, '', '');
        InsertData('MA', XMoroccoLbl, '504', '', '', 0, 1, '', '');
        InsertData('DZ', XAlgeriaLbl, '012', '', '', 0, 1, '', '');
        InsertData('TN', XTunisiaLbl, '788', '', '', 0, 1, '', '');
        InsertData('KE', XKenyaLbl, '404', '', '', 0, 1, '', '');
        InsertData('UG', XUgandaLbl, '800', '', '', 1, 1, '', '');
        InsertData('AE', XUnitedArabEmiratesLbl, '784', '', '', 1, 1, '', '');
        InsertData('MZ', XMozambiqueLbl, '508', '', '', 0, 1, '', '');
        InsertData('SZ', XSwazilandLbl, '748', '', '', 1, 1, '', '');
        InsertData('FI', XFinlandLbl, '246', 'FI', 'FI', 0, 1, '', '');
        InsertData('HU', XHungaryLbl, '348', 'HU', 'HU', 1, 1, '9910', '');
        InsertVATRegNoFormat('HU', 10000, 'HU########');
        InsertVATRegNoFormat('HU', 20000, '########');
        InsertData('RO', XRomaniaLbl, '642', 'RO', 'RO', 0, 1, '9947', '');
        InsertVATRegNoFormat('RO', 10000, 'RO##########');
        InsertData('EL', XGreeceLbl, '300', 'EL', 'EL', 0, 1, '', '');
        InsertData('IE', XIrelandLbl, '372', 'IE', 'IE', 2, 1, '9935', '');
        InsertData('NG', XNigeriaLbl, '566', '', '', 1, 1, '', '');
        InsertData('PH', XPhilippinesLbl, '608', '', '', 0, 1, '', '');
        InsertData('TZ', XTanzaniaLbl, '834', '', '', 0, 1, '', '');
        InsertData('HR', XCroatiaLbl, '191', 'HR', 'HR', 0, 1, '9934', '');
        InsertVATRegNoFormat('HR', 10000, 'HR###########');
        InsertData('CY', XCyprusLbl, '196', 'CY', 'CY', 0, 1, '9928', '');
        InsertVATRegNoFormat('CY', 10000, 'CY########@');
        InsertVATRegNoFormat('CY', 20000, '########@');
        InsertData('MT', XMaltaLbl, '470', 'MT', 'MT', 0, 1, '9943', '');
        InsertVATRegNoFormat('MT', 10000, 'MT########');
        InsertVATRegNoFormat('MT', 20000, '########');
        InsertData('SK', XSlovakiaLbl, '703', 'SK', 'SK', 0, 1, '9950', '');
        InsertVATRegNoFormat('SK', 10000, 'SK#########');
        InsertVATRegNoFormat('SK', 20000, 'SK##########');
        InsertVATRegNoFormat('SK', 30000, '#########');
        InsertVATRegNoFormat('SK', 40000, '##########');
        InsertData('BN', XBruneiDarussalamLbl, '096', '', '', 1, 0, '', '');
        InsertData('FJ', XFijiIslandsLbl, '242', '', '', 1, 0, '', '');
        InsertData('JP', XJapanLbl, '392', '', '', 1, 0, '', '');
        InsertData('SA', XSaudiArabiaLbl, '682', '', '', 1, 0, '', '');
        InsertData('SB', XSolomonIslandsLbl, '090', '', '', 1, 0, '', '');
        InsertData('VU', XVanuatuLbl, '548', '', '', 1, 0, '', '');
        InsertData('WS', XSamoaLbl, '882', '', '', 1, 0, '', '');
        InsertData('RS', XSerbiaLbl, '688', '', '', 0, 1, '9948', '');
        InsertData('ME', XMontenegroLbl, '499', '', '', 0, 1, '9941', '');
        InsertData('CN', XChinaTxtLbl, '156', '', '', 0, 0, '', '');
        InsertData('CR', XCostaRicaLbl, '188', '', '', 0, 0, '', '');
        InsertData('AF', XAfghanistanLbl, '004', '', '', 0, 1, '', '');
        InsertData('AL', XAlbaniaLbl, '008', '', '', 0, 1, '', '');
        InsertData('AD', XAndorraLbl, '020', '', '', 0, 1, '', '');
        InsertData('AO', XAngolaLbl, '024', '', '', 0, 1, '', '');
        InsertData('AI', XAnguillaLbl, '660', '', '', 0, 1, '', '');
        InsertData('AQ', XAntarcticaLbl, '010', '', '', 0, 1, '', '');
        InsertData('AG', XAntiguaBarbudaLbl, '028', '', '', 0, 1, '', '');
        InsertData('AR', XArgentinaLbl, '032', '', '', 0, 0, '', '');
        InsertData('AM', XArmeniaLbl, '051', '', '', 0, 1, '', '');
        InsertData('AW', XArubaLbl, '533', '', '', 0, 1, '', '');
        InsertData('AZ', XAzerbaijanLbl, '031', '', '', 0, 1, '', '');
        InsertData('BS', XBahamasLbl, '044', '', '', 0, 0, '', '');
        InsertData('BH', XBahrainLbl, '048', '', '', 1, 0, '', '');
        InsertData('BD', XBangladeshLbl, '050', '', '', 1, 0, '', '');
        InsertData('BB', XBarbadosLbl, '052', '', '', 0, 0, '', '');
        InsertData('BY', XBelarusLbl, '112', '', '', 0, 0, '', '');
        InsertData('BZ', XBelizeLbl, '084', '', '', 0, 0, '', '');
        InsertData('BJ', XBeninLbl, '204', '', '', 0, 1, '', '');
        InsertData('BM', XBermudaLbl, '060', '', '', 0, 1, '', '');
        InsertData('BT', XBhutanLbl, '064', '', '', 0, 0, '', '');
        InsertData('BO', XBoliviaLbl, '068', '', '', 0, 0, '', '');
        InsertData('BQ', XBonaireLbl, '535', '', '', 0, 1, '', '');
        InsertData('BA', XBosniaHerzegovinaLbl, '070', '', '', 0, 1, '', '');
        InsertData('BW', XBotswanaLbl, '072', '', '', 0, 1, '', '');
        InsertData('BV', XBouvetIslandLbl, '074', '', '', 0, 1, '', '');
        InsertData('IO', XBritishIndianOceanLbl, '086', '', '', 0, 1, '', '');
        InsertData('BF', XBurkinaFasoLbl, '854', '', '', 0, 1, '', '');
        InsertData('BI', XBurundiLbl, '108', '', '', 0, 1, '', '');
        InsertData('CV', XCaboVerdeLbl, '132', '', '', 0, 1, '', '');
        InsertData('KH', XCambodiaLbl, '116', '', '', 1, 0, '', '');
        InsertData('CM', XCameroonLbl, '120', '', '', 0, 1, '', '');
        InsertData('KY', XCaymanIslandsLbl, '136', '', '', 0, 0, '', '');
        InsertData('CF', XCentralAfricanLbl, '140', '', '', 0, 1, '', '');
        InsertData('TD', XChadLbl, '148', '', '', 0, 1, '', '');
        InsertData('CL', XChileLbl, '152', '', '', 0, 0, '', '');
        InsertData('CX', XChristmasIslandLbl, '162', '', '', 0, 1, '', '');
        InsertData('CC', XCocosIslandsLbl, '166', '', '', 0, 1, '', '');
        InsertData('CO', XColombiaLbl, '170', '', '', 0, 0, '', '');
        InsertData('KM', XComorosLbl, '174', '', '', 0, 1, '', '');
        InsertData('CD', XCongoDRLbl, '180', '', '', 0, 1, '', '');
        InsertData('CG', XCongoLbl, '178', '', '', 0, 1, '', '');
        InsertData('CK', XCookIslandsLbl, '184', '', '', 1, 0, '', '');
        InsertData('CU', XCubaLbl, '192', '', '', 0, 0, '', '');
        InsertData('CW', XCuracaoLbl, '531', '', '', 0, 1, '', '');
        InsertData('CI', XCotedIvoireLbl, '384', '', '', 0, 1, '', '');
        InsertData('DJ', XDjiboutiLbl, '262', '', '', 0, 1, '', '');
        InsertData('DM', XDominicaLbl, '212', '', '', 0, 0, '', '');
        InsertData('DO', XDominicanLbl, '214', '', '', 0, 0, '', '');
        InsertData('EC', XEcuadorLbl, '218', '', '', 0, 0, '', '');
        InsertData('EG', XEgyptLbl, '818', '', '', 1, 0, '', '');
        InsertData('SV', XElSalvadorLbl, '222', '', '', 0, 0, '', '');
        InsertData('GQ', XEquatorialGuineaLbl, '226', '', '', 0, 1, '', '');
        InsertData('ER', XEritreaLbl, '232', '', '', 0, 1, '', '');
        InsertData('ET', XEthiopiaLbl, '231', '', '', 1, 1, '', '');
        InsertData('FK', XFalklandIslandsLbl, '238', '', '', 0, 0, '', '');
        InsertData('FO', XFaroeIslandsLbl, '234', '', '', 0, 1, '', '');
        InsertData('GF', XFrenchGuianaLbl, '254', '', '', 0, 1, '', '');
        InsertData('PF', XFrenchPolynesiaLbl, '258', '', '', 1, 1, '', '');
        InsertData('TF', XFrenchSouthernLbl, '260', '', '', 0, 1, '', '');
        InsertData('GA', XGabonLbl, '266', '', '', 0, 1, '', '');
        InsertData('GM', XGambiaLbl, '270', '', '', 0, 1, '', '');
        InsertData('GE', XGeorgiaLbl, '268', '', '', 0, 1, '', '');
        InsertData('GH', XGhanaLbl, '288', '', '', 0, 1, '', '');
        InsertData('GI', XGibraltarLbl, '292', '', '', 0, 1, '', '');
        InsertData('GL', XGreenlandLbl, '304', '', '', 0, 1, '', '');
        InsertData('GD', XGrenadaLbl, '308', '', '', 0, 0, '', '');
        InsertData('GP', XGuadeloupeLbl, '312', '', '', 0, 1, '', '');
        InsertData('GU', XGuamLbl, '316', '', '', 1, 1, '', '');
        InsertData('GT', XGuatemalaLbl, '320', '', '', 0, 0, '', '');
        InsertData('GG', XGuernseyLbl, '831', '', '', 0, 1, '', '');
        InsertData('GN', XGuineaLbl, '324', '', '', 0, 1, '', '');
        InsertData('GW', XGuineaBissauLbl, '624', '', '', 0, 1, '', '');
        InsertData('GY', XGuyanaLbl, '328', '', '', 0, 0, '', '');
        InsertData('HT', XHaitiLbl, '332', '', '', 0, 0, '', '');
        InsertData('HM', XHeardIslandLbl, '334', '', '', 0, 1, '', '');
        InsertData('VA', XHolySeeLbl, '336', '', '', 0, 1, '', '');
        InsertData('HN', XHondurasLbl, '340', '', '', 0, 0, '', '');
        InsertData('HK', XHongKongLbl, '344', '', '', 1, 0, '', '');
        InsertData('IM', XIsleManLbl, '833', '', '', 0, 1, '', '');
        InsertData('IL', XIsraelLbl, '376', '', '', 1, 0, '', '');
        InsertData('JM', XJamaicaLbl, '388', '', '', 0, 0, '', '');
        InsertData('JE', XJerseyLbl, '832', '', '', 0, 1, '', '');
        InsertData('JO', XJordanLbl, '400', '', '', 1, 0, '', '');
        InsertData('KZ', XKazakhstanLbl, '398', '', '', 0, 0, '', '');
        InsertData('KI', XKiribatiLbl, '296', '', '', 1, 1, '', '');
        InsertData('KP', XNorthKoreaLbl, '408', '', '', 0, 0, '', '');
        InsertData('KR', XSouthKoreaLbl, '410', '', '', 1, 0, '', '');
        InsertData('KW', XKuwaitLbl, '414', '', '', 1, 0, '', '');
        InsertData('KG', XKyrgyzstanLbl, '417', '', '', 0, 0, '', '');
        InsertData('LA', XLaosLbl, '418', '', '', 1, 0, '', '');
        InsertData('LB', XLebanonLbl, '422', '', '', 1, 0, '', '');
        InsertData('LS', XLesothoLbl, '426', '', '', 0, 1, '', '');
        InsertData('LR', XLiberiaLbl, '430', '', '', 0, 1, '', '');
        InsertData('LY', XLibyaLbl, '434', '', '', 0, 1, '', '');
        InsertData('LI', XLiechtensteinLbl, '438', '', '', 0, 1, '', '');
        InsertData('MO', XMacaoLbl, '446', '', '', 1, 0, '', '');
        InsertData('MG', XMadagascarLbl, '450', '', '', 0, 1, '', '');
        InsertData('MW', XMalawiLbl, '454', '', '', 0, 1, '', '');
        InsertData('MV', XMaldivesLbl, '462', '', '', 1, 0, '', '');
        InsertData('ML', XMaliLbl, '466', '', '', 0, 1, '', '');
        InsertData('MH', XMarshallIslandsLbl, '584', '', '', 1, 1, '', '');
        InsertData('MQ', XMartiniqueLbl, '474', '', '', 0, 1, '', '');
        InsertData('MR', XMauritaniaLbl, '478', '', '', 0, 1, '', '');
        InsertData('MU', XMauritiusLbl, '480', '', '', 0, 1, '', '');
        InsertData('YT', XMayotteLbl, '175', '', '', 0, 1, '', '');
        InsertData('FM', XMicronesiaLbl, '583', '', '', 1, 1, '', '');
        InsertData('MD', XMoldovaLbl, '498', '', '', 0, 0, '', '');
        InsertData('MC', XMonacoLbl, '492', '', '', 0, 1, '', '');
        InsertData('MN', XMongoliaLbl, '496', '', '', 0, 0, '', '');
        InsertData('MS', XMontserratLbl, '500', '', '', 0, 0, '', '');
        InsertData('MM', XMyanmarLbl, '104', '', '', 1, 0, '', '');
        InsertData('NA', XNamibiaLbl, '516', '', '', 0, 1, '', '');
        InsertData('NR', XNauruLbl, '520', '', '', 1, 1, '', '');
        InsertData('NP', XNepalLbl, '524', '', '', 1, 0, '', '');
        InsertData('NC', XNewCaledoniaLbl, '540', '', '', 1, 1, '', '');
        InsertData('NE', XNigerLbl, '562', '', '', 0, 1, '', '');
        InsertData('NU', XNiueLbl, '570', '', '', 1, 1, '', '');
        InsertData('NF', XNorfolkIslandLbl, '574', '', '', 0, 1, '', '');
        InsertData('MK', XNorthMacedoniaLbl, '807', '', '', 0, 1, '', '');
        InsertData('MP', XNorthernMarianaLbl, '580', '', '', 1, 1, '', '');
        InsertData('OM', XOmanLbl, '512', '', '', 1, 0, '', '');
        InsertData('PK', XPakistanLbl, '586', '', '', 1, 0, '', '');
        InsertData('PW', XPalauLbl, '585', '', '', 1, 1, '', '');
        InsertData('PS', XPalestineLbl, '275', '', '', 1, 0, '', '');
        InsertData('PA', XPanamaLbl, '591', '', '', 0, 0, '', '');
        InsertData('PG', XPapuaNewGuineaLbl, '598', '', '', 1, 1, '', '');
        InsertData('PY', XParaguayLbl, '600', '', '', 0, 0, '', '');
        InsertData('PE', XPeruLbl, '604', '', '', 0, 0, '', '');
        InsertData('PN', XPitcairnLbl, '612', '', '', 1, 0, '', '');
        InsertData('PR', XPuertoRicoLbl, '630', '', '', 2, 1, '', '');
        InsertData('QA', XQatarLbl, '634', '', '', 1, 0, '', '');
        InsertData('RW', XRwandaLbl, '646', '', '', 0, 1, '', '');
        InsertData('RE', XReunionLbl, '638', '', '', 0, 1, '', '');
        InsertData('BL', XSaintBarthelemyLbl, '652', '', '', 0, 1, '', '');
        InsertData('SH', XSaintHelenaLbl, '654', '', '', 0, 1, '', '');
        InsertData('KN', XSaintKittsNevisLbl, '659', '', '', 0, 0, '', '');
        InsertData('LC', XSaintLuciaLbl, '662', '', '', 0, 0, '', '');
        InsertData('MF', XSaintMartinLbl, '663', '', '', 0, 1, '', '');
        InsertData('PM', XSaintPierreQuelonLbl, '666', '', '', 0, 1, '', '');
        InsertData('VC', XSaintVincentLbl, '670', '', '', 0, 0, '', '');
        InsertData('SM', XSanMarinoLbl, '674', '', '', 0, 1, '', '');
        InsertData('ST', XSaoTomeLbl, '678', '', '', 0, 1, '', '');
        InsertData('SN', XSenegalLbl, '686', '', '', 0, 1, '', '');
        InsertData('SC', XSeychellesLbl, '690', '', '', 0, 1, '', '');
        InsertData('SL', XSierraLeoneLbl, '694', '', '', 0, 1, '', '');
        InsertData('SX', XSintMaartenLbl, '534', '', '', 0, 1, '', '');
        InsertData('SO', XSomaliaLbl, '706', '', '', 0, 1, '', '');
        InsertData('GS', XSouthGeorgiaLbl, '239', '', '', 0, 1, '', '');
        InsertData('SS', XSouthSudanLbl, '728', '', '', 0, 1, '', '');
        InsertData('LK', XSriLankaLbl, '144', '', '', 1, 0, '', '');
        InsertData('SD', XSudanLbl, '729', '', '', 1, 0, '', '');
        InsertData('SR', XSurinameLbl, '740', '', '', 0, 0, '', '');
        InsertData('SJ', XSvalbardJanMayenLbl, '744', '', '', 0, 1, '', '');
        InsertData('SY', XSyriaLbl, '760', '', '', 1, 0, '', '');
        InsertData('TW', XTaiwanLbl, '158', '', '', 1, 0, '', '');
        InsertData('TJ', XTajikistanLbl, '762', '', '', 0, 0, '', '');
        InsertData('TL', XTimorLesteLbl, '626', '', '', 1, 1, '', '');
        InsertData('TG', XTogoLbl, '768', '', '', 0, 1, '', '');
        InsertData('TK', XTokelauLbl, '772', '', '', 1, 1, '', '');
        InsertData('TO', XTongaLbl, '776', '', '', 1, 1, '', '');
        InsertData('TT', XTrinidadTobagoLbl, '780', '', '', 0, 0, '', '');
        InsertData('TM', XTurkmenistanLbl, '795', '', '', 0, 0, '', '');
        InsertData('TC', XTurksCalcosLbl, '796', '', '', 0, 0, '', '');
        InsertData('TV', XTuvaluLbl, '798', '', '', 1, 1, '', '');
        InsertData('UA', XUkraineLbl, '804', '', '', 0, 0, '', '');
        InsertData('UM', XUSMinorOutlyingLbl, '581', '', '', 0, 0, '', '');
        InsertData('UY', XUruguayLbl, '858', '', '', 0, 0, '', '');
        InsertData('UZ', XUzbekistanLbl, '860', '', '', 0, 0, '', '');
        InsertData('VE', XVenezuelLbl, '862', '', '', 0, 0, '', '');
        InsertData('VN', XVietnamLbl, '704', '', '', 1, 0, '', '');
        InsertData('VG', XVirginIslandsBrLbl, '092', '', '', 0, 0, '', '');
        InsertData('VI', XVirginIslandsUSLbl, '850', '', '', 0, 0, '', '');
        InsertData('WF', XWallisatunaLbl, '876', '', '', 1, 1, '', '');
        InsertData('EH', XWesternSaharaLbl, '732', '', '', 0, 1, '', '');
        InsertData('YE', XYemenLbl, '887', '', '', 1, 0, '', '');
        InsertData('ZM', XZambiaLbl, '894', '', '', 0, 1, '', '');
        InsertData('ZW', XZimbabweLbl, '716', '', '', 0, 1, '', '');
        InsertData('AX', XAlandIslandsLbl, '248', '', '', 0, 1, '', '');
    end;

    var
        Country: Record "Country/Region";
        VATRegNoFormat: Record "VAT Registration No. Format";
        XAustriaLbl: Label 'Austria', MaxLength = 50;
        XAustraliaLbl: Label 'Australia', MaxLength = 50;
        XBelgiumLbl: Label 'Belgium', MaxLength = 50;
        XBulgariaLbl: Label 'Bulgaria', MaxLength = 50;
        XBrazilLbl: Label 'Brazil', MaxLength = 50;
        XCanadaLbl: Label 'Canada', MaxLength = 50;
        XChinaTxtLbl: Label 'China', MaxLength = 50;
        XCroatiaLbl: Label 'Croatia', MaxLength = 50;
        XCyprusLbl: Label 'Cyprus', MaxLength = 50;
        XSwitzerlandLbl: Label 'Switzerland', MaxLength = 50;
        XMontenegroLbl: Label 'Montenegro', MaxLength = 50;
        XSerbiaLbl: Label 'Serbia', MaxLength = 50;
        XCzechiaLbl: Label 'Czechia', MaxLength = 50;
        XGermanyLbl: Label 'Germany', MaxLength = 50;
        XDenmarkLbl: Label 'Denmark', MaxLength = 50;
        XSpainLbl: Label 'Spain', MaxLength = 50;
        XEstoniaLbl: Label 'Estonia', MaxLength = 50;
        XFranceLbl: Label 'France', MaxLength = 50;
        XGreatBritainLbl: Label 'Great Britain', MaxLength = 50;
        XIndonesiaLbl: Label 'Indonesia', MaxLength = 50;
        XIndiaLbl: Label 'India', MaxLength = 50;
        XIcelandLbl: Label 'Iceland', MaxLength = 50;
        XItalyLbl: Label 'Italy', MaxLength = 50;
        XLuxembourgLbl: Label 'Luxembourg', MaxLength = 50;
        XLithuaniaLbl: Label 'Lithuania', MaxLength = 50;
        XLatviaLbl: Label 'Latvia', MaxLength = 50;
        XMalaysiaLbl: Label 'Malaysia', MaxLength = 50;
        XMexicoLbl: Label 'Mexico', MaxLength = 50;
        XNetherlandsLbl: Label 'Netherlands', MaxLength = 50;
        XNorwayLbl: Label 'Norway', MaxLength = 50;
        XNewZealandLbl: Label 'New Zealand', MaxLength = 50;
        XPolandLbl: Label 'Poland', MaxLength = 50;
        XPortugalLbl: Label 'Portugal', MaxLength = 50;
        XRussiaLbl: Label 'Russia', MaxLength = 50;
        XSingaporeLbl: Label 'Singapore', MaxLength = 50;
        XSwedenLbl: Label 'Sweden', MaxLength = 50;
        XSloveniaLbl: Label 'Slovenia', MaxLength = 50;
        XThailandLbl: Label 'Thailand', MaxLength = 50;
        XTurkeyLbl: Label 'Türkiye', MaxLength = 50;
        XUSALbl: Label 'USA', MaxLength = 50;
        XSouthAfricaLbl: Label 'South Africa', MaxLength = 50;
        XMoroccoLbl: Label 'Morocco', MaxLength = 50;
        XAlgeriaLbl: Label 'Algeria', MaxLength = 50;
        XTunisiaLbl: Label 'Tunisia', MaxLength = 50;
        XKenyaLbl: Label 'Kenya', MaxLength = 50;
        XUgandaLbl: Label 'Uganda', MaxLength = 50;
        XUnitedArabEmiratesLbl: Label 'United Arab Emirates', MaxLength = 50;
        XMozambiqueLbl: Label 'Mozambique', MaxLength = 50;
        XSwazilandLbl: Label 'Swaziland', MaxLength = 50;
        XFinlandLbl: Label 'Finland', MaxLength = 50;
        XHungaryLbl: Label 'Hungary', MaxLength = 50;
        XRomaniaLbl: Label 'Romania', MaxLength = 50;
        XGreeceLbl: Label 'Greece', MaxLength = 50;
        XIrelandLbl: Label 'Ireland', MaxLength = 50;
        XNigeriaLbl: Label 'Nigeria', MaxLength = 50;
        XPhilippinesLbl: Label 'Philippines', MaxLength = 50;
        XTanzaniaLbl: Label 'Tanzania', MaxLength = 50;
        XMaltaLbl: Label 'Malta', MaxLength = 50;
        XSlovakiaLbl: Label 'Slovakia', MaxLength = 50;
        XBruneiDarussalamLbl: Label 'Brunei Darussalam', MaxLength = 50;
        XFijiIslandsLbl: Label 'Fiji Islands', MaxLength = 50;
        XJapanLbl: Label 'Japan', MaxLength = 50;
        XSaudiArabiaLbl: Label 'Saudi Arabia', MaxLength = 50;
        XSolomonIslandsLbl: Label 'Solomon Islands', MaxLength = 50;
        XVanuatuLbl: Label 'Vanuatu', MaxLength = 50;
        XSamoaLbl: Label 'Samoa', MaxLength = 50;
        XCostaRicaLbl: Label 'Costa Rica', MaxLength = 50;
        XProvinceLbl: Label 'Province', MaxLength = 30;
        XStateLbl: Label 'State', MaxLength = 30;
        XRegionLbl: Label 'Region', MaxLength = 30;
        XNothernIrelandLbl: Label 'Nothern Ireland', MaxLength = 50;
        XAfghanistanLbl: Label 'Afghanistan', MaxLength = 50;
        XAlbaniaLbl: Label 'Albania', MaxLength = 50;
        XAndorraLbl: Label 'Andorra', MaxLength = 50;
        XAngolaLbl: Label 'Angola', MaxLength = 50;
        XAnguillaLbl: Label 'Anguilla', MaxLength = 50;
        XAntarcticaLbl: Label 'Antarctica', MaxLength = 50;
        XAntiguaBarbudaLbl: Label 'Antigua and Barbuda', MaxLength = 50;
        XArgentinaLbl: Label 'Argentina', MaxLength = 50;
        XArmeniaLbl: Label 'Armenia', MaxLength = 50;
        XArubaLbl: Label 'Aruba', MaxLength = 50;
        XAzerbaijanLbl: Label 'Azerbaijan', MaxLength = 50;
        XBahamasLbl: Label 'Bahamas', MaxLength = 50;
        XBahrainLbl: Label 'Bahrain', MaxLength = 50;
        XBangladeshLbl: Label 'Bangladesh', MaxLength = 50;
        XBarbadosLbl: Label 'Barbados', MaxLength = 50;
        XBelarusLbl: Label 'Belarus', MaxLength = 50;
        XBelizeLbl: Label 'Belize', MaxLength = 50;
        XBeninLbl: Label 'Benin', MaxLength = 50;
        XBermudaLbl: Label 'Bermuda', MaxLength = 50;
        XBhutanLbl: Label 'Bhutan', MaxLength = 50;
        XBoliviaLbl: Label 'Bolivia', MaxLength = 50;
        XBonaireLbl: Label 'Bonaire, Sint Eustatius and Saba', MaxLength = 50;
        XBosniaHerzegovinaLbl: Label 'Bosnia and Herzegovina', MaxLength = 50;
        XBotswanaLbl: Label 'Botswana', MaxLength = 50;
        XBouvetIslandLbl: Label 'Bouvet Island', MaxLength = 50;
        XBritishIndianOceanLbl: Label 'British Indian Ocean Territory', MaxLength = 50;
        XBurkinaFasoLbl: Label 'Burkina Faso', MaxLength = 50;
        XBurundiLbl: Label 'Burundi', MaxLength = 50;
        XCaboVerdeLbl: Label 'Cabo Verde', MaxLength = 50;
        XCambodiaLbl: Label 'Cambodia', MaxLength = 50;
        XCameroonLbl: Label 'Cameroon', MaxLength = 50;
        XCaymanIslandsLbl: Label 'Cayman Islands', MaxLength = 50;
        XCentralAfricanLbl: Label 'Central African Republic', MaxLength = 50;
        XChadLbl: Label 'Chad', MaxLength = 50;
        XChileLbl: Label 'Chile', MaxLength = 50;
        XChristmasIslandLbl: Label 'Christmas Island', MaxLength = 50;
        XCocosIslandsLbl: Label 'Cocos Islands', MaxLength = 50;
        XColombiaLbl: Label 'Colombia', MaxLength = 50;
        XComorosLbl: Label 'Comoros', MaxLength = 50;
        XCongoDRLbl: Label 'Congo (Democratic Republic)', MaxLength = 50;
        XCongoLbl: Label 'Congo', MaxLength = 50;
        XCookIslandsLbl: Label 'Cook Islands', MaxLength = 50;
        XCubaLbl: Label 'Cuba', MaxLength = 50;
        XCuracaoLbl: Label 'Curaçao', MaxLength = 50;
        XCotedIvoireLbl: Label 'Côte d''Ivoire', MaxLength = 50;
        XDjiboutiLbl: Label 'Djibouti', MaxLength = 50;
        XDominicaLbl: Label 'Dominica', MaxLength = 50;
        XDominicanLbl: Label 'Dominican Republic', MaxLength = 50;
        XEcuadorLbl: Label 'Ecuador', MaxLength = 50;
        XEgyptLbl: Label 'Egypt', MaxLength = 50;
        XElSalvadorLbl: Label 'El Salvador', MaxLength = 50;
        XEquatorialGuineaLbl: Label 'Equatorial Guinea', MaxLength = 50;
        XEritreaLbl: Label 'Eritrea', MaxLength = 50;
        XEthiopiaLbl: Label 'Ethiopia', MaxLength = 50;
        XFalklandIslandsLbl: Label 'Falkland Islands', MaxLength = 50;
        XFaroeIslandsLbl: Label 'Faroe Islands', MaxLength = 50;
        XFrenchGuianaLbl: Label 'French Guiana', MaxLength = 50;
        XFrenchPolynesiaLbl: Label 'French Polynesia', MaxLength = 50;
        XFrenchSouthernLbl: Label 'French Southern Territories', MaxLength = 50;
        XGabonLbl: Label 'Gabon', MaxLength = 50;
        XGambiaLbl: Label 'Gambia', MaxLength = 50;
        XGeorgiaLbl: Label 'Georgia', MaxLength = 50;
        XGhanaLbl: Label 'Ghana', MaxLength = 50;
        XGibraltarLbl: Label 'Gibraltar', MaxLength = 50;
        XGreenlandLbl: Label 'Greenland', MaxLength = 50;
        XGrenadaLbl: Label 'Grenada', MaxLength = 50;
        XGuadeloupeLbl: Label 'Guadeloupe', MaxLength = 50;
        XGuamLbl: Label 'Guam', MaxLength = 50;
        XGuatemalaLbl: Label 'Guatemala', MaxLength = 50;
        XGuernseyLbl: Label 'Guernsey', MaxLength = 50;
        XGuineaLbl: Label 'Guinea', MaxLength = 50;
        XGuineaBissauLbl: Label 'Guinea-Bissau', MaxLength = 50;
        XGuyanaLbl: Label 'Guyana', MaxLength = 50;
        XHaitiLbl: Label 'Haiti', MaxLength = 50;
        XHeardIslandLbl: Label 'Heard Island and McDonald Islands', MaxLength = 50;
        XHolySeeLbl: Label 'Holy See', MaxLength = 50;
        XHondurasLbl: Label 'Honduras', MaxLength = 50;
        XHongKongLbl: Label 'Hong Kong', MaxLength = 50;
        XIsleManLbl: Label 'Isle of Man', MaxLength = 50;
        XIsraelLbl: Label 'Israel', MaxLength = 50;
        XJamaicaLbl: Label 'Jamaica', MaxLength = 50;
        XJerseyLbl: Label 'Jersey', MaxLength = 50;
        XJordanLbl: Label 'Jordan', MaxLength = 50;
        XKazakhstanLbl: Label 'Kazakhstan', MaxLength = 50;
        XKiribatiLbl: Label 'Kiribati', MaxLength = 50;
        XNorthKoreaLbl: Label 'North Korea', MaxLength = 50;
        XSouthKoreaLbl: Label 'South Korea', MaxLength = 50;
        XKuwaitLbl: Label 'Kuwait', MaxLength = 50;
        XKyrgyzstanLbl: Label 'Kyrgyzstan', MaxLength = 50;
        XLaosLbl: Label 'Laos', MaxLength = 50;
        XLebanonLbl: Label 'Lebanon', MaxLength = 50;
        XLesothoLbl: Label 'Lesotho', MaxLength = 50;
        XLiberiaLbl: Label 'Liberia', MaxLength = 50;
        XLibyaLbl: Label 'Libya', MaxLength = 50;
        XLiechtensteinLbl: Label 'Liechtenstein', MaxLength = 50;
        XMacaoLbl: Label 'Macao', MaxLength = 50;
        XMadagascarLbl: Label 'Madagascar', MaxLength = 50;
        XMalawiLbl: Label 'Malawi', MaxLength = 50;
        XMaldivesLbl: Label 'Maldives', MaxLength = 50;
        XMaliLbl: Label 'Mali', MaxLength = 50;
        XMarshallIslandsLbl: Label 'Marshall Islands', MaxLength = 50;
        XMartiniqueLbl: Label 'Martinique', MaxLength = 50;
        XMauritaniaLbl: Label 'Mauritania', MaxLength = 50;
        XMauritiusLbl: Label 'Mauritius', MaxLength = 50;
        XMayotteLbl: Label 'Mayotte', MaxLength = 50;
        XMicronesiaLbl: Label 'Micronesia', MaxLength = 50;
        XMoldovaLbl: Label 'Moldova', MaxLength = 50;
        XMonacoLbl: Label 'Monaco', MaxLength = 50;
        XMongoliaLbl: Label 'Mongolia', MaxLength = 50;
        XMontserratLbl: Label 'Montserrat', MaxLength = 50;
        XMyanmarLbl: Label 'Myanmar', MaxLength = 50;
        XNamibiaLbl: Label 'Namibia', MaxLength = 50;
        XNauruLbl: Label 'Nauru', MaxLength = 50;
        XNepalLbl: Label 'Nepal', MaxLength = 50;
        XNewCaledoniaLbl: Label 'New Caledonia', MaxLength = 50;
        XNigerLbl: Label 'Niger', MaxLength = 50;
        XNiueLbl: Label 'Niue', MaxLength = 50;
        XNorfolkIslandLbl: Label 'Norfolk Island', MaxLength = 50;
        XNorthMacedoniaLbl: Label 'North Macedonia', MaxLength = 50;
        XNorthernMarianaLbl: Label 'Northern Mariana Islands', MaxLength = 50;
        XOmanLbl: Label 'Oman', MaxLength = 50;
        XPakistanLbl: Label 'Pakistan', MaxLength = 50;
        XPalauLbl: Label 'Palau', MaxLength = 50;
        XPalestineLbl: Label 'Palestine', MaxLength = 50;
        XPanamaLbl: Label 'Panama', MaxLength = 50;
        XPapuaNewGuineaLbl: Label 'Papua New Guinea', MaxLength = 50;
        XParaguayLbl: Label 'Paraguay', MaxLength = 50;
        XPeruLbl: Label 'Peru', MaxLength = 50;
        XPitcairnLbl: Label 'Pitcairn', MaxLength = 50;
        XPuertoRicoLbl: Label 'Puerto Rico', MaxLength = 50;
        XQatarLbl: Label 'Qatar', MaxLength = 50;
        XRwandaLbl: Label 'Rwanda', MaxLength = 50;
        XReunionLbl: Label 'Réunion', MaxLength = 50;
        XSaintBarthelemyLbl: Label 'Saint Barthélemy', MaxLength = 50;
        XSaintHelenaLbl: Label 'Saint Helena, Ascension and Tristan da Cunha', MaxLength = 50;
        XSaintKittsNevisLbl: Label 'Saint Kitts and Nevis', MaxLength = 50;
        XSaintLuciaLbl: Label 'Saint Lucia', MaxLength = 50;
        XSaintMartinLbl: Label 'Saint Martin', MaxLength = 50;
        XSaintPierreQuelonLbl: Label 'Saint Pierre and Miquelon', MaxLength = 50;
        XSaintVincentLbl: Label 'Saint Vincent and the Grenadines', MaxLength = 50;
        XSanMarinoLbl: Label 'San Marino', MaxLength = 50;
        XSaoTomeLbl: Label 'São Tomé and Príncipe', MaxLength = 50;
        XSenegalLbl: Label 'Senegal', MaxLength = 50;
        XSeychellesLbl: Label 'Seychelles', MaxLength = 50;
        XSierraLeoneLbl: Label 'Sierra Leone', MaxLength = 50;
        XSintMaartenLbl: Label 'Sint Maarten', MaxLength = 50;
        XSomaliaLbl: Label 'Somalia', MaxLength = 50;
        XSouthGeorgiaLbl: Label 'South Georgia and the South Sandwich Islands', MaxLength = 50;
        XSouthSudanLbl: Label 'South Sudan', MaxLength = 50;
        XSriLankaLbl: Label 'Sri Lanka', MaxLength = 50;
        XSudanLbl: Label 'Sudan', MaxLength = 50;
        XSurinameLbl: Label 'Suriname', MaxLength = 50;
        XSvalbardJanMayenLbl: Label 'Svalbard and Jan Mayen', MaxLength = 50;
        XSyriaLbl: Label 'Syrian Arab Republic', MaxLength = 50;
        XTaiwanLbl: Label 'Taiwan', MaxLength = 50;
        XTajikistanLbl: Label 'Tajikistan', MaxLength = 50;
        XTimorLesteLbl: Label 'Timor-Leste', MaxLength = 50;
        XTogoLbl: Label 'Togo', MaxLength = 50;
        XTokelauLbl: Label 'Tokelau', MaxLength = 50;
        XTongaLbl: Label 'Tonga', MaxLength = 50;
        XTrinidadTobagoLbl: Label 'Trinidad and Tobago', MaxLength = 50;
        XTurkmenistanLbl: Label 'Turkmenistan', MaxLength = 50;
        XTurksCalcosLbl: Label 'Turks and Caicos Islands', MaxLength = 50;
        XTuvaluLbl: Label 'Tuvalu', MaxLength = 50;
        XUkraineLbl: Label 'Ukraine', MaxLength = 50;
        XUSMinorOutlyingLbl: Label 'US Minor Outlying Islands', MaxLength = 50;
        XUruguayLbl: Label 'Uruguay', MaxLength = 50;
        XUzbekistanLbl: Label 'Uzbekistan', MaxLength = 50;
        XVenezuelLbl: Label 'Venezuela', MaxLength = 50;
        XVietnamLbl: Label 'Vietnam', MaxLength = 50;
        XVirginIslandsBrLbl: Label 'British Virgin Islands', MaxLength = 50;
        XVirginIslandsUSLbl: Label 'US Virgin Islands', MaxLength = 50;
        XWallisatunaLbl: Label 'Wallis and Futuna', MaxLength = 50;
        XWesternSaharaLbl: Label 'Western Sahara', MaxLength = 50;
        XYemenLbl: Label 'Yemen', MaxLength = 50;
        XZambiaLbl: Label 'Zambia', MaxLength = 50;
        XZimbabweLbl: Label 'Zimbabwe', MaxLength = 50;
        XAlandIslandsLbl: Label 'Åland Islands', MaxLength = 50;

    procedure InsertData("Code": Code[10]; Name: Text[50]; ISONumericCode: Code[3]; "EU Country Code": Code[10]; "Intrastat Code": Code[10]; "Address Format": Option; "Contact Address Format": Option; VATScheme: Code[10]; CountyName: Text[30])
    begin
        InsertDataExtended(
          Code, Name, CopyStr(Code, 1, 2), ISONumericCode, "EU Country Code",
          "Intrastat Code", "Address Format", "Contact Address Format", VATScheme, CountyName);
    end;

    procedure InsertDataExtended("Code": Code[10]; Name: Text[50]; ISOCode: Code[2]; ISONumericCode: Code[3]; "EU Country Code": Code[10]; "Intrastat Code": Code[10]; "Address Format": Option; "Contact Address Format": Option; VATScheme: Code[10]; CountyName: Text[30])
    begin
        Country.Init();
        Country.Validate(Code, Code);
        Country.Validate("ISO Code", ISOCode);
        Country.Validate("ISO Numeric Code", ISONumericCode);
        Country.Validate(Name, Name);
        Country.Validate("EU Country/Region Code", "EU Country Code");
        Country.Validate("Intrastat Code", "Intrastat Code");
        Country.Validate("Address Format", "Address Format");
        Country.Validate("Contact Address Format", "Contact Address Format");
        Country.Validate("VAT Scheme", VATScheme);
        Country.Validate("County Name", CountyName);
        if Country.Insert(true) then;
    end;

    procedure InsertVATRegNoFormat("Country Code": Code[10]; "Line No.": Integer; Format: Text[20])
    begin
        VATRegNoFormat.Init();
        VATRegNoFormat.Validate("Country/Region Code", "Country Code");
        VATRegNoFormat.Validate("Line No.", "Line No.");
        VATRegNoFormat.Validate(Format, Format);
        if VATRegNoFormat.Insert(true) then;
    end;
}

