// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.ExpenseAgent;

permissionset 6904 "Expense Management - Objects"
{
    Caption = 'Expense Management - Objects';
    Access = Internal;
    Assignable = false;

    Permissions =
        table Expense = X,
        table "Expense Category" = X,
        table "Expense Report Comment Line" = X,
        table "Expense User" = X,
        table "Expense Group" = X,
        table "Expense Itemization" = X,
        table "Expense Location" = X,
        table "Expense Agent Setup" = X,
        table "Expense Agent Status" = X,
#if not CLEAN29
#pragma warning disable AL0432 // Object is obsoleted
        table "Expense Agent Consumption" = X,
#pragma warning restore AL0432
#endif
        table "Expense Agent Env. Consumption" = X,
        table "Expense Participant" = X,
        table "Expense Rule Condition" = X,
        table "Expense Rule Header" = X,
        table "Expense Payment Method" = X,
        table "Expense Posting Group" = X,
        table "Expense Report Header" = X,
        table "Expense Report Line" = X,
        table "Expense Report Line Particip." = X,
        table "Expense Report Line Per Diem" = X,
        table "Expense Subcategory" = X,
        table "Expense Per Diem" = X,
        table "Expense Report Line Item" = X,
        table "Posted Exp. Rep. Line Particip" = X,
        table "Posted Expense Report Header" = X,
        table "Posted Expense Report Line" = X,
        table "Posted Exp. Rep. Line Item" = X,
        table "Posted Exp. Rep. Line Per Diem" = X,
        table "Expense Ledger Entry" = X,
        table "EA Email" = X,
        table "EA Email Attachment" = X,
        table "EA Scheduler Task" = X,
        table "Expense Approval Setup" = X,
        table "Expense Team" = X,
        table "Expense Rule Violation" = X,
        table "Expense Report Rule Violation" = X,
        table "Expense Policy" = X,
        table "Expense Policy Evaluation" = X,
        table "Posted Exp. Policy Evaluation" = X,
        table "Tenant Feedback Setting" = X,
        table "EA Outbox Email" = X,
        table "EA KPI" = X,
        table "EA KPI Entry" = X,
        table "Expense VAT Specification" = X,
        table "Expense Report Line VAT Spec." = X,
        table "Posted Exp. Rep. Line VAT Spec" = X,
        table "Expense Vendor" = X,
        table "Expense Capabilities Buffer" = X,
        table Traveler = X,
        table "Expense Activity Log Entry" = X,
        table "Expense Project Buf" = X,
        table "Expense Vehicle Type" = X,
        table "Mileage Rate Setup" = X,
        page "EA Billing Overview" = X,
        page "EA Scheduler Tasks" = X,
        page "EA Outbox Emails" = X,
        page "Expense Report Line Items" = X,
        page "Expense VAT Specification" = X,
        page "Expense VAT Spec. FactBox" = X,
        page "Expense Report Line VAT Spec." = X,
        page "Expense Report Line VATFactBox" = X,
        page Expense = X,
        page "Expense Categories" = X,
        page "Expense Category Card" = X,
        page "Expense Report Comment Sheet" = X,
        page "Expense User" = X,
        page "Expense Users" = X,
        page "Expense Factbox" = X,
        page "Expense Groups" = X,
        page "Expense Itemizations" = X,
        page "Expense Location Card" = X,
        page "Expense Locations" = X,
        page "Expense Management Rules" = X,
        page "Expense Agent Setup" = X,
        page "Expense Agent Status" = X,
        page "Expense Participants" = X,
        page "Expense Rule Card" = X,
        page "Expense Rule Conditions" = X,
        page "Expense Posting Groups" = X,
        page "Exp. Posting Groups Preview" = X,
        page "Exp. Locations Preview" = X,
        page "Exp. Payment Methods Preview" = X,
        page "Exp. No. Series Preview" = X,
        page "Exp. No. Series Lines Preview" = X,
        page "Exp. Rules Preview" = X,
        page "Exp. Rule Conditions Preview" = X,
        page "Exp. Categories Preview" = X,
        page "Exp. Subcategories Preview" = X,
        page "Expense Report" = X,
        page "Manager Expense Report" = X,
        page "Expense Report Line Particips" = X,
        page "Expense Report Line Per Diems" = X,
        page "Expense Report Lines" = X,
        page "Expense Report SubPage" = X,
        page "Expense Reports" = X,
        page "Expense Management Role Center" = X,
        page "Manager Expense Reports" = X,
        page "Expense Subcategories" = X,
        page "Expense Vendors" = X,
        page "Expense Vendor Card" = X,
        page "Accountant Expenses" = X,
        page "Accountant Expense Reports" = X,
        page Expenses = X,
        page "Per Diem Expenses" = X,
        page "Posted Exp. Rep. Line Particip" = X,
        page "Posted Expense Report" = X,
        page "Posted Expense Report Lines" = X,
        page "Posted Expense Reports" = X,
        page "Posted Exp. Rep. Line Items" = X,
        page "Posted Exp. Rep. Line Per Diem" = X,
#if not CLEAN29
#pragma warning disable AL0432
        page "Posted Exp. Report Statistics" = X,
#pragma warning restore AL0432
#endif
        page "Posted Expense Report FactBox" = X,
        page "Posted Expense Report Stats" = X,
        page "Posted Expense Report VAT Spec" = X,
        page "Expense Report VAT Spec." = X,
        page "Expense Ledger Entries" = X,
        page "Expense Approval Setup" = X,
        page "Expense Teams" = X,
        page "Add Expenses To Expense Report" = X,
        page "Expense Billing Information" = X,
        page "Expense Rule Violations" = X,
        page "Expense Report Rule Violations" = X,
        page "Expense Policies" = X,
        page "Expense Policy Evaluations" = X,
        page "Expense Policy Evaluation Card" = X,
        page "Posted Exp. Policy Evaluations" = X,
        page "Posted Policy Evaluation Card" = X,
        page "Expense Statistics" = X,
        page "Posted Expense Report SubP." = X,
        page "Posted Exp. Report Line Items" = X,
        page "Posted Expense Billing Info." = X,
        page "Expense Payment Methods" = X,
        page "Expense Report List" = X,
        page "Mileage Rate Setup" = X,
        page "Expense Vehicle Types" = X,
        page "Expense Report Stats" = X,
#if not CLEAN29
#pragma warning disable AL0432
        page "Expense Report Statistics" = X,
#pragma warning restore AL0432
#endif
        page "Expense Report FactBox" = X,
        page "Expense Activity Log FactBox" = X,
        page "Expense Approval Setups Part" = X,
        page "Expense Picture" = X,
        page Travelers = X,
        page "Travel Request Card" = X,
        page "Travel Request Subform" = X,
        page "Travel Request List" = X,
        codeunit "Travel Request Approval" = X,
        codeunit "Expense Attachment Mgt." = X,
        codeunit "Expense Auto Population" = X,
        codeunit "Expense Event Subscriber" = X,
        codeunit "Expense Agent Privacy Subs." = X,
        codeunit "Expense Consumption Handler" = X,
        codeunit "Expense Currency" = X,
        codeunit "Expense Manual Release" = X,
        codeunit "Expense Manual Reopen" = X,
        codeunit "Expense Rule Validation" = X,
        codeunit "Expense Report-Post" = X,
        codeunit "Expense Report" = X,
        codeunit "Expense Report Batch Post Mgt." = X,
        codeunit "Expense Report Manual Release" = X,
        codeunit "Expense Report Manual Reopen" = X,
        codeunit "Expense Total Caption Class" = X,
        codeunit "Cancel Posted Expense Report" = X,
        codeunit "Create Expense Report" = X,
        codeunit "Install Expense Agent Setup" = X,
        codeunit "Upgrade Expense Agent Setup" = X,
        codeunit "EA Agent Dispatcher" = X,
        codeunit "EA Agent Error Handler" = X,
        codeunit "EA Agent Recovery" = X,
        codeunit "EA Agent Scheduler" = X,
        codeunit "EA Email Setup" = X,
        codeunit "EA Http Client" = X,
        codeunit "EA Retrieve Emails" = X,
        codeunit "Release Exp. Report Document" = X,
        codeunit "Release Expense Document" = X,
        codeunit "Exp. Preview Post. Subscriber" = X,
        codeunit "Exp. Preview Posting Handler" = X,
        codeunit "Expense Preview Post Instance" = X,
        codeunit "Expense Approval Helper" = X,
        codeunit "Create Expense Agent Setup" = X,
        codeunit "Create Expense Categories" = X,
        codeunit "Create Expense VAT Rates" = X,
        codeunit "Create Expense GL Account" = X,
        codeunit "Create Expense No. Series" = X,
        codeunit "Exp. Attach. Buffer Handler" = X,
        codeunit "Expense Doc No Visibility" = X,
        codeunit "Expense Doc. Att. Subscribers" = X,
        codeunit "Expense Per Diem Calculation" = X,
        codeunit "Expense Preview Post Mgt." = X,
        codeunit "Expense Report Approval Mgmt" = X,
        codeunit "Expense Vendor Matching" = X,
        codeunit "Expense OAuth Client" = X,
        codeunit "Expense API Currency Helper" = X,
        codeunit "Expense Capabilities Provider" = X,
        codeunit "Expense Activity Log Mgt." = X,
        codeunit "Expense Projects Builder" = X,
        codeunit "Exp. Policies To Eval Builder" = X,
        codeunit "Import Expense User" = X,
        report "Expense Report Cover Page" = X,
        report "Expense Report Summary Page" = X,
        report "Expense Report Details" = X;
}