table 'Weekly Calendar Time Intelligence'
	lineageTag: b5edcdee-7bc9-4b07-b2f0-676f08cf924f

	measure 'Net Change YTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR LastDayAvailable = MAX ( 'Date'[FW DayOfYearNumber] )
			    VAR LastFiscalYearAvailable = MAX ( 'Date'[FW YearNumber] )
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW DayOfYearNumber] <= LastDayAvailable,
			            'Date'[FW YearNumber] = LastFiscalYearAvailable
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date total
		lineageTag: 5ce89637-9eb0-40a3-a406-18447e99a8c9

	measure 'Net Change QTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR LastDayAvailable =  MAX ( 'Date'[FW DayOfQuarterNumber] )
			    VAR LastFiscalYearQuarterAvailable = MAX ( 'Date'[FW YearQuarterNumber] )
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW DayOfQuarterNumber] <= LastDayAvailable,
			            'Date'[FW YearQuarterNumber] = LastFiscalYearQuarterAvailable
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date total
		lineageTag: 684c3421-9799-4914-adfc-c01ae270fcc6

	measure 'Net Change MTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR LastDayAvailable =  MAX ( 'Date'[FW DayOfMonthNumber] )
			    VAR LastFiscalYearMonthAvailable = MAX ( 'Date'[FW YearMonthNumber] )
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW DayOfMonthNumber] <= LastDayAvailable,
			            'Date'[FW YearMonthNumber] = LastFiscalYearMonthAvailable
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date total
		lineageTag: 33adc0ab-28a1-42c1-bd1f-fc336b71c0a0

	measure 'Net Change WTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR LastDayOfWeekAvailable =  MAX ( 'Date'[WeekDayNumber] )
			    VAR LastFiscalYearWeekAvailable = MAX ( 'Date'[FW YearWeekNumber] )
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[WeekDayNumber] <= LastDayOfWeekAvailable,
			            'Date'[FW YearWeekNumber] = LastFiscalYearWeekAvailable
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date total
		lineageTag: 9e6efe4a-1d25-4472-83de-730575daf1e4

	measure 'Net Change PY (Weekly)' =
			
			IF (
			    [ShowValueForDates],
			    SUMX (
			        VALUES ( 'Date'[FW YearNumber] ),
			        VAR CurrentFiscalYearNumber = 'Date'[FW YearNumber]
			        VAR DaysSelected =
			            CALCULATETABLE (
			                VALUES ( 'Date'[FW DayOfYearNumber] ),
			                REMOVEFILTERS (
			                    'Date'[Day Type],
			                    'Date'[Week Day],
			                    'Date'[WeekDayNumber]
			                ),
			                'Date'[DatesWithTransactions] = TRUE
			            )
			        RETURN
			            CALCULATE (
			                [Net Change],
			                'Date'[FW YearNumber] = CurrentFiscalYearNumber - 1,
			                DaysSelected,
			                ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] )
			            )
			    )
			)
		formatString: #,0.00
		displayFolder: Net Change\Period-over-period growth
		lineageTag: 93f7a911-438c-4ce5-b1c7-fed619c28fc1

	measure 'Net Change YOY % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change YOY (Weekly)],
			    [Net Change PY (Weekly)]
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-over-period growth
		lineageTag: 5a485417-2801-473e-8b5a-b38e1e347afb

	measure 'Net Change YOY (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change]
			VAR ValuePreviousPeriod = [Net Change PY (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-over-period growth
		lineageTag: 08c97c47-0947-407c-9d67-954a75dc70aa

	measure 'Net Change PQ (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    SUMX ( 
			        VALUES ( 'Date'[FW YearQuarterNumber] ),
			        VAR CurrentFiscalYearQuarterNumber = 'Date'[FW YearQuarterNumber]
			        VAR DaysSelected = 
			            CALCULATETABLE (
			                VALUES ( 'Date'[FW DayOfQuarterNumber] ),
			                REMOVEFILTERS (
			                    'Date'[Day Type],
			                    'Date'[Week Day],
			                    'Date'[WeekDayNumber]
			                ),
			                'Date'[DatesWithTransactions] = TRUE
			            )
			        RETURN 
			            CALCULATE (
			                [Net Change],
			                'Date'[FW YearQuarterNumber] = CurrentFiscalYearQuarterNumber - 1,
			                DaysSelected,
			                ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] )
			            )
			    )
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-over-period growth
		lineageTag: 224e9ba2-20ab-449b-80ea-9a6bf998f4ca

	measure 'Net Change QOQ (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change]
			VAR ValuePreviousPeriod = [Net Change PQ (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-over-period growth
		lineageTag: b9a25b73-2a6b-49ba-9ddd-592a0c74c1f9

	measure 'Net Change QOQ % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change QOQ (Weekly)],
			    [Net Change PQ (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-over-period growth
		lineageTag: 13f50a0b-f854-4d14-9cf5-c45567277cdf

	measure 'Net Change PW (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    SUMX ( 
			        VALUES ( 'Date'[FW YearWeekNumber] ),
			        VAR CurrentFiscalYearWeekNumber = 'Date'[FW YearWeekNumber] 
			        VAR DaysSelected = 
			            CALCULATETABLE (
			                VALUES ( 'Date'[WeekDayNumber] ),
			                REMOVEFILTERS (
			                    'Date'[Day Type],
			                    'Date'[Week Day],
			                    'Date'[WeekDayNumber]
			                ),
			                'Date'[DatesWithTransactions] = TRUE
			            )
			        RETURN 
			            CALCULATE (
			                [Net Change],
			                'Date'[FW YearWeekNumber] = CurrentFiscalYearWeekNumber - 1,
			                KEEPFILTERS ( DaysSelected ),
			                ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] )
			            )
			    )
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-over-period growth
		lineageTag: 60b99dd9-1578-4bd6-9283-d70e514c7709

	measure 'Net Change WOW (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change]
			VAR ValuePreviousPeriod = [Net Change PW (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-over-period growth
		lineageTag: fb81988b-87b3-480e-ae3f-ba4cf7dd6510

	measure 'Net Change WOW % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change WOW (Weekly)],
			    [Net Change PW (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-over-period growth
		lineageTag: c6b1ec67-2793-4b2f-aa5c-a45fcac17d65

	measure 'Net Change PP (Weekly)' = ```
			
			SWITCH ( 
			    TRUE,
			    ISINSCOPE ( 'Date'[FW Week Year] ), [Net Change PW (Weekly)],
			    -- The month level should not be managed in a 445 calendar
			    ISINSCOPE ( 'Date'[FW Quarter Year] ), [Net Change PQ (Weekly)],
			    ISINSCOPE ( 'Date'[FW Year] ), [Net Change PY (Weekly)]
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-over-period growth
		lineageTag: df60c08e-ba5d-4829-8cf2-01c411505f93

	measure 'Net Change POP (Weekly)' = ```
			
			SWITCH ( 
			    TRUE,
			    ISINSCOPE ( 'Date'[FW Week Year] ), [Net Change WOW (Weekly)],
			    -- The month level should not be managed in a 445 calendar
			    ISINSCOPE ( 'Date'[FW Quarter Year] ), [Net Change QOQ (Weekly)],
			    ISINSCOPE ( 'Date'[FW Year] ), [Net Change YOY (Weekly)]
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-over-period growth
		lineageTag: c66d8533-93bb-41a1-a347-d04bdca4f778

	measure 'Net Change POP % (Weekly)' = ```
			
			SWITCH ( 
			    TRUE,
			    ISINSCOPE ( 'Date'[FW Week Year] ), [Net Change WOW % (Weekly)],
			    -- The month level should not be managed in a 445 calendar
			    ISINSCOPE ( 'Date'[FW Quarter Year] ), [Net Change QOQ % (Weekly)],
			    ISINSCOPE ( 'Date'[FW Year] ), [Net Change YOY % (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-over-period growth
		lineageTag: 21cc5c96-ce0a-490c-9d5b-9ccf7c93d3c5

	measure 'Net Change PYTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR PreviousFiscalYear = MAX ( 'Date'[FW YearNumber] ) - 1
			    VAR LastDayOfFiscalYearAvailable = 
			        CALCULATE ( 
			            MAX ( 'Date'[FW DayOfYearNumber] ),
			            REMOVEFILTERS (                -- Remove filters from
			                'Date'[Day Type],       -- filter-safe columns
			                'Date'[Week Day],       -- to get the last day with data
			                'Date'[WeekDayNumber] -- selected in the report
			            ),
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearNumber] = PreviousFiscalYear,
			            'Date'[FW DayOfYearNumber] <= LastDayOfFiscalYearAvailable,
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date growth
		lineageTag: f43e4681-3bef-4395-9f3d-1ff4603741a2

	measure 'Net Change PQTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR PreviousFiscalYearQuarter = MAX ( 'Date'[FW YearQuarterNumber] ) - 1
			    VAR LastDayOfFiscalYearQuarterAvailable = 
			        CALCULATE ( 
			            MAX ( 'Date'[FW DayOfQuarterNumber] ),
			            REMOVEFILTERS (                -- Remove filters from
			                'Date'[Day Type],       -- filter-safe columns
			                'Date'[Week Day],       -- to get the last day with data
			                'Date'[WeekDayNumber] -- selected in the report
			            ),
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearQuarterNumber] = PreviousFiscalYearQuarter,
			            'Date'[FW DayOfQuarterNumber] <= LastDayOfFiscalYearQuarterAvailable,
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date growth
		lineageTag: e557faad-f9a4-4304-9ca9-3b631bc1f6fb

	measure 'Net Change YOYTD (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change YTD (Weekly)]
			VAR ValuePreviousPeriod = [Net Change PYTD (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date growth
		lineageTag: a6db5fc1-b670-4b7f-b3eb-dd037de9cb05

	measure 'Net Change YOYTD % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change YOYTD (Weekly)],
			    [Net Change PYTD (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-to-date growth
		lineageTag: 774f0d14-e81d-4c27-90a2-7060b7db7655

	measure 'Net Change QOQTD (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change QTD (Weekly)]
			VAR ValuePreviousPeriod = [Net Change PQTD (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date growth
		lineageTag: 5a343c2d-0e6a-4cbc-b27f-ae5c2ea7b2f3

	measure 'Sales Amount QOQTD % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change QOQTD (Weekly)],
			    [Net Change PQTD (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-to-date growth
		lineageTag: d59db534-8368-49b0-8d5d-df467a20ce12

	measure 'Net Change PWTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR PreviousFiscalYearWeek = MAX ( 'Date'[FW YearWeekNumber] ) - 1
			    VAR LastDayOfWeekAvailable = 
			        CALCULATE ( 
			            MAX ( 'Date'[WeekDayNumber] ),
			            REMOVEFILTERS (                -- Remove filters from
			                'Date'[Day Type],       -- filter-safe columns
			                'Date'[Week Day],       -- to get the last day with data
			                'Date'[WeekDayNumber] -- selected in the report
			            ),
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearWeekNumber] = PreviousFiscalYearWeek,
			            'Date'[WeekDayNumber] <= LastDayOfWeekAvailable,
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date growth
		lineageTag: aaeadd64-0a61-4783-a58c-2f66b1a675dc

	measure 'Net Change WOWTD (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change WTD (Weekly)]
			VAR ValuePreviousPeriod = [Net Change PWTD (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date growth
		lineageTag: 1ae27b0a-e613-46de-956d-d76f8fceb41e

	measure 'Net Change WOWTD % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change WOWTD (Weekly)],
			    [Net Change PWTD (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-to-date growth
		lineageTag: 2337a7a6-cb4f-4059-b087-372be29a2738

	measure 'Net Change MAT (364) (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates], 
			    VAR LastDayMAT =  MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 363
			    VAR Result = 
			        CALCULATE ( 
			            [Net Change], 
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT 
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT
			        ) 
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Moving annual total growth
		lineageTag: 17d69d56-8459-4516-bacc-4b4211506fab

	measure 'Net Change PYMAT (364) (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates], 
			    VAR LastDayAvailable = MAX ( 'Date'[Sequential365DayNumber] )
			    VAR LastDayMAT = LastDayAvailable - 364 -- go back 52 weeks
			    VAR FirstDayMAT = LastDayMAT - 363
			    VAR Result = 
			        CALCULATE ( 
			            [Net Change], 
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT 
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT
			        ) 
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Moving annual total growth
		lineageTag: 54725121-ea6b-4f9f-b4a3-ddaf772ab546

	measure 'Net Change MATG (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change MAT (364) (Weekly)]
			VAR ValuePreviousPeriod = [Net Change PYMAT (364) (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Moving annual total growth
		lineageTag: ba27f3d6-4793-482f-92bb-c947c8cbe72f

	measure 'Net Change MATG % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change MATG (Weekly)],
			    [Net Change PYMAT (364) (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Moving annual total growth
		lineageTag: febc92bc-ac26-4e14-bc35-4b45eb239a65

	measure 'Net Change PYC (Weekly)' = ```
			
			IF (
			    [ShowValueForDates] && HASONEVALUE ( 'Date'[FW YearNumber] ),
			    VAR PreviousFiscalYear = MAX ( 'Date'[FW YearNumber] ) - 1
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearNumber] = PreviousFiscalYear
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: d971b565-75bb-4373-ab89-12b67d18d071

	measure 'Net Change YTDOPY (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change YTD (Weekly)]
			VAR ValuePreviousPeriod = [Net Change PYC (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: 1d8c9b78-a143-4727-9e7f-fdc76731c318

	measure 'Net Change YTDOPY % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change YTDOPY (Weekly)],
			    [Net Change PYC (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: dbde4cb0-2279-4f9a-b9fc-a9983234b0f6

	measure 'Net Change PQC (Weekly)' =
			
			IF (
			    [ShowValueForDates] && HASONEVALUE ( 'Date'[FW YearQuarterNumber] ),
			    VAR PreviousFiscalYearQuarter = MAX ( 'Date'[FW YearQuarterNumber] ) - 1
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearQuarterNumber] = PreviousFiscalYearQuarter
			        )
			    RETURN
			        Result
			)
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: a7e48503-776f-49e8-99c8-fa5ac6bb7b68

	measure 'Net Change QTDOPQ (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change QTD (Weekly)]
			VAR ValuePreviousPeriod = [Net Change PQC (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: 183a93e9-a97b-4e7c-9705-92fb14188e32

	measure 'Net Change QTDOPQ % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change QTDOPQ (Weekly)],
			    [Net Change PQC (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: a579821d-97ea-410a-a318-f4625b8479db

	measure 'Net Change PWC (Weekly)' = ```
			
			IF (
			    [ShowValueForDates] && HASONEVALUE ( 'Date'[FW YearWeekNumber] ),
			    VAR PreviousFiscalYearWeek = MAX ( 'Date'[FW YearWeekNumber] ) - 1
			    VAR Result =
			        CALCULATE (
			            [Net Change],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearWeekNumber] = PreviousFiscalYearWeek
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: d11bde8f-affa-4e2c-88ac-3b9c4b1f83a8

	measure 'Net Change WTDOPW (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Net Change WTD (Weekly)]
			VAR ValuePreviousPeriod = [Net Change PWC (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: 3e901542-c858-4aae-8ebc-c1dcace181e9

	measure 'Net Change WTDOPW % (Weekly)' = ```
			
			DIVIDE ( 
			    [Net Change WTDOPW (Weekly)],
			    [Net Change PWC (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Net Change\Period-to-date over full previous period
		lineageTag: 3c326be1-dd6e-4e96-9f8f-8aa7686d33e5

	measure 'Net Change AVG 4W (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    VAR LastDayMAT =
			        MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 27
			    VAR Period4W =
			        CALCULATETABLE (
			            VALUES ( 'Date'[Sequential365DayNumber] ),
			            ALLEXCEPT (
			                'Date',
			                'Date'[Day Type],
			                'Date'[Week Day]
			            ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT 
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT,
			            'Date'[DatesWithTransactions] = TRUE
			        )
			    VAR FirstDayWithData =
			        CALCULATE (
			            MIN ( 'G/L Entries'[Posting Date] ),
			            REMOVEFILTERS ()
			        )
			    VAR FirstDayInPeriod =
			        MINX (
			            Period4W,
			            'Date'[Sequential365DayNumber]
			        )
			    VAR Result =
			        IF (
			            FirstDayWithData <= FirstDayInPeriod,
			            CALCULATE (
			                AVERAGEX ( Period4W, [Net Change] ),
			                REMOVEFILTERS ( 'Date' )
			            )
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Moving averages
		lineageTag: b0f59b71-e53f-49c3-8ad3-fe52b83c5313

	measure 'Net Change AVG 1Q (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    VAR LastDayMAT =
			        MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 13 * 7 + 1
			    VAR Period1Q =
			        CALCULATETABLE (
			            VALUES ( 'Date'[Sequential365DayNumber] ),
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT 
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT,
			            'Date'[DatesWithTransactions] = TRUE
			        )
			    VAR FirstDayWithData =
			        CALCULATE (
			            MIN ( 'G/L Entries'[Posting Date] ),
			            REMOVEFILTERS ()
			        )
			    VAR FirstDayInPeriod =
			        MINX (
			            Period1Q,
			            'Date'[Sequential365DayNumber]
			        )
			    VAR Result =
			        IF (
			            FirstDayWithData <= FirstDayInPeriod,
			            CALCULATE (
			                AVERAGEX ( Period1Q, [Net Change] ),
			                REMOVEFILTERS ( 'Date' )
			            )
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Moving averages
		lineageTag: 1ee904cb-cf20-4173-8b29-b1413c873ba6

	measure 'Net Change AVG 1Y (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    VAR LastDayMAT =
			        MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 363
			    VAR Period1Y =
			        CALCULATETABLE (
			            VALUES ( 'Date'[Sequential365DayNumber] ),
			            ALLEXCEPT (
			                'Date',
			                'Date'[Day Type],
			                'Date'[Week Day]
			            ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT,
			            'Date'[DatesWithTransactions] = TRUE
			        )
			    VAR FirstDayWithData =
			        CALCULATE (
			            MIN ( 'G/L Entries'[Posting Date] ),
			            REMOVEFILTERS ()
			        )
			    VAR FirstDayInPeriod =
			        MINX (
			            Period1Y,
			            'Date'[Sequential365DayNumber]
			        )
			    VAR Result =
			        IF (
			            FirstDayWithData <= FirstDayInPeriod,
			            CALCULATE (
			                AVERAGEX ( Period1Y, [Net Change] ),
			                REMOVEFILTERS ( 'Date' )
			            )
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Net Change\Moving averages
		lineageTag: bf5ea3d0-02a0-4088-b308-33a68787677e

	measure 'Balance at Date YTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR LastDayAvailable = MAX ( 'Date'[FW DayOfYearNumber] )
			    VAR LastFiscalYearAvailable = MAX ( 'Date'[FW YearNumber] )
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW DayOfYearNumber] <= LastDayAvailable,
			            'Date'[FW YearNumber] = LastFiscalYearAvailable
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date total
		lineageTag: 3b704581-3a80-4a7e-8d0e-4742c68b1267

	measure 'Balance at Date QTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR LastDayAvailable =  MAX ( 'Date'[FW DayOfQuarterNumber] )
			    VAR LastFiscalYearQuarterAvailable = MAX ( 'Date'[FW YearQuarterNumber] )
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW DayOfQuarterNumber] <= LastDayAvailable,
			            'Date'[FW YearQuarterNumber] = LastFiscalYearQuarterAvailable
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date total
		lineageTag: b8cd7f36-ac2b-4ca2-b0a9-a8668f4946c2

	measure 'Balance at Date MTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR LastDayAvailable =  MAX ( 'Date'[FW DayOfMonthNumber] )
			    VAR LastFiscalYearMonthAvailable = MAX ( 'Date'[FW YearMonthNumber] )
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW DayOfMonthNumber] <= LastDayAvailable,
			            'Date'[FW YearMonthNumber] = LastFiscalYearMonthAvailable
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date total
		lineageTag: afe852c7-d544-46a9-b324-fe5a5e80a081

	measure 'Balance at Date WTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR LastDayOfWeekAvailable =  MAX ( 'Date'[WeekDayNumber] )
			    VAR LastFiscalYearWeekAvailable = MAX ( 'Date'[FW YearWeekNumber] )
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[WeekDayNumber] <= LastDayOfWeekAvailable,
			            'Date'[FW YearWeekNumber] = LastFiscalYearWeekAvailable
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date total
		lineageTag: af7d8847-59a5-4564-a5db-1127713ed1b4

	measure 'Balance at Date PY (Weekly)' =
			
			IF (
			    [ShowValueForDates],
			    SUMX (
			        VALUES ( 'Date'[FW YearNumber] ),
			        VAR CurrentFiscalYearNumber = 'Date'[FW YearNumber]
			        VAR DaysSelected =
			            CALCULATETABLE (
			                VALUES ( 'Date'[FW DayOfYearNumber] ),
			                REMOVEFILTERS (
			                    'Date'[Day Type],
			                    'Date'[Week Day],
			                    'Date'[WeekDayNumber]
			                ),
			                'Date'[DatesWithTransactions] = TRUE
			            )
			        RETURN
			            CALCULATE (
			                [Balance at Date],
			                'Date'[FW YearNumber] = CurrentFiscalYearNumber - 1,
			                DaysSelected,
			                ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] )
			            )
			    )
			)
		formatString: #,0.00
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: 1d3d6e90-23bd-4f79-bcb3-a4b998210d2a

	measure 'Balance at Date YOY % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date YOY (Weekly)],
			    [Balance at Date PY (Weekly)]
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: 32264947-72e4-4793-b04e-80c061947581

	measure 'Balance at Date YOY (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date]
			VAR ValuePreviousPeriod = [Balance at Date PY (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: 61a64b2b-673b-4a18-af83-cf3a9e4cf226

	measure 'Balance at Date PQ (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    SUMX ( 
			        VALUES ( 'Date'[FW YearQuarterNumber] ),
			        VAR CurrentFiscalYearQuarterNumber = 'Date'[FW YearQuarterNumber]
			        VAR DaysSelected = 
			            CALCULATETABLE (
			                VALUES ( 'Date'[FW DayOfQuarterNumber] ),
			                REMOVEFILTERS (
			                    'Date'[Day Type],
			                    'Date'[Week Day],
			                    'Date'[WeekDayNumber]
			                ),
			                'Date'[DatesWithTransactions] = TRUE
			            )
			        RETURN 
			            CALCULATE (
			                [Balance at Date],
			                'Date'[FW YearQuarterNumber] = CurrentFiscalYearQuarterNumber - 1,
			                DaysSelected,
			                ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] )
			            )
			    )
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: f7e533b0-47ee-4011-b98d-280a2f2dc4aa

	measure 'Balance at Date QOQ (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date]
			VAR ValuePreviousPeriod = [Balance at Date PQ (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: 7023a59a-f6b8-456b-985d-a1bba4561b59

	measure 'Balance at Date QOQ % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date QOQ (Weekly)],
			    [Balance at Date PQ (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: b1046c7d-e80c-4fb2-9f12-6c949f2e36cb

	measure 'Balance at Date PW (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    SUMX ( 
			        VALUES ( 'Date'[FW YearWeekNumber] ),
			        VAR CurrentFiscalYearWeekNumber = 'Date'[FW YearWeekNumber] 
			        VAR DaysSelected = 
			            CALCULATETABLE (
			                VALUES ( 'Date'[WeekDayNumber] ),
			                REMOVEFILTERS (
			                    'Date'[Day Type],
			                    'Date'[Week Day],
			                    'Date'[WeekDayNumber]
			                ),
			                'Date'[DatesWithTransactions] = TRUE
			            )
			        RETURN 
			            CALCULATE (
			                [Balance at Date],
			                'Date'[FW YearWeekNumber] = CurrentFiscalYearWeekNumber - 1,
			                KEEPFILTERS ( DaysSelected ),
			                ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] )
			            )
			    )
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: 709ce724-6f95-4e7c-9b81-f6505cad5704

	measure 'Balance at Date WOW (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date]
			VAR ValuePreviousPeriod = [Balance at Date PW (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: bba7a844-ce46-4919-90d3-2c47becd123d

	measure 'Balance at Date WOW % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date WOW (Weekly)],
			    [Balance at Date PW (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: cb3305fa-e30d-47c3-9d92-f55543e70ef7

	measure 'Balance at Date PP (Weekly)' = ```
			
			SWITCH ( 
			    TRUE,
			    ISINSCOPE ( 'Date'[FW Week Year] ), [Balance at Date PW (Weekly)],
			    -- The month level should not be managed in a 445 calendar
			    ISINSCOPE ( 'Date'[FW Quarter Year] ), [Balance at Date PQ (Weekly)],
			    ISINSCOPE ( 'Date'[FW Year] ), [Balance at Date PY (Weekly)]
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: 59dc5f90-eeab-41ef-919d-f60b17206cb5

	measure 'Balance at Date POP (Weekly)' = ```
			
			SWITCH ( 
			    TRUE,
			    ISINSCOPE ( 'Date'[FW Week Year] ), [Balance at Date WOW (Weekly)],
			    -- The month level should not be managed in a 445 calendar
			    ISINSCOPE ( 'Date'[FW Quarter Year] ), [Balance at Date QOQ (Weekly)],
			    ISINSCOPE ( 'Date'[FW Year] ), [Balance at Date YOY (Weekly)]
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: 64ab27cf-9b58-47ac-857d-2f7555817705

	measure 'Balance at Date POP % (Weekly)' = ```
			
			SWITCH ( 
			    TRUE,
			    ISINSCOPE ( 'Date'[FW Week Year] ), [Balance at Date WOW % (Weekly)],
			    -- The month level should not be managed in a 445 calendar
			    ISINSCOPE ( 'Date'[FW Quarter Year] ), [Balance at Date QOQ % (Weekly)],
			    ISINSCOPE ( 'Date'[FW Year] ), [Balance at Date YOY % (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-over-period growth
		lineageTag: de9b60da-8db0-4873-b10b-b9b639f61320

	measure 'Balance at Date PYTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR PreviousFiscalYear = MAX ( 'Date'[FW YearNumber] ) - 1
			    VAR LastDayOfFiscalYearAvailable = 
			        CALCULATE ( 
			            MAX ( 'Date'[FW DayOfYearNumber] ),
			            REMOVEFILTERS (                -- Remove filters from
			                'Date'[Day Type],       -- filter-safe columns
			                'Date'[Week Day],       -- to get the last day with data
			                'Date'[WeekDayNumber] -- selected in the report
			            ),
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearNumber] = PreviousFiscalYear,
			            'Date'[FW DayOfYearNumber] <= LastDayOfFiscalYearAvailable,
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: b2c6f444-e763-4d13-87ee-9fb9f89cdafb

	measure 'Balance at Date PQTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR PreviousFiscalYearQuarter = MAX ( 'Date'[FW YearQuarterNumber] ) - 1
			    VAR LastDayOfFiscalYearQuarterAvailable = 
			        CALCULATE ( 
			            MAX ( 'Date'[FW DayOfQuarterNumber] ),
			            REMOVEFILTERS (                -- Remove filters from
			                'Date'[Day Type],       -- filter-safe columns
			                'Date'[Week Day],       -- to get the last day with data
			                'Date'[WeekDayNumber] -- selected in the report
			            ),
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearQuarterNumber] = PreviousFiscalYearQuarter,
			            'Date'[FW DayOfQuarterNumber] <= LastDayOfFiscalYearQuarterAvailable,
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: 348591ae-c150-4cdf-877d-bbac132d6339

	measure 'Balance at Date YOYTD (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date YTD (Weekly)]
			VAR ValuePreviousPeriod = [Balance at Date PYTD (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: 0e059e65-be2d-4ce7-8bf5-3108ee097444

	measure 'Balance at Date YOYTD % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date YOYTD (Weekly)],
			    [Balance at Date PYTD (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: 4c39b6f1-d7f3-4772-9485-f995aa07786b

	measure 'Balance at Date QOQTD (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date QTD (Weekly)]
			VAR ValuePreviousPeriod = [Balance at Date PQTD (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: 8fb7ceea-2c95-4387-8983-c2a621e1a0bd

	measure 'Balance at Date QOQTD % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date QOQTD (Weekly)],
			    [Balance at Date PQTD (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: 698a9a1d-1c94-474a-b044-6d306c28f22f

	measure 'Balance at Date PWTD (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates],
			    VAR PreviousFiscalYearWeek = MAX ( 'Date'[FW YearWeekNumber] ) - 1
			    VAR LastDayOfWeekAvailable = 
			        CALCULATE ( 
			            MAX ( 'Date'[WeekDayNumber] ),
			            REMOVEFILTERS (                -- Remove filters from
			                'Date'[Day Type],       -- filter-safe columns
			                'Date'[Week Day],       -- to get the last day with data
			                'Date'[WeekDayNumber] -- selected in the report
			            ),
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearWeekNumber] = PreviousFiscalYearWeek,
			            'Date'[WeekDayNumber] <= LastDayOfWeekAvailable,
			            'Date'[DatesWithTransactions] = TRUE 
			        )
			    RETURN
			        Result
			)
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: c24f6c17-097f-401d-a19f-a98f5d294da9

	measure 'Balance at Date WOWTD (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date WTD (Weekly)]
			VAR ValuePreviousPeriod = [Balance at Date PWTD (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: 33cf4a14-4cb1-4e58-8e2c-cb48f52336a5

	measure 'Balance at Date WOWTD % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date WOWTD (Weekly)],
			    [Balance at Date PWTD (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-to-date growth
		lineageTag: 3e285be1-dff8-48b6-82c5-1a38a3cf70b8

	measure 'Balance at Date MAT (364) (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates], 
			    VAR LastDayMAT =  MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 363
			    VAR Result = 
			        CALCULATE ( 
			            [Balance at Date], 
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT 
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT
			        ) 
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Moving annual total growth
		lineageTag: fbc270f3-299e-41bc-9f59-d890e9246b2c

	measure 'Balance at Date PYMAT (364) (Weekly)' = ```
			
			IF ( 
			    [ShowValueForDates], 
			    VAR LastDayAvailable = MAX ( 'Date'[Sequential365DayNumber] )
			    VAR LastDayMAT = LastDayAvailable - 364 -- go back 52 weeks
			    VAR FirstDayMAT = LastDayMAT - 363
			    VAR Result = 
			        CALCULATE ( 
			            [Balance at Date], 
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT 
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT
			        ) 
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Moving annual total growth
		lineageTag: 052cf896-05a4-428a-9719-f582a789e468

	measure 'Balance at Date MATG (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date MAT (364) (Weekly)]
			VAR ValuePreviousPeriod = [Balance at Date PYMAT (364) (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Moving annual total growth
		lineageTag: 34009324-5a7d-46bf-91ce-4945405519fe

	measure 'Balance at Date MATG % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date MATG (Weekly)],
			    [Balance at Date PYMAT (364) (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Moving annual total growth
		lineageTag: 00cead71-a2cf-4126-8741-41a5d6cb642c

	measure 'Balance at Date PYC (Weekly)' = ```
			
			IF (
			    [ShowValueForDates] && HASONEVALUE ( 'Date'[FW YearNumber] ),
			    VAR PreviousFiscalYear = MAX ( 'Date'[FW YearNumber] ) - 1
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearNumber] = PreviousFiscalYear
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: 32acea58-752d-4ac9-ac0b-23e4e494adca

	measure 'Balance at Date YTDOPY (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date YTD (Weekly)]
			VAR ValuePreviousPeriod = [Balance at Date PYC (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: 07e0cf08-3870-409b-8c35-300cb0e7130d

	measure 'Balance at Date YTDOPY % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date YTDOPY (Weekly)],
			    [Balance at Date PYC (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: 8236c9cf-e981-4812-8839-6a940b705e2e

	measure 'Balance at Date PQC (Weekly)' =
			
			IF (
			    [ShowValueForDates] && HASONEVALUE ( 'Date'[FW YearQuarterNumber] ),
			    VAR PreviousFiscalYearQuarter = MAX ( 'Date'[FW YearQuarterNumber] ) - 1
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearQuarterNumber] = PreviousFiscalYearQuarter
			        )
			    RETURN
			        Result
			)
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: 3d180d11-183a-405b-b8fb-5332d7c6f778

	measure 'Balance at Date QTDOPQ (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date QTD (Weekly)]
			VAR ValuePreviousPeriod = [Balance at Date PQC (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: 82f3db32-df50-4a6e-81c7-39b82228a5d1

	measure 'Balance at Date QTDOPQ % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date QTDOPQ (Weekly)],
			    [Balance at Date PQC (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: 9cf6aade-9894-414f-a299-6a38592d1d6a

	measure 'Balance at Date PWC (Weekly)' = ```
			
			IF (
			    [ShowValueForDates] && HASONEVALUE ( 'Date'[FW YearWeekNumber] ),
			    VAR PreviousFiscalYearWeek = MAX ( 'Date'[FW YearWeekNumber] ) - 1
			    VAR Result =
			        CALCULATE (
			            [Balance at Date],
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[FW YearWeekNumber] = PreviousFiscalYearWeek
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: bb3dad3d-0476-4db3-8b90-176c1bf59a60

	measure 'Balance at Date WTDOPW (Weekly)' = ```
			
			VAR ValueCurrentPeriod = [Balance at Date WTD (Weekly)]
			VAR ValuePreviousPeriod = [Balance at Date PWC (Weekly)]
			VAR Result =
			    IF (
			        NOT ISBLANK ( ValueCurrentPeriod ) 
			            && NOT ISBLANK ( ValuePreviousPeriod ),
			        ValueCurrentPeriod - ValuePreviousPeriod
			    )
			RETURN
			    Result
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: 351ecebf-146a-4b14-8309-06da69b93199

	measure 'Balance at Date WTDOPW % (Weekly)' = ```
			
			DIVIDE ( 
			    [Balance at Date WTDOPW (Weekly)],
			    [Balance at Date PWC (Weekly)]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Balance at Date\Period-to-date over full previous period
		lineageTag: 49914b47-480e-49d6-86a0-5ce4d8f862b8

	measure 'Balance at Date AVG 4W (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    VAR LastDayMAT =
			        MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 27
			    VAR Period4W =
			        CALCULATETABLE (
			            VALUES ( 'Date'[Sequential365DayNumber] ),
			            ALLEXCEPT (
			                'Date',
			                'Date'[Day Type],
			                'Date'[Week Day]
			            ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT 
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT,
			            'Date'[DatesWithTransactions] = TRUE
			        )
			    VAR FirstDayWithData =
			        CALCULATE (
			            MIN ( 'G/L Entries'[Posting Date] ),
			            REMOVEFILTERS ()
			        )
			    VAR FirstDayInPeriod =
			        MINX (
			            Period4W,
			            'Date'[Sequential365DayNumber]
			        )
			    VAR Result =
			        IF (
			            FirstDayWithData <= FirstDayInPeriod,
			            CALCULATE (
			                AVERAGEX ( Period4W, [Balance at Date] ),
			                REMOVEFILTERS ( 'Date' )
			            )
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Moving averages
		lineageTag: ede6119f-7d22-4e1f-8337-1dbb5e52645f

	measure 'Balance at Date AVG 1Q (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    VAR LastDayMAT =
			        MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 13 * 7 + 1
			    VAR Period1Q =
			        CALCULATETABLE (
			            VALUES ( 'Date'[Sequential365DayNumber] ),
			            ALLEXCEPT ( 'Date', 'Date'[Day Type], 'Date'[Week Day] ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT 
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT,
			            'Date'[DatesWithTransactions] = TRUE
			        )
			    VAR FirstDayWithData =
			        CALCULATE (
			            MIN ( 'G/L Entries'[Posting Date] ),
			            REMOVEFILTERS ()
			        )
			    VAR FirstDayInPeriod =
			        MINX (
			            Period1Q,
			            'Date'[Sequential365DayNumber]
			        )
			    VAR Result =
			        IF (
			            FirstDayWithData <= FirstDayInPeriod,
			            CALCULATE (
			                AVERAGEX ( Period1Q, [Balance at Date] ),
			                REMOVEFILTERS ( 'Date' )
			            )
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Moving averages
		lineageTag: eae02c04-aa5b-46ff-9e70-1c923d2669fe

	measure 'Balance at Date AVG 1Y (Weekly)' = ```
			
			IF (
			    [ShowValueForDates],
			    VAR LastDayMAT =
			        MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 363
			    VAR Period1Y =
			        CALCULATETABLE (
			            VALUES ( 'Date'[Sequential365DayNumber] ),
			            ALLEXCEPT (
			                'Date',
			                'Date'[Day Type],
			                'Date'[Week Day]
			            ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT,
			            'Date'[DatesWithTransactions] = TRUE
			        )
			    VAR FirstDayWithData =
			        CALCULATE (
			            MIN ( 'G/L Entries'[Posting Date] ),
			            REMOVEFILTERS ()
			        )
			    VAR FirstDayInPeriod =
			        MINX (
			            Period1Y,
			            'Date'[Sequential365DayNumber]
			        )
			    VAR Result =
			        IF (
			            FirstDayWithData <= FirstDayInPeriod,
			            CALCULATE (
			                AVERAGEX ( Period1Y, [Balance at Date] ),
			                REMOVEFILTERS ( 'Date' )
			            )
			        )
			    RETURN
			        Result
			)
			
			```
		formatString: #,0.00
		displayFolder: Balance at Date\Moving averages
		lineageTag: b80b3f5e-a395-40e5-a5be-a652a2dc56e9

	measure 'Average Collection Period AVG 1Y (Weekly)' =
			
			IF (
			    [ShowValueForDates],
			    VAR LastDayMAT =
			        MAX ( 'Date'[Sequential365DayNumber] )
			    VAR FirstDayMAT = LastDayMAT - 363
			    VAR Period1Y =
			        CALCULATETABLE (
			            VALUES ( 'Date'[Sequential365DayNumber] ),
			            ALLEXCEPT (
			                'Date',
			                'Date'[Day Type],
			                'Date'[Week Day]
			            ),
			            'Date'[Sequential365DayNumber] >= FirstDayMAT
			                && 'Date'[Sequential365DayNumber] <= LastDayMAT,
			            'Date'[DatesWithTransactions] = TRUE
			        )
			    VAR FirstDayWithData =
			        CALCULATE (
			            MIN ( 'G/L Entries'[Posting Date] ),
			            REMOVEFILTERS ()
			        )
			    VAR FirstDayInPeriod =
			        MINX (
			            Period1Y,
			            'Date'[Sequential365DayNumber]
			        )
			    VAR Result =
			        IF (
			            FirstDayWithData <= FirstDayInPeriod,
			            CALCULATE (
			                [Average Collection Period (Days)],
			                Period1Y
			            )
			        )
			    RETURN
			        Result
			)
		formatString: #,0.00
		displayFolder: Net Change\Moving averages
		lineageTag: 1ad02373-d35e-44ab-b087-6af8baaad589

	column Column1
		dataType: string
		isHidden
		lineageTag: e84f4a01-f709-47f3-92c7-99de1b0ea283
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Weekly Calendar Time Intelligence-49cf1c41-8dd5-469f-9790-7e8ad1a974bb' = m
		mode: import
		queryGroup: Measures
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

