table 'Translated Localized Labels'
	lineageTag: 3223610e-dc06-4d4a-9680-a7f3fb616df2

	measure 'CONNECT YOUR DATA Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "CONECTAR LOS DATOS",
			   "de-DE", "MIT EIGENEN DATEN VERBINDEN",
			   "fr-FR", "CONNECTER VOS DONNÉES",
			   "cs-CZ", "PŘIPOJENÍ DAT",
			   "da-DK", "FORBIND DINE DATA",
			   "de-AT", "MIT EIGENEN DATEN VERBINDEN",
			   "de-CH", "MIT EIGENEN DATEN VERBINDEN",
			   "en-AU", "CONNECT YOUR DATA",
			   "en-CA", "CONNECT YOUR DATA",
			   "en-GB", "CONNECT YOUR DATA",
			   "en-NZ", "CONNECT YOUR DATA",
			   "es-MX", "CONECTAR LOS DATOS",
			   "fi-FI", "YHDISTÄ TIETOSI",
			   "fr-BE", "CONNECTER VOS DONNÉES",
			   "fr-CA", "CONNECTER VOS DONNÉES",
			   "fr-CH", "CONNECTER VOS DONNÉES",
			   "is-IS", "TENGIÐ GÖGN",
			   "it-CH", "CONNETTI I DATI",
			   "it-IT", "CONNETTI I DATI",
			   "nb-NO", "KOBLE TIL DATAENE",
			   "nl-BE", "UW GEGEVENS VERBINDEN",
			   "nl-NL", "UW GEGEVENS VERBINDEN",
			   "ru-RU", "CONNECT YOUR DATA",
			   "sv-SE", "ANSLUT DINA DATA",
			   "CONNECT YOUR DATA"
			)
		lineageTag: 0a4a9105-dfae-47b1-ba59-ba9ff92fcf01

	measure '1. Download the Finance Connector for Power BI Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "1. Descargar Finance Connector for Power BI",
			   "de-DE", "1. Finance Connector for Power BI herunterladen",
			   "fr-FR", "1. Téléchargez Finance Connector for Power BI",
			   "cs-CZ", "1. Stažení řešení Finance Connector for Power BI",
			   "da-DK", "1. Download Finance Connector for Power BI",
			   "de-AT", "1. Finance Connector for Power BI herunterladen",
			   "de-CH", "1. Finance Connector for Power BI herunterladen",
			   "en-AU", "1. Download the Finance Connector for Power BI",
			   "en-CA", "1. Download the Finance Connector for Power BI",
			   "en-GB", "1. Download the Finance Connector for Power BI",
			   "en-NZ", "1. Download the Finance Connector for Power BI",
			   "es-MX", "1. Descargar Finance Connector for Power BI",
			   "fi-FI", "1. Lataa Finance Connector for Power BI",
			   "fr-BE", "1. Téléchargez Finance Connector for Power BI",
			   "fr-CA", "1. Téléchargez Finance Connector for Power BI",
			   "fr-CH", "1. Téléchargez Finance Connector for Power BI",
			   "is-IS", "1. Sækja Finance Connector for Power BI",
			   "it-CH", "1. Scaricare Finance Connector for Power BI",
			   "it-IT", "1. Scaricare Finance Connector for Power BI",
			   "nb-NO", "1. Last ned Finance Connector for Power BI",
			   "nl-BE", "1. De Finance Connector for Power BI downloaden",
			   "nl-NL", "1. De Finance Connector for Power BI downloaden",
			   "ru-RU", "1. Download the Finance Connector for Power BI",
			   "sv-SE", "1. Ladda ned Finance Connector for Power BI",
			   "1. Download the Finance Connector for Power BI"
			)
		lineageTag: b50bd1a8-a06c-4768-9ec0-a150073d6df1

	measure '2. Configure Dynamics 365 Business Central Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "2. Configurar Dynamics 365 Business Central",
			   "de-DE", "2. Dynamics 365 Business Central konfigurieren",
			   "fr-FR", "2. Configurez Dynamics 365 Business Central",
			   "cs-CZ", "2. Konfigurace Dynamics 365 Business Central",
			   "da-DK", "2. Konfigurer Dynamics 365 Business Central",
			   "de-AT", "2. Dynamics 365 Business Central konfigurieren",
			   "de-CH", "2. Dynamics 365 Business Central konfigurieren",
			   "en-AU", "2. Configure Dynamics 365 Business Central",
			   "en-CA", "2. Configure Dynamics 365 Business Central",
			   "en-GB", "2. Configure Dynamics 365 Business Central",
			   "en-NZ", "2. Configure Dynamics 365 Business Central",
			   "es-MX", "2. Configurar Dynamics 365 Business Central",
			   "fi-FI", "2. Määritä Dynamics 365 Business Central",
			   "fr-BE", "2. Configurez Dynamics 365 Business Central",
			   "fr-CA", "2. Configurez Dynamics 365 Business Central",
			   "fr-CH", "2. Configurez Dynamics 365 Business Central",
			   "is-IS", "2. Grunnstillið Dynamics 365 Business Central",
			   "it-CH", "2. Configurare Dynamics 365 Business Central",
			   "it-IT", "2. Configurare Dynamics 365 Business Central",
			   "nb-NO", "2. Konfigurer Dynamics 365 Business Central",
			   "nl-BE", "2. Dynamics 365 Business Central configureren",
			   "nl-NL", "2. Dynamics 365 Business Central configureren",
			   "ru-RU", "2. Configure Dynamics 365 Business Central",
			   "sv-SE", "2. Konfigurera Dynamics 365 Business Central",
			   "2. Configure Dynamics 365 Business Central"
			)
		lineageTag: 1d0f8020-abb7-4625-b817-dfd22d86851c

	measure 'USE, EDIT AND BUILD YOUR OWN REPORTS Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "USAR, EDITAR Y CREAR SUS PROPIOS INFORMES",
			   "de-DE", "EIGENE BERICHTE VERWENDEN, BEARBEITEN UND ERSTELLEN",
			   "fr-FR", "UTILISER, MODIFIER ET CRÉER VOS PROPRES ÉTATS",
			   "cs-CZ", "POUŽÍVÁNÍ, ÚPRAVA A TVORBA VLASTNÍCH SESTAV",
			   "da-DK", "BRUG, REDIGER OG OPRET DINE EGNE RAPPORTER",
			   "de-AT", "EIGENE BERICHTE VERWENDEN, BEARBEITEN UND ERSTELLEN",
			   "de-CH", "EIGENE BERICHTE VERWENDEN, BEARBEITEN UND ERSTELLEN",
			   "en-AU", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "en-CA", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "en-GB", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "en-NZ", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "es-MX", "USAR, EDITAR Y CREAR SUS PROPIOS INFORMES",
			   "fi-FI", "KÄYTÄ, MUOKKAA JA LUO OMIA RAPORTTEJA",
			   "fr-BE", "UTILISER, MODIFIER ET CRÉER VOS PROPRES ÉTATS",
			   "fr-CA", "Utilisez, modifiez et créez vos propres rapports",
			   "fr-CH", "UTILISER, MODIFIER ET CRÉER VOS PROPRES ÉTATS",
			   "is-IS", "NOTIÐ, BREYTIÐ OG BÚIÐ TIL EIGIN SKÝRSLUR",
			   "it-CH", "USA, MODIFICA E CREA I TUOI REPORT",
			   "it-IT", "USA, MODIFICA E CREA I TUOI REPORT",
			   "nb-NO", "BRUK, REDIGER OG BYGG DINE EGNE RAPPORTER",
			   "nl-BE", "UW EIGEN RAPPORTEN GEBRUIKEN, BEWERKEN EN MAKEN",
			   "nl-NL", "UW EIGEN RAPPORTEN GEBRUIKEN, BEWERKEN EN MAKEN",
			   "ru-RU", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "sv-SE", "ANVÄND, REDIGERA OCH SKAPA EGNA RAPPORTER",
			   "USE, EDIT AND BUILD YOUR OWN REPORTS"
			)
		lineageTag: b70d5003-56fd-4cb7-bb8a-ab27feac9717

	measure 'Finance includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch. Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Finanzas incluye una variedad de informes prediseñados para ayudarlo a ver sus datos de inmediato. Puede editar estos informes o crear el suyo propio desde cero.",
			   "de-DE", "Finanzen enthält eine Vielzahl vordefinierter Berichte, mit denen Sie Ihre Daten unmittelbar ansehen können. Sie können diese Berichte bearbeiten oder Ihren eigenen Bericht von Grund auf neu erstellen.",
			   "fr-FR", "Finance inclut une variété d’états prédéfinis pour vous aider à voir vos données immédiatement. Vous pouvez modifier ces états ou créer votre propre état à partir de zéro.",
			   "cs-CZ", "Finance obsahují řadu předpřipravených sestav, které vám pomohou okamžitě zobrazit vaše data. Tyto sestavy můžete upravovat nebo si vytvořit vlastní sestavu od základu.",
			   "da-DK", "Finans indeholder en række færdigbyggede rapporter, der hjælper dig med at få vist dine data med det samme. Du kan redigere disse rapporter eller oprette din egen rapport fra bunden.",
			   "de-AT", "Finanzen enthält eine Vielzahl vordefinierter Berichte, mit denen Sie Ihre Daten unmittelbar ansehen können. Sie können diese Berichte bearbeiten oder Ihren eigenen Bericht von Grund auf neu erstellen.",
			   "de-CH", "Finanzen enthält eine Vielzahl vordefinierter Berichte, mit denen Sie Ihre Daten unmittelbar ansehen können. Sie können diese Berichte bearbeiten oder Ihren eigenen Bericht von Grund auf neu erstellen.",
			   "en-AU", "Finance includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "en-CA", "Finance includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "en-GB", "Finance includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "en-NZ", "Finance includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "es-MX", "Finanzas incluye una variedad de informes prediseñados para ayudarlo a ver sus datos de inmediato. Puede editar estos informes o crear el suyo propio desde cero.",
			   "fi-FI", "Taloushallinto sisältää erilaisia esimääritettyjä raportteja, joiden avulla voit tarkastella tietoja välittömästi. Voit muokata näitä raportteja tai luoda oman raportin alusta alkaen.",
			   "fr-BE", "Finance inclut une variété d’états prédéfinis pour vous aider à voir vos données immédiatement. Vous pouvez modifier ces états ou créer votre propre état à partir de zéro.",
			   "fr-CA", "La fonction Finance comprend divers rapports prédéfinis qui vous permettent de visualiser immédiatement vos données. Vous pouvez modifier ces rapports ou créer vos propres rapports à partir de zéro.",
			   "fr-CH", "Finance inclut une variété d’états prédéfinis pour vous aider à voir vos données immédiatement. Vous pouvez modifier ces états ou créer votre propre état à partir de zéro.",
			   "is-IS", "Fjármál bjóða upp á innbyggðar skýrslur til að skoða gögn samstundis. Hægt er að breyta skýrslunum eða búa til eigin skýrslur frá grunni.",
			   "it-CH", "I dati finanziari includono una serie di report predefiniti che consentono di visualizzare immediatamente i dati. È possibile modificare questi report o creare il proprio report da zero.",
			   "it-IT", "I dati finanziari includono una serie di report predefiniti che consentono di visualizzare immediatamente i dati. È possibile modificare questi report o creare il proprio report da zero.",
			   "nb-NO", "Finans inneholder en rekke forhåndsbygde rapporter som hjelper deg med å se dataene umiddelbart. Du kan redigere disse rapportene eller lage din egen rapport fra bunnen av.",
			   "nl-BE", "Financiën omvatten een verscheidenheid aan vooraf gemaakte rapporten om u te helpen uw gegevens direct te bekijken. U kunt deze rapporten bewerken of uw eigen rapport helemaal opnieuw maken.",
			   "nl-NL", "Financiën omvatten een verscheidenheid aan vooraf gemaakte rapporten om u te helpen uw gegevens direct te bekijken. U kunt deze rapporten bewerken of uw eigen rapport helemaal opnieuw maken.",
			   "ru-RU", "Finance includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "sv-SE", "Ekonomi omfattar en mängd olika färdiga rapporter som gör det enkelt att se data direkt. Du kan redigera dessa rapporter eller skapa en egen rapport från grunden.",
			   "Finance includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch."
			)
		lineageTag: 7c6050c5-833c-4d31-8797-f54e1a459b56

	measure 'HELP AND SUPPORT Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "AYUDA Y SOPORTE",
			   "de-DE", "HILFE UND SUPPORT",
			   "fr-FR", "AIDE ET SUPPORT",
			   "cs-CZ", "POMOC A PODPORA",
			   "da-DK", "HJÆLP OG SUPPORT",
			   "de-AT", "HILFE UND SUPPORT",
			   "de-CH", "HILFE UND SUPPORT",
			   "en-AU", "HELP AND SUPPORT",
			   "en-CA", "HELP AND SUPPORT",
			   "en-GB", "HELP AND SUPPORT",
			   "en-NZ", "HELP AND SUPPORT",
			   "es-MX", "AYUDA Y SOPORTE",
			   "fi-FI", "OHJE JA TUKI",
			   "fr-BE", "AIDE ET SUPPORT",
			   "fr-CA", "AIDE ET SUPPORT",
			   "fr-CH", "AIDE ET SUPPORT",
			   "is-IS", "HJÁLP OG STUÐNINGUR",
			   "it-CH", "GUIDA E SUPPORTO",
			   "it-IT", "GUIDA E SUPPORTO",
			   "nb-NO", "HJELP OG KUNDESTØTTE",
			   "nl-BE", "HELP EN ONDERSTEUNING",
			   "nl-NL", "HELP EN ONDERSTEUNING",
			   "ru-RU", "HELP AND SUPPORT",
			   "sv-SE", "HJÄLP OCH SUPPORT",
			   "HELP AND SUPPORT"
			)
		lineageTag: aaff8630-6312-43bb-b016-28b989121107

	measure 'For help and support with your new report please visit the Analytics overview documentation. Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Para obtener ayuda y soporte técnico con su nuevo informe, visite la documentación de información general de Analytics.",
			   "de-DE", "Hilfe und Unterstützung für Ihren neuen Bericht finden Sie in der Dokumentation Analysen – Übersicht.",
			   "fr-FR", "Pour obtenir de l’aide et de l’assistance concernant votre nouvel état, consultez la documentation de vue d’ensemble de l’analyse.",
			   "cs-CZ", "Nápovědu a podporu k nové sestavě naleznete v dokumentaci k přehledu Analytics.",
			   "da-DK", "Du kan få hjælp og support til din nye rapport i dokumentationen til analyseoversigten.",
			   "de-AT", "Hilfe und Unterstützung für Ihren neuen Bericht finden Sie in der Dokumentation Analysen – Übersicht.",
			   "de-CH", "Hilfe und Unterstützung für Ihren neuen Bericht finden Sie in der Dokumentation Analysen – Übersicht.",
			   "en-AU", "For help and support with your new report please visit the Analytics overview documentation.",
			   "en-CA", "For help and support with your new report please visit the Analytics overview documentation.",
			   "en-GB", "For help and support with your new report please visit the Analytics overview documentation.",
			   "en-NZ", "For help and support with your new report please visit the Analytics overview documentation.",
			   "es-MX", "Para obtener ayuda y soporte técnico con su nuevo informe, visite la documentación de información general de Analytics.",
			   "fi-FI", "Lisätietoja ja tukea uudelle raportillesi löydät analytiikan yleiskatsauksen dokumentaatiosta.",
			   "fr-BE", "Pour obtenir de l’aide et de l’assistance concernant votre nouvel état, consultez la documentation de vue d’ensemble de l’analyse.",
			   "fr-CA", "Pour obtenir de l’aide et de l’assistance concernant votre nouveau rapport, veuillez consulter la documentation relative à la présentation générale des analyses.",
			   "fr-CH", "Pour obtenir de l’aide et de l’assistance concernant votre nouvel état, consultez la documentation de vue d’ensemble de l’analyse.",
			   "is-IS", "Lesið fylgigögn greiningaryfirlitsins til að fá hjálp og aðstoð við nýju skýrsluna.",
			   "it-CH", "Per assistenza e supporto per il nuovo report, vedere la documentazione generale di analisi.",
			   "it-IT", "Per assistenza e supporto per il nuovo report, vedere la documentazione generale di analisi.",
			   "nb-NO", "Hvis du vil ha hjelp og støtte med den nye rapporten, kan du gå til dokumentasjonen for analyseoversikten.",
			   "nl-BE", "Ga voor hulp en ondersteuning met uw nieuwe rapport naar de Analytics-overzichtsdocumentatie.",
			   "nl-NL", "Ga voor hulp en ondersteuning met uw nieuwe rapport naar de Analytics-overzichtsdocumentatie.",
			   "ru-RU", "For help and support with your new report please visit the Analytics overview documentation.",
			   "sv-SE", "Hjälp och support med den nya rapporten finns i översiktsdokumentationen för Analys.",
			   "For help and support with your new report please visit the Analytics overview documentation."
			)
		lineageTag: 53d97413-4ec0-47b1-8798-4b3d2aae7884

	measure 'for Business Central Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "para Business Central",
			   "de-DE", "für Business Central",
			   "fr-FR", "pour Business Central",
			   "cs-CZ", "pro Business Central",
			   "da-DK", "til Business Central",
			   "de-AT", "für Business Central",
			   "de-CH", "für Business Central",
			   "en-AU", "for Business Central",
			   "en-CA", "for Business Central",
			   "en-GB", "for Business Central",
			   "en-NZ", "for Business Central",
			   "es-MX", "para Business Central",
			   "fi-FI", "Business Centralille",
			   "fr-BE", "pour Business Central",
			   "fr-CA", "pour Business Central",
			   "fr-CH", "pour Business Central",
			   "is-IS", "fyrir Business Central",
			   "it-CH", "per Business Central",
			   "it-IT", "per Business Central",
			   "nb-NO", "for Business Central",
			   "nl-BE", "voor Business Central",
			   "nl-NL", "voor Business Central",
			   "ru-RU", "for Business Central",
			   "sv-SE", "för Business Central",
			   "for Business Central"
			)
		lineageTag: 0eab0ab6-a1a6-4bda-8c62-2daea3d179c8

	measure 'Last Refreshed Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Última actualización",
			   "de-DE", "Zuletzt aktualisiert",
			   "fr-FR", "Dernière actualisation",
			   "cs-CZ", "Naposledy aktualizováno",
			   "da-DK", "Sidst opdateret",
			   "de-AT", "Zuletzt aktualisiert",
			   "de-CH", "Zuletzt aktualisiert",
			   "en-AU", "Last Refreshed",
			   "en-CA", "Last Refreshed",
			   "en-GB", "Last Refreshed",
			   "en-NZ", "Last Refreshed",
			   "es-MX", "Última actualización",
			   "fi-FI", "Päivitetty viimeksi",
			   "fr-BE", "Dernière actualisation",
			   "fr-CA", "Dernière actualisation",
			   "fr-CH", "Dernière actualisation",
			   "is-IS", "Síðast uppfært",
			   "it-CH", "Ultimo aggiornamento",
			   "it-IT", "Ultimo aggiornamento",
			   "nb-NO", "Sist oppdatert",
			   "nl-BE", "Laatst vernieuwd",
			   "nl-NL", "Laatst vernieuwd",
			   "ru-RU", "Last Refreshed",
			   "sv-SE", "Uppdaterades senast",
			   "Last Refreshed"
			)
		lineageTag: da49d838-038c-4094-baf2-181512eee6df

	measure 'Company Name Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Nombre empresa",
			   "de-DE", "Mandantenname",
			   "fr-FR", "Nom de la société",
			   "cs-CZ", "Název společnosti",
			   "da-DK", "Virksomhedsnavn",
			   "de-AT", "Mandantenname",
			   "de-CH", "Mandantenname",
			   "en-AU", "Company Name",
			   "en-CA", "Company Name",
			   "en-GB", "Company Name",
			   "en-NZ", "Company Name",
			   "es-MX", "Nombre empresa",
			   "fi-FI", "Yrityksen nimi",
			   "fr-BE", "Nom de la société",
			   "fr-CA", "Nom de la compagnie",
			   "fr-CH", "Nom de la société",
			   "is-IS", "Heiti fyrirtækis",
			   "it-CH", "Nome società",
			   "it-IT", "Nome società",
			   "nb-NO", "Selskapsnavn",
			   "nl-BE", "Bedrijfsnaam",
			   "nl-NL", "Bedrijfsnaam",
			   "ru-RU", "Company Name",
			   "sv-SE", "Företagsnamn",
			   "Company Name"
			)
		lineageTag: 4d29b23e-69e5-4763-a68c-033638ce25a4

	measure 'Analysis Entries as of Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Movimientos de análisis a partir de",
			   "de-DE", "Analyseposten zum",
			   "fr-FR", "Écritures analyse au",
			   "cs-CZ", "Položky analýzy ke dni",
			   "da-DK", "Analyseposter fra og med",
			   "de-AT", "Analyseposten zum",
			   "de-CH", "Analyseposten zum",
			   "en-AU", "Analysis Entries as of",
			   "en-CA", "Analysis Entries as of",
			   "en-GB", "Analysis Entries as of",
			   "en-NZ", "Analysis Entries as of",
			   "es-MX", "Movimientos de análisis a partir de",
			   "fi-FI", "Analyysitapahtumat alkaen",
			   "fr-BE", "Écritures analyse au",
			   "fr-CA", "Écritures analyse au",
			   "fr-CH", "Écritures analyse au",
			   "is-IS", "Greiningarfærslur frá og með",
			   "it-CH", "Movimenti analisi a partire da",
			   "it-IT", "Movimenti analisi a partire da",
			   "nb-NO", "Analyseposter per",
			   "nl-BE", "Analyseposten vanaf",
			   "nl-NL", "Analyseposten vanaf",
			   "ru-RU", "Analysis Entries as of",
			   "sv-SE", "Analysera transaktioner per",
			   "Analysis Entries as of"
			)
		lineageTag: 94aefe55-eb9d-48ba-854d-53993e2a8b55

	measure 'Billing Forecast by Billing Period, Customer and Contract No. Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Previsión de facturación por periodo de facturación, cliente y n.º contrato",
			   "de-DE", "Abrechnungsplanung nach Abrechnungsperiode, Debitor und Vertragsnr.",
			   "fr-FR", "Prévision de facturation par période de facturation, client et n° contrat",
			   "cs-CZ", "Prognóza fakturace podle fakturačního období, zákazníka a č. smlouvy",
			   "da-DK", "Faktureringsprognose efter faktureringsperiode, debitor og kontraktnr.",
			   "de-AT", "Abrechnungsplanung nach Abrechnungsperiode, Debitor und Vertragsnr.",
			   "de-CH", "Abrechnungsplanung nach Abrechnungsperiode, Debitor und Vertragsnr.",
			   "en-AU", "Billing Forecast by Billing Period, Customer and Contract No.",
			   "en-CA", "Billing Forecast by Billing Period, Customer and Contract No.",
			   "en-GB", "Billing Forecast by Billing Period, Customer and Contract No.",
			   "en-NZ", "Billing Forecast by Billing Period, Customer and Contract No.",
			   "es-MX", "Previsión de facturación por periodo de facturación, cliente y n.º contrato",
			   "fi-FI", "Laskutusennuste laskutuskauden, asiakkaan ja sopimuksen numeron mukaan",
			   "fr-BE", "Prévision de facturation par période de facturation, client et n° contrat",
			   "fr-CA", "Prévision de facturation par période de facturation, client et n° contrat",
			   "fr-CH", "Prévision de facturation par période de facturation, client et n° contrat",
			   "is-IS", "Reikningsspá eftir reikningstímabili, viðskiptavini og samningsnúmeri.",
			   "it-CH", "Previsione di fatturazione per periodo di fatturazione, cliente e nr. contratto",
			   "it-IT", "Previsione di fatturazione per periodo di fatturazione, cliente e nr. contratto",
			   "nb-NO", "Faktureringsprognose etter faktureringsperiode, kunde- og kontraktnr.",
			   "nl-BE", "Factureringsprognose per factureringsperiode, klant en contractnr.",
			   "nl-NL", "Factureringsprognose per factureringsperiode, klant en contractnr.",
			   "ru-RU", "Billing Forecast by Billing Period, Customer and Contract No.",
			   "sv-SE", "Faktureringsprognos per faktureringsperiod, kund och kontraktsnr",
			   "Billing Forecast by Billing Period, Customer and Contract No."
			)
		lineageTag: 550417f4-7b29-4f88-85df-34b4ea9dc53d

	measure 'Billing Forecast by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Previsión de facturación por mes y año naturales",
			   "de-DE", "Abrechnungsplanung nach Kalenderjahr und Monat",
			   "fr-FR", "Prévision de facturation par année civile et par mois",
			   "cs-CZ", "Prognóza fakturace podle kalendářního roku a měsíce",
			   "da-DK", "Faktureringsprognose efter kalenderår og måned",
			   "de-AT", "Abrechnungsplanung nach Kalenderjahr und Monat",
			   "de-CH", "Abrechnungsplanung nach Kalenderjahr und Monat",
			   "en-AU", "Billing Forecast by Calendar Year and Month",
			   "en-CA", "Billing Forecast by Calendar Year and Month",
			   "en-GB", "Billing Forecast by Calendar Year and Month",
			   "en-NZ", "Billing Forecast by Calendar Year and Month",
			   "es-MX", "Previsión de facturación por mes y año naturales",
			   "fi-FI", "Laskutusennuste kalenterivuosittain ja -kuukausittain",
			   "fr-BE", "Prévision de facturation par année civile et par mois",
			   "fr-CA", "Prévision de facturation par année civile et par mois",
			   "fr-CH", "Prévision de facturation par année civile et par mois",
			   "is-IS", "Reikningsspá eftir almanaksári og -mánuði",
			   "it-CH", "Previsione fatturazione per anno e mese di calendario",
			   "it-IT", "Previsione fatturazione per anno e mese di calendario",
			   "nb-NO", "Faktureringsprognose etter kalenderår og måned",
			   "nl-BE", "Factureringsprognose per kalenderjaar en -maand",
			   "nl-NL", "Factureringsprognose per kalenderjaar en -maand",
			   "ru-RU", "Billing Forecast by Calendar Year and Month",
			   "sv-SE", "Faktureringsprognos per kalenderår och månad",
			   "Billing Forecast by Calendar Year and Month"
			)
		lineageTag: 97388aaa-d65f-4115-beba-9815bc1dfac4

	measure 'Billing Schedule Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Programación de facturación",
			   "de-DE", "Abrechnungszeitplan",
			   "fr-FR", "Échéancier de facturation",
			   "cs-CZ", "Plán fakturace",
			   "da-DK", "Faktureringsskema",
			   "de-AT", "Abrechnungszeitplan",
			   "de-CH", "Abrechnungszeitplan",
			   "en-AU", "Billing Schedule",
			   "en-CA", "Billing Schedule",
			   "en-GB", "Billing Schedule",
			   "en-NZ", "Billing Schedule",
			   "es-MX", "Programación de facturación",
			   "fi-FI", "Laskutusaikataulu",
			   "fr-BE", "Échéancier de facturation",
			   "fr-CA", "Calendrier de facturation",
			   "fr-CH", "Échéancier de facturation",
			   "is-IS", "Greiðsluáætlun",
			   "it-CH", "Programmazione fatturazione",
			   "it-IT", "Programmazione fatturazione",
			   "nb-NO", "Faktureringsplan",
			   "nl-BE", "Factureringsplanning",
			   "nl-NL", "Factureringsplanning",
			   "ru-RU", "Billing Schedule",
			   "sv-SE", "Faktureringsschema",
			   "Billing Schedule"
			)
		lineageTag: 878726a9-8d31-4394-b149-5265721df19c

	measure 'Change of Mon. Recurring Revenue by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Cambio de ingresos periódicos mensuales por mes y año",
			   "de-DE", "Änderung dermon. wiederkehrenden Umsätze nach Jahr und Monat",
			   "fr-FR", "Modification revenu récurrent mensuel par année et par mois",
			   "cs-CZ", "Změna měsíčního periodického výnosu podle roku a měsíce",
			   "da-DK", "Ændring af månedlig tilbagevendende omsætning efter kalenderår og måned",
			   "de-AT", "Änderung dermon. wiederkehrenden Umsätze nach Jahr und Monat",
			   "de-CH", "Änderung dermon. wiederkehrenden Umsätze nach Jahr und Monat",
			   "en-AU", "Change of Mon. Recurring Revenue by Year and Month",
			   "en-CA", "Change of Mon. Recurring Revenue by Year and Month",
			   "en-GB", "Change of Mon. Recurring Revenue by Year and Month",
			   "en-NZ", "Change of Mon. Recurring Revenue by Year and Month",
			   "es-MX", "Cambio de ingresos periódicos mensuales por mes y año",
			   "fi-FI", "Kk:ttain toistuvan tuoton muutos vuosittain ja kuukausittain",
			   "fr-BE", "Modification revenu récurrent mensuel par année et par mois",
			   "fr-CA", "Modification revenu récurrent mensuel par année et par mois",
			   "fr-CH", "Modification revenu récurrent mensuel par année et par mois",
			   "is-IS", "Breyting á mán. endurteknum tekjum eftir ári og mánuði",
			   "it-CH", "Modifica dei ricavi periodici mensili per anno e mese",
			   "it-IT", "Modifica dei ricavi periodici mensili per anno e mese",
			   "nb-NO", "Endring i månedlig gjentakende inntekt etter år og måned",
			   "nl-BE", "Wijziging van maand. periodieke opbrengst per jaar en maand",
			   "nl-NL", "Wijziging van maand. periodieke opbrengst per jaar en maand",
			   "ru-RU", "Change of Mon. Recurring Revenue by Year and Month",
			   "sv-SE", "Ändring av månatliga återkommande intäkter per år och månad",
			   "Change of Mon. Recurring Revenue by Year and Month"
			)
		lineageTag: 76ea3322-b622-4622-82c3-e59a3cafff76

	measure 'Current Date Range: Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Intervalo de fechas actual:",
			   "de-DE", "Aktueller Datumsbereich:",
			   "fr-FR", "Plage de dates actuelle :",
			   "cs-CZ", "Aktuální rozsah dat:",
			   "da-DK", "Aktuelt datointerval:",
			   "de-AT", "Aktueller Datumsbereich:",
			   "de-CH", "Aktueller Datumsbereich:",
			   "en-AU", "Current Date Range:",
			   "en-CA", "Current Date Range:",
			   "en-GB", "Current Date Range:",
			   "en-NZ", "Current Date Range:",
			   "es-MX", "Intervalo de fechas actual:",
			   "fi-FI", "Nykyinen päivämääräalue:",
			   "fr-BE", "Plage de dates actuelle :",
			   "fr-CA", "Plage de dates actuelle :",
			   "fr-CH", "Plage de dates actuelle :",
			   "is-IS", "Núverandi dagsetningabil:",
			   "it-CH", "Intervallo di date corrente:",
			   "it-IT", "Intervallo di date corrente:",
			   "nb-NO", "Nåværende datoområde:",
			   "nl-BE", "Huidig datumbereik:",
			   "nl-NL", "Huidig datumbereik:",
			   "ru-RU", "Current Date Range:",
			   "sv-SE", "Aktuellt datumintervall:",
			   "Current Date Range:"
			)
		lineageTag: 46568020-b81b-462e-bbbe-dd97ac9cdac9

	measure 'Customer Contract Deferrals Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Fraccionamientos de contratos de clientes",
			   "de-DE", "Abgrenzungen von Debitorenverträgen",
			   "fr-FR", "Reports contrat client",
			   "cs-CZ", "Časová rozlišení zákaznické smlouvy",
			   "da-DK", "Periodiseringer af debitorkontrakt",
			   "de-AT", "Abgrenzungen von Debitorenverträgen",
			   "de-CH", "Abgrenzungen von Debitorenverträgen",
			   "en-AU", "Customer Contract Deferrals",
			   "en-CA", "Customer Contract Deferrals",
			   "en-GB", "Customer Contract Deferrals",
			   "en-NZ", "Customer Contract Deferrals",
			   "es-MX", "Fraccionamientos de contratos de clientes",
			   "fi-FI", "Asiakassopimuksen siirrot",
			   "fr-BE", "Reports contrat client",
			   "fr-CA", "Reports contrat client",
			   "fr-CH", "Reports contrat client",
			   "is-IS", "Samningsfrestanir viðskiptavinar",
			   "it-CH", "Differimenti contratto del cliente",
			   "it-IT", "Differimenti contratto del cliente",
			   "nb-NO", "Kundekontraktperiodiseringer",
			   "nl-BE", "Uitstel van klantcontracten",
			   "nl-NL", "Uitstel van klantcontracten",
			   "ru-RU", "Customer Contract Deferrals",
			   "sv-SE", "Periodiseringar av kundkontrakt",
			   "Customer Contract Deferrals"
			)
		lineageTag: 073ba338-d74d-4d9c-80a1-84291f96df3c

	measure 'Customer Contract Lines Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Líneas de contrato de cliente",
			   "de-DE", "Debitorenvertragszeilen",
			   "fr-FR", "Lignes contrat client",
			   "cs-CZ", "Řádky zákaznické smlouvy",
			   "da-DK", "Debitorkontraktlinjer",
			   "de-AT", "Debitorenvertragszeilen",
			   "de-CH", "Debitorenvertragszeilen",
			   "en-AU", "Customer Contract Lines",
			   "en-CA", "Customer Contract Lines",
			   "en-GB", "Customer Contract Lines",
			   "en-NZ", "Customer Contract Lines",
			   "es-MX", "Líneas de contrato de cliente",
			   "fi-FI", "Asiakassopimusrivit",
			   "fr-BE", "Lignes contrat client",
			   "fr-CA", "Lignes contrat client",
			   "fr-CH", "Lignes contrat client",
			   "is-IS", "Samningslínur viðskiptavinar",
			   "it-CH", "Righe contratto del cliente",
			   "it-IT", "Righe contratto del cliente",
			   "nb-NO", "Kundekontraktlinjer",
			   "nl-BE", "Klantcontractregels",
			   "nl-NL", "Klantcontractregels",
			   "ru-RU", "Customer Contract Lines",
			   "sv-SE", "Kundkontraktsrader",
			   "Customer Contract Lines"
			)
		lineageTag: 53dc3c17-f39f-4acc-be6f-c1478c73fcc1

	measure 'Customer Deferrals (Caption) Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Fraccionamientos de clientes",
			   "de-DE", "Debitorenabgrenzungen",
			   "fr-FR", "Reports client",
			   "cs-CZ", "Časová rozlišení zákazníka",
			   "da-DK", "Debitorperiodiseringer",
			   "de-AT", "Debitorenabgrenzungen",
			   "de-CH", "Debitorenabgrenzungen",
			   "en-AU", "Customer Deferrals",
			   "en-CA", "Customer Deferrals",
			   "en-GB", "Customer Deferrals",
			   "en-NZ", "Customer Deferrals",
			   "es-MX", "Fraccionamientos de clientes",
			   "fi-FI", "Asiakassiirrot",
			   "fr-BE", "Reports client",
			   "fr-CA", "Reports client",
			   "fr-CH", "Reports client",
			   "is-IS", "Frestanir viðskiptamanns",
			   "it-CH", "Differimenti cliente",
			   "it-IT", "Differimenti cliente",
			   "nb-NO", "Kundeperiodiseringer",
			   "nl-BE", "Klantuitstel",
			   "nl-NL", "Klantuitstel",
			   "ru-RU", "Customer Deferrals",
			   "sv-SE", "Kundperiodiseringar",
			   "Customer Deferrals"
			)
		lineageTag: f4621477-30d0-4a2e-bfad-d9d77f945dab

	measure 'Mon. Recurring Revenue Analysis Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis de ingresos periódicos mensuales",
			   "de-DE", "Mon. wiederkehrende Umsatzanalyse",
			   "fr-FR", "Analyse du revenu récurrent mensuel",
			   "cs-CZ", "Analýza měsíčních periodických výnosů",
			   "da-DK", "Månedlig tilbagevendende indtægtsanalyse",
			   "de-AT", "Mon. wiederkehrende Umsatzanalyse",
			   "de-CH", "Mon. wiederkehrende Umsatzanalyse",
			   "en-AU", "Mon. Recurring Revenue Analysis",
			   "en-CA", "Mon. Recurring Revenue Analysis",
			   "en-GB", "Mon. Recurring Revenue Analysis",
			   "en-NZ", "Mon. Recurring Revenue Analysis",
			   "es-MX", "Análisis de ingresos periódicos mensuales",
			   "fi-FI", "Kk:ttain toistuvan tuoton analyysi",
			   "fr-BE", "Analyse du revenu récurrent mensuel",
			   "fr-CA", "Analyse du revenu récurrent mensuel",
			   "fr-CH", "Analyse du revenu récurrent mensuel",
			   "is-IS", "Mán. endurtekin tekjugreining",
			   "it-CH", "Analisi ricavi periodici mensili",
			   "it-IT", "Analisi ricavi periodici mensili",
			   "nb-NO", "Månedlig gjentakende inntektsanalyse",
			   "nl-BE", "Maand. periodieke analyse van opbrengst",
			   "nl-NL", "Maand. periodieke analyse van opbrengst",
			   "ru-RU", "Mon. Recurring Revenue Analysis",
			   "sv-SE", "Analys av månatliga återkommande intäkter",
			   "Mon. Recurring Revenue Analysis"
			)
		lineageTag: 6cef4547-b030-49bd-a5c2-3d4a5aa41f23

	measure 'Mon. Recurring Revenue and Mon. Recurring Revenue PY by Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales e ingresos periódicos mensuales AA por mes natural",
			   "de-DE", "Mon. wiederkehrende Umsätze und monatlich wiederkehrende Umsätze VJ nach Kalendermonat",
			   "fr-FR", "Revenu récurrent mensuel et revenu récurrent mensuel AP par mois civil",
			   "cs-CZ", "Měsíční periodické výnosy a měsíční periodické výnosy PR podle kalendářního měsíce",
			   "da-DK", "Månedlige tilbagevendende indtægter og månedlige tilbagevendende indtægter FÅ efter kalendermåned",
			   "de-AT", "Mon. wiederkehrende Umsätze und monatlich wiederkehrende Umsätze VJ nach Kalendermonat",
			   "de-CH", "Mon. wiederkehrende Umsätze und monatlich wiederkehrende Umsätze VJ nach Kalendermonat",
			   "en-AU", "Mon. Recurring Revenue and Mon. Recurring Revenue PY by Calendar Month",
			   "en-CA", "Mon. Recurring Revenue and Mon. Recurring Revenue PY by Calendar Month",
			   "en-GB", "Mon. Recurring Revenue and Mon. Recurring Revenue PY by Calendar Month",
			   "en-NZ", "Mon. Recurring Revenue and Mon. Recurring Revenue PY by Calendar Month",
			   "es-MX", "Ingresos periódicos mensuales e ingresos periódicos mensuales AA por mes natural",
			   "fi-FI", "Kk:ttain toistuva tuotto ja Kk:ttain toistuva tuotto EDV kalenterikuukausittain",
			   "fr-BE", "Revenu récurrent mensuel et revenu récurrent mensuel AP par mois civil",
			   "fr-CA", "Revenu récurrent mensuel et revenu récurrent mensuel AP par mois civil",
			   "fr-CH", "Revenu récurrent mensuel et revenu récurrent mensuel AP par mois civil",
			   "is-IS", "Mán. endurteknar tekjur og mán. endurteknar tekjur fyrra árs eftir almanaksmánuði",
			   "it-CH", "Ricavi periodici mensili e ricavi periodici mensili PY per mese di calendario",
			   "it-IT", "Ricavi periodici mensili e ricavi periodici mensili PY per mese di calendario",
			   "nb-NO", "Månedlig gjentakende inntekt og månedlig gjentakende inntekt PÅ etter kalendermåned",
			   "nl-BE", "Maand. periodieke opbrengst en maand. periodieke opbrengst VJ per kalendermaand",
			   "nl-NL", "Maand. periodieke opbrengst en maand. periodieke opbrengst VJ per kalendermaand",
			   "ru-RU", "Mon. Recurring Revenue and Mon. Recurring Revenue PY by Calendar Month",
			   "sv-SE", "Månatliga återkommande intäkter och månatliga återkommande intäkter FÅ per kalendermånad",
			   "Mon. Recurring Revenue and Mon. Recurring Revenue PY by Calendar Month"
			)
		lineageTag: 099bddf0-33b6-4f48-8377-203e8ba0a7af

	measure 'Mon. Recurring Revenue and Year-Over-Year Growth by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales y crecimiento interanual por mes y año naturales",
			   "de-DE", "Mon. wiederkehrende Umsätze und Wachstum gegenüber dem Vorjahr nach Kalenderjahr und Monat",
			   "fr-FR", "Revenu récurrent mensuel et croissance d’une année à l’autre par année civile et par mois",
			   "cs-CZ", "Měsíční periodické výnosy a meziroční růst podle kalendářního roku a měsíce",
			   "da-DK", "Månedlig tilbagevendende omsætning og vækst fra år til år efter kalenderår og måned",
			   "de-AT", "Mon. wiederkehrende Umsätze und Wachstum gegenüber dem Vorjahr nach Kalenderjahr und Monat",
			   "de-CH", "Mon. wiederkehrende Umsätze und Wachstum gegenüber dem Vorjahr nach Kalenderjahr und Monat",
			   "en-AU", "Mon. Recurring Revenue and Year-Over-Year Growth by Calendar Year and Month",
			   "en-CA", "Mon. Recurring Revenue and Year-Over-Year Growth by Calendar Year and Month",
			   "en-GB", "Mon. Recurring Revenue and Year-Over-Year Growth by Calendar Year and Month",
			   "en-NZ", "Mon. Recurring Revenue and Year-Over-Year Growth by Calendar Year and Month",
			   "es-MX", "Ingresos periódicos mensuales y crecimiento interanual por mes y año naturales",
			   "fi-FI", "Kk:ttain toistuva tuotto ja vuosittainen kasvu kalenterivuosittain ja -kuukausittain",
			   "fr-BE", "Revenu récurrent mensuel et croissance d’une année à l’autre par année civile et par mois",
			   "fr-CA", "Revenu récurrent mensuel et croissance d’une année à l’autre par année civile et par mois",
			   "fr-CH", "Revenu récurrent mensuel et croissance d’une année à l’autre par année civile et par mois",
			   "is-IS", "Mán. endurteknar tekjur og vöxtur milli ára eftir almanaksári og -mánuði",
			   "it-CH", "Ricavi periodici mensili e crescita anno su anno per anno e mese di calendario",
			   "it-IT", "Ricavi periodici mensili e crescita anno su anno per anno e mese di calendario",
			   "nb-NO", "Månedlig gjentakende inntekst og vekst år for år etter kalenderår og måned",
			   "nl-BE", "Maand. periodieke opbrengst en jaar-tot-jaar groei per kalenderjaar en -maand",
			   "nl-NL", "Maand. periodieke opbrengst en jaar-tot-jaar groei per kalenderjaar en -maand",
			   "ru-RU", "Mon. Recurring Revenue and Year-Over-Year Growth by Calendar Year and Month",
			   "sv-SE", "Månatliga återkommande intäkter och tillväxt år för år per kalenderår och månad",
			   "Mon. Recurring Revenue and Year-Over-Year Growth by Calendar Year and Month"
			)
		lineageTag: b46e31dd-929b-4ecf-8964-cf8b4580537f

	measure 'Mon. Recurring Revenue by Customer Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales por cliente",
			   "de-DE", "Mon. wiederkehrende Umsätze nach Debitor",
			   "fr-FR", "Revenu récurrent mensuel par client",
			   "cs-CZ", "Měsíční periodické výnosy podle zákazníka",
			   "da-DK", "Månedlig tilbagevendende indtægt efter debitor",
			   "de-AT", "Mon. wiederkehrende Umsätze nach Debitor",
			   "de-CH", "Mon. wiederkehrende Umsätze nach Debitor",
			   "en-AU", "Mon. Recurring Revenue by Customer",
			   "en-CA", "Mon. Recurring Revenue by Customer",
			   "en-GB", "Mon. Recurring Revenue by Customer",
			   "en-NZ", "Mon. Recurring Revenue by Customer",
			   "es-MX", "Ingresos periódicos mensuales por cliente",
			   "fi-FI", "Kk:ttain toistuva tuotto asiakkaittain",
			   "fr-BE", "Revenu récurrent mensuel par client",
			   "fr-CA", "Revenu récurrent mensuel par client",
			   "fr-CH", "Revenu récurrent mensuel par client",
			   "is-IS", "Mán. endurteknar tekjur eftir viðskiptavini",
			   "it-CH", "Ricavi periodici mensili per cliente",
			   "it-IT", "Ricavi periodici mensili per cliente",
			   "nb-NO", "Månedlig gjentakende inntekt etter kunde",
			   "nl-BE", "Maand. periodieke opbrengst per klant",
			   "nl-NL", "Maand. periodieke opbrengst per klant",
			   "ru-RU", "Mon. Recurring Revenue by Customer",
			   "sv-SE", "Månatliga återkommande intäkter per kund",
			   "Mon. Recurring Revenue by Customer"
			)
		lineageTag: 86c6e436-d86a-4ea3-81bb-942ad93dc96b

	measure 'Mon. Recurring Revenue by Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales por vendedor",
			   "de-DE", "Mon. wiederkehrende Umsätze nach Verkäufer",
			   "fr-FR", "Revenu récurrent mensuel par vendeur",
			   "cs-CZ", "Měsíční periodické výnosy podle prodejce",
			   "da-DK", "Månedlig tilbagevendende indtægt efter sælger",
			   "de-AT", "Mon. wiederkehrende Umsätze nach Verkäufer",
			   "de-CH", "Mon. wiederkehrende Umsätze nach Verkäufer",
			   "en-AU", "Mon. Recurring Revenue by Salesperson",
			   "en-CA", "Mon. Recurring Revenue by Salesperson",
			   "en-GB", "Mon. Recurring Revenue by Salesperson",
			   "en-NZ", "Mon. Recurring Revenue by Salesperson",
			   "es-MX", "Ingresos periódicos mensuales por vendedor",
			   "fi-FI", "Kk:ttain toistuva tuotto myyjittäin",
			   "fr-BE", "Revenu récurrent mensuel par vendeur",
			   "fr-CA", "Mois Revenus récurrents par représentant",
			   "fr-CH", "Revenu récurrent mensuel par vendeur",
			   "is-IS", "Mán. endurteknar tekjur eftir sölumanni",
			   "it-CH", "Ricavi periodici mensili per venditore",
			   "it-IT", "Ricavi periodici mensili per venditore",
			   "nb-NO", "Månedlig gjentakende inntekt etter selger",
			   "nl-BE", "Maand. periodieke opbrengst per verkoper",
			   "nl-NL", "Maand. periodieke opbrengst per verkoper",
			   "ru-RU", "Mon. Recurring Revenue by Salesperson",
			   "sv-SE", "Månatliga återkommande intäkter per säljare",
			   "Mon. Recurring Revenue by Salesperson"
			)
		lineageTag: ecc13d05-bb8f-4c64-be64-bd4d753a2f8d

	measure 'Mon. Recurring Revenue by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales por mes y año naturales",
			   "de-DE", "Mon. wiederkehrende Umsätze nach Kalenderjahr und Monat",
			   "fr-FR", "Revenu récurrent mensuel par année civile et par mois",
			   "cs-CZ", "Měsíční periodické výnosy podle kalendářního roku a měsíce",
			   "da-DK", "Månedlig tilbagevendende omsætning efter kalenderår og måned",
			   "de-AT", "Mon. wiederkehrende Umsätze nach Kalenderjahr und Monat",
			   "de-CH", "Mon. wiederkehrende Umsätze nach Kalenderjahr und Monat",
			   "en-AU", "Mon. Recurring Revenue by Calendar Year and Month",
			   "en-CA", "Mon. Recurring Revenue by Calendar Year and Month",
			   "en-GB", "Mon. Recurring Revenue by Calendar Year and Month",
			   "en-NZ", "Mon. Recurring Revenue by Calendar Year and Month",
			   "es-MX", "Ingresos periódicos mensuales por mes y año naturales",
			   "fi-FI", "Kk:ttain toistuva tuotto kalenterivuosittain ja -kuukausittain",
			   "fr-BE", "Revenu récurrent mensuel par année civile et par mois",
			   "fr-CA", "Revenu récurrent mensuel par année civile et par mois",
			   "fr-CH", "Revenu récurrent mensuel par année civile et par mois",
			   "is-IS", "Mán. endurteknar tekjur eftir almanaksári og -mánuði",
			   "it-CH", "Ricavi periodici mensili per anno e mese di calendario",
			   "it-IT", "Ricavi periodici mensili per anno e mese di calendario",
			   "nb-NO", "Månedlig gjentakende inntekt etter kalenderår og måned",
			   "nl-BE", "Maand. periodieke opbrengst per kalenderjaar en -maand",
			   "nl-NL", "Maand. periodieke opbrengst per kalenderjaar en -maand",
			   "ru-RU", "Mon. Recurring Revenue by Calendar Year and Month",
			   "sv-SE", "Månatliga återkommande intäkter per kalenderår och månad",
			   "Mon. Recurring Revenue by Calendar Year and Month"
			)
		lineageTag: 7e9bfa7a-d0d1-4885-9d86-b02de9483267

	measure 'Mon. Recurring Revenue by Item Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales por producto",
			   "de-DE", "Mon. wiederkehrende Umsätze nach Artikel",
			   "fr-FR", "Revenu récurrent mensuel par article",
			   "cs-CZ", "Měsíční periodické výnosy podle zboží",
			   "da-DK", "Månedlig tilbagevendende indtægt efter vare",
			   "de-AT", "Mon. wiederkehrende Umsätze nach Artikel",
			   "de-CH", "Mon. wiederkehrende Umsätze nach Artikel",
			   "en-AU", "Mon. Recurring Revenue by Item",
			   "en-CA", "Mon. Recurring Revenue by Item",
			   "en-GB", "Mon. Recurring Revenue by Item",
			   "en-NZ", "Mon. Recurring Revenue by Item",
			   "es-MX", "Ingresos periódicos mensuales por producto",
			   "fi-FI", "Kk:ttain toistuva tuotto nimikkeittäin",
			   "fr-BE", "Revenu récurrent mensuel par article",
			   "fr-CA", "Revenu récurrent mensuel par article",
			   "fr-CH", "Revenu récurrent mensuel par article",
			   "is-IS", "Mán. endurteknar tekjur eftir vöru",
			   "it-CH", "Ricavi periodici mensili per articolo",
			   "it-IT", "Ricavi periodici mensili per articolo",
			   "nb-NO", "Månedlig gjentakende inntekt etter vare",
			   "nl-BE", "Maand. periodieke opbrengst per artikel",
			   "nl-NL", "Maand. periodieke opbrengst per artikel",
			   "ru-RU", "Mon. Recurring Revenue by Item",
			   "sv-SE", "Månatliga återkommande intäkter per artikel",
			   "Mon. Recurring Revenue by Item"
			)
		lineageTag: 1a76e5f4-e4df-4617-9f62-036d50f674ff

	measure 'Mon. Recurring Revenue by Item Category Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales por categoría de producto",
			   "de-DE", "Mon. wiederkehrende Umsätze nach Kategorie",
			   "fr-FR", "Catégorie revenu récurrent mensuel par article",
			   "cs-CZ", "Měsíční periodické výnosy podle kategorie zboží",
			   "da-DK", "Månedlig tilbagevendende indtægt efter kategori",
			   "de-AT", "Mon. wiederkehrende Umsätze nach Kategorie",
			   "de-CH", "Mon. wiederkehrende Umsätze nach Kategorie",
			   "en-AU", "Mon. Recurring Revenue by Item Category",
			   "en-CA", "Mon. Recurring Revenue by Item Category",
			   "en-GB", "Mon. Recurring Revenue by Item Category",
			   "en-NZ", "Mon. Recurring Revenue by Item Category",
			   "es-MX", "Ingresos periódicos mensuales por categoría de producto",
			   "fi-FI", "Kk:ttain toistuva tuotto nimikeluokittain",
			   "fr-BE", "Catégorie revenu récurrent mensuel par article",
			   "fr-CA", "Catégorie revenu récurrent mensuel par article",
			   "fr-CH", "Catégorie revenu récurrent mensuel par article",
			   "is-IS", "Mán. endurteknar tekjur eftir vöruflokkum",
			   "it-CH", "Ricavi periodici mensili per categoria articolo",
			   "it-IT", "Ricavi periodici mensili per categoria articolo",
			   "nb-NO", "Månedlig gjentakende inntekt etter varekategori",
			   "nl-BE", "Maand. periodieke opbrengst per artikelcategorie",
			   "nl-NL", "Maand. periodieke opbrengst per artikelcategorie",
			   "ru-RU", "Mon. Recurring Revenue by Item Category",
			   "sv-SE", "Månatliga återkommande intäkter per artikelkategori",
			   "Mon. Recurring Revenue by Item Category"
			)
		lineageTag: 17afa1b0-2619-4864-81a3-1021c875f6e6

	measure 'Mon. Recurring Revenue Churn and Downgrade by Customer Contract Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Abandono y rebaja de ingresos periódicos mensuales por contrato de cliente",
			   "de-DE", "Mon. wiederkehrende Umsatzabwanderung und Downgrade nach Debitorenvertrag",
			   "fr-FR", "Attrition et rétrogradation revenu récurrent mensuel par contrat client",
			   "cs-CZ", "Odchod zákazníků a downgrade měsíčních periodických výnosů podle zákaznické smlouvy",
			   "da-DK", "Månedlig tilbagevendende indtægtsafgang og nedgradering efter debitorkontrakt",
			   "de-AT", "Mon. wiederkehrende Umsatzabwanderung und Downgrade nach Debitorenvertrag",
			   "de-CH", "Mon. wiederkehrende Umsatzabwanderung und Downgrade nach Debitorenvertrag",
			   "en-AU", "Mon. Recurring Revenue Churn and Downgrade by Customer Contract",
			   "en-CA", "Mon. Recurring Revenue Churn and Downgrade by Customer Contract",
			   "en-GB", "Mon. Recurring Revenue Churn and Downgrade by Customer Contract",
			   "en-NZ", "Mon. Recurring Revenue Churn and Downgrade by Customer Contract",
			   "es-MX", "Abandono y rebaja de ingresos periódicos mensuales por contrato de cliente",
			   "fi-FI", "Kk:ttain toistuvan tuoton Vaihtuvuus ja Palautus asiakassopimuksittain",
			   "fr-BE", "Attrition et rétrogradation revenu récurrent mensuel par contrat client",
			   "fr-CA", "Attrition et rétrogradation revenu récurrent mensuel par contrat client",
			   "fr-CH", "Attrition et rétrogradation revenu récurrent mensuel par contrat client",
			   "is-IS", "Mán uppsögn endurtekinna tekna og niðurfærsla eftir samningi við viðskiptavin",
			   "it-CH", "Abbandono e downgrade ricavi periodici mensili per contratto cliente",
			   "it-IT", "Abbandono e downgrade ricavi periodici mensili per contratto cliente",
			   "nb-NO", "Månedlig gjentakende inntektsfrafall og -nedgradering etter kundekontrakt",
			   "nl-BE", "Maand. periodiek opbrengstverloop en downgrade per klantcontract",
			   "nl-NL", "Maand. periodiek opbrengstverloop en downgrade per klantcontract",
			   "ru-RU", "Mon. Recurring Revenue Churn and Downgrade by Customer Contract",
			   "sv-SE", "Månatliga återkommande intäktsbortfall och nedgradering per kundkontrakt",
			   "Mon. Recurring Revenue Churn and Downgrade by Customer Contract"
			)
		lineageTag: 4d3f4eed-f343-4abd-83ce-daa8399da37b

	measure 'Mon. Recurring Revenue New and Upgrade by Customer Contract Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales nuevos y actualizados por contrato de cliente",
			   "de-DE", "Mon. wiederkehrende Neuumsätze und Upgrade nach Debitorenvertrag",
			   "fr-FR", "Revenu récurrent mensuel nouveau et mis à niveau par contrat client",
			   "cs-CZ", "Noví zákazníci a upgrade měsíčních periodických výnosů podle zákaznické smlouvy",
			   "da-DK", "Månedlig tilbagevendende indtægter Nye og opgradering efter debitorkontrakt",
			   "de-AT", "Mon. wiederkehrende Neuumsätze und Upgrade nach Debitorenvertrag",
			   "de-CH", "Mon. wiederkehrende Neuumsätze und Upgrade nach Debitorenvertrag",
			   "en-AU", "Mon. Recurring Revenue New and Upgrade by Customer Contract",
			   "en-CA", "Mon. Recurring Revenue New and Upgrade by Customer Contract",
			   "en-GB", "Mon. Recurring Revenue New and Upgrade by Customer Contract",
			   "en-NZ", "Mon. Recurring Revenue New and Upgrade by Customer Contract",
			   "es-MX", "Ingresos periódicos mensuales nuevos y actualizados por contrato de cliente",
			   "fi-FI", "Kk:ttain toistuvan tuoton Uusi ja Päivitä asiakassopimuksittain",
			   "fr-BE", "Revenu récurrent mensuel nouveau et mis à niveau par contrat client",
			   "fr-CA", "Revenu récurrent mensuel nouveau et mis à niveau par contrat client",
			   "fr-CH", "Revenu récurrent mensuel nouveau et mis à niveau par contrat client",
			   "is-IS", "Mán. Endurteknar tekjur nýjar og uppfærðar eftir samningi við viðskiptavin",
			   "it-CH", "Novità e aggiornamento ricavi periodici mensili per contratto cliente",
			   "it-IT", "Novità e aggiornamento ricavi periodici mensili per contratto cliente",
			   "nb-NO", "Månedlig gjentakende inntekt ny og oppgradering etter kundekontrakt",
			   "nl-BE", "Maand. periodieke opbrengst nieuw en upgrade per klantcontract",
			   "nl-NL", "Maand. periodieke opbrengst nieuw en upgrade per klantcontract",
			   "ru-RU", "Mon. Recurring Revenue New and Upgrade by Customer Contract",
			   "sv-SE", "Månatliga återkommande intäkter, nya och nedgradering per kundkontrakt",
			   "Mon. Recurring Revenue New and Upgrade by Customer Contract"
			)
		lineageTag: f89404e1-e02b-40ff-a53c-caf606d194c3

	measure 'Monthly Sales and Cost Forecast by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Previsión mensual de ingresos y costes por mes y año natural",
			   "de-DE", "Monatliche Umsatz- und Kostenplanung nach Kalenderjahr und Monat",
			   "fr-FR", "Revenus mensuels et coûts prévus par année civile et par mois",
			   "cs-CZ", "Měsíční prognóza výnosů a nákladů podle kalendářního roku a měsíce",
			   "da-DK", "Månedlig omsætning og omkostningsprognose efter kalenderår og måned",
			   "de-AT", "Monatliche Umsatz- und Kostenplanung nach Kalenderjahr und Monat",
			   "de-CH", "Monatliche Umsatz- und Kostenplanung nach Kalenderjahr und Monat",
			   "en-AU", "Monthly Revenue and Cost Forecast by Calendar Year and Month",
			   "en-CA", "Monthly Revenue and Cost Forecast by Calendar Year and Month",
			   "en-GB", "Monthly Revenue and Cost Forecast by Calendar Year and Month",
			   "en-NZ", "Monthly Revenue and Cost Forecast by Calendar Year and Month",
			   "es-MX", "Previsión mensual de ingresos y costos por mes y año natural",
			   "fi-FI", "Kuukausittainen tuotto- ja kustannusennuste kalenterivuovuosittain ja -kuukausittain",
			   "fr-BE", "Revenus mensuels et coûts prévus par année civile et par mois",
			   "fr-CA", "Revenus mensuels et coûts prévus par année civile et par mois",
			   "fr-CH", "Revenus mensuels et coûts prévus par année civile et par mois",
			   "is-IS", "Mánaðarleg tekju- og kostnaðarspá eftir almanaksári og -mánuði",
			   "it-CH", "Previsioni mensili di ricavi e costi per anno e mese di calendario",
			   "it-IT", "Previsioni mensili di ricavi e costi per anno e mese di calendario",
			   "nb-NO", "Månedlig inntekts- og kostnadsprognose etter kalenderår og måned",
			   "nl-BE", "Maandelijkse opbrengst- en kostenprognose per kalenderjaar en -maand",
			   "nl-NL", "Maandelijkse opbrengst- en kostenprognose per kalenderjaar en -maand",
			   "ru-RU", "Monthly Revenue and Cost Forecast by Calendar Year and Month",
			   "sv-SE", "Månatlig intäkts- och kostnadsprognos per kalenderår och månad",
			   "Monthly Revenue and Cost Forecast by Calendar Year and Month"
			)
		lineageTag: 541796e8-5303-483b-b0a2-896236758965

	measure 'Monthly Sales and Cost Forecast by Salesperson, Customer and Contract No. Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Previsión mensual de ingresos y costes por vendedor, cliente y n.º contrato",
			   "de-DE", "Monatliche Umsatz- und Kostenplanung nach Verkäufer, Debitor und Vertragsnr.",
			   "fr-FR", "Revenus mensuels et coûts prévus par vendeur, client et n° contrat",
			   "cs-CZ", "Prognóza měsíčních výnosů a nákladů podle prodejce, zákazníka a č. smlouvy",
			   "da-DK", "Månedlig omsætning og omkostningsprognose efter sælger, debitor og kontraktnr.",
			   "de-AT", "Monatliche Umsatz- und Kostenplanung nach Verkäufer, Debitor und Vertragsnr.",
			   "de-CH", "Monatliche Umsatz- und Kostenplanung nach Verkäufer, Debitor und Vertragsnr.",
			   "en-AU", "Monthly Revenue and Cost Forecast by Salesperson, Customer and Contract No.",
			   "en-CA", "Monthly Revenue and Cost Forecast by Salesperson, Customer and Contract No.",
			   "en-GB", "Monthly Revenue and Cost Forecast by Salesperson, Customer and Contract No.",
			   "en-NZ", "Monthly Revenue and Cost Forecast by Salesperson, Customer and Contract No.",
			   "es-MX", "Previsión mensual de ingresos y costos por vendedor, cliente y n.º contrato",
			   "fi-FI", "Kuukausittainen tuotto- ja kustannusennuste myyjän, asiakkaan ja sopimuksen numeron mukaan",
			   "fr-BE", "Revenus mensuels et coûts prévus par vendeur, client et n° contrat",
			   "fr-CA", "Prévisions mensuelles de revenus et de coûts par représentant, client et numéro de contrat",
			   "fr-CH", "Revenus mensuels et coûts prévus par vendeur, client et n° contrat",
			   "is-IS", "Mánaðarleg tekju- og kostnaðarspá sölumanns, viðskiptavinar og samnings nr.",
			   "it-CH", "Previsione mensile dei ricavi e dei costi per venditore, cliente e nr. contratto",
			   "it-IT", "Previsione mensile dei ricavi e dei costi per venditore, cliente e nr. contratto",
			   "nb-NO", "Månedlig inntekts- og kostnadsprognose etter selger, kunde- og kontraktnr.",
			   "nl-BE", "Maandelijkse opbrengst en kostenprognose per verkoper, klant en contractnr.",
			   "nl-NL", "Maandelijkse opbrengst en kostenprognose per verkoper, klant en contractnr.",
			   "ru-RU", "Monthly Revenue and Cost Forecast by Salesperson, Customer and Contract No.",
			   "sv-SE", "Månatliga intäkter och kostnadsprognos per säljare, kund och kontraktsnr",
			   "Monthly Revenue and Cost Forecast by Salesperson, Customer and Contract No."
			)
		lineageTag: 6278d3d4-d4fe-487b-8afd-080e47fc5193

	measure 'Released and Deferred Amount by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe liberado y fraccionado por mes y año naturales",
			   "de-DE", "Freigegebener und abgegrenzter Betrag nach Kalenderjahr und Monat",
			   "fr-FR", "Montant lancé et échelonné par année civile et par mois",
			   "cs-CZ", "Uvolněná a časové rozlišená částka podle kalendářního roku a měsíce",
			   "da-DK", "Frigivne og udskudte beløb efter kalenderår og måned",
			   "de-AT", "Freigegebener und abgegrenzter Betrag nach Kalenderjahr und Monat",
			   "de-CH", "Freigegebener und abgegrenzter Betrag nach Kalenderjahr und Monat",
			   "en-AU", "Released and Deferred Amount by Calendar Year and Month",
			   "en-CA", "Released and Deferred Amount by Calendar Year and Month",
			   "en-GB", "Released and Deferred Amount by Calendar Year and Month",
			   "en-NZ", "Released and Deferred Amount by Calendar Year and Month",
			   "es-MX", "Importe liberado y fraccionado por mes y año naturales",
			   "fi-FI", "Vapautettu ja siirretty summa kalenterivuosittain ja -kuukausittain",
			   "fr-BE", "Montant lancé et échelonné par année civile et par mois",
			   "fr-CA", "Montant libéré et différé par année civile et par mois",
			   "fr-CH", "Montant lancé et échelonné par année civile et par mois",
			   "is-IS", "Losuð og frestuð upphæð eftir almanaksári og -mánuði",
			   "it-CH", "Importo rilasciato e differito per anno e mese di calendario",
			   "it-IT", "Importo rilasciato e differito per anno e mese di calendario",
			   "nb-NO", "Frigitt og periodisert beløp etter kalenderår og måned",
			   "nl-BE", "Vrijgegeven en uitgesteld bedrag per kalenderjaar en -maand",
			   "nl-NL", "Vrijgegeven en uitgesteld bedrag per kalenderjaar en -maand",
			   "ru-RU", "Released and Deferred Amount by Calendar Year and Month",
			   "sv-SE", "Frisläppt och periodiserat belopp per kalenderår och månad",
			   "Released and Deferred Amount by Calendar Year and Month"
			)
		lineageTag: 5be47dec-2eee-49ba-8137-98a86ba713e5

	measure 'Revenue Analysis Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis de ingresos",
			   "de-DE", "Umsatzanalyse",
			   "fr-FR", "Analyse du revenu",
			   "cs-CZ", "Analýza výnosů",
			   "da-DK", "Omsætningsanalyse",
			   "de-AT", "Umsatzanalyse",
			   "de-CH", "Umsatzanalyse",
			   "en-AU", "Revenue Analysis",
			   "en-CA", "Revenue Analysis",
			   "en-GB", "Revenue Analysis",
			   "en-NZ", "Revenue Analysis",
			   "es-MX", "Análisis de ingresos",
			   "fi-FI", "Tuottoanalyysi",
			   "fr-BE", "Analyse du revenu",
			   "fr-CA", "Analyse du revenu",
			   "fr-CH", "Analyse du revenu",
			   "is-IS", "Greining tekja",
			   "it-CH", "Analisi ricavi",
			   "it-IT", "Analisi ricavi",
			   "nb-NO", "Inntektsanalyse",
			   "nl-BE", "Opbrengstanalyse",
			   "nl-NL", "Opbrengstanalyse",
			   "ru-RU", "Revenue Analysis",
			   "sv-SE", "Intäktsanalys",
			   "Revenue Analysis"
			)
		lineageTag: 5f1f6e4c-1c46-4771-96c4-2adad19e6441

	measure 'Revenue by Customer Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos por cliente",
			   "de-DE", "Umsatz nach Debitor",
			   "fr-FR", "Revenu par client",
			   "cs-CZ", "Výnosy podle zákazníka",
			   "da-DK", "Omsætning pr. debitor",
			   "de-AT", "Umsatz nach Debitor",
			   "de-CH", "Umsatz nach Debitor",
			   "en-AU", "Revenue by Customer",
			   "en-CA", "Revenue by Customer",
			   "en-GB", "Revenue by Customer",
			   "en-NZ", "Revenue by Customer",
			   "es-MX", "Ingresos por cliente",
			   "fi-FI", "Asiakaskohtainen tuotto",
			   "fr-BE", "Revenu par client",
			   "fr-CA", "Revenu par client",
			   "fr-CH", "Revenu par client",
			   "is-IS", "Tekjur eftir viðskiptamanni",
			   "it-CH", "Ricavi per cliente",
			   "it-IT", "Ricavi per cliente",
			   "nb-NO", "Inntekt etter kunde",
			   "nl-BE", "Opbrengst per klant",
			   "nl-NL", "Opbrengst per klant",
			   "ru-RU", "Revenue by Customer",
			   "sv-SE", "Intäkt per kund",
			   "Revenue by Customer"
			)
		lineageTag: 4a81cfb0-3e45-4c8d-b22c-f1ad8699f3e6

	measure 'Revenue by Item Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos por producto",
			   "de-DE", "Umsatz nach Artikel",
			   "fr-FR", "Revenu par article",
			   "cs-CZ", "Výnosy podle zboží",
			   "da-DK", "Omsætning pr. vare",
			   "de-AT", "Umsatz nach Artikel",
			   "de-CH", "Umsatz nach Artikel",
			   "en-AU", "Revenue by Item",
			   "en-CA", "Revenue by Item",
			   "en-GB", "Revenue by Item",
			   "en-NZ", "Revenue by Item",
			   "es-MX", "Ingresos por producto",
			   "fi-FI", "Nimikekohtainen tuotto",
			   "fr-BE", "Revenu par article",
			   "fr-CA", "Revenu par article",
			   "fr-CH", "Revenu par article",
			   "is-IS", "Tekjur eftir vöru",
			   "it-CH", "Ricavi per articolo",
			   "it-IT", "Ricavi per articolo",
			   "nb-NO", "Inntekt etter vare",
			   "nl-BE", "Opbrengst per artikel",
			   "nl-NL", "Opbrengst per artikel",
			   "ru-RU", "Revenue by Item",
			   "sv-SE", "Intäkt per artikel",
			   "Revenue by Item"
			)
		lineageTag: 0b4d132f-6a8a-49e7-9e58-348621695e40

	measure 'Revenue by Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos por vendedor",
			   "de-DE", "Umsatz nach Verkäufer",
			   "fr-FR", "Revenu par vendeur",
			   "cs-CZ", "Výnosy podle prodejce",
			   "da-DK", "Omsætning pr. sælger",
			   "de-AT", "Umsatz nach Verkäufer",
			   "de-CH", "Umsatz nach Verkäufer",
			   "en-AU", "Revenue by Salesperson",
			   "en-CA", "Revenue by Salesperson",
			   "en-GB", "Revenue by Salesperson",
			   "en-NZ", "Revenue by Salesperson",
			   "es-MX", "Ingresos por vendedor",
			   "fi-FI", "Myyjäkohtainen tuotto",
			   "fr-BE", "Revenu par vendeur",
			   "fr-CA", "Revenus par représentant",
			   "fr-CH", "Revenu par vendeur",
			   "is-IS", "Tekjur eftir sölumanni",
			   "it-CH", "Ricavi per venditore",
			   "it-IT", "Ricavi per venditore",
			   "nb-NO", "Inntekt per selger",
			   "nl-BE", "Opbrengst per verkoper",
			   "nl-NL", "Opbrengst per verkoper",
			   "ru-RU", "Revenue by Salesperson",
			   "sv-SE", "Intäkt per säljare",
			   "Revenue by Salesperson"
			)
		lineageTag: 8f79e3c2-8e6e-4cf4-8117-e6bd04d85996

	measure 'Revenue Development Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Desarrollo de ingresos",
			   "de-DE", "Umsatzentwicklung",
			   "fr-FR", "Développement du revenu",
			   "cs-CZ", "Vývoj výnosů",
			   "da-DK", "Omsætningsudvikling",
			   "de-AT", "Umsatzentwicklung",
			   "de-CH", "Umsatzentwicklung",
			   "en-AU", "Revenue Development",
			   "en-CA", "Revenue Development",
			   "en-GB", "Revenue Development",
			   "en-NZ", "Revenue Development",
			   "es-MX", "Desarrollo de ingresos",
			   "fi-FI", "Tuottokehitys",
			   "fr-BE", "Développement du revenu",
			   "fr-CA", "Développement du revenu",
			   "fr-CH", "Développement du revenu",
			   "is-IS", "Tekjuþróun",
			   "it-CH", "Sviluppo ricavi",
			   "it-IT", "Sviluppo ricavi",
			   "nb-NO", "Inntektsutvikling",
			   "nl-BE", "Opbrengstontwikkeling",
			   "nl-NL", "Opbrengstontwikkeling",
			   "ru-RU", "Revenue Development",
			   "sv-SE", "Intäktsutveckling",
			   "Revenue Development"
			)
		lineageTag: 1ed4bc86-f8d3-4574-adf2-3de940e2103b

	measure 'Sales and Cost Forecast Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Previsión de ingresos",
			   "de-DE", "Umsatzplanung",
			   "fr-FR", "Prévision de revenu",
			   "cs-CZ", "Prognóza výnosů",
			   "da-DK", "Indtægtsprognose",
			   "de-AT", "Umsatzplanung",
			   "de-CH", "Umsatzplanung",
			   "en-AU", "Revenue Forecast",
			   "en-CA", "Revenue Forecast",
			   "en-GB", "Revenue Forecast",
			   "en-NZ", "Revenue Forecast",
			   "es-MX", "Previsión de ingresos",
			   "fi-FI", "Tuottoennuste",
			   "fr-BE", "Prévision de revenu",
			   "fr-CA", "Prévision de revenu",
			   "fr-CH", "Prévision de revenu",
			   "is-IS", "Tekjuspá",
			   "it-CH", "Previsione ricavi",
			   "it-IT", "Previsione ricavi",
			   "nb-NO", "Inntektsprognose",
			   "nl-BE", "Opbrengstprognose",
			   "nl-NL", "Opbrengstprognose",
			   "ru-RU", "Revenue Forecast",
			   "sv-SE", "Intäktsprognos",
			   "Revenue Forecast"
			)
		lineageTag: e9b49c11-bef6-4774-a20b-192cbce0ccfe

	measure 'Revenue Year-Over-Year Growth Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Crecimiento interanual de los ingresos",
			   "de-DE", "Umsatzwachstum im Vergleich zum Vorjahr",
			   "fr-FR", "Croissance du revenu d’une année sur l’autre",
			   "cs-CZ", "Meziroční růst výnosů",
			   "da-DK", "Omsætning fra år til år vækst",
			   "de-AT", "Umsatzwachstum im Vergleich zum Vorjahr",
			   "de-CH", "Umsatzwachstum im Vergleich zum Vorjahr",
			   "en-AU", "Revenue Year-Over-Year Growth",
			   "en-CA", "Revenue Year-Over-Year Growth",
			   "en-GB", "Revenue Year-Over-Year Growth",
			   "en-NZ", "Revenue Year-Over-Year Growth",
			   "es-MX", "Crecimiento interanual de los ingresos",
			   "fi-FI", "Tuoton vuosittainen kasvu",
			   "fr-BE", "Croissance du revenu d’une année sur l’autre",
			   "fr-CA", "Croissance du revenu d’une année sur l’autre",
			   "fr-CH", "Croissance du revenu d’une année sur l’autre",
			   "is-IS", "Tekjuvöxtur milli ára",
			   "it-CH", "Crescita ricavi anno su anno",
			   "it-IT", "Crescita ricavi anno su anno",
			   "nb-NO", "Inntekstvekst år for år",
			   "nl-BE", "Opbrengstgroei jaar-tot-jaar",
			   "nl-NL", "Opbrengstgroei jaar-tot-jaar",
			   "ru-RU", "Revenue Year-Over-Year Growth",
			   "sv-SE", "Tillväxtökning år för år",
			   "Revenue Year-Over-Year Growth"
			)
		lineageTag: a7d84e67-5fb7-4d38-89e5-b83455b93aa9

	measure 'Subscription Billing Analysis Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis Subscription Billing",
			   "de-DE", "Subscription Billing-Analyse",
			   "fr-FR", "Analyse Subscription Billing",
			   "cs-CZ", "Analýza Subscription Billing",
			   "da-DK", "Analyse af Subscription Billing",
			   "de-AT", "Subscription Billing-Analyse",
			   "de-CH", "Subscription Billing-Analyse",
			   "en-AU", "Subscription Billing Analysis",
			   "en-CA", "Subscription Billing Analysis",
			   "en-GB", "Subscription Billing Analysis",
			   "en-NZ", "Subscription Billing Analysis",
			   "es-MX", "Análisis Subscription Billing",
			   "fi-FI", "Subscription Billing – Analyysi",
			   "fr-BE", "Analyse Subscription Billing",
			   "fr-CA", "Analyse Subscription Billing",
			   "fr-CH", "Analyse Subscription Billing",
			   "is-IS", "Subscription Billing greining",
			   "it-CH", "Analisi Subscription Billing",
			   "it-IT", "Analisi Subscription Billing",
			   "nb-NO", "Subscription Billing-analyse",
			   "nl-BE", "Analyse van Subscription Billing",
			   "nl-NL", "Analyse van Subscription Billing",
			   "ru-RU", "Subscription Billing Analysis",
			   "sv-SE", "Analys av Subscription Billing",
			   "Subscription Billing Analysis"
			)
		lineageTag: a3252ec9-bc13-4ba2-8ddb-4b218b358217

	measure 'Subscription Billing Overview Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Información general Subscription Billing",
			   "de-DE", "Übersicht über Subscription Billing",
			   "fr-FR", "Vue d’ensemble de Subscription Billing",
			   "cs-CZ", "Přehled Subscription Billing",
			   "da-DK", "Oversigt over Subscription Billing",
			   "de-AT", "Übersicht über Subscription Billing",
			   "de-CH", "Übersicht über Subscription Billing",
			   "en-AU", "Subscription Billing Overview",
			   "en-CA", "Subscription Billing Overview",
			   "en-GB", "Subscription Billing Overview",
			   "en-NZ", "Subscription Billing Overview",
			   "es-MX", "Información general Subscription Billing",
			   "fi-FI", "Subscription Billing – Yleiskatsaus",
			   "fr-BE", "Vue d’ensemble de Subscription Billing",
			   "fr-CA", "Vue d’ensemble de Subscription Billing",
			   "fr-CH", "Vue d’ensemble de Subscription Billing",
			   "is-IS", "Subscription Billing yfirlit",
			   "it-CH", "Panoramica di Subscription Billing",
			   "it-IT", "Panoramica di Subscription Billing",
			   "nb-NO", "Oversikt over Subscription Billing",
			   "nl-BE", "Overzicht van Subscription Billing",
			   "nl-NL", "Overzicht van Subscription Billing",
			   "ru-RU", "Subscription Billing Overview",
			   "sv-SE", "Översikt över Subscription Billing",
			   "Subscription Billing Overview"
			)
		lineageTag: 46da08f4-9f2b-4015-9d38-1591ae7667bf

	measure 'Top 5 Customers by Mon. Recurring Revenue Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Los 5 clientes principales por Ingresos periódicos mensuales",
			   "de-DE", "Top-5-Debitoren nach mon. wiederkehrenden Umsätzen",
			   "fr-FR", "5 premiers clients par revenu récurrent mensuel",
			   "cs-CZ", "5 předních zákazníků podle měsíčního periodického výnosu",
			   "da-DK", "Top 5 debitorer efter månedlig tilbagevendende indtægt",
			   "de-AT", "Top-5-Debitoren nach mon. wiederkehrenden Umsätzen",
			   "de-CH", "Top-5-Debitoren nach mon. wiederkehrenden Umsätzen",
			   "en-AU", "Top 5 Customers by Mon. Recurring Revenue",
			   "en-CA", "Top 5 Customers by Mon. Recurring Revenue",
			   "en-GB", "Top 5 Customers by Mon. Recurring Revenue",
			   "en-NZ", "Top 5 Customers by Mon. Recurring Revenue",
			   "es-MX", "Los 5 clientes principales por Ingresos periódicos mensuales",
			   "fi-FI", "Viisi suurinta asiakasta kk:ttain toistuvan tuoton mukaan",
			   "fr-BE", "5 premiers clients par revenu récurrent mensuel",
			   "fr-CA", "5 premiers clients par revenu récurrent mensuel",
			   "fr-CH", "5 premiers clients par revenu récurrent mensuel",
			   "is-IS", "5 hæstu viðskiptavinirnir eftir mán. endurteknum tekjum",
			   "it-CH", "Primi 5 clienti per ricavi periodici mensili",
			   "it-IT", "Primi 5 clienti per ricavi periodici mensili",
			   "nb-NO", "Beste fem kunder etter månedlig gjentakende inntekt",
			   "nl-BE", "Top 5 klanten per maand. periodieke opbrengst",
			   "nl-NL", "Top 5 klanten per maand. periodieke opbrengst",
			   "ru-RU", "Top 5 Customers by Mon. Recurring Revenue",
			   "sv-SE", "5 främsta kunderna per månatliga återkommande intäkter",
			   "Top 5 Customers by Mon. Recurring Revenue"
			)
		lineageTag: 7553c68d-684f-4926-9238-0d04f0dac63a

	measure 'Top 5 Vendors by Mon. Recurring Cost Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Los 5 principales proveedores por coste periódico mensual",
			   "de-DE", "Top-5-Kreditoren nach mon. wiederkehrenden Kosten",
			   "fr-FR", "5 premiers fournisseurs par coût mensuel récurrent",
			   "cs-CZ", "5 nejlepších prodejců podle měsíčních periodických nákladů",
			   "da-DK", "Top 5 kreditorer efter månedlige tilbagevendende omkostninger",
			   "de-AT", "Top-5-Kreditoren nach mon. wiederkehrenden Kosten",
			   "de-CH", "Top-5-Kreditoren nach mon. wiederkehrenden Kosten",
			   "en-AU", "Top 5 Vendors by Mon. Recurring Cost",
			   "en-CA", "Top 5 Vendors by Mon. Recurring Cost",
			   "en-GB", "Top 5 Vendors by Mon. Recurring Cost",
			   "en-NZ", "Top 5 Vendors by Mon. Recurring Cost",
			   "es-MX", "Los 5 principales proveedores por costo periódico mensual",
			   "fi-FI", "5 suurinta toimittajaa kk:ttain toistuvien kustannusten mukaan",
			   "fr-BE", "5 premiers fournisseurs par coût mensuel récurrent",
			   "fr-CA", "5 premiers fournisseurs par coût mensuel récurrent",
			   "fr-CH", "5 premiers fournisseurs par coût mensuel récurrent",
			   "is-IS", "5 hæstu lánardrottnar fyrir mán. endurtekinn kostnað",
			   "it-CH", "Primi 5 fornitori per costo periodico mensile",
			   "it-IT", "Primi 5 fornitori per costo periodico mensile",
			   "nb-NO", "Beste fem leverandører etter månedlig gjentakende kostnad",
			   "nl-BE", "Top 5 leveranciers op maand. periodieke kosten",
			   "nl-NL", "Top 5 leveranciers op maand. periodieke kosten",
			   "ru-RU", "Top 5 Vendors by Mon. Recurring Cost",
			   "sv-SE", "5 främsta leverantörer per månatlig återkommande kostnad",
			   "Top 5 Vendors by Mon. Recurring Cost"
			)
		lineageTag: 8b985f10-aaff-40d1-bc78-9390c4e754bb

	measure 'Total Contract Value Analysis Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis del valor total del contrato",
			   "de-DE", "Gesamtvertragswertanalyse",
			   "fr-FR", "Analyse de la valeur totale du contrat",
			   "cs-CZ", "Analýza celkové hodnoty smlouvy",
			   "da-DK", "Analyse af samlet kontraktværdi",
			   "de-AT", "Gesamtvertragswertanalyse",
			   "de-CH", "Gesamtvertragswertanalyse",
			   "en-AU", "Total Contract Value Analysis",
			   "en-CA", "Total Contract Value Analysis",
			   "en-GB", "Total Contract Value Analysis",
			   "en-NZ", "Total Contract Value Analysis",
			   "es-MX", "Análisis del valor total del contrato",
			   "fi-FI", "Sopimuksen kokonaisarvon analyysi",
			   "fr-BE", "Analyse de la valeur totale du contrat",
			   "fr-CA", "Analyse de la valeur totale du contrat",
			   "fr-CH", "Analyse de la valeur totale du contrat",
			   "is-IS", "Heildargreining samningsvirðis",
			   "it-CH", "Analisi valore totale del contratto",
			   "it-IT", "Analisi valore totale del contratto",
			   "nb-NO", "Analyse av total kontraktverdi",
			   "nl-BE", "Analyse van totale contractwaarde",
			   "nl-NL", "Analyse van totale contractwaarde",
			   "ru-RU", "Total Contract Value Analysis",
			   "sv-SE", "Analys av totalt kontraktsvärde",
			   "Total Contract Value Analysis"
			)
		lineageTag: b4c8e534-7971-4f5a-aa28-44d55825bb95

	measure 'Total Contract Value and Total Contract Value PY by Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor total del contrato y valor total del contrato AA por mes natural",
			   "de-DE", "Gesamtvertragswert und Gesamtvertragswert VJ nach Kalendermonat",
			   "fr-FR", "Valeur totale du contrat et valeur totale du contrat AP par mois civil",
			   "cs-CZ", "Celková hodnota smlouvy a PR celkové hodnoty smlouvy podle kalendářního měsíce",
			   "da-DK", "Samlet kontraktværdi og samlet kontraktværdi FÅ efter kalendermåned",
			   "de-AT", "Gesamtvertragswert und Gesamtvertragswert VJ nach Kalendermonat",
			   "de-CH", "Gesamtvertragswert und Gesamtvertragswert VJ nach Kalendermonat",
			   "en-AU", "Total Contract Value and Total Contract Value PY by Calendar Month",
			   "en-CA", "Total Contract Value and Total Contract Value PY by Calendar Month",
			   "en-GB", "Total Contract Value and Total Contract Value PY by Calendar Month",
			   "en-NZ", "Total Contract Value and Total Contract Value PY by Calendar Month",
			   "es-MX", "Valor total del contrato y valor total del contrato AA por mes natural",
			   "fi-FI", "Sopimuksen kokonaisarvo ja Sopimuksen kokonaisarvo EDV kalenterikuukausittain",
			   "fr-BE", "Valeur totale du contrat et valeur totale du contrat AP par mois civil",
			   "fr-CA", "Valeur totale du contrat et valeur totale du contrat AP par mois civil",
			   "fr-CH", "Valeur totale du contrat et valeur totale du contrat AP par mois civil",
			   "is-IS", "Heildarsamningsvirði og heildarsamningsvirði fyrra árs eftir almanaksmánuði",
			   "it-CH", "Valore totale dei contratti e valore totale dei contratti PY per mese di calendario",
			   "it-IT", "Valore totale dei contratti e valore totale dei contratti PY per mese di calendario",
			   "nb-NO", "Total kontraktverdi og total kontraktverdi PÅ etter kalendermåned",
			   "nl-BE", "Totale contractwaarde en totale contractwaarde VJ per kalendermaand",
			   "nl-NL", "Totale contractwaarde en totale contractwaarde VJ per kalendermaand",
			   "ru-RU", "Total Contract Value and Total Contract Value PY by Calendar Month",
			   "sv-SE", "Totalt kontraktsvärde och totalt kontraktsvärde FÅ per kalendermånad",
			   "Total Contract Value and Total Contract Value PY by Calendar Month"
			)
		lineageTag: 3366c01d-e753-47f9-a126-727a4509520e

	measure 'Total Contract Value and Year-Over-Year Growth by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor total del contrato y crecimiento interanual por mes y año naturales",
			   "de-DE", "Gesamtvertragswert und Wachstum gegenüber dem Vorjahr nach Kalenderjahr und Monat",
			   "fr-FR", "Valeur totale des contrats et croissance d’une année à l’autre par année civile et par mois",
			   "cs-CZ", "Celková hodnota smlouvy a meziroční růst podle kalendářního roku a měsíce",
			   "da-DK", "Samlet kontraktværdi og vækst fra år til år efter kalenderår og måned",
			   "de-AT", "Gesamtvertragswert und Wachstum gegenüber dem Vorjahr nach Kalenderjahr und Monat",
			   "de-CH", "Gesamtvertragswert und Wachstum gegenüber dem Vorjahr nach Kalenderjahr und Monat",
			   "en-AU", "Total Contract Value and Year-Over-Year Growth by Calendar Year and Month",
			   "en-CA", "Total Contract Value and Year-Over-Year Growth by Calendar Year and Month",
			   "en-GB", "Total Contract Value and Year-Over-Year Growth by Calendar Year and Month",
			   "en-NZ", "Total Contract Value and Year-Over-Year Growth by Calendar Year and Month",
			   "es-MX", "Valor total del contrato y crecimiento interanual por mes y año naturales",
			   "fi-FI", "Sopimuksen kokonaisarvo ja vuosittainen kasvu kalenterivuosittain ja -kuukausittain",
			   "fr-BE", "Valeur totale des contrats et croissance d’une année à l’autre par année civile et par mois",
			   "fr-CA", "Valeur totale des contrats et croissance d’une année à l’autre par année civile et par mois",
			   "fr-CH", "Valeur totale des contrats et croissance d’une année à l’autre par année civile et par mois",
			   "is-IS", "Heildarvirði samnings og vöxtur milli ára eftir almanaksári og -mánuði",
			   "it-CH", "Valore totale del contratto e crescita anno su anno per anno e mese di calendario",
			   "it-IT", "Valore totale del contratto e crescita anno su anno per anno e mese di calendario",
			   "nb-NO", "Total kontraktverdi og vekst år for år etter kalenderår og måned",
			   "nl-BE", "Totale contractwaarde en jaar-tot-jaar groei per kalenderjaar en -maand",
			   "nl-NL", "Totale contractwaarde en jaar-tot-jaar groei per kalenderjaar en -maand",
			   "ru-RU", "Total Contract Value and Year-Over-Year Growth by Calendar Year and Month",
			   "sv-SE", "Totalt kontraktsvärde och tillväxt år för år per kalenderår och månad",
			   "Total Contract Value and Year-Over-Year Growth by Calendar Year and Month"
			)
		lineageTag: f4ec51de-5053-4fa7-b85c-d043bdf2ba52

	measure 'Total Contract Value by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor total de contrato por mes y año naturales",
			   "de-DE", "Gesamtvertragswert nach Kalenderjahr und Monat",
			   "fr-FR", "Valeur totale du contrat par année civile et par mois",
			   "cs-CZ", "Celková hodnota smlouvy podle kalendářního roku a měsíce",
			   "da-DK", "Samlet kontraktværdi efter kalenderår og måned",
			   "de-AT", "Gesamtvertragswert nach Kalenderjahr und Monat",
			   "de-CH", "Gesamtvertragswert nach Kalenderjahr und Monat",
			   "en-AU", "Total Contract Value by Calendar Year and Month",
			   "en-CA", "Total Contract Value by Calendar Year and Month",
			   "en-GB", "Total Contract Value by Calendar Year and Month",
			   "en-NZ", "Total Contract Value by Calendar Year and Month",
			   "es-MX", "Valor total de contrato por mes y año naturales",
			   "fi-FI", "Sopimuksen kokonaisarvo kalenterivuosittain ja -kuukausittain",
			   "fr-BE", "Valeur totale du contrat par année civile et par mois",
			   "fr-CA", "Valeur totale du contrat par année civile et par mois",
			   "fr-CH", "Valeur totale du contrat par année civile et par mois",
			   "is-IS", "Heildarverðmæti samnings eftir almanaksári og -mánuði",
			   "it-CH", "Valore totale del contratto per anno e mese di calendario",
			   "it-IT", "Valore totale del contratto per anno e mese di calendario",
			   "nb-NO", "Total kontraktverdi etter kalenderår og måned",
			   "nl-BE", "Totale contractwaarde per kalenderjaar en -maand",
			   "nl-NL", "Totale contractwaarde per kalenderjaar en -maand",
			   "ru-RU", "Total Contract Value by Calendar Year and Month",
			   "sv-SE", "Totalt kontraktsvärde per kalenderår och månad",
			   "Total Contract Value by Calendar Year and Month"
			)
		lineageTag: db2b801b-db63-4d38-ad79-dccf345b3e99

	measure 'Total Contract Value Year-Over-Year Growth Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Crecimiento interanual del valor total del contrato",
			   "de-DE", "Wachstum des Gesamtvertragswerts gegenüber dem Vorjahr",
			   "fr-FR", "Croissance de la valeur totale des contrats d’une année à l’autre",
			   "cs-CZ", "Meziroční růst celkové hodnoty smlouvy",
			   "da-DK", "Samlet kontraktværdi Vækst fra år til år",
			   "de-AT", "Wachstum des Gesamtvertragswerts gegenüber dem Vorjahr",
			   "de-CH", "Wachstum des Gesamtvertragswerts gegenüber dem Vorjahr",
			   "en-AU", "Total Contract Value Year-Over-Year Growth",
			   "en-CA", "Total Contract Value Year-Over-Year Growth",
			   "en-GB", "Total Contract Value Year-Over-Year Growth",
			   "en-NZ", "Total Contract Value Year-Over-Year Growth",
			   "es-MX", "Crecimiento interanual del valor total del contrato",
			   "fi-FI", "Sopimuksen kokonaisarvo – Vuosittainen kasvu",
			   "fr-BE", "Croissance de la valeur totale des contrats d’une année à l’autre",
			   "fr-CA", "Croissance de la valeur totale des contrats d’une année à l’autre",
			   "fr-CH", "Croissance de la valeur totale des contrats d’une année à l’autre",
			   "is-IS", "Heildarvöxtur samningsvirðis á milli ára",
			   "it-CH", "Crescita anno su anno del valore totale dei contratti",
			   "it-IT", "Crescita anno su anno del valore totale dei contratti",
			   "nb-NO", "Total kontraktverdivekst år for år",
			   "nl-BE", "Groei totale contractwaarde jaar-tot-jaar",
			   "nl-NL", "Groei totale contractwaarde jaar-tot-jaar",
			   "ru-RU", "Total Contract Value Year-Over-Year Growth",
			   "sv-SE", "Totalt kontraktsvärde tillväxt år för år",
			   "Total Contract Value Year-Over-Year Growth"
			)
		lineageTag: d18afde3-f0f5-4fd8-958c-1cc89de93fe6

	measure 'Vendor Contract Deferrals Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Fraccionamientos de contrato de proveedor",
			   "de-DE", "Kreditorenvertragsabgrenzungen",
			   "fr-FR", "Reports de contrat fournisseur",
			   "cs-CZ", "Časová rozlišení dodavatelské smlouvy",
			   "da-DK", "Periodiseringer af kreditorkontrakt",
			   "de-AT", "Kreditorenvertragsabgrenzungen",
			   "de-CH", "Kreditorenvertragsabgrenzungen",
			   "en-AU", "Vendor Contract Deferrals",
			   "en-CA", "Vendor Contract Deferrals",
			   "en-GB", "Vendor Contract Deferrals",
			   "en-NZ", "Vendor Contract Deferrals",
			   "es-MX", "Fraccionamientos de contrato de proveedor",
			   "fi-FI", "Toimittajasopimuksen siirrot",
			   "fr-BE", "Reports de contrat fournisseur",
			   "fr-CA", "Reports de contrat fournisseur",
			   "fr-CH", "Reports de contrat fournisseur",
			   "is-IS", "Frestanir lánardrottnasamnings",
			   "it-CH", "Differimenti contratto del fornitore",
			   "it-IT", "Differimenti contratto del fornitore",
			   "nb-NO", "Leverandørkontraktperiodiseringer",
			   "nl-BE", "Uitstel van leverancierscontracten",
			   "nl-NL", "Uitstel van leverancierscontracten",
			   "ru-RU", "Vendor Contract Deferrals",
			   "sv-SE", "Kontraktsperiodiseringar för leverantör",
			   "Vendor Contract Deferrals"
			)
		lineageTag: b347a370-d51c-416a-bb8b-038e54c52fcd

	measure 'Vendor Deferrals (Caption) Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Fraccionamientos de proveedores",
			   "de-DE", "Kreditorenabgrenzungen",
			   "fr-FR", "Reports fournisseur",
			   "cs-CZ", "Časová rozlišení dodavatele",
			   "da-DK", "Kreditorperiodiseringer",
			   "de-AT", "Kreditorenabgrenzungen",
			   "de-CH", "Kreditorenabgrenzungen",
			   "en-AU", "Vendor Deferrals",
			   "en-CA", "Vendor Deferrals",
			   "en-GB", "Vendor Deferrals",
			   "en-NZ", "Vendor Deferrals",
			   "es-MX", "Fraccionamientos de proveedores",
			   "fi-FI", "Toimittajasiirrot",
			   "fr-BE", "Reports fournisseur",
			   "fr-CA", "Reports fournisseur",
			   "fr-CH", "Reports fournisseur",
			   "is-IS", "Frestun lánardrottins",
			   "it-CH", "Differimenti fornitore",
			   "it-IT", "Differimenti fornitore",
			   "nb-NO", "Leverandørperiodiseringer",
			   "nl-BE", "Leveranciersuitstel",
			   "nl-NL", "Leveranciersuitstel",
			   "ru-RU", "Vendor Deferrals",
			   "sv-SE", "Leverantörsperiodiseringar",
			   "Vendor Deferrals"
			)
		lineageTag: 0ad61b9c-7718-45d5-b8ac-90b302b596cb

	measure 'Back button Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Botón Atrás",
			   "de-DE", "Schaltfläche „Zurück“",
			   "fr-FR", "Bouton Retour",
			   "cs-CZ", "Tlačítko zpět",
			   "da-DK", "Knappen Tilbage",
			   "de-AT", "Schaltfläche „Zurück“",
			   "de-CH", "Schaltfläche „Zurück“",
			   "en-AU", "Back button",
			   "en-CA", "Back button",
			   "en-GB", "Back button",
			   "en-NZ", "Back button",
			   "es-MX", "Botón Atrás",
			   "fi-FI", "Takaisin-painike",
			   "fr-BE", "Bouton Retour",
			   "fr-CA", "Bouton Retour",
			   "fr-CH", "Bouton Retour",
			   "is-IS", "Bakkhnappur",
			   "it-CH", "Pulsante Indietro",
			   "it-IT", "Pulsante Indietro",
			   "nb-NO", "Tilbakeknapp",
			   "nl-BE", "Knop Terug",
			   "nl-NL", "Knop Terug",
			   "ru-RU", "Back button",
			   "sv-SE", "Knappen Föregående",
			   "Back button"
			)
		lineageTag: c7179c22-ad28-4b0e-83a3-e275c4173712

	measure 'Monthly Recurring Revenue, Monthly Recurring Cost, Monthly Net Profit, Active Customers, Total Contract Value, Change in Monthly Recurring Revenue Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ingresos periódicos mensuales, Coste periódico mensual, Beneficio neto mensual, Clientes activos, Valor total del contrato, Cambio en los ingresos periódicos mensuales",
			   "de-DE", "Mon. wiederkehrende Umsätze, Monatlich wiederkehrende Kosten, monatlicher Nettogewinn, aktive Debitoren, Gesamtvertragswert, Veränderung der monatlich wiederkehrenden Umsätze",
			   "fr-FR", "Revenu récurrent mensuel, Coût mensuel récurrent, Marge nette par mois, Clients actifs, Valeur totale du contrat, Évolution du revenu mensuel récurrent",
			   "cs-CZ", "Měsíční periodické výnosy, Měsíční periodické náklady, Měsíční čistý zisk, Aktivní zákazníci, Celková hodnota smlouvy, Změna měsíčních periodických výnosů",
			   "da-DK", "Månedlig tilbagevendende omsætning, Månedlig tilbagevendende omkostning, Månedlig nettofortjeneste, Aktive debitorer, Samlet kontraktværdi, Ændring i månedlig tilbagevendende omsætning",
			   "de-AT", "Mon. wiederkehrende Umsätze, Monatlich wiederkehrende Kosten, monatlicher Nettogewinn, aktive Debitoren, Gesamtvertragswert, Veränderung der monatlich wiederkehrenden Umsätze",
			   "de-CH", "Mon. wiederkehrende Umsätze, Monatlich wiederkehrende Kosten, monatlicher Nettogewinn, aktive Debitoren, Gesamtvertragswert, Veränderung der monatlich wiederkehrenden Umsätze",
			   "en-AU", "Monthly Recurring Revenue, Monthly Recurring Cost, Monthly Net Profit, Active Customers, Total Contract Value, Change in Monthly Recurring Revenue",
			   "en-CA", "Monthly Recurring Revenue, Monthly Recurring Cost, Monthly Net Profit, Active Customers, Total Contract Value, Change in Monthly Recurring Revenue",
			   "en-GB", "Monthly Recurring Revenue, Monthly Recurring Cost, Monthly Net Profit, Active Customers, Total Contract Value, Change in Monthly Recurring Revenue",
			   "en-NZ", "Monthly Recurring Revenue, Monthly Recurring Cost, Monthly Net Profit, Active Customers, Total Contract Value, Change in Monthly Recurring Revenue",
			   "es-MX", "Ingresos periódicos mensuales, Costo periódico mensual, Beneficio neto mensual, Clientes activos, Valor total del contrato, Cambio en los ingresos periódicos mensuales",
			   "fi-FI", "Kuukausittain toistuva tuotto, Kuukausittainen toistuva kustannus, Kuukausittainen nettotulos, Aktiiviset asiakkaat, Sopimuksen kokonaisarvo, Kuukausittain toistuvan tuoton muutos",
			   "fr-BE", "Revenu récurrent mensuel, Coût mensuel récurrent, Marge nette par mois, Clients actifs, Valeur totale du contrat, Évolution du revenu mensuel récurrent",
			   "fr-CA", "Revenus mensuels récurrents, coûts mensuels récurrents, bénéfice net mensuel, clients actifs, valeur totale du contrat, variation des revenus mensuels récurrent",
			   "fr-CH", "Revenu récurrent mensuel, Coût mensuel récurrent, Marge nette par mois, Clients actifs, Valeur totale du contrat, Évolution du revenu mensuel récurrent",
			   "is-IS", "Mánaðarlegar endurteknar tekjur, mánaðarlegur endurtekinn kostnaður, mánaðarlegur hreinn hagnaður, virkir viðskiptavinir, heildarvirði samnings, breyting á mánaðarlegum endurteknum tekjum",
			   "it-CH", "Ricavi periodici mensili, costo periodico mensile, profitto netto mensile, clienti attivi, Valore totale contratto, variazione ricavi periodici mensili",
			   "it-IT", "Ricavi periodici mensili, costo periodico mensile, profitto netto mensile, clienti attivi, Valore totale contratto, variazione ricavi periodici mensili",
			   "nb-NO", "Månedlig gjentakende inntekt, månedlig gjentakende kostnad, månedlig nettofortjeneste, aktive kunder, total kontraktverdi, endring i månedlig gjentakende inntekt",
			   "nl-BE", "Maandelijkse periodieke opbrengst, Maandelijkse periodieke kosten, Maandelijkse nettowinst, Actieve klanten, Totale contractwaarde, Wijziging in maandelijks periodieke opbrengst",
			   "nl-NL", "Maandelijkse periodieke opbrengst, Maandelijkse periodieke kosten, Maandelijkse nettowinst, Actieve klanten, Totale contractwaarde, Wijziging in maandelijks periodieke opbrengst",
			   "ru-RU", "Monthly Recurring Revenue, Monthly Recurring Cost, Monthly Net Profit, Active Customers, Total Contract Value, Change in Monthly Recurring Revenue",
			   "sv-SE", "Månatliga återkommande intäkter, månatlig återkommande kostnad, månatlig nettovinst, aktiva kunder, totalt kontraktsvärde, förändring i månatliga återkommande intäkter",
			   "Monthly Recurring Revenue, Monthly Recurring Cost, Monthly Net Profit, Active Customers, Total Contract Value, Change in Monthly Recurring Revenue"
			)
		lineageTag: 38308fd7-4a4e-4476-b054-702230eab91d

	measure 'Churn Analysis Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis de abandono",
			   "de-DE", "Abwanderungsanalyse",
			   "fr-FR", "Analyse de l’attrition",
			   "cs-CZ", "Analýza ztráty zákazníků",
			   "da-DK", "Analyse af debitorafgang",
			   "de-AT", "Abwanderungsanalyse",
			   "de-CH", "Abwanderungsanalyse",
			   "en-AU", "Churn Analysis",
			   "en-CA", "Churn Analysis",
			   "en-GB", "Churn Analysis",
			   "en-NZ", "Churn Analysis",
			   "es-MX", "Análisis de abandono",
			   "fi-FI", "Vaihtuvuusanalyysi",
			   "fr-BE", "Analyse de l’attrition",
			   "fr-CA", "Analyse de l’attrition",
			   "fr-CH", "Analyse de l’attrition",
			   "is-IS", "Greining á uppsögnum",
			   "it-CH", "Analisi abbandono",
			   "it-IT", "Analisi abbandono",
			   "nb-NO", "Frafallsanalyse",
			   "nl-BE", "Verloopanalyse",
			   "nl-NL", "Verloopanalyse",
			   "ru-RU", "Churn Analysis",
			   "sv-SE", "Bortfallsanalys",
			   "Churn Analysis"
			)
		lineageTag: a3bec4e6-28c9-4bfb-8d26-a1b240688934

	measure 'Avg. Mon. Churn Rate % by Year and Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "% tasa de abandono men. medio por año y mes",
			   "de-DE", "Durchschn. mon. Abwanderungsrate % nach Jahr und Monat",
			   "fr-FR", "% taux d’attrition mensuel moyen par année et par mois",
			   "cs-CZ", "Prům. měsíční míra úbytku (%) podle roku a měsíce",
			   "da-DK", "Gennemsnitlig månedlig afgangsrateprocent efter år og måned",
			   "de-AT", "Durchschn. mon. Abwanderungsrate % nach Jahr und Monat",
			   "de-CH", "Durchschn. mon. Abwanderungsrate % nach Jahr und Monat",
			   "en-AU", "Avg. Mon. Churn Rate % by Year and Month",
			   "en-CA", "Avg. Mon. Churn Rate % by Year and Month",
			   "en-GB", "Avg. Mon. Churn Rate % by Year and Month",
			   "en-NZ", "Avg. Mon. Churn Rate % by Year and Month",
			   "es-MX", "% tasa de abandono men. medio por año y mes",
			   "fi-FI", "Keskim. kk:ttainen vaihtuvuusprosentti % vuosittain ja kuukausittain",
			   "fr-BE", "% taux d’attrition mensuel moyen par année et par mois",
			   "fr-CA", "% taux d’attrition mensuel moyen par année et par mois",
			   "fr-CH", "% taux d’attrition mensuel moyen par année et par mois",
			   "is-IS", "Meðaltími mán. uppsagna % eftir ári og mánuði",
			   "it-CH", "% tasso medio di abbandono mensile per anno e mese",
			   "it-IT", "% tasso medio di abbandono mensile per anno e mese",
			   "nb-NO", "Gj.sn. månedlig frafallsrate i prosent etter år og måned",
			   "nl-BE", "Gem. maand. % verloop per jaar en maand",
			   "nl-NL", "Gem. maand. % verloop per jaar en maand",
			   "ru-RU", "Avg. Mon. Churn Rate % by Year and Month",
			   "sv-SE", "Genomsnittlig månatlig bortfallsgrad % per år och månad",
			   "Avg. Mon. Churn Rate % by Year and Month"
			)
		lineageTag: 1a862496-ca01-4eeb-8a5b-e339662da515

	column unused
		isHidden
		displayFolder: unused
		lineageTag: 2df11e89-93a7-4fe5-b94b-0c245f211b77
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

