namespace System.Tooling;

using System.PerformanceProfile;

page 1931 "Performance Profiles"
{
    Caption = 'Performance Profiles';
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Administration;
    AboutTitle = 'About performance profiles';
    AboutText = 'View the profiles generated by profiler schedules. The profiler uses sampling technology, so the results may differ slightly between recordings of the same scenario.';
    DeleteAllowed = false;
    ModifyAllowed = false;
    SourceTable = "Performance Profiles";

    layout
    {
        area(Content)
        {
            repeater(Profiles)
            {
                field("Start Time"; Rec."Starting Date-Time")
                {
                    Caption = 'Start Time';
                    ToolTip = 'The time the profile was started.';
                }

                field("Username"; Rec."User Name")
                {
                    Caption = 'Username';
                    ToolTip = 'The name of the user that was profiled.';
                }

                field("Client Type"; Rec."Client Type")
                {
                    Caption = 'Client Type';
                    ToolTip = 'The type of the client that was profiled.';
                }

                field("Activity Description"; Rec."Activity Description")
                {
                    Caption = 'Activity Description';
                    ToolTip = 'A short description of the activity that was profiled.';
                }

                field("Object Display Name"; Rec."Object Display Name")
                {
                    Caption = 'Object';
                    ToolTip = 'The object that contains the entry point for this profile.';
                }

                field(Duration; Rec.Duration)
                {
                    Caption = 'Activity Duration';
                    ToolTip = 'The duration of the activity that was profiled in milliseconds.';
                }

                field("Http Call Duration"; Rec."Http Call Duration")
                {
                    Caption = 'Duration of Http Calls';
                    ToolTip = 'The duration of the http calls during the activity that was profiled in milliseconds.';
                }

                field("Http Call Number"; Rec."Http Call Number")
                {
                    Caption = 'Number of Http Calls';
                    ToolTip = 'The number of http calls during the activity that was profiled.';
                }

                field("Client Session ID"; Rec."Client Session ID")
                {
                    Caption = 'Client Session ID';
                    ToolTip = 'The ID of the client session that was profiled.';
                }

                field("Schedule ID"; Rec."Schedule ID")
                {
                    Caption = 'Schedule ID';
                    ToolTip = 'The ID of the schedule that was used to profile the activity.';
                    TableRelation = "Performance Profile Scheduler"."Schedule ID";
                    DrillDownPageId = "Perf. Profiler Schedules Card";
                }
            }
        }
    }

    trigger OnOpenPage()
    begin
        Rec.SetAutoCalcFields("User Name", "Client Type");
    end;
}