// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.ExpenseAgent;

using Microsoft.Foundation.Company;

report 6953 "No Receipt Declaration"
{
    Caption = 'No Receipt Declaration';
    DefaultRenderingLayout = WordLayout;
    ApplicationArea = Basic, Suite;
    WordMergeDataItem = Expense;

    dataset
    {
        dataitem(Expense; Expense)
        {
            RequestFilterFields = "No.", "Expense User No.", "Expense Date";

            column(ExpenseNo; "No.")
            {
                IncludeCaption = true;
            }
            column(EmployeeName; EmployeeName)
            {
            }
            column(CompanyName; CompanyInformation.Name)
            {
                IncludeCaption = true;
            }
            column(ExpenseDate; "Expense Date")
            {
                IncludeCaption = true;
            }
            column(MerchantName; "Merchant Name")
            {
                IncludeCaption = true;
            }
            column(Description; Description)
            {
                IncludeCaption = true;
            }
            column(Justification; Justification)
            {
                IncludeCaption = true;
            }
            column(No_Receipt_Decl__Current; "No Receipt Decl. Current")
            {
                IncludeCaption = true;
            }
            column(CurrencyCode; "Currency Code")
            {
                IncludeCaption = true;
            }
            column(Amount; Amount)
            {
                IncludeCaption = true;
            }
            column(AmountLCY; "Amount (LCY)")
            {
                IncludeCaption = true;
            }
            column(NoReceiptReason; "No Receipt Reason")
            {
                IncludeCaption = true;
            }
            column(GeneratedAt; "No Receipt Generated At")
            {
                IncludeCaption = true;
            }
            column(GeneratedBy; "No Receipt Generated By")
            {
                IncludeCaption = true;
            }

            trigger OnAfterGetRecord()
            var
                ExpenseUser: Record "Expense User";
            begin
                Clear(EmployeeName);
                if "Expense User No." = '' then
                    exit;

                ExpenseUser.SetLoadFields(Name);
                if ExpenseUser.Get("Expense User No.") then
                    EmployeeName := ExpenseUser.Name;
            end;
        }
    }

    requestpage
    {
        layout
        {
            area(Content)
            {
                group(Options)
                {
                }
            }
        }
    }

    rendering
    {
        layout(WordLayout)
        {
            Type = Word;
            Caption = 'No Receipt Declaration';
            Summary = 'Declaration containing expense details and the reason that a receipt is unavailable.';
            LayoutFile = './src/Expense/Reports/NoReceiptDeclaration.docx';
        }
    }

    labels
    {
        ReportTitleLbl = 'No Receipt Declaration';
        EmployeeSectionLbl = 'Employee';
        NameLbl = 'Employee';
        ExpenseSectionLbl = 'Expense';
        ExpenseNoLbl = 'Expense No.';
        MissingReceiptSectionLbl = 'Missing receipt';
        NonCompliantLbl = 'NON-COMPLIANT - REPLACEMENT PROOF, NOT AN ORIGINAL RECEIPT';
        StandardDeclarationTxt = 'I certify that this expense was incurred for a legitimate business purpose, that the information provided is accurate to the best of my knowledge, and that I have not received or submitted another reimbursement claim for this expense.';
    }

    trigger OnPreReport()
    begin
        CompanyInformation.Get();
    end;

    var
        CompanyInformation: Record "Company Information";
        EmployeeName: Text[100];
}