// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.Finance.Analysis;

using Microsoft.Foundation.NoSeries;
using System.Utilities;

table 687 "Payment Practice Header"
{
    DataClassification = CustomerContent;

    fields
    {
        field(1; "No."; Integer)
        {
            AutoIncrement = true;
        }
        field(2; "Starting Date"; Date)
        {
            trigger OnValidate()
            begin
                ValidateDates();
            end;
        }
        field(3; "Ending Date"; Date)
        {
            trigger OnValidate()
            begin
                ValidateDates();
            end;
        }
        field(4; "Aggregation Type"; Enum "Paym. Prac. Aggregation Type")
        {
            InitValue = 1;

            trigger OnValidate()
            begin
                ValidateFieldChange(Rec."Aggregation Type");
                Rec.CalcFields("Lines Exist");
                if not Rec."Lines Exist" then
                    exit;

                if ConfirmManagement.GetResponseOrDefault(StrSubstNo(ClearHeaderQst, FieldCaption("Aggregation Type")), true) then
                    ClearHeader()
                else
                    "Aggregation Type" := xRec."Aggregation Type";
            end;
        }
        field(5; "Header Type"; Enum "Paym. Prac. Header Type")
        {
            InitValue = 1;

            trigger OnValidate()
            begin
                ValidateFieldChange(Rec."Aggregation Type");
                Rec.CalcFields("Lines Exist");
                if not Rec."Lines Exist" then
                    exit;

                if ConfirmManagement.GetResponseOrDefault(StrSubstNo(ClearHeaderQst, FieldCaption("Header Type")), true) then
                    ClearHeader()
                else
                    "Header Type" := xRec."Header Type";
            end;
        }
        field(6; "Average Agreed Payment Period"; Integer)
        {
            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(7; "Average Actual Payment Period"; Integer)
        {
            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(8; "Pct Paid on Time"; Decimal)
        {
            AutoFormatType = 0;

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(9; "Generated On"; DateTime)
        {

        }
        field(10; "Generated By"; Code[20])
        {

        }
        field(11; "Lines Exist"; Boolean)
        {
            CalcFormula = exist("Payment Practice Line" where("Header No." = field("No.")));
            FieldClass = FlowField;
        }
        field(12; "Modified Manually"; Boolean)
        {

        }
        field(15; "Reporting Scheme"; Enum "Paym. Prac. Reporting Scheme")
        {
            ToolTip = 'Specifies the reporting scheme for the payment practice.';

            trigger OnValidate()
            begin
                if Rec."Reporting Scheme" = xRec."Reporting Scheme" then
                    exit;

                Rec.CalcFields("Lines Exist");
                if Rec."Lines Exist" then
                    if ConfirmManagement.GetResponseOrDefault(StrSubstNo(ClearHeaderQst, FieldCaption("Reporting Scheme")), true) then
                        ClearHeader()
                    else begin
                        "Reporting Scheme" := xRec."Reporting Scheme";
                        exit;
                    end;

                UpdatePaymentPeriodCodeForScheme();
            end;
        }
        field(16; "Payment Period Code"; Code[20])
        {
            TableRelation = "Payment Period Header".Code where("Reporting Scheme" = field("Reporting Scheme"));
            ToolTip = 'Specifies the payment period template used for period aggregation.';
        }
        field(20; "Total Number of Payments"; Integer)
        {
            Editable = false;
            ToolTip = 'Specifies the total number of payments.';
        }
        field(21; "Total Amount of Payments"; Decimal)
        {
            Editable = false;
            AutoFormatType = 1;
            AutoFormatExpression = '';
            ToolTip = 'Specifies the total amount of payments.';
        }
        field(22; "Total Amt. of Overdue Payments"; Decimal)
        {
            Editable = false;
            AutoFormatType = 1;
            AutoFormatExpression = '';
            ToolTip = 'Specifies the total amount of overdue payments.';
        }
        field(23; "Pct Overdue Due to Dispute"; Decimal)
        {
            Editable = false;
            AutoFormatType = 0;
            ToolTip = 'Specifies the percentage of overdue payments due to dispute.';
        }
    }

    keys
    {
        key(Key1; "No.")
        {
            Clustered = true;
        }
    }

    trigger OnInsert()
    var
        DisputeRetData: Record "Paym. Prac. Dispute Ret. Data";
    begin
        UpdateNo();
        DetectReportingScheme();
        UpdatePaymentPeriodCodeForScheme();

        DisputeRetData.Init();
        DisputeRetData."Header No." := "No.";
        DisputeRetData.Insert();
    end;

    trigger OnDelete()
    begin
        DeleteLinkedRecords();
    end;

    var
        ConfirmManagement: Codeunit "Confirm Management";
        ClearHeaderQst: Label 'Changing %1 will delete existing lines. Do you want to continue?', Comment = '%1 = Field name';
        DateValidationErr: Label 'Starting Date must be less than or equal to Ending Date.';

    procedure UpdateNo(): Integer
    var
        SequenceNoMgt: Codeunit "Sequence No. Mgt.";
    begin
        if Rec."No." = 0 then
            Rec.Validate("No.", SequenceNoMgt.GetNextSeqNo(Database::"Payment Practice Header"));
    end;

    local procedure DeleteLinkedRecords()
    var
        PaymentPracticeLine: Record "Payment Practice Line";
        PaymentPracticeData: Record "Payment Practice Data";
        DisputeRetData: Record "Paym. Prac. Dispute Ret. Data";
    begin
        PaymentPracticeLine.SetRange("Header No.", "No.");
        PaymentPracticeLine.DeleteAll();
        PaymentPracticeData.SetRange("Header No.", "No.");
        PaymentPracticeData.DeleteAll();
        if DisputeRetData.Get("No.") then
            DisputeRetData.Delete();
        Rec.CalcFields("Lines Exist");
    end;

    procedure ClearHeader()
    var
        PaymentPracticeLine: Record "Payment Practice Line";
        PaymentPracticeData: Record "Payment Practice Data";
    begin
        "Generated On" := 0DT;
        "Generated By" := '';
        PaymentPracticeLine.SetRange("Header No.", "No.");
        PaymentPracticeLine.DeleteAll();
        PaymentPracticeData.SetRange("Header No.", "No.");
        PaymentPracticeData.DeleteAll();
        Rec.CalcFields("Lines Exist");
    end;

    local procedure ValidateFieldChange(PaymentPracticeLinesAggregator: Interface PaymentPracticeLinesAggregator)
    begin
        PaymentPracticeLinesAggregator.ValidateHeader(Rec);
    end;

    local procedure ValidateDates()
    begin
        if (Rec."Starting Date" <> 0D) and (Rec."Ending Date" <> 0D) then
            if Rec."Starting Date" > Rec."Ending Date" then
                Error(DateValidationErr);
    end;

    local procedure DetectReportingScheme()
    var
        PaymentPeriodMgt: Codeunit "Payment Period Mgt.";
    begin
        "Reporting Scheme" := PaymentPeriodMgt.DetectReportingScheme();
    end;

    local procedure UpdatePaymentPeriodCodeForScheme()
    var
        PaymentPeriodHeader: Record "Payment Period Header";
    begin
        PaymentPeriodHeader.SetRange("Reporting Scheme", "Reporting Scheme");

        // Step 1: default template for scheme
        PaymentPeriodHeader.SetRange(Default, true);
        if PaymentPeriodHeader.FindFirst() then begin
            "Payment Period Code" := PaymentPeriodHeader.Code;
            exit;
        end;

        // Step 2: sole template for scheme
        PaymentPeriodHeader.SetRange(Default);
        if PaymentPeriodHeader.Count = 1 then begin
            PaymentPeriodHeader.FindFirst();
            "Payment Period Code" := PaymentPeriodHeader.Code;
            exit;
        end;

        // Step 3: blank (multiple non-default or none)
        "Payment Period Code" := '';
    end;

}
