table 'Sustainability Goals'
	lineageTag: da071c77-b29a-499b-a452-91aa43e7f707

	measure 'CO2 Target' =
			
			SUM ( 'Sustainability Goals'[Target Value For CO2] )
		displayFolder: _Sustainability Goals Measures\_CO2
		lineageTag: b01821d8-2d59-4b3a-990d-0649f5ef5324

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CO2 Realized (%)' =
			
			DIVIDE ( [CO2 Current Value], [CO2 Target] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Sustainability Goals Measures\_CO2
		lineageTag: afd43b65-54b6-4089-9d0c-b3252fffc250

	measure 'CH4 Target' =
			
			SUM ( 'Sustainability Goals'[Target Value For CH4] )
		displayFolder: _Sustainability Goals Measures\_CH4
		lineageTag: c4ebd68e-2f5b-4f14-87ea-22d0572de7b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'N2O Target' =
			
			SUM ( 'Sustainability Goals'[Target Value For N2O] )
		displayFolder: _Sustainability Goals Measures\N2O
		lineageTag: 06cf511e-dc95-4fe6-8249-5d7c7d2f7db5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CH4 Realized (%)' =
			
			DIVIDE ( [CH4 Current Value], [CH4 Target] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Sustainability Goals Measures\_CH4
		lineageTag: 8802864b-165b-4836-9781-e4cc533fd043

	measure 'N2O Realized (%)' =
			
			DIVIDE ( [N2O Current Value], [N2O Target] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Sustainability Goals Measures\N2O
		lineageTag: b2d19c75-09fe-4965-883d-923297c12105

	measure 'Water Target' =
			
			SUM ( 'Sustainability Goals'[Target Value For Water Intensity] )
		displayFolder: _Sustainability Goals Measures\_Water
		lineageTag: 7b5ae209-a294-40ae-bc72-8e4fa7c07e1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Waste Target' =
			
			SUM ( 'Sustainability Goals'[Target Value For Waste Intensity] )
		displayFolder: _Sustainability Goals Measures\_Waste
		lineageTag: 6084f614-54a8-46e5-833e-5c1f32943669

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Water Realized (%)' =
			
			DIVIDE ( [Water Intensity], [Water Target] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Sustainability Goals Measures\_Water
		lineageTag: 4b5c1806-9d18-4ff9-942d-496f87142de9

	measure 'Waste Realized (%)' =
			
			DIVIDE ( [Waste Intensity], [Waste Target] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Sustainability Goals Measures\_Waste
		lineageTag: e3ecf69e-7b4e-42f9-a169-35cd1acee720

	measure 'CO2e Realized (%)' =
			
			DIVIDE ( [CO2e Current Value], [CO2e Target] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Sustainability Goals Measures\_CO2e
		lineageTag: f6b9bc51-30f4-488c-9689-f83de8705dc2

	measure 'CO2 Current Value' =
			
			VAR SustainabilityGoalsTable =
			    SUMMARIZECOLUMNS (
			        'Sustainability Goals'[Score Card No.],
			        "CO2 Emissions",
			            CALCULATE (
			                SUM ( 'Sustainability Ledger Entries'[Emission CO2] ),
			                ALL ( 'Date' ),
			                DATESBETWEEN (
			                    'Date'[Date],
			                    MIN ( 'Sustainability Goals'[Start Date] ),
			                    MAX ( 'Sustainability Goals'[End Date] )
			                )
			            )
			    )
			RETURN
			    SUMX ( SustainabilityGoalsTable, [CO2 Emissions] )
		displayFolder: _Sustainability Goals Measures\_CO2
		lineageTag: 925995aa-74e6-4c44-be1f-cd4de53b8b9f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CH4 Current Value' =
			
			VAR SustainabilityGoalsTable =
			    SUMMARIZECOLUMNS (
			        'Sustainability Goals'[Score Card No.],
			        "CH4 Emissions",
			            CALCULATE (
			                SUM ( 'Sustainability Ledger Entries'[Emission CH4] ),
			                ALL ( 'Date' ),
			                DATESBETWEEN (
			                    'Date'[Date],
			                    MIN ( 'Sustainability Goals'[Start Date] ),
			                    MAX ( 'Sustainability Goals'[End Date] )
			                )
			            )
			    )
			RETURN
			    SUMX ( SustainabilityGoalsTable, [CH4 Emissions] )
		displayFolder: _Sustainability Goals Measures\_CH4
		lineageTag: 24fa7b6f-957c-46f0-9d1c-5462365aaa56

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'N2O Current Value' =
			
			VAR SustainabilityGoalsTable =
			    SUMMARIZECOLUMNS (
			        'Sustainability Goals'[Score Card No.],
			        "N2O Emissions",
			            CALCULATE (
			                SUM ( 'Sustainability Ledger Entries'[Emission N2O] ),
			                ALL ( 'Date' ),
			                DATESBETWEEN (
			                    'Date'[Date],
			                    MIN ( 'Sustainability Goals'[Start Date] ),
			                    MAX ( 'Sustainability Goals'[End Date] )
			                )
			            )
			    )
			RETURN
			    SUMX ( SustainabilityGoalsTable, [N2O Emissions] )
		displayFolder: _Sustainability Goals Measures\N2O
		lineageTag: 09aa2b0e-d6dd-44dc-b602-1241c31b7296

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CO2e Current Value' =
			
			VAR SustainabilityGoalsTable =
			    SUMMARIZECOLUMNS (
			        'Sustainability Goals'[Score Card No.],
			        "CO2e Emissions",
			            CALCULATE (
			                SUM ( 'Sustainability Ledger Entries'[Emission CO2e] ),
			                ALL ( 'Date' ),
			                DATESBETWEEN (
			                    'Date'[Date],
			                    MIN ( 'Sustainability Goals'[Start Date] ),
			                    MAX ( 'Sustainability Goals'[End Date] )
			                )
			            )
			    )
			RETURN
			    SUMX ( SustainabilityGoalsTable, [CO2e Emissions] )
		displayFolder: _Sustainability Goals Measures\_CO2e
		lineageTag: 6a2ab28f-e47c-421b-83a2-80f52548c8c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Water Current Value' =
			
			VAR SustainabilityGoalsTable =
			    SUMMARIZECOLUMNS (
			        'Sustainability Goals'[Score Card No.],
			        "Water Intensity",
			            CALCULATE (
			                SUM ( 'Sustainability Ledger Entries'[Wat. Intensity] ),
			                ALL ( 'Date' ),
			                DATESBETWEEN (
			                    'Date'[Date],
			                    MIN ( 'Sustainability Goals'[Start Date] ),
			                    MAX ( 'Sustainability Goals'[End Date] )
			                )
			            )
			    )
			RETURN
			    SUMX ( SustainabilityGoalsTable, [Water Intensity] )
		displayFolder: _Sustainability Goals Measures\_Water
		lineageTag: fbe8597e-4a1a-43b5-a4be-4acf4fca27cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Waste Current Value' =
			
			VAR SustainabilityGoalsTable =
			    SUMMARIZECOLUMNS (
			        'Sustainability Goals'[Score Card No.],
			        "Waste Intensity",
			            CALCULATE (
			                SUM ( 'Sustainability Ledger Entries'[Wast. Intensity] ),
			                ALL ( 'Date' ),
			                DATESBETWEEN (
			                    'Date'[Date],
			                    MIN ( 'Sustainability Goals'[Start Date] ),
			                    MAX ( 'Sustainability Goals'[End Date] )
			                )
			            )
			    )
			RETURN
			    SUMX ( SustainabilityGoalsTable, [Waste Intensity] )
		displayFolder: _Sustainability Goals Measures\_Waste
		lineageTag: b4eba006-0dca-43eb-914e-16cb1e95de17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Score Card No.'
		dataType: string
		lineageTag: 7c16c01d-e33a-46b7-b5f1-e0df80d60b71
		summarizeBy: none
		sourceColumn: Score Card No.

		annotation SummarizationSetBy = Automatic

	column 'No.'
		dataType: string
		lineageTag: b92d3b27-f546-4342-9bae-8a836e57f2b4
		summarizeBy: none
		sourceColumn: No.

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 4e5619ba-dc90-4e38-9100-241b6babb275
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Owner
		dataType: string
		lineageTag: 27e0a1eb-a476-4fbb-bb0f-2fa204a7445f
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column 'Country/Region Code'
		dataType: string
		isHidden
		lineageTag: 0bd5348d-ee7c-4fcc-88be-dd48e4281301
		summarizeBy: none
		sourceColumn: Country/Region Code

		annotation SummarizationSetBy = Automatic

	column 'Responsibility Centre'
		dataType: string
		isHidden
		lineageTag: d595aa23-f7b6-4f6d-ba6f-01026ae4dc9f
		summarizeBy: none
		sourceColumn: Responsibility Centre

		annotation SummarizationSetBy = Automatic

	column 'Target Value For CO2'
		dataType: double
		lineageTag: 35d5ba40-73bf-48a2-ba3a-96ec25e22721
		summarizeBy: sum
		sourceColumn: Target Value For CO2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Value For CH4'
		dataType: double
		lineageTag: a10c9c0f-ecea-4c46-8826-620a84f8471b
		summarizeBy: sum
		sourceColumn: Target Value For CH4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Value For N2O'
		dataType: double
		lineageTag: 83c35783-9e36-4de2-b241-adf36be8ae85
		summarizeBy: sum
		sourceColumn: Target Value For N2O

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Value For Water Intensity'
		dataType: double
		lineageTag: 3ce01cc9-15cf-4464-9d90-515d879fb55e
		summarizeBy: sum
		sourceColumn: Target Value For Water Intensity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Value For Waste Intensity'
		dataType: double
		lineageTag: 1f4dd665-9b6e-4b16-aab8-e8b86d011584
		summarizeBy: sum
		sourceColumn: Target Value For Waste Intensity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Main Goal'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 01436eb1-5942-4ae5-bf48-8e4cff25c9ef
		summarizeBy: none
		sourceColumn: Main Goal

		annotation SummarizationSetBy = Automatic

	column lineNo
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f73455cf-69bf-4adb-9e98-11dfbd0c310d
		summarizeBy: sum
		sourceColumn: lineNo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fbba48b3-d78d-4405-9195-784441d6da6b
		summarizeBy: none
		sourceColumn: Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0342fa70-be23-458d-8a1f-82dc030203ca
		summarizeBy: none
		sourceColumn: End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Baseline Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29cec17a-f3a0-4d03-bf17-33a414e9ff6d
		summarizeBy: none
		sourceColumn: Baseline Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Baseline End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 07d4c22d-fdd8-4bf9-826b-c6328996ef4b
		summarizeBy: none
		sourceColumn: Baseline End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Sustainability Goals' = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY,API_ENDPOINT, []),
				    TableData = Source{[Name="pbiSustainabilityGoals",Signature="table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(TableData,{{"scoreCardNo", "Score Card No."}, {"no", "No."}, {"name", "Name"}, {"owner", "Owner"}, {"countryRegion", "Country/Region Code"}, {"responsibilityCentre", "Responsibility Centre"}, {"targetValueForCo2", "Target Value For CO2"}, {"targetValueForCh4", "Target Value For CH4"}, {"targetValueForN2O", "Target Value For N2O"}, {"targetValueForWaterIntensity", "Target Value For Water Intensity"}, {"targetValueForWasteIntensity", "Target Value For Waste Intensity"}, {"mainGoal", "Main Goal"}, {"startDate", "Start Date"}, {"endDate", "End Date"}, {"baselineStartDate", "Baseline Start Date"}, {"baselineEndDate", "Baseline End Date"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"ETag"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

