codeunit 101256 "Create VAT Statement Line"
{

    trigger OnRun()
    begin
        DemoDataSetup.Get();
        if DemoDataSetup."Company Type" = DemoDataSetup."Company Type"::"Sales Tax" then
            exit;

        InsertData('0', XOUTGOINGACTIVITIES, 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('', '', 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('00', XSubmittedto0PERCENTVAT, 2, '', 0, 0, '', '', '00.1..00.3', 0, 0, true, 0, false);
        InsertData('00.1', XGoods0PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XG0, '', 2, 1, false, 0, false);
        InsertData('00.2', XServices0PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XS0, '', 2, 1, false, 0, false);
        InsertData('00.3', XInvestments0PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XI0, '', 2, 1, false, 0, false);
        InsertData('01', XSubmittedto6PERCENTVAT, 2, '', 0, 0, '', '', '01.1..01.3', 0, 0, true, 0, false);
        InsertData('01.1', XGoods6PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XG1, '', 2, 1, false, 0, false);
        InsertData('01.2', XServices6PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XS1, '', 2, 1, false, 0, false);
        InsertData('02', XSubmittedto12PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XG2, '', 2, 1, true, 0, false);
        InsertData('03', XSubmittedto21PERCENTVAT, 2, '', 0, 0, '', '', '03.1..03.3', 0, 0, true, 0, false);
        InsertData('03.1', XGoods21PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), DemoDataSetup.GoodsVATCode(), '', 2, 1, false, 0, false);
        InsertData('03.2', XServices21PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), DemoDataSetup.ServicesVATCode(), '', 2, 1, false, 0, false);
        InsertData('03.3', XInvestments21PERCENTVAT, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XI3, '', 2, 1, false, 0, false);
        InsertData('45', XAmountVATexcl, 2, '', 0, 0, '', '', '45.1..45.3', 0, 0, true, 0, false);
        InsertData('45.1', XGoods0PERCENTVAT, 1, '', 7, 2, XCC, XG0, '', 2, 1, false, 0, false);
        InsertData('45.1', XGoods6PERCENTVAT, 1, '', 7, 2, XCC, XG1, '', 2, 1, false, 0, false);
        InsertData('45.1', XGoods12PERCENTVAT, 1, '', 7, 2, XCC, XG2, '', 2, 1, false, 0, false);
        InsertData('45.1', XGoods21PERCENTVAT, 1, '', 7, 2, XCC, DemoDataSetup.GoodsVATCode(), '', 2, 1, false, 0, false);
        InsertData('45.2', XServices0PERCENTVAT, 1, '', 7, 2, XCC, XS0, '', 2, 1, false, 0, false);
        InsertData('45.2', XServices6PERCENTVAT, 1, '', 7, 2, XCC, XS1, '', 2, 1, false, 0, false);
        InsertData('45.2', XServices21PERCENTVAT, 1, '', 7, 2, XCC, DemoDataSetup.ServicesVATCode(), '', 2, 1, false, 0, false);
        InsertData('45.3', XInvestments0PERCENTVAT, 1, '', 7, 2, XCC, XI0, '', 2, 1, false, 0, false);
        InsertData('45.3', XInvestments21PERCENTVAT, 1, '', 7, 2, XCC, XI3, '', 2, 1, false, 0, false);
        InsertData('46', XIntraCommunityICDeliveries, 2, '', 0, 0, '', '', '46.1..46.3', 0, 0, true, 0, false);
        InsertData('46.1', XGoods0PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), XG0, '', 2, 1, false, 0, false);
        InsertData('46.1', XGoods6PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), XG1, '', 2, 1, false, 0, false);
        InsertData('46.1', XGoods12PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), XG2, '', 2, 1, false, 0, false);
        InsertData('46.1', XGoods21PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), DemoDataSetup.GoodsVATCode(), '', 2, 1, false, 0, false);
        InsertData('46.3', XInvestments0PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), XI0, '', 2, 1, false, 0, false);
        InsertData('46.3', XInvestments21PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), XI3, '', 2, 1, false, 0, false);
        InsertData('47', XExporttocountriesnotmemberEU, 2, '', 0, 0, '', '', '47.1..47.3', 0, 0, true, 0, false);
        InsertData('47.1', XGoods0PERCENTVAT, 1, '', 7, 2, XIMPEXP, XG0, '', 2, 1, false, 0, false);
        InsertData('47.1', XGoods6PERCENTVAT, 1, '', 7, 2, XIMPEXP, XG1, '', 2, 1, false, 0, false);
        InsertData('47.1', XGoods12PERCENTVAT, 1, '', 7, 2, XIMPEXP, XG2, '', 2, 1, false, 0, false);
        InsertData('47.1', XGoods21PERCENTVAT, 1, '', 7, 2, XIMPEXP, DemoDataSetup.GoodsVATCode(), '', 2, 1, false, 0, false);
        InsertData('47.2', XServices0PERCENTVAT, 1, '', 7, 2, XIMPEXP, XS0, '', 2, 1, false, 0, false);
        InsertData('47.2', XServices6PERCENTVAT, 1, '', 7, 2, XIMPEXP, XS1, '', 2, 1, false, 0, false);
        InsertData('47.2', XServices21PERCENTVAT, 1, '', 7, 2, XIMPEXP, DemoDataSetup.ServicesVATCode(), '', 2, 1, false, 0, false);
        InsertData('47.2', XServices0PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), XS0, '', 2, 1, false, 0, false);
        InsertData('47.2', XServices6PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), XS1, '', 2, 1, false, 0, false);
        InsertData('47.2', XServices21PERCENTVAT, 1, '', 7, 2, DemoDataSetup.EUCode(), DemoDataSetup.ServicesVATCode(), '', 2, 1, false, 0, false);
        InsertData('47.3', XInvestments0PERCENTVAT, 1, '', 7, 2, XIMPEXP, XI0, '', 2, 1, false, 0, false);
        InsertData('47.3', XInvestments21PERCENTVAT, 1, '', 7, 2, XIMPEXP, XI3, '', 2, 1, false, 0, false);
        InsertData('48', XCreditmemosconcRow46, 2, '', 0, 0, '', '', '48.1..48.3', 0, 0, true, 1, false);
        InsertData('48.1', XGoods0PERCENTVAT, 1, '', 3, 2, DemoDataSetup.EUCode(), XG0, '', 2, 1, false, 0, false);
        InsertData('48.1', XGoods6PERCENTVAT, 1, '', 3, 2, DemoDataSetup.EUCode(), XG1, '', 2, 1, false, 0, false);
        InsertData('48.1', XGoods12PERCENTVAT, 1, '', 3, 2, DemoDataSetup.EUCode(), XG2, '', 2, 1, false, 0, false);
        InsertData('48.1', XGoods21PERCENTVAT, 1, '', 3, 2, DemoDataSetup.EUCode(), DemoDataSetup.GoodsVATCode(), '', 2, 1, false, 0, false);
        InsertData('48.3', XCreditmemosconcRow00, 1, '', 3, 2, DemoDataSetup.EUCode(), XI0, '', 2, 1, false, 0, false);
        InsertData('48.3', XCreditmemosconcRow00, 1, '', 3, 2, DemoDataSetup.EUCode(), XI3, '', 2, 1, false, 0, false);
        InsertData('49', XCMconcRow000102034547, 2, '', 0, 0, '', '', '49.1..49.3', 0, 0, true, 1, false);
        InsertData('49.1', XCreditmemosconcRow00, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XG0, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow01, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XG1, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow02, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XG2, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow03, 1, '', 3, 2, DemoDataSetup.DomesticCode(), DemoDataSetup.GoodsVATCode(), '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow45, 1, '', 3, 2, XCC, XG0, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow45, 1, '', 3, 2, XCC, XG1, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow45, 1, '', 3, 2, XCC, XG2, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow45, 1, '', 3, 2, XCC, DemoDataSetup.GoodsVATCode(), '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, XG0, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, XG1, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, XG2, '', 2, 1, false, 0, false);
        InsertData('49.1', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, DemoDataSetup.GoodsVATCode(), '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow00, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XS0, '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow01, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XS1, '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow03, 1, '', 3, 2, DemoDataSetup.DomesticCode(), DemoDataSetup.ServicesVATCode(), '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow47, 1, '', 3, 2, DemoDataSetup.EUCode(), XS0, '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow47, 1, '', 3, 2, DemoDataSetup.EUCode(), XS1, '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow47, 1, '', 3, 2, DemoDataSetup.EUCode(), DemoDataSetup.ServicesVATCode(), '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow45, 1, '', 3, 2, XCC, XS0, '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow45, 1, '', 3, 2, XCC, XS1, '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow45, 1, '', 3, 2, XCC, DemoDataSetup.ServicesVATCode(), '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, XS0, '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, XS1, '', 2, 1, false, 0, false);
        InsertData('49.2', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, DemoDataSetup.ServicesVATCode(), '', 2, 1, false, 0, false);
        InsertData('49.3', XCreditmemosconcRow00, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XI0, '', 2, 1, false, 0, false);
        InsertData('49.3', XCreditmemosconcRow03, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XI3, '', 2, 1, false, 0, false);
        InsertData('49.3', XCreditmemosconcRow45, 1, '', 3, 2, XCC, XI0, '', 2, 1, false, 0, false);
        InsertData('49.3', XCreditmemosconcRow45, 1, '', 3, 2, XCC, XI3, '', 2, 1, false, 0, false);
        InsertData('49.3', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, XI0, '', 2, 1, false, 0, false);
        InsertData('49.3', XCreditmemosconcRow47, 1, '', 3, 2, XIMPEXP, XI3, '', 2, 1, false, 0, false);
        InsertData('', '', 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('50', XPAYABLEANDDEDUCTIBLETAXES, 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('', '', 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('54', XTaxespayableforRow00010203, 2, '', 0, 0, '', '', '54.1..54.4', 0, 0, true, 1, false);
        InsertData('54.1', XTaxespayableforRow01, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XG1, '', 1, 0, false, 0, false);
        InsertData('54.1', XTaxespayableforRow02, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XG2, '', 1, 0, false, 0, false);
        InsertData('54.1', XTaxespayableforRow03, 1, '', 7, 2, DemoDataSetup.DomesticCode(), DemoDataSetup.GoodsVATCode(), '', 1, 0, false, 0, false);
        InsertData('54.2', XTaxespayableforRow01, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XS1, '', 1, 0, false, 0, false);
        InsertData('54.2', XTaxespayableforRow03, 1, '', 7, 2, DemoDataSetup.DomesticCode(), DemoDataSetup.ServicesVATCode(), '', 1, 0, false, 0, false);
        InsertData('54.3', XTaxespayableforRow03, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XI3, '', 1, 0, false, 0, false);
        InsertData('54.4', XTaxespayableVATOnly, 1, '', 7, 2, DemoDataSetup.DomesticCode(), XVAT, '', 1, 0, false, 0, false);
        InsertData('55', XTaxespayableforICAcquisitions, 2, '', 0, 0, '', '', '55.1..55.3', 0, 0, true, 1, false);
        InsertData('55.1', XRevChrgVATICAcqGoods0PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG0, '', 1, 1, false, 0, false);
        InsertData('55.1', XRevChrgVATICAcqGoods6PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG1, '', 1, 1, false, 0, false);
        InsertData('55.1', XRevChrgVATICAcqGoods12PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG2, '', 1, 1, false, 0, false);
        InsertData('55.1', XRevChrgVATICAcqGoods21PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), DemoDataSetup.GoodsVATCode(), '', 1, 1, false, 0, false);
        InsertData('55.3', XRevChrgVATICAcqInvst0PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XI0, '', 1, 1, false, 0, false);
        InsertData('55.3', XRevChrgVATICAcqInvst21PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XI3, '', 1, 1, false, 0, false);
        InsertData('56', XRevChrgVATActinvCocontractors, 2, '', 0, 0, '', '', '56.1..56.3', 0, 0, true, 1, false);
        InsertData('56.1', XWIPGoods0PERCENTVAT, 1, '', 7, 1, XCC, XG0, '', 1, 1, false, 0, false);
        InsertData('56.1', XWIPGoods6PERCENTVAT, 1, '', 7, 1, XCC, XG1, '', 1, 1, false, 0, false);
        InsertData('56.1', XWIPGoods12PERCENTVAT, 1, '', 7, 1, XCC, XG2, '', 1, 1, false, 0, false);
        InsertData('56.1', XWIPGoods21PERCENTVAT, 1, '', 7, 1, XCC, DemoDataSetup.GoodsVATCode(), '', 1, 1, false, 0, false);
        InsertData('56.2', XServices0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XS0, '', 1, 1, false, 0, false);
        InsertData('56.2', XServices6PERCENTVAT2, 1, '', 7, 1, DemoDataSetup.EUCode(), XS1, '', 1, 1, false, 0, false);
        InsertData('56.2', XServices21PERCENTVAT2, 1, '', 7, 1, DemoDataSetup.EUCode(), DemoDataSetup.ServicesVATCode(), '', 1, 1, false, 0, false);
        InsertData('56.2', XWIPServices0PERCENTVAT, 1, '', 7, 1, XCC, XS0, '', 1, 1, false, 0, false);
        InsertData('56.2', XWIPServices6PERCENTVAT, 1, '', 7, 1, XCC, XS1, '', 1, 1, false, 0, false);
        InsertData('56.2', XWIPServices21PERCENTVAT, 1, '', 7, 1, XCC, DemoDataSetup.ServicesVATCode(), '', 1, 1, false, 0, false);
        InsertData('56.3', XWIPInvestments0PERCENTVAT, 1, '', 7, 1, XCC, XI0, '', 1, 1, false, 0, false);
        InsertData('56.3', XWIPInvestments21PERCENTVAT, 1, '', 7, 1, XCC, XI3, '', 1, 1, false, 0, false);
        InsertData('57', XRevChargeVATforImport, 2, '', 0, 0, '', '', '57.1..57.3', 0, 0, true, 1, false);
        InsertData('57.1', XImportGoods0PERCENTVAT, 1, '', 7, 1, XIMPREV, XG0, '', 1, 1, false, 0, false);
        InsertData('57.1', XImportGoods6PERCENTVAT, 1, '', 7, 1, XIMPREV, XG1, '', 1, 1, false, 0, false);
        InsertData('57.1', XImportGoods12PERCENTVAT, 1, '', 7, 1, XIMPREV, XG2, '', 1, 1, false, 0, false);
        InsertData('57.1', XImportGoods21PERCENTVAT, 1, '', 7, 1, XIMPREV, DemoDataSetup.GoodsVATCode(), '', 1, 1, false, 0, false);
        InsertData('57.2', XImportServices0PERCENTVAT, 1, '', 7, 1, XIMPREV, XS0, '', 1, 1, false, 0, false);
        InsertData('57.2', XImportServices6PERCENTVAT, 1, '', 7, 1, XIMPREV, XS1, '', 1, 1, false, 0, false);
        InsertData('57.2', XImportServices21PERCENTVAT, 1, '', 7, 1, XIMPREV, DemoDataSetup.ServicesVATCode(), '', 1, 1, false, 0, false);
        InsertData('57.3', XImportInvestments0PERCENTVAT, 1, '', 7, 1, XIMPREV, XI0, '', 1, 1, false, 0, false);
        InsertData('57.3', XImportInvestments21PERCENTVAT, 1, '', 7, 1, XIMPREV, XI3, '', 1, 1, false, 0, false);
        InsertData('59', XDeductibleVAT, 2, '', 0, 0, '', '', '59.1..59.4', 0, 0, true, 0, false);
        InsertData('59.1', XIncomingGoods0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XG0, '', 1, 0, false, 0, false);
        InsertData('59.1', XIncomingGoods6PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XG1, '', 1, 0, false, 0, false);
        InsertData('59.1', XIncomingGoods12PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XG2, '', 1, 0, false, 0, false);
        InsertData('59.1', XIncomingGoods21PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), DemoDataSetup.GoodsVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.1', XICAcquisofGoods0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG0, '', 1, 0, false, 0, false);
        InsertData('59.1', XICAcquisofGoods6PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG1, '', 1, 0, false, 0, false);
        InsertData('59.1', XICAcquisofGoods12PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG2, '', 1, 0, false, 0, false);
        InsertData('59.1', XICAcquisofGoods21PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), DemoDataSetup.GoodsVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.1', XWIPGoods0PERCENTVAT, 1, '', 7, 1, XCC, XG0, '', 1, 0, false, 0, false);
        InsertData('59.1', XWIPGoods6PERCENTVAT, 1, '', 7, 1, XCC, XG1, '', 1, 0, false, 0, false);
        InsertData('59.1', XWIPGoods12PERCENTVAT, 1, '', 7, 1, XCC, XG2, '', 1, 0, false, 0, false);
        InsertData('59.1', XWIPGoods21PERCENTVAT, 1, '', 7, 1, XCC, DemoDataSetup.GoodsVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.1', XImportGoods0PERCENTVAT, 1, '', 7, 1, XIMPREV, XG0, '', 1, 0, false, 0, false);
        InsertData('59.1', XImportGoods6PERCENTVAT, 1, '', 7, 1, XIMPREV, XG1, '', 1, 0, false, 0, false);
        InsertData('59.1', XImportGoods12PERCENTVAT, 1, '', 7, 1, XIMPREV, XG2, '', 1, 0, false, 0, false);
        InsertData('59.1', XImportGoods21PERCENTVAT, 1, '', 7, 1, XIMPREV, DemoDataSetup.GoodsVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.1', XImpExpGoods0PERCENTVAT, 1, '', 7, 1, XIMPEXP, XG0, '', 1, 0, false, 0, false);
        InsertData('59.1', XImpExpGoods6PERCENTVAT, 1, '', 7, 1, XIMPEXP, XG1, '', 1, 0, false, 0, false);
        InsertData('59.1', XImpExpGoods12PERCENTVAT, 1, '', 7, 1, XIMPEXP, XG2, '', 1, 0, false, 0, false);
        InsertData('59.1', XImpExpGoods21PERCENTVAT, 1, '', 7, 1, XIMPEXP, DemoDataSetup.GoodsVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.2', XIncomingServices0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XS0, '', 1, 0, false, 0, false);
        InsertData('59.2', XIncomingServices6PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XS1, '', 1, 0, false, 0, false);
        InsertData('59.2', XIncomingServices21PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), DemoDataSetup.ServicesVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.2', XIncomingServices0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XS0, '', 1, 0, false, 0, false);
        InsertData('59.2', XIncomingServices6PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XS1, '', 1, 0, false, 0, false);
        InsertData('59.2', XIncomingServices21PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), DemoDataSetup.ServicesVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.2', XWIPServices0PERCENTVAT, 1, '', 7, 1, XCC, XS0, '', 1, 0, false, 0, false);
        InsertData('59.2', XWIPServices6PERCENTVAT, 1, '', 7, 1, XCC, XS1, '', 1, 0, false, 0, false);
        InsertData('59.2', XWIPServices21PERCENTVAT, 1, '', 7, 1, XCC, DemoDataSetup.ServicesVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.2', XImportServices0PERCENTVAT, 1, '', 7, 1, XIMPREV, XS0, '', 1, 0, false, 0, false);
        InsertData('59.2', XImportServices6PERCENTVAT, 1, '', 7, 1, XIMPREV, XS1, '', 1, 0, false, 0, false);
        InsertData('59.2', XImportServices21PERCENTVAT, 1, '', 7, 1, XIMPREV, DemoDataSetup.ServicesVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.2', XImpExpServices0PERCVAT, 1, '', 7, 1, XIMPEXP, XS0, '', 1, 0, false, 0, false);
        InsertData('59.2', XImpExpServices6PERCVAT, 1, '', 7, 1, XIMPEXP, XS1, '', 1, 0, false, 0, false);
        InsertData('59.2', XImpExpServices21PERCVAT, 1, '', 7, 1, XIMPEXP, DemoDataSetup.ServicesVATCode(), '', 1, 0, false, 0, false);
        InsertData('59.3', XIncomingInvestment0PERCVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XI0, '', 1, 0, false, 0, false);
        InsertData('59.3', XIncomingInvestment21PERCVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XI3, '', 1, 0, false, 0, false);
        InsertData('59.3', XICAcqofInvestments0PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XI0, '', 1, 0, false, 0, false);
        InsertData('59.3', XICAcqofInvestments21PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XI3, '', 1, 0, false, 0, false);
        InsertData('59.3', XWIPInvestments0PERCENTVAT, 1, '', 7, 1, XCC, XI0, '', 1, 0, false, 0, false);
        InsertData('59.3', XWIPInvestments21PERCENTVAT, 1, '', 7, 1, XCC, XI3, '', 1, 0, false, 0, false);
        InsertData('59.3', XImportInvestments0PERCENTVAT, 1, '', 7, 1, XIMPREV, XI0, '', 1, 0, false, 0, false);
        InsertData('59.3', XImportInvestments21PERCENTVAT, 1, '', 7, 1, XIMPREV, XI3, '', 1, 0, false, 0, false);
        InsertData('59.3', XImpExpInvestments0PERCVAT, 1, '', 7, 1, XIMPEXP, XI0, '', 1, 0, false, 0, false);
        InsertData('59.3', XImpExpInvestments21PERCVAT, 1, '', 7, 1, XIMPEXP, XI3, '', 1, 0, false, 0, false);
        InsertData('59.4', XInvoicesOnlyVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XVAT, '', 1, 0, false, 0, false);
        InsertData('61', XRevisionsforTotVATPayable, 3, '', 0, 0, '', '', '', 0, 1, true, 1, false);
        InsertData('62', XRevisionsforTotVATDeductible, 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('63', XReimbVATReceivedCreditMemos, 2, '', 0, 0, '', '', '63.1..63.4', 0, 0, true, 1, false);
        InsertData('63.1', XReimbVATRecCMGoods6PERCVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XG1, '', 1, 0, false, 0, false);
        InsertData('63.1', XReimbVATRecCMGoods12PERCVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XG2, '', 1, 0, false, 0, false);
        InsertData('63.1', XReimbVATRecCMGoods21PERCVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), DemoDataSetup.GoodsVATCode(), '', 1, 0, false, 0, false);
        InsertData('63.2', XReimbVATRecCMServ6PERCVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XS1, '', 1, 0, false, 0, false);
        InsertData('63.2', XReimbVATRecCMServ21PERCVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), DemoDataSetup.ServicesVATCode(), '', 1, 0, false, 0, false);
        InsertData('63.3', XReimbVATRecCMInvestm21PERCVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XI3, '', 1, 0, false, 0, false);
        InsertData('63.4', XCreditMemosOnlyVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XVAT, '', 1, 0, false, 0, false);
        InsertData('64', XReimbVATShippedCreditMemos, 2, '', 0, 0, '', '', '64.1..64.4', 0, 0, true, 0, false);
        InsertData('64.1', XCreditmemosconcRow01, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XG1, '', 1, 0, false, 0, false);
        InsertData('64.1', XCreditmemosconcRow02, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XG2, '', 1, 0, false, 0, false);
        InsertData('64.1', XCreditmemosconcRow03, 1, '', 3, 2, DemoDataSetup.DomesticCode(), DemoDataSetup.GoodsVATCode(), '', 1, 0, false, 0, false);
        InsertData('64.2', XCreditmemosconcRow01, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XS1, '', 1, 0, false, 0, false);
        InsertData('64.2', XCreditmemosconcRow03, 1, '', 3, 2, DemoDataSetup.DomesticCode(), DemoDataSetup.ServicesVATCode(), '', 1, 0, false, 0, false);
        InsertData('64.3', XCreditmemosconcRow03, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XI3, '', 1, 0, false, 0, false);
        InsertData('64.4', XCreditMemosOnlyVAT, 1, '', 3, 2, DemoDataSetup.DomesticCode(), XVAT, '', 1, 0, false, 0, false);
        InsertData('65', XReservedforVATPayable, 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('66', XReservedforVATDeductible, 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('', '', 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('71/72', XStatementTotals, 2, '', 0, 0, '', '', 'XX|YY', 0, 0, true, 0, false);
        InsertData('XX', XLeft54555657616365, 2, '', 0, 0, '', '', '54|55|56|57|61|63|65', 0, 0, true, 1, false);
        InsertData('YY', XRight59626466, 2, '', 0, 0, '', '', '59|62|64|66', 0, 0, true, 0, false);
        InsertData('', '', 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
        InsertData('81', XGoodsinclIncCreditMemos, 2, '', 0, 0, '', '', '81.1..81.4|84.1|85.01|85.11|85.21|85.41|86.1|87.1', 0, 0, true, 0, false);
        InsertData('81.1', XGoods0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XG0, '', 2, 0, false, 0, false);
        InsertData('81.1', XGoods6PERCENTVAT2, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XG1, '', 2, 0, false, 0, false);
        InsertData('81.1', XGoods12PERCENTVAT2, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XG2, '', 2, 0, false, 0, false);
        InsertData('81.1', XGoods21PERCENTVAT2, 1, '', 7, 1, DemoDataSetup.DomesticCode(), DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('81.1', XImportGoods0PERCENTVAT, 1, '', 7, 1, XIMPEXP, XG0, '', 2, 0, false, 0, false);
        InsertData('81.1', XImportGoods6PERCENTVAT, 1, '', 7, 1, XIMPEXP, XG1, '', 2, 0, false, 0, false);
        InsertData('81.1', XImportGoods12PERCENTVAT, 1, '', 7, 1, XIMPEXP, XG2, '', 2, 0, false, 0, false);
        InsertData('81.1', XImportGoods21PERCENTVAT, 1, '', 7, 1, XIMPEXP, DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('82', XServinclIncCreditMemos, 2, '', 0, 0, '', '', '82.2..82.9|85.02|85.12|85.22|85.32|85.42|87.2', 0, 0, true, 0, false);
        InsertData('82.2', XServices0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XS0, '', 2, 0, false, 0, false);
        InsertData('82.2', XServices6PERCENTVAT2, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XS1, '', 2, 0, false, 0, false);
        InsertData('82.2', XServices21PERCENTVAT2, 1, '', 7, 1, DemoDataSetup.DomesticCode(), DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('82.2', XImportServices0PERCENTVAT, 1, '', 7, 1, XIMPEXP, XS0, '', 2, 0, false, 0, false);
        InsertData('82.2', XImportServices6PERCENTVAT, 1, '', 7, 1, XIMPEXP, XS1, '', 2, 0, false, 0, false);
        InsertData('82.2', XImportServices21PERCENTVAT, 1, '', 7, 1, XIMPEXP, DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('83', XInvestGoodsinclIncCreditMemos, 2, '', 0, 0, '', '', '83.3|84.3|85.03|85.13|85.23|85.43|86.3|87.3', 0, 0, true, 0, false);
        InsertData('83.3', XInvestment0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XI0, '', 2, 0, false, 0, false);
        InsertData('83.3', XInvestment21PERCENTVAT, 1, '', 7, 1, DemoDataSetup.DomesticCode(), XI3, '', 2, 0, false, 0, false);
        InsertData('83.3', XImportInvestments0PERCENTVAT, 1, '', 7, 1, XIMPEXP, XI0, '', 2, 0, false, 0, false);
        InsertData('83.3', XImportInvestments21PERCENTVAT, 1, '', 7, 1, XIMPEXP, XI3, '', 2, 0, false, 0, false);
        InsertData('84', XCreditMemosconcICAcquisitions, 2, '', 0, 0, '', '', '84.1..84.3', 0, 0, true, 1, false);
        InsertData('84.1', XCMGoods0PERCENTVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), XG0, '', 2, 0, false, 0, false);
        InsertData('84.1', XCMGoods6PERCENTVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), XG1, '', 2, 0, false, 0, false);
        InsertData('84.1', XCMGoods12PERCENTVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), XG2, '', 2, 0, false, 0, false);
        InsertData('84.1', XCMGoods21PERCENTVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('84.3', XCreditMemosInvGoods0PERCVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), XI0, '', 2, 0, false, 0, false);
        InsertData('84.3', XCreditMemosInvGoods21PERCVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), XI3, '', 2, 0, false, 0, false);
        InsertData('85', XCreditMemosconcRow818283, 2, '', 0, 0, '', '', '85.01..85.43', 0, 0, true, 1, false);
        InsertData('85.01', XCMGoods0PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XG0, '', 2, 0, false, 0, false);
        InsertData('85.01', XCMGoods6PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XG1, '', 2, 0, false, 0, false);
        InsertData('85.01', XCMGoods12PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XG2, '', 2, 0, false, 0, false);
        InsertData('85.01', XCMGoods21PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.02', XCMServices0PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XS0, '', 2, 0, false, 0, false);
        InsertData('85.02', XCMServices6PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XS1, '', 2, 0, false, 0, false);
        InsertData('85.02', XCMServices21PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.03', XCMInvestment0PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XI0, '', 2, 0, false, 0, false);
        InsertData('85.03', XCMInvestment21PERCENTVAT, 1, '', 3, 1, DemoDataSetup.DomesticCode(), XI3, '', 2, 0, false, 0, false);
        InsertData('85.11', XCMGoods0PERCENTVAT, 1, '', 3, 1, XCC, XG0, '', 2, 0, false, 0, false);
        InsertData('85.11', XCMGoods6PERCENTVAT, 1, '', 3, 1, XCC, XG1, '', 2, 0, false, 0, false);
        InsertData('85.11', XCMGoods12PERCENTVAT, 1, '', 3, 1, XCC, XG2, '', 2, 0, false, 0, false);
        InsertData('85.11', XCMGoods21PERCENTVAT, 1, '', 3, 1, XCC, DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.12', XCMServices0PERCENTVAT, 1, '', 3, 1, XCC, XS0, '', 2, 0, false, 0, false);
        InsertData('85.12', XCMServices6PERCENTVAT, 1, '', 3, 1, XCC, XS1, '', 2, 0, false, 0, false);
        InsertData('85.12', XCMServices21PERCENTVAT, 1, '', 3, 1, XCC, DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.13', XCMInvestment0PERCENTVAT, 1, '', 3, 1, XCC, XI0, '', 2, 0, false, 0, false);
        InsertData('85.13', XCMInvestment21PERCENTVAT, 1, '', 3, 1, XCC, XI3, '', 2, 0, false, 0, false);
        InsertData('85.21', XCMImportGoods0PERCENTVAT, 1, '', 3, 1, XIMPEXP, XG0, '', 2, 0, false, 0, false);
        InsertData('85.21', XCMImportGoods6PERCENTVAT, 1, '', 3, 1, XIMPEXP, XG1, '', 2, 0, false, 0, false);
        InsertData('85.21', XCMImportGoods12PERCENTVAT, 1, '', 3, 1, XIMPEXP, XG2, '', 2, 0, false, 0, false);
        InsertData('85.21', XCMImportGoods21PERCENTVAT, 1, '', 3, 1, XIMPEXP, DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.22', XCMImportServices0PERCENTVAT, 1, '', 3, 1, XIMPEXP, XS0, '', 2, 0, false, 0, false);
        InsertData('85.22', XCMImportServices6PERCENTVAT, 1, '', 3, 1, XIMPEXP, XS1, '', 2, 0, false, 0, false);
        InsertData('85.22', XCMImportServices21PERCENTVAT, 1, '', 3, 1, XIMPEXP, DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.23', XCMImportInvestments0PERCVAT, 1, '', 3, 1, XIMPEXP, XI0, '', 2, 0, false, 0, false);
        InsertData('85.23', XCMImportInvestments21PERCVAT, 1, '', 3, 1, XIMPEXP, XI3, '', 2, 0, false, 0, false);
        InsertData('85.32', XCMServices0PERCENTVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), XS0, '', 2, 0, false, 0, false);
        InsertData('85.32', XCMServices6PERCENTVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), XS1, '', 2, 0, false, 0, false);
        InsertData('85.32', XCMServices21PERCENTVAT, 1, '', 3, 1, DemoDataSetup.EUCode(), DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.41', XCMImportGoods0PERCENTVAT, 1, '', 3, 1, XIMPREV, XG0, '', 2, 0, false, 0, false);
        InsertData('85.41', XCMImportGoods6PERCENTVAT, 1, '', 3, 1, XIMPREV, XG1, '', 2, 0, false, 0, false);
        InsertData('85.41', XCMImportGoods12PERCENTVAT, 1, '', 3, 1, XIMPREV, XG2, '', 2, 0, false, 0, false);
        InsertData('85.41', XCMImportGoods21PERCENTVAT, 1, '', 3, 1, XIMPREV, DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.42', XCMImportServices0PERCENTVAT, 1, '', 3, 1, XIMPREV, XS0, '', 2, 0, false, 0, false);
        InsertData('85.42', XCMImportServices6PERCENTVAT, 1, '', 3, 1, XIMPREV, XS1, '', 2, 0, false, 0, false);
        InsertData('85.42', XCMImportServices21PERCENTVAT, 1, '', 3, 1, XIMPREV, DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('85.43', XCMImportInvestments0PERCVAT, 1, '', 3, 1, XIMPREV, XI0, '', 2, 0, false, 0, false);
        InsertData('85.43', XCMImportInvestments21PERCVAT, 1, '', 3, 1, XIMPREV, XI3, '', 2, 0, false, 0, false);
        InsertData('86', XAmntIntraCommAcquisitionsICA, 2, '', 0, 0, '', '', '86.1..86.3|84.1|84.3', 0, 0, true, 0, false);
        InsertData('86.1', XICAGoods0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG0, '', 2, 0, false, 0, false);
        InsertData('86.1', XICAGoods6PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG1, '', 2, 0, false, 0, false);
        InsertData('86.1', XICAGoods12PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XG2, '', 2, 0, false, 0, false);
        InsertData('86.1', XICAGoods21PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('86.3', XICAInvestmentGoods0PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XI0, '', 2, 0, false, 0, false);
        InsertData('86.3', XICAInvestmentGoods21PERCVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XI3, '', 2, 0, false, 0, false);
        InsertData('87', XOtherOperatingActivities, 2, '', 0, 0, '', '', '87.1..87.3|85.11..85.13|85.31..85.43', 0, 0, true, 0, false);
        InsertData('87.1', XWIPGoods0PERCENTVAT, 1, '', 7, 1, XCC, XG0, '', 2, 0, false, 0, false);
        InsertData('87.1', XWIPGoods6PERCENTVAT, 1, '', 7, 1, XCC, XG1, '', 2, 0, false, 0, false);
        InsertData('87.1', XWIPGoods12PERCENTVAT, 1, '', 7, 1, XCC, XG2, '', 2, 0, false, 0, false);
        InsertData('87.1', XWIPGoods21PERCENTVAT, 1, '', 7, 1, XCC, DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('87.1', XImportGoodsRevCharge0PERCVAT, 1, '', 7, 1, XIMPREV, XG0, '', 2, 0, false, 0, false);
        InsertData('87.1', XImportGoodsRevCharge6PERCVAT, 1, '', 7, 1, XIMPREV, XG1, '', 2, 0, false, 0, false);
        InsertData('87.1', XImportGoodsRevCharge12PERCVAT, 1, '', 7, 1, XIMPREV, XG2, '', 2, 0, false, 0, false);
        InsertData('87.1', XImportGoodsRevCharge21PERCVAT, 1, '', 7, 1, XIMPREV, DemoDataSetup.GoodsVATCode(), '', 2, 0, false, 0, false);
        InsertData('87.2', XWIPServices0PERCENTVAT, 1, '', 7, 1, XCC, XS0, '', 2, 0, false, 0, false);
        InsertData('87.2', XWIPServices6PERCENTVAT, 1, '', 7, 1, XCC, XS1, '', 2, 0, false, 0, false);
        InsertData('87.2', XWIPServices21PERCENTVAT, 1, '', 7, 1, XCC, DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('87.2', XImportEUServices0PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XS0, '', 2, 0, false, 0, false);
        InsertData('87.2', XImportEUServices6PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), XS1, '', 2, 0, false, 0, false);
        InsertData('87.2', XImportEUServices21PERCENTVAT, 1, '', 7, 1, DemoDataSetup.EUCode(), DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('87.2', XImportServRevCharge0PERCVAT, 1, '', 7, 1, XIMPREV, XS0, '', 2, 0, false, 0, false);
        InsertData('87.2', XImportServRevCharge6PERCVAT, 1, '', 7, 1, XIMPREV, XS1, '', 2, 0, false, 0, false);
        InsertData('87.2', XImportServRevCharge21PERCVAT, 1, '', 7, 1, XIMPREV, DemoDataSetup.ServicesVATCode(), '', 2, 0, false, 0, false);
        InsertData('87.3', XWIPInvestments0PERCENTVAT, 1, '', 7, 1, XCC, XI0, '', 2, 0, false, 0, false);
        InsertData('87.3', XWIPInvestments21PERCENTVAT, 1, '', 7, 1, XCC, XI3, '', 2, 0, false, 0, false);
        InsertData('87.3', XImportInvstRevCharge0PERCVAT, 1, '', 7, 1, XIMPREV, XI0, '', 2, 0, false, 0, false);
        InsertData('87.3', XImportInvstRevCharge21PERCVAT, 1, '', 7, 1, XIMPREV, XI3, '', 2, 0, false, 0, false);
        InsertData('91', XPrepayment, 3, '', 0, 0, '', '', '', 0, 0, true, 0, false);
    end;

    var
        DemoDataSetup: Record "Demo Data Setup";
        NextLineNo: Integer;
        XVAT: Label 'VAT';
        XDEFAULT: Label 'DEFAULT';
        XIMPEXP: Label 'IMPEXP';
        XIMPREV: Label 'IMPREV';
        XCC: Label 'CC';
        XG0: Label 'G0';
        XG1: Label 'G1';
        XG2: Label 'G2';
        XS0: Label 'S0';
        XS1: Label 'S1';
        XI0: Label 'I0';
        XI3: Label 'I3';
        XOUTGOINGACTIVITIES: Label 'OUTGOING ACTIVITIES';
        XSubmittedto0PERCENTVAT: Label 'Submitted to 0 % VAT';
        XGoods0PERCENTVAT: Label '  Goods 0% VAT';
        XServices0PERCENTVAT: Label '  Services 0% VAT';
        XInvestments0PERCENTVAT: Label '  Investments 0% VAT';
        XSubmittedto6PERCENTVAT: Label 'Submitted to 6% VAT';
        XGoods6PERCENTVAT: Label ' Goods 6% VAT';
        XServices6PERCENTVAT: Label ' Services 6% VAT';
        XSubmittedto12PERCENTVAT: Label 'Submitted to 12 % VAT';
        XSubmittedto21PERCENTVAT: Label 'Submitted to 21 % VAT';
        XGoods21PERCENTVAT: Label ' Goods 21% VAT';
        XServices21PERCENTVAT: Label ' Services 21% VAT';
        XInvestments21PERCENTVAT: Label ' Investments 21% VAT';
        XAmountVATexcl: Label 'Amount (VAT excl.)';
        XGoods12PERCENTVAT: Label ' Goods 12% VAT';
        XIntraCommunityICDeliveries: Label 'Intra-Community (IC) Deliveries';
        XCreditmemosconcRow46: Label 'Credit memos conc. Row 46';
        XCreditmemosconcRow00: Label '  Credit memos conc. Row 00';
        XCMconcRow000102034547: Label '  Credit memos conc. Row 00,01,02,03,45,47';
        XCreditmemosconcRow01: Label '  Credit memos conc. Row 01';
        XCreditmemosconcRow02: Label '  Credit memos conc. Row 02';
        XCreditmemosconcRow03: Label '  Credit memos conc. Row 03';
        XCreditmemosconcRow45: Label '  Credit memos conc. Row 45';
        XCreditmemosconcRow47: Label '  Credit memos conc. Row 47';
        XPAYABLEANDDEDUCTIBLETAXES: Label 'PAYABLE AND DEDUCTIBLE TAXES';
        XTaxespayableforRow00010203: Label 'Taxes payable for Row 00,01,02,03';
        XTaxespayableforRow01: Label '  Taxes payable for Row 01';
        XTaxespayableforRow02: Label '  Taxes payable for Row 02';
        XTaxespayableforRow03: Label '  Taxes payable for Row 03';
        XTaxespayableVATOnly: Label '  Taxes payable (VAT Only)';
        XTaxespayableforICAcquisitions: Label 'Taxes payable for IC Acquisitions';
        XRevChrgVATICAcqGoods0PERCVAT: Label '  Rev. Charge VAT for IC Acquis. Goods 0% VAT';
        XRevChrgVATICAcqGoods6PERCVAT: Label '  Rev. Charge VAT for IC Acquis. Goods 6% VAT';
        XRevChrgVATICAcqGoods12PERCVAT: Label '  Rev. Charge VAT for IC Acquis. Goods 12% VAT';
        XRevChrgVATICAcqGoods21PERCVAT: Label '  Rev. Charge VAT for IC Acquis. Goods 21% VAT';
        XRevChrgVATICAcqInvst0PERCVAT: Label '  Rev. Charge VAT for IC Acquis. Invest. 0% VAT';
        XRevChrgVATICAcqInvst21PERCVAT: Label '  Rev. Charge VAT for IC Acquis. Invest. 21% VAT';
        XRevChrgVATActinvCocontractors: Label 'Rev. Charge VAT for Activ inv. Cocontractors';
        XWIPGoods0PERCENTVAT: Label '  WIP Goods 0% VAT';
        XWIPGoods6PERCENTVAT: Label '  WIP Goods 6% VAT';
        XWIPGoods12PERCENTVAT: Label '  WIP Goods 12% VAT';
        XWIPGoods21PERCENTVAT: Label '  WIP Goods 21% VAT';
        XServices6PERCENTVAT2: Label '  Services 6% VAT';
        XServices21PERCENTVAT2: Label '  Services 21% VAT';
        XWIPServices0PERCENTVAT: Label '  WIP Services 0% VAT';
        XWIPServices6PERCENTVAT: Label '  WIP Services 6% VAT';
        XWIPServices21PERCENTVAT: Label '  WIP Services 21% VAT';
        XWIPInvestments0PERCENTVAT: Label '  WIP Investments 0% VAT';
        XWIPInvestments21PERCENTVAT: Label '  WIP Investments 21% VAT';
        XRevChargeVATforImport: Label 'Rev. Charge VAT for Import';
        XImportGoods0PERCENTVAT: Label '  Import Goods 0% VAT';
        XImportGoods6PERCENTVAT: Label '  Import Goods 6% VAT';
        XImportGoods12PERCENTVAT: Label '  Import Goods 12% VAT';
        XImportGoods21PERCENTVAT: Label '  Import Goods 21% VAT';
        XImportServices0PERCENTVAT: Label '  Import Services 0% VAT';
        XImportServices6PERCENTVAT: Label '  Import Services 6% VAT';
        XImportServices21PERCENTVAT: Label '  Import Services 21% VAT';
        XImportInvestments0PERCENTVAT: Label '  Import Investments 0% VAT';
        XImportInvestments21PERCENTVAT: Label '  Import Investments 21% VAT';
        XDeductibleVAT: Label 'Deductible VAT';
        XIncomingGoods0PERCENTVAT: Label '  Incoming Goods 0% VAT';
        XIncomingGoods6PERCENTVAT: Label '  Incoming Goods 6% VAT';
        XIncomingGoods12PERCENTVAT: Label '  Incoming Goods 12% VAT';
        XIncomingGoods21PERCENTVAT: Label '  Incoming Goods 21% VAT';
        XICAcquisofGoods0PERCENTVAT: Label '  IC Acquis. of Goods 0% VAT';
        XICAcquisofGoods6PERCENTVAT: Label '  IC Acquis. of Goods 6% VAT';
        XICAcquisofGoods12PERCENTVAT: Label '  IC Acquis. of Goods 12% VAT';
        XICAcquisofGoods21PERCENTVAT: Label '  IC Acquis. of Goods 21% VAT';
        XImpExpGoods0PERCENTVAT: Label '  Import/Export Goods 0% VAT';
        XImpExpGoods6PERCENTVAT: Label '  Import/Export Goods 6% VAT';
        XImpExpGoods12PERCENTVAT: Label '  Import/Export Goods 12% VAT';
        XImpExpGoods21PERCENTVAT: Label '  Import/Export Goods 21% VAT';
        XIncomingServices0PERCENTVAT: Label '  Incoming Services 0% VAT';
        XIncomingServices6PERCENTVAT: Label '  Incoming Services 6% VAT';
        XIncomingServices21PERCENTVAT: Label '  Incoming Services 21% VAT';
        XImpExpServices0PERCVAT: Label '  Import/Export Services 0% VAT';
        XImpExpServices6PERCVAT: Label '  Import/Export Services 6% VAT';
        XImpExpServices21PERCVAT: Label '  Import/Export Services 21% VAT';
        XIncomingInvestment0PERCVAT: Label '  Incoming Investment 0% VAT';
        XIncomingInvestment21PERCVAT: Label '  Incoming Investment 21% VAT';
        XICAcqofInvestments0PERCVAT: Label '  IC Acquis. of Investments 0% VAT';
        XICAcqofInvestments21PERCVAT: Label '  IC Acquis. of Investments 21% VAT';
        XImpExpInvestments0PERCVAT: Label '  Import/Export Investments 0% VAT';
        XImpExpInvestments21PERCVAT: Label '  Import/Export Investments 21% VAT';
        XInvoicesOnlyVAT: Label '  Invoices (Only VAT)';
        XRevisionsforTotVATPayable: Label 'Revisions for Total VAT Payable';
        XRevisionsforTotVATDeductible: Label 'Revisions for Total VAT Deductible';
        XReimbVATRecCMGoods6PERCVAT: Label '  Reimb. of VAT for Rec. CM Goods (6% VAT)';
        XReimbVATRecCMGoods12PERCVAT: Label '  Reimb. of VAT for Rec. CM Goods (12% VAT)';
        XReimbVATRecCMGoods21PERCVAT: Label '  Reimb. of VAT for Rec. CM Goods (21% VAT)';
        XReimbVATRecCMServ6PERCVAT: Label '  Reimb. of VAT for Rec. CM Services (6% VAT)';
        XReimbVATRecCMServ21PERCVAT: Label '  Reimb. of VAT for Rec. CM Services (21% VAT)';
        XReimbVATRecCMInvestm21PERCVAT: Label '  Reimb. of VAT for Rec. CM Investm. (21% VAT)';
        XCreditMemosOnlyVAT: Label '  Credit Memos (Only VAT)';
        XReimbVATReceivedCreditMemos: Label 'Reimbursement of VAT for Received Credit Memos';
        XReimbVATShippedCreditMemos: Label 'Reimbursement of VAT for Shipped Credit Memos';
        XReservedforVATPayable: Label 'Reserved for VAT Payable';
        XReservedforVATDeductible: Label 'Reserved for VAT Deductible';
        XStatementTotals: Label 'Statement Totals';
        XLeft54555657616365: Label 'Left      54+55+56+57+61+63+65';
        XRight59626466: Label 'Right   59+62+64+66';
        XGoodsinclIncCreditMemos: Label 'Goods, incl. Incoming Credit Memos';
        XGoods6PERCENTVAT2: Label '  Goods 6% VAT';
        XGoods12PERCENTVAT2: Label '  Goods 12% VAT';
        XGoods21PERCENTVAT2: Label '  Goods 21% VAT';
        XServinclIncCreditMemos: Label 'Services, incl. Incoming Credit Memos';
        XInvestGoodsinclIncCreditMemos: Label 'Investm. Goods, incl. Incoming Credit Memos';
        XInvestment0PERCENTVAT: Label '  Investment 0% VAT';
        XInvestment21PERCENTVAT: Label '  Investment 21% VAT';
        XCreditMemosconcICAcquisitions: Label 'Credit Memos conc. IC Acquisitions';
        XCMGoods0PERCENTVAT: Label '  CM Goods 0% VAT';
        XCMGoods6PERCENTVAT: Label '  CM Goods 6% VAT';
        XCMGoods12PERCENTVAT: Label '  CM Goods 12% VAT';
        XCMGoods21PERCENTVAT: Label '  CM Goods 21% VAT';
        XCreditMemosInvGoods0PERCVAT: Label '  Credit Memos Investment Goods 0% VAT';
        XCreditMemosInvGoods21PERCVAT: Label '  Credit Memos Investment Goods 21% VAT';
        XCMServices0PERCENTVAT: Label '  CM Services 0% VAT';
        XCMServices6PERCENTVAT: Label '  CM Services 6% VAT';
        XCMServices21PERCENTVAT: Label '  CM Services 21% VAT';
        XCMInvestment0PERCENTVAT: Label '  CM Investment 0% VAT';
        XCMInvestment21PERCENTVAT: Label '  CM Investment 21% VAT';
        XCMImportGoods0PERCENTVAT: Label '  CM Import Goods 0% VAT';
        XCMImportGoods6PERCENTVAT: Label '  CM Import Goods 6% VAT';
        XCMImportGoods12PERCENTVAT: Label '  CM Import Goods 12% VAT';
        XCMImportGoods21PERCENTVAT: Label '  CM Import Goods 21% VAT';
        XCreditMemosconcRow818283: Label 'Credit Memos conc. Row 81,82,83';
        XCMImportServices0PERCENTVAT: Label '  CM Import Services 0% VAT';
        XCMImportServices6PERCENTVAT: Label '  CM Import Services 6% VAT';
        XCMImportServices21PERCENTVAT: Label '  CM Import Services 21% VAT';
        XCMImportInvestments0PERCVAT: Label '  CM Import Investments 0% VAT';
        XCMImportInvestments21PERCVAT: Label '  CM Import Investments 21% VAT';
        XAmntIntraCommAcquisitionsICA: Label 'Amount of Intra-Community Acquisitions (ICA)';
        XICAGoods0PERCENTVAT: Label '  ICA Goods 0% VAT';
        XICAGoods6PERCENTVAT: Label '  ICA Goods 6% VAT';
        XICAGoods12PERCENTVAT: Label '  ICA Goods 12% VAT';
        XICAGoods21PERCENTVAT: Label '  ICA Goods 21% VAT';
        XICAInvestmentGoods0PERCVAT: Label '  ICA Investment Goods 0% VAT';
        XICAInvestmentGoods21PERCVAT: Label '  ICA Investment Goods 21% VAT';
        XOtherOperatingActivities: Label 'Other Operating Activities';
        XImportGoodsRevCharge0PERCVAT: Label '  Import Goods Reverse Charge 0% VAT';
        XImportGoodsRevCharge6PERCVAT: Label '  Import Goods Reverse Charge 6% VAT';
        XImportGoodsRevCharge12PERCVAT: Label '  Import Goods Reverse Charge 12% VAT';
        XImportGoodsRevCharge21PERCVAT: Label '  Import Goods Reverse Charge 21% VAT';
        XImportEUServices0PERCENTVAT: Label '  Import EU Services 0% VAT';
        XImportEUServices6PERCENTVAT: Label '  Import EU Services 6% VAT';
        XImportEUServices21PERCENTVAT: Label '  Import EU Services 21% VAT';
        XImportServRevCharge0PERCVAT: Label '  Import Services Reverse Charge 0% VAT';
        XImportServRevCharge6PERCVAT: Label '  Import Services Reverse Charge 6% VAT';
        XImportServRevCharge21PERCVAT: Label '  Import Services Reverse Charge 21% VAT';
        XImportInvstRevCharge0PERCVAT: Label '  Import Investments Reverse Charge 0% VAT';
        XImportInvstRevCharge21PERCVAT: Label '  Import Investments Reverse Charge 21% VAT';
        XPrepayment: Label 'Prepayment';
        XExporttocountriesnotmemberEU: Label 'Export to other countries (not member of EU)';

    procedure InsertData(RowNo: Code[10]; Description: Text[50]; Type: Option; AccountTotaling: Text[30]; DocumentType: Option; GenPostingType: Option; VATBusPostingGroup: Code[20]; VATProdPostingGroup: Code[20]; RowTotaling: Text[50]; AmountType: Option; CalculateWith: Option; Print: Boolean; PrintWith: Option; NewPage: Boolean)
    var
        VATStatementLine: Record "VAT Statement Line";
    begin
        VATStatementLine.Init();
        VATStatementLine.Validate("Statement Template Name", XVAT);
        VATStatementLine.Validate("Statement Name", XDEFAULT);
        NextLineNo := NextLineNo + 10000;
        VATStatementLine.Validate("Line No.", NextLineNo);
        VATStatementLine.Validate("Row No.", RowNo);
        VATStatementLine.Validate(Description, Description);
        VATStatementLine.Validate(Type, Type);
        VATStatementLine.Validate("Account Totaling", AccountTotaling);
        VATStatementLine.Validate("Document Type", DocumentType);
        VATStatementLine.Validate("Gen. Posting Type", GenPostingType);
        VATStatementLine.Validate("VAT Bus. Posting Group", VATBusPostingGroup);
        VATStatementLine.Validate("VAT Prod. Posting Group", VATProdPostingGroup);
        VATStatementLine.Validate("Row Totaling", RowTotaling);
        VATStatementLine.Validate("Amount Type", AmountType);
        VATStatementLine.Validate("Calculate with", CalculateWith);
        VATStatementLine.Validate(Print, Print);
        VATStatementLine.Validate("Print with", PrintWith);
        VATStatementLine.Validate("New Page", NewPage);
        VATStatementLine.Validate("Print on Official VAT Form", Print);
        VATStatementLine.Insert();
    end;
}

