// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.Finance.Analysis;

using System.Telemetry;
using System.Utilities;

page 687 "Payment Practice Card"
{
    ApplicationArea = All;
    Caption = 'Payment Practice';
    PageType = Card;
    SourceTable = "Payment Practice Header";

    layout
    {
        area(Content)
        {
            group(General)
            {
                Caption = 'General';
                field("No."; Rec."No.")
                {
                    ToolTip = 'Specifies the number of the payment practice header.';
                }
                field("Reporting Scheme"; Rec."Reporting Scheme")
                {
                    trigger OnValidate()
                    begin
                        UpdateVisibility();
                        CurrPage.Update(true);
                    end;
                }
                field("Payment Period Code"; Rec."Payment Period Code")
                {
                    ShowMandatory = true;
                }
                field("Aggregation Type"; Rec."Aggregation Type")
                {
                    ToolTip = 'Specifies the aggregation type of the payment practice.';
                }
                field("Header Type"; Rec."Header Type")
                {
                    ToolTip = 'Specifies the source for entries in the payment practice.';
                }
                field("Starting Date"; Rec."Starting Date")
                {
                    ToolTip = 'Specifies the starting date of the payment practice.';
                }
                field("Ending Date"; Rec."Ending Date")
                {
                    ToolTip = 'Specifies the ending date of the payment practice.';
                }
                field("Generated On"; Rec."Generated On")
                {
                    Editable = false;
                    ToolTip = 'Specifies the date and time when the payment practice was generated.';
                }
                field("Generated By"; Rec."Generated By")
                {
                    Editable = false;
                    ToolTip = 'Specifies the user who generated the payment practice.';
                }
                field("Lines Exist"; Rec."Lines Exist")
                {
                    Editable = false;
                    ToolTip = 'Specifies whether the payment practice has lines.';
                    Visible = false;
                }
                field("Modified Manually"; Rec."Modified Manually")
                {
                    Editable = false;
                    ToolTip = 'Specifies whether the payment practice was modified manually.';
                }
            }
            group("Payment Statistics")
            {
                Caption = 'Payment Statistics';
                field("Average Agreed Payment Period"; Rec."Average Agreed Payment Period")
                {
                    ToolTip = 'Specifies the average agreed payment period.';

                    trigger OnDrillDown()
                    begin
                        ShowHeaderDataLines();
                    end;
                }
                field("Average Actual Payment Period"; Rec."Average Actual Payment Period")
                {
                    ToolTip = 'Specifies the average actual payment period.';

                    trigger OnDrillDown()
                    begin
                        ShowHeaderDataLines();
                    end;
                }
                field("Pct Paid on Time"; Rec."Pct Paid on Time")
                {
                    ToolTip = 'Specifies the percentage paid on time.';

                    trigger OnDrillDown()
                    begin
                        ShowHeaderDataLines();
                    end;
                }
                field("Total Number of Payments"; Rec."Total Number of Payments")
                {
                    Visible = IsDisputeRetention;
                }
                field("Total Amount of Payments"; Rec."Total Amount of Payments")
                {
                    Visible = IsDisputeRetention;
                }
                field("Total Amt. of Overdue Payments"; Rec."Total Amt. of Overdue Payments")
                {
                    Visible = IsDisputeRetention;
                }
                field("Pct Overdue Due to Dispute"; Rec."Pct Overdue Due to Dispute")
                {
                    Visible = IsDisputeRetention;
                }
            }
            group("Dispute & Retention")
            {
                Caption = 'Dispute & Retention';
                Visible = IsDisputeRetention;
                field(DisputeRetentionLink; DisputeRetentionLinkTxt)
                {
                    Caption = 'Dispute & Retention Details';
#pragma warning disable AA0219
                    ToolTip = 'Opens the Dispute & Retention details page for this payment practice.';
#pragma warning restore AA0219
                    Editable = false;
                    Style = StandardAccent;
                    ShowCaption = false;

                    trigger OnDrillDown()
                    var
                        DisputeRetData: Record "Paym. Prac. Dispute Ret. Data";
                    begin
                        if DisputeRetData.Get(Rec."No.") then
                            Page.RunModal(Page::"Paym. Prac. Dispute Ret. Card", DisputeRetData);
                    end;
                }
            }
            part(Lines; "Payment Practice Lines")
            {
                ApplicationArea = All;
                SubPageLink = "Header No." = field("No.");
                UpdatePropagation = Both;
                Visible = true;
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(Generate)
            {
                Caption = 'Generate';
                ToolTip = 'Generates the data and lines for the payment practice.';
                Image = CashFlow;

                trigger OnAction()
                var
                    PaymentPractices: Codeunit "Payment Practices";
                    ConfirmManagement: Codeunit "Confirm Management";
                begin
                    if Rec."Lines Exist" then
                        if not ConfirmManagement.GetResponse(LinesWillBeDeletedQst, false) then
                            exit;

                    Rec.ClearHeader();
                    if not PaymentPractices.Generate(Rec) then
                        Message(NoEntriesFoundMsg);
                    UpdateVisibility();
                    CurrPage.Update();
                end;
            }
            action(Print)
            {
                Caption = 'Print';
                ToolTip = 'Prints the payment practice report.';
                Image = Print;

                trigger OnAction()
                begin
                    PrepareLayout(Rec."Aggregation Type");
                    Rec.SetRecFilter();
                    Report.Run(Report::"Payment Practice", false, true, Rec);
                    FeatureTelemetry.LogUptake('0000KSV', 'Payment Practices', "Feature Uptake Status"::Used);
                end;
            }
            action(ExportGBCSV)
            {
                Caption = 'Export CSV';
                ToolTip = 'Exports the Dispute/Retention scheme data in CSV format.';
                Image = Export;
                Visible = IsDisputeRetention;

                trigger OnAction()
                var
                    PaymPracGBCSVExport: Codeunit "Paym. Prac. GB CSV Export";
                begin
                    PaymPracGBCSVExport.Export(Rec);
                end;
            }
            action(ExportAUCSV)
            {
                Caption = 'Export CSV';
                ToolTip = 'Exports the Small Business scheme data in CSV format.';
                Image = Export;
                Visible = IsSmallBusiness;

                trigger OnAction()
                var
                    PaymPracAUCSVExport: Codeunit "Paym. Prac. AU CSV Export";
                begin
                    PaymPracAUCSVExport.Export(Rec);
                end;
            }
        }
        area(Promoted)
        {
            actionref(Generate_Promoted; Generate)
            {
            }
            actionref(Print_Promoted; Print)
            {
            }
            actionref(ExportGBCSV_Promoted; ExportGBCSV)
            {
            }
            actionref(ExportAUCSV_Promoted; ExportAUCSV)
            {
            }
        }
    }

    trigger OnOpenPage()
    begin
        UpdateVisibility();
        CurrPage.Update();
    end;

    trigger OnAfterGetCurrRecord()
    begin
        UpdateVisibility();
    end;

    var
        FeatureTelemetry: Codeunit "Feature Telemetry";
        LinesWillBeDeletedQst: Label 'All previously generated lines will be deleted. Do you want to continue?';
        NoEntriesFoundMsg: Label 'The payment practice generator found no entries corresponding to the header type, starting and ending date.';
        IsDisputeRetention: Boolean;
        IsSmallBusiness: Boolean;
        DisputeRetentionLinkTxt: Label 'View or edit Dispute & Retention details';

    local procedure PrepareLayout(PaymentPracticeLinesAggregator: Interface PaymentPracticeLinesAggregator)
    begin
        PaymentPracticeLinesAggregator.PrepareLayout();
    end;

    local procedure ShowHeaderDataLines()
    var
        PaymentPracticeData: Record "Payment Practice Data";
    begin
        PaymentPracticeData.SetRange("Header No.", Rec."No.");
        Page.RunModal(Page::"Payment Practice Data List", PaymentPracticeData);
    end;

    local procedure UpdateVisibility()
    begin
        IsDisputeRetention := Rec."Reporting Scheme" = Rec."Reporting Scheme"::"Dispute & Retention";
        IsSmallBusiness := Rec."Reporting Scheme" = Rec."Reporting Scheme"::"Small Business";
        CurrPage.Lines.Page.UpdateVisibility(Rec."Aggregation Type", Rec."Header Type", Rec."Reporting Scheme");
    end;
}
