# Security tools
name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number

trigger: none
pr: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily at midnight
  branches:
    include:
    - main
    - releases/*
    
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/heads/main

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: d365bc-agentpool-nonprod-1ESPT
    stages:
    - stage: ComponentGovernanceStage
      jobs:
      - job: ComponentGovernanceJob
        displayName: 'Component Governance'
        steps:
        - task: NuGetAuthenticate@1

        - powershell: |
            cd $(Build.SourcesDirectory);
            .\build.ps1 -ALGoProject 'System Application' -AutoFill    
          displayName: 'Build System Application'

        - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
          displayName: 'Component Detection'
          inputs:
            sourceScanPath: $(Agent.BuildDirectory)/s/Actions
            verbosity: 'Verbose'
