// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.ExpenseAgent;

codeunit 7128 "Create Expense Rule Headers"
{
    Access = Internal;
    InherentEntitlements = X;
    InherentPermissions = X;
    TableNo = "Expense Rule Header";

    trigger OnRun()
    begin
        InsertExpenseRuleHeaders(Rec);
    end;

    internal procedure InsertExpenseRuleHeaders(var ExpenseRuleHeader: Record "Expense Rule Header")
    begin
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetENTERTAINTxt(), '', 0D, Enum::"Expense Justification"::"Against Conditions", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetHOTELSTxt(), '', 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetMileageTxt(), '', 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetMoraleTxt(), '', 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.UnitedArabEmiratesAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AustriaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AustraliaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BelgiumAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BulgariaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BruneiDarussalamAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BrazilAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SwitzerlandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SwitzerlandGeneva(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SwitzerlandZurich(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ChinaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CostaRicaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CyprusAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CzechiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AlgeriaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.EstoniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GreeceAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SpainAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FinlandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FijiIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CroatiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.HungaryAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.IndonesiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.IrelandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.IndiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.IcelandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ItalyAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.JapanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.JapanTokyo(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.KenyaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LithuaniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LuxembourgAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LatviaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MoroccoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MontenegroAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MaltaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MexicoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MalaysiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MozambiqueAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NigeriaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NorthernIrelandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NetherlandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NorwayAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NorwayOslo(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NewZealandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PhilippinesAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PolandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PortugalAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.RomaniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SerbiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.RussiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaudiArabiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SolomonIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SwedenAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SingaporeAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SloveniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SlovakiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SwazilandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ThailandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TunisiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TurkiyeAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TanzaniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.UgandaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.VanuatuAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SamoaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SouthAfricaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AfghanistanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AlbaniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AndorraAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AngolaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AnguillaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AntarcticaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AntiguaBarbudaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ArgentinaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ArmeniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ArubaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AzerbaijanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BahamasAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BahrainAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BangladeshAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BarbadosAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BelarusAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BelizeAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BeninAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BermudaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BhutanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BoliviaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BonaireAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BosniaHerzegovinaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BotswanaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BouvetIslandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BritishIndianOceanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BurkinaFasoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.BurundiAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CaboVerdeAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CambodiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CameroonAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CaymanIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CentralAfricanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ChadAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ChileAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ChristmasIslandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CocosIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ColombiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ComorosAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CongoDRAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CongoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CookIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CubaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CuracaoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CotedIvoireAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.DjiboutiAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.DominicaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.DominicanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.EcuadorAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.EgyptAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ElSalvadorAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.EquatorialGuineaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.EritreaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.EthiopiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FalklandIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FaroeIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FrenchGuianaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FrenchPolynesiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FrenchSouthernAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GabonAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GambiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GeorgiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GhanaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GibraltarAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GreenlandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GrenadaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GuadeloupeAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GuamAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GuatemalaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GuernseyAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GuineaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GuineaBissauAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GuyanaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.HaitiAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.HeardIslandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.HolySeeAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.HondurasAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.HongKongAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.IsleManAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.IsraelAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.JamaicaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.JerseyAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.JordanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.KazakhstanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.KiribatiAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NorthKoreaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SouthKoreaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.KuwaitAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.KyrgyzstanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LaosAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LebanonAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LesothoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LiberiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LibyaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.LiechtensteinAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MacaoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MadagascarAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MalawiAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MaldivesAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MaliAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MarshallIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MartiniqueAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MauritaniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MauritiusAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MayotteAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MicronesiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MoldovaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MonacoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MongoliaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MontserratAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.MyanmarAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NamibiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NauruAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NepalAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NewCaledoniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NigerAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NiueAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NorfolkIslandAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NorthMacedoniaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.NorthernMarianaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.OmanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PakistanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PalauAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PalestineAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PanamaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PapuaNewGuineaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ParaguayAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PeruAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PitcairnAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.PuertoRicoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.QatarAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.RwandaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ReunionAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaintBarthelemyAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaintHelenaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaintKittsNevisAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaintLuciaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaintMartinAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaintPierreQuelonAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaintVincentAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SanMarinoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SaoTomeAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SenegalAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SeychellesAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SierraLeoneAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SintMaartenAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SomaliaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SouthGeorgiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SouthSudanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SriLankaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SudanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SurinameAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SvalbardJanMayenAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.SyriaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TaiwanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TajikistanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TimorLesteAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TogoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TokelauAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TongaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TrinidadTobagoAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TurkmenistanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TurksCalcosAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.TuvaluAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.UkraineAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.USMinorOutlyingAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.UruguayAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.UzbekistanAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.VenezuelAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.VietnamAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.VirginIslandsBrAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.VirginIslandsUSAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.WallisatunaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.WesternSaharaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.YemenAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ZambiaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.ZimbabweAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.AlandIslandsAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.CanadaAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.DenmarkAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.DenmarkCph(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.Domestic(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FranceAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.FranceParis(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.GermanyAll(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.UKLondon(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.USAFlorida(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.USANY(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
        InsertExpenseRuleHeader(ExpenseRuleHeader, CreateExpenseCategories.GetPERDIEMTxt(), CreateExpenseLocation.USAOther(), 0D, Enum::"Expense Justification"::" ", false, '', '', '');
    end;

    local procedure InsertExpenseRuleHeader(var ExpenseRuleHeader: Record "Expense Rule Header"; ExpenseCategoryCode: Code[20]; ExpenseLocationCode: Code[20]; EffectiveDate: Date; JustificationRequired: Enum "Expense Justification"; RequiredSpecificMerchant: Boolean; SpecificMerchantName: Text[100]; CurrencyCode: Code[10]; UnitOfMeasureCode: Code[10])
    var
        ExistingCategory: Record "Expense Category";
        IsHandled: Boolean;
    begin
        // prevent inserting invalid data
        if ExpenseCategoryCode <> '' then
            if ExistingCategory.Get(ExpenseCategoryCode) then
                if ExistingCategory."Expense Detail Required" <> ExistingCategory."Expense Detail Required"::"Per Diem" then
                    exit;

        CreateExpenseCategories.OnBeforeAddRuleSeed(ExpenseRuleHeader, ExpenseCategoryCode, ExpenseLocationCode, CurrencyCode, JustificationRequired, IsHandled);
        if IsHandled then
            exit;
        if ExpenseRuleHeader.Get(ExpenseCategoryCode, ExpenseLocationCode, EffectiveDate) then
            exit;
        ExpenseRuleHeader."Expense Category Code" := ExpenseCategoryCode;
        ExpenseRuleHeader."Expense Location" := ExpenseLocationCode;
        ExpenseRuleHeader."Effective Date" := EffectiveDate;
        ExpenseRuleHeader."Justification Required" := JustificationRequired;
        ExpenseRuleHeader."Required Specific Merchant" := RequiredSpecificMerchant;
        ExpenseRuleHeader."Specific Merchant Name" := SpecificMerchantName;
        ExpenseRuleHeader."Currency Code" := CurrencyCode;
        ExpenseRuleHeader."Unit of Measure Code" := UnitOfMeasureCode;
        ExpenseRuleHeader.Insert();
    end;

    var
        CreateExpenseCategories: Codeunit "Create Expense Categories";
        CreateExpenseLocation: Codeunit "Create Expense Locations";
}