// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.Manufacturing.Subcontracting;

permissionset 99001500 "Sub. Permissionset"
{
    Assignable = true;
    Caption = 'Subcontracting Permissionset', Locked = true;
    Permissions = table "Sub. Management Setup" = X,
        tabledata "Sub. Management Setup" = RIMD,
        table "Subcontractor Price" = X,
        tabledata "Subcontractor Price" = RIMD,
        codeunit "Single Instance Dictionary" = X,
        codeunit "Subc. Business Setup Ext." = X,
        codeunit "Subc. Calc. Prod. Order Ext." = X,
        codeunit "Sub. Calc.StandardCost Ext." = X,
        codeunit "Subc. Calc BOM Tree Ext." = X,
        codeunit "Subc. Calc Subcontracts Ext." = X,
        codeunit "Subc. Carry Out Action Ext." = X,
        codeunit "Sub. Create Prod. Ord. Opt." = X,
        codeunit "Subc. Create Prod. Rtng. Ext." = X,
        codeunit "Sub. CrPurchSubcon(Yes/No)" = X,
        codeunit "Subc. Date Calculation Mgt." = X,
        codeunit "Sub. DirectTransferLine Ext." = X,
        codeunit "Sub. Factbox Mgmt." = X,
        codeunit "Sub. ItemChargeAssPurchExt" = X,
        codeunit "Sub. Item Extension" = X,
        codeunit "Sub. ItemJnlCheckExt" = X,
        codeunit "Sub. ItemJnlPostLine Ext" = X,
        codeunit "Sub. Notification Mgmt." = X,
        codeunit "Subc. Planning Comp. Ext." = X,
        codeunit "Subc. Planning Line Mgmt Ext." = X,
        codeunit "Sub. Price Management" = X,
        codeunit "Subc. Prod. Order Comp. Ext." = X,
        codeunit "Subc. Prod. Order Rtng. Ext." = X,
        codeunit "Subc. Prod. Ord. Comp. Res." = X,
        codeunit "Sub. ProdOrderCreateBind" = X,
        codeunit "Sub. Purch. Post Ext" = X,
        codeunit "Sub. Purchase Header Ext" = X,
        codeunit "Sub. Purchase Line Ext" = X,
        codeunit "Sub. Reporting Triggers Ext" = X,
        codeunit "Sub. Req.Line Extension" = X,
        codeunit "Subc. Req. Wksh. Make Ord." = X,
        codeunit "Sub. SelectionFilterMgmt" = X,
        codeunit "Subcontracting Comp. Init." = X,
        codeunit "Subcontracting Management" = X,
        codeunit "Subcontracting Mgmt." = X,
        codeunit "Sub. Synchronize Management" = X,
        codeunit "Sub. Temp Data Initializer" = X,
        codeunit "Sub. TempProdOrdBind" = X,
        codeunit "Sub. Transfer Line Ext." = X,
        codeunit "Sub. TransferPost Ext" = X,
        codeunit "Sub. Transfer Rcpt Line Ext." = X,
        codeunit "Sub. Transfer Shpt Line Ext." = X,
        codeunit "Sub. TransOrderPostRcpt Ext" = X,
        codeunit "Sub. TransOrderPostShpt Ext" = X,
        codeunit "Sub. TransOrderPostTrans Ext" = X,
        codeunit "Sub. Trans Rcpt Header Ext" = X,
        codeunit "Sub. Trans Shpt Header Ext" = X,
        codeunit "Sub. Vendor Extension" = X,
        codeunit "Sub. Version Mgmt." = X,
        codeunit "Sub. Whse Direct Posting" = X,
        codeunit "Sub. WhsePostReceipt Ext" = X,
        codeunit "Sub. WhsePurchRelease Ext" = X,
        codeunit "Subc. Work Center Extension" = X,
        codeunit "Subcontracting Install" = X,
        page "Sub. Management Setup" = X,
        page "Sub. Prod. Order Components" = X,
        page "Sub. Purchase Line Factbox" = X,
        page "Sub. PurchProvisionWizard" = X,
        page "Sub. Routing Info Factbox" = X,
        page "Sub. Temp BOM Lines" = X,
        page "Sub. Temp Prod Order Comp" = X,
        page "Sub. TempProdOrdRtngLines" = X,
        page "Sub. Temp Routing Lines" = X,
        page "Sub. Transfer Line Factbox" = X,
        page "Subcontractor Prices" = X,
        report "Sub. Create Prod. Routing" = X,
        report "Sub. Create SubC.Transf. Order" = X,
        report "Sub. Create SubCReturnOrder" = X,
        report "Sub. Detailed Calculation" = X,
        report "Sub. Dispatching List" = X;
}