table 'Company Encoding'
	isHidden
	lineageTag: 9104d373-1d32-4da1-8038-0c54219dde4d

	column ParameterValue
		dataType: string
		isHidden
		lineageTag: d39a75fd-04cb-49c7-849e-29f3e129ee76
		summarizeBy: none
		sourceColumn: ParameterValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Encoded Company Name'
		dataType: string
		isHidden
		lineageTag: d8f09e29-5dbd-45b0-9345-0a2fcadae11e
		summarizeBy: none
		sourceColumn: Encoded Company Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Company Encoding' = m
		mode: import
		source =
				let
				    Source = #table(
				        {"ParameterValue"},
				        {{COMPANY}}
				    ),
				    #"Added Encoded Column" = Table.AddColumn(Source, "Encoded Company Name", each Uri.EscapeDataString(COMPANY), type text)
				in
				    #"Added Encoded Column"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

