table 'Date Table Setup'
	isHidden
	lineageTag: 37ac1c95-4d8e-4cd2-b4b0-8da6a570a732

	measure 'Last Refresh Label' = ```
			
			VAR LastRefreshLabel = [Last Refreshed Label] & ": "
			
			VAR LastRefreshDate =
			    FORMAT (
			        VALUES ( 'Date Table Setup'[Today] ),
			        BLANK(),
			        USERCULTURE ()
			    )
			VAR LastRefreshTime =
			    FORMAT (
			        VALUES ( 'Date Table Setup'[Last Refresh Time] ),
			        "hh:nn AMPM",
			        USERCULTURE ()
			    )
			VAR CompanyName = [Company Name Label] & ": "
			
			RETURN
			    CompanyName & COMPANY[Company Label] & " - " & LastRefreshLabel & LastRefreshDate & " " & LastRefreshTime 
			
			```
		isHidden
		lineageTag: e7b1a511-0434-4a1f-9f89-bad75c47c214

		changedProperty = IsHidden

	column fiscalCalendarFirstMonth
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b490bce1-f1e3-4231-b975-4d0813e4e3f2
		summarizeBy: sum
		sourceColumn: fiscalCalendarFirstMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column firstDayOfWeek
		dataType: string
		isHidden
		lineageTag: 588f8b2a-9328-4c58-89f6-1a01a73366e0
		summarizeBy: none
		sourceColumn: firstDayOfWeek

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column isoCountryHolidays
		dataType: string
		isHidden
		lineageTag: 8c33920a-27ba-483a-9190-2883d4e105c5
		summarizeBy: none
		sourceColumn: isoCountryHolidays

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column weeklyType
		dataType: string
		isHidden
		lineageTag: 900e20e9-95cb-4c29-8bf4-1142233d23a1
		summarizeBy: none
		sourceColumn: weeklyType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quarterWeekType
		dataType: string
		isHidden
		lineageTag: 93bf3ea3-1d37-4614-8f33-3b5711169bbf
		summarizeBy: none
		sourceColumn: quarterWeekType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column calendarRange
		dataType: string
		isHidden
		lineageTag: 157bfbb1-0fb3-4236-8f71-d3d6f49f87e3
		summarizeBy: none
		sourceColumn: calendarRange

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column calendarPrefix
		dataType: string
		isHidden
		lineageTag: 0208fce2-9d78-45d2-bf37-b7c23d6093db
		summarizeBy: none
		sourceColumn: calendarPrefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fiscalGregorianPrefix
		dataType: string
		isHidden
		lineageTag: a1d48796-cecc-42ea-9d96-7b4e5242d94a
		summarizeBy: none
		sourceColumn: fiscalGregorianPrefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fiscalWeeklyPrefix
		dataType: string
		isHidden
		lineageTag: 99b19bda-9593-46b9-937b-1f2cfacce5ef
		summarizeBy: none
		sourceColumn: fiscalWeeklyPrefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column useCustomFisclPeriods
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8b6a81e7-2ffe-4cd2-9897-7c63256915c4
		summarizeBy: none
		sourceColumn: useCustomFisclPeriods

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ignoreWeeklyPeriods
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0c8190cd-ac5b-4797-b43d-97daf9a25b78
		summarizeBy: none
		sourceColumn: ignoreWeeklyPeriods

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dateTblStart
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: fdbd3648-dfd2-4cab-80b3-1d06bef05483
		summarizeBy: none
		sourceColumn: dateTblStart

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dateTblEnd
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: ce90c10f-0b81-4ce8-a178-046e8bbc52a5
		summarizeBy: none
		sourceColumn: dateTblEnd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'First Day of Week'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c1b3b87d-281a-4581-aac0-d249d4dac123
		summarizeBy: sum
		sourceColumn: First Day of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Today
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 837d4b28-ce15-48b7-9234-7a9fa3e09e90
		summarizeBy: none
		sourceColumn: Today

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column timeZone
		dataType: string
		isHidden
		lineageTag: 765f8424-368a-4b97-884c-86649ea746b4
		summarizeBy: none
		sourceColumn: timeZone

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column timeZoneDisplayName
		dataType: string
		isHidden
		lineageTag: 8bbaa57b-59e4-4595-beae-8dac2a656435
		summarizeBy: none
		sourceColumn: timeZoneDisplayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entryNo
		dataType: string
		isHidden
		lineageTag: 98e1c20e-0014-4ee6-a8ee-27d746b85c31
		summarizeBy: none
		sourceColumn: entryNo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		isHidden
		lineageTag: bf057e75-a7be-4401-a7b6-6630b54be27f
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh Time'
		dataType: dateTime
		isHidden
		formatString: Long Time
		lineageTag: 103976c8-8c8e-4b35-ad30-274b0b6b9d69
		summarizeBy: none
		sourceColumn: Last Refresh Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column tenantID
		dataType: string
		lineageTag: 9f524090-2113-45a8-83e7-8a1af9dfbd04
		summarizeBy: none
		sourceColumn: tenantID

		annotation SummarizationSetBy = Automatic

	column 'UTC Hours'
		dataType: int64
		formatString: 0
		lineageTag: 757c29eb-0a9e-42bd-aa55-bce0d3904a41
		summarizeBy: sum
		sourceColumn: UTC Hours

		annotation SummarizationSetBy = Automatic

	column 'UTC Minutes'
		dataType: int64
		formatString: 0
		lineageTag: eb9c78c6-6e92-4cdd-b85e-e16a39f45b92
		summarizeBy: sum
		sourceColumn: UTC Minutes

		annotation SummarizationSetBy = Automatic

	partition 'Date Table Setup' = m
		mode: import
		queryGroup: 'Date Tables'
		source =
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY, API_ENDPOINT, []),
				    TableData = Source{[Name = "dateSetups", Signature = "table"]}[Data],
				    CheckTenantIDColumnExists = if Table.HasColumns(TableData, "tenantID") then TableData else Table.AddColumn(TableData, "tenantID", each null, type text),
				    #"Convert UTC to Local" = ConvertUTC(CheckTenantIDColumnExists),
				    #"Removed Columns" = Table.RemoveColumns(#"Convert UTC to Local", {"ETag"}),
				    #"Added Conditional Column" = Table.AddColumn(
				        #"Removed Columns",
				        "First Day of Week",
				        each
				            if [firstDayOfWeek] = "Sunday" then
				                0
				            else if [firstDayOfWeek] = "Monday" then
				                1
				            else if [firstDayOfWeek] = "Tuesday" then
				                2
				            else if [firstDayOfWeek] = "Wednesday" then
				                3
				            else if [firstDayOfWeek] = "Thursday" then
				                4
				            else if [firstDayOfWeek] = "Friday" then
				                5
				            else if [firstDayOfWeek] = "Saturday" then
				                6
				            else
				                1
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column", {{"First Day of Week", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(
				        #"Changed Type",
				        each [calendarRange],
				        each
				            if [calendarRange] = "Weekly" then
				                "FiscalWeekly"
				            else if [calendarRange] = "Fiscal Calendar" then
				                "FiscalGregorian"
				            else
				                "Calendar",
				        Replacer.ReplaceText,
				        {"calendarRange"}
				    ),
				    #"Replaced Value1" = Table.ReplaceValue(
				        #"Replaced Value", "", "F", Replacer.ReplaceValue, {"fiscalGregorianPrefix"}
				    ),
				    #"Replaced Value2" = Table.ReplaceValue(
				        #"Replaced Value1", "", "FW", Replacer.ReplaceValue, {"fiscalWeeklyPrefix"}
				    ),
				    #"Changed Type3" = Table.TransformColumnTypes(
				        #"Replaced Value2",
				        {
				            {"fiscalCalendarFirstMonth", Int64.Type},
				            {"firstDayOfWeek", type text},
				            {"isoCountryHolidays", type text},
				            {"weeklyType", type text},
				            {"quarterWeekType", type text},
				            {"calendarRange", type text},
				            {"calendarPrefix", type text},
				            {"fiscalGregorianPrefix", type text},
				            {"fiscalWeeklyPrefix", type text},
				            {"useCustomFisclPeriods", type logical},
				            {"ignoreWeeklyPeriods", type logical},
				            {"timeZone", type text},
				            {"timeZoneDisplayName", type text},
				            {"dateTblStart", type date},
				            {"dateTblEnd", type date}
				        }
				    )
				in
				    #"Changed Type3"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

