table 'Working Days'
	isHidden
	lineageTag: 79c87eda-aae2-46cf-b742-1dc760cf1681

	column FSG_PBI_Day_Number
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f1862b55-590d-4afb-b757-0fb76cdfab33
		summarizeBy: sum
		sourceColumn: FSG_PBI_Day_Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: 13edca2c-1c75-4aa3-81d5-a818d65faf50
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	partition 'Working Days' = m
		mode: import
		queryGroup: 'Date Tables'
		source =
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY,API_ENDPOINT, []),
				    TableData = Source{[Name="workingDays",Signature="table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(TableData,{"ETag"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"dayNumber", "FSG_PBI_Day_Number"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"FSG_PBI_Day_Number", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

