table 'Back Links'
	isHidden
	lineageTag: 3e1e429b-5a8a-4753-81a6-7104a1063929

	measure 'Base Link' =
			
			VAR BusinessCentral = "https://businesscentral.dynamics.com/"
			VAR TenantID = VALUES('Date Table Setup'[tenantID])
			VAR Environment = VALUES(ENVIRONMENT[ENVIRONMENT])
			VAR Company = "?company=" & VALUES('Company Encoding'[Encoded Company Name])
			RETURN BusinessCentral & TenantID & "/" & Environment & "/" & Company
		isHidden
		lineageTag: d4610d12-08d0-4e03-93f0-369ded9c2630

		changedProperty = IsHidden

	measure 'Calendar Entries Back Link' = ```
			
			VAR Endpoint = "&page=99000759&"
			VAR baseLink = [Base Link] & Endpoint
			
			// Build filter context(transformed low-cardinality values only )
			VAR CapacityTypePrep =
			    CONCATENATEX(VALUES ( 'Calendar Entries'[Capacity Type] ), 'Calendar Entries'[Capacity Type], "|" )
			VAR CapacityType = 
			    SUBSTITUTE(SUBSTITUTE(CapacityTypePrep, "Work Center", "0"), "Machine Center","1")
			
			VAR SelectedDates = VALUES ( 'Date'[Date] )
			VAR DateRangeStarts =
			    FILTER (
			        SelectedDates,
			        VAR CurrentDate = 'Date'[Date]
			        RETURN COUNTROWS ( FILTER ( SelectedDates, 'Date'[Date] = CurrentDate - 1 ) ) = 0
			    )
			// Conservative estimate: 23 chars ("yyyy-mm-dd..yyyy-mm-dd" + separator) per consecutive date run
			VAR ProjectedRangedLength = COUNTROWS ( DateRangeStarts ) * 23

			// Project the URL length from the raw filter values without building the (possibly huge) URL string
			VAR ProjectedLength =
			    LEN ( baseLink )
			    + LEN ( "filter='Calendar Entry'.'Capacity Type' IS ''" ) + LEN ( CapacityType )
			    + LEN ( " AND 'Calendar Entry'.'No.' IS " )
			    + SUMX ( VALUES ( 'Calendar Entries'[No.] ), LEN ( 'Calendar Entries'[No.] ) + 1 )
			    + LEN ( " AND 'Calendar Entry'.'Date' IS " ) + ProjectedRangedLength
			RETURN
			    // Fall back to the unfiltered page if the URL exceeds the 2000 character limit
			    IF (
			        ProjectedLength <= 2000,
			        baseLink
			            & "filter='Calendar Entry'.'Capacity Type' IS " & "'" & CapacityType & "'"
			            & " AND 'Calendar Entry'.'No.' IS " & CONCATENATEX(VALUES ( 'Calendar Entries'[No.] ), 'Calendar Entries'[No.], "|" )
			            & " AND 'Calendar Entry'.'Date' IS " & [Ranged],
			    baseLink
			    )
			```
		isHidden
		lineageTag: 08219a66-0acd-42a9-8e13-5380f953c9a2

		changedProperty = IsHidden

	measure Ranged = ```
			
			VAR _FilterTable = VALUES('Date'[Date])
			VAR IndexedDates = 
			    ADDCOLUMNS(
			        _FilterTable,
			        "@Index", RANKX(
			            SUMMARIZECOLUMNS(
			                'Date'[Date], _FilterTable
			            ),
			            'Date'[Date],
			            ,
			            ASC,
			            DENSE
			        )
			    )
			VAR PreviousIndexedDate = 
				ADDCOLUMNS(
					IndexedDates,
					"@Previous Date", 
						VAR PrevIndex = [@Index] - 1
						RETURN SELECTCOLUMNS(
							FILTER(IndexedDates, [@Index] = PrevIndex),
							[Date])
				)
			
			VAR CalculateBreakPoint = 
				ADDCOLUMNS(
					PreviousIndexedDate,
					"@Break Point", 
					IF( NOT DATEDIFF([@Previous Date],'Date'[Date],DAY) = 1, TRUE(), FALSE() )
				)
			VAR BreakPointTable = FILTER(CalculateBreakPoint, [@Break Point] = TRUE())
			
			VAR MaxDate = CALCULATE(MAX('Date'[Date]),_FilterTable)
			
			var NextIndex = 
				ADDCOLUMNS(
					BreakPointTable,
					"@NextIndex", 
					SELECTCOLUMNS(
						OFFSET( +1, BreakPointTable ),
						[@Index]
					) - 1
				)
			
			VAR NextDate = 
				ADDCOLUMNS(
					NextIndex,
					"@NextDate", 
						VAR PrevIndex = [@Index] - 1
						RETURN SELECTCOLUMNS(
							FILTER(IndexedDates, [@Index] = [@NextIndex]),
							[Date])
				)
			
			VAR Ranged = 
			ADDCOLUMNS(
				NextDate,
				"@Range",
				IF( ISBLANK([@NextDate]), 
				FORMAT ( 'Date'[Date], "yyyy-mm-dd" ) & ".." & FORMAT ( MaxDate ,"yyyy-mm-dd"),
				FORMAT ( 'Date'[Date], "yyyy-mm-dd" ) & ".." & FORMAT ( [@NextDate] ,"yyyy-mm-dd")
				)
			)
			
			Return CONCATENATEX(Ranged, [@Range], "|")
			```
		isHidden
		lineageTag: 7764e004-d0c4-4ea9-ae7c-0fd5c4f23610

		changedProperty = IsHidden

	measure 'Prod. Order Capacity Need Back Link' = ```
			
			VAR Endpoint = "&page=99000820&"
			VAR baseLink = [Base Link] & Endpoint
			
			// Build filter context(transformed low-cardinality values only )
			
			VAR RequestedOnlyInput = 
			    CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[Requested Only] ), 'Prod Order Capacity Need'[Requested Only], "|" )
			VAR RequestedOnly = 
			    SUBSTITUTE(SUBSTITUTE(RequestedOnlyInput, "FALSE", "0"), "TRUE","1")
			
			VAR SelectedDates = VALUES ( 'Date'[Date] )
			VAR DateRangeStarts =
			    FILTER (
			        SelectedDates,
			        VAR CurrentDate = 'Date'[Date]
			        RETURN COUNTROWS ( FILTER ( SelectedDates, 'Date'[Date] = CurrentDate - 1 ) ) = 0
			    )
			// Conservative estimate: 23 chars ("yyyy-mm-dd..yyyy-mm-dd" + separator) per consecutive date run
			VAR ProjectedRangedLength = COUNTROWS ( DateRangeStarts ) * 23

			// Project the URL length from the raw filter values without building the (possibly huge) URL string
			VAR ProjectedLength =
			    LEN ( baseLink )
			    + LEN ( "filter='Prod. Order Capacity Need'.'Work Center No.' IS ''" )
			    + SUMX ( VALUES ( 'Prod Order Capacity Need'[workCenterNo] ), LEN ( 'Prod Order Capacity Need'[workCenterNo] ) + 1 )
			    + LEN ( " AND 'Prod. Order Capacity Need'.'No.' IS ''" )
			    + SUMX ( VALUES ( 'Prod Order Capacity Need'[no] ), LEN ( 'Prod Order Capacity Need'[no] ) + 1 )
			    + LEN ( " AND 'Prod. Order Capacity Need'.'Type' IS ''" )
			    + SUMX ( VALUES ( 'Prod Order Capacity Need'[Type] ), LEN ( 'Prod Order Capacity Need'[Type] ) + 1 )
			    + LEN ( " AND 'Prod. Order Capacity Need'.'Date' IS " ) + ProjectedRangedLength
			    + LEN ( " AND 'Prod. Order Capacity Need'.'Prod. Order No.' IS ''" )
			    + SUMX ( VALUES ( 'Prod Order Capacity Need'[Prod. Order No.] ), LEN ( 'Prod Order Capacity Need'[Prod. Order No.] ) + 1 )
			    + LEN ( " AND 'Prod. Order Capacity Need'.'Status' IS ''" )
			    + SUMX ( VALUES ( 'Production Orders'[Prod Order Status] ), LEN ( 'Production Orders'[Prod Order Status] ) + 1 )
			    + LEN ( " AND 'Prod. Order Capacity Need'.'Requested Only' IS ''" ) + LEN ( RequestedOnly )
			RETURN
			    // Fall back to the unfiltered page if the URL exceeds the 2000 character limit
			    IF (
			        ProjectedLength <= 2000,
			        baseLink
			            & "filter='Prod. Order Capacity Need'.'Work Center No.' IS " & "'" & CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[workCenterNo] ), 'Prod Order Capacity Need'[workCenterNo], "|" ) & "'"
			            & " AND 'Prod. Order Capacity Need'.'No.' IS " & "'" & CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[no] ), 'Prod Order Capacity Need'[no], "|" ) & "'"
			            & " AND 'Prod. Order Capacity Need'.'Type' IS " & "'" & CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[Type] ), 'Prod Order Capacity Need'[Type], "|" ) & "'"
			            & " AND 'Prod. Order Capacity Need'.'Date' IS " & [Ranged]
			            & " AND 'Prod. Order Capacity Need'.'Prod. Order No.' IS " & "'" & CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[Prod. Order No.] ), 'Prod Order Capacity Need'[Prod. Order No.], "|" )  & "'"
			            & " AND 'Prod. Order Capacity Need'.'Status' IS " & "'" & CONCATENATEX(VALUES( 'Production Orders'[Prod Order Status]),  'Production Orders'[Prod Order Status], "|" ) & "'" &  " AND 'Prod. Order Capacity Need'.'Requested Only' IS " & "'" & RequestedOnly & "'",
			    baseLink
			    )
			```
		isHidden
		lineageTag: ebbde43d-0b1a-4736-8c3c-71e9a3180437

		changedProperty = IsHidden

	measure 'Work Center Need Qty Back Link' = ```
			
			VAR Endpoint = "&page=99000820&"
			VAR baseLink = [Base Link] & Endpoint
			
			VAR SelectedDates = VALUES ( 'Date'[Date] )
			VAR DateRangeStarts =
			    FILTER (
			        SelectedDates,
			        VAR CurrentDate = 'Date'[Date]
			        RETURN COUNTROWS ( FILTER ( SelectedDates, 'Date'[Date] = CurrentDate - 1 ) ) = 0
			    )
			// Conservative estimate: 23 chars ("yyyy-mm-dd..yyyy-mm-dd" + separator) per consecutive date run
			VAR ProjectedRangedLength = COUNTROWS ( DateRangeStarts ) * 23

			// Project the URL length from the raw filter values without building the (possibly huge) URL string
			VAR ProjectedLength =
			    LEN ( baseLink )
			    + LEN ( "filter='Prod. Order Capacity Need'.'Work Center No.' IS ''" )
			    + SUMX ( VALUES ( 'Prod Order Capacity Need'[workCenterNo] ), LEN ( 'Prod Order Capacity Need'[workCenterNo] ) + 1 )
			    + LEN ( " AND 'Prod. Order Capacity Need'.'No.' IS ''" )
			    + SUMX ( VALUES ( 'Prod Order Capacity Need'[no] ), LEN ( 'Prod Order Capacity Need'[no] ) + 1 )
			    + LEN ( " AND 'Prod. Order Capacity Need'.'Type' IS ''" )
			    + SUMX ( VALUES ( 'Prod Order Capacity Need'[Type] ), LEN ( 'Prod Order Capacity Need'[Type] ) + 1 )
			    + LEN ( " AND 'Prod. Order Capacity Need'.'Date' IS " ) + ProjectedRangedLength
			    + LEN ( " AND 'Prod. Order Capacity Need'.'Requested Only' IS 'No'" )
			RETURN
			    // Fall back to the unfiltered page if the URL exceeds the 2000 character limit
			    IF (
			        ProjectedLength <= 2000,
			        baseLink
			            & "filter='Prod. Order Capacity Need'.'Work Center No.' IS " & "'" &
			    CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[workCenterNo] ), 'Prod Order Capacity Need'[workCenterNo], "|" ) & "'"
			            & " AND 'Prod. Order Capacity Need'.'No.' IS " & "'" & 
			    CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[no] ), 'Prod Order Capacity Need'[no], "|" ) & "'"
			            & " AND 'Prod. Order Capacity Need'.'Type' IS " & "'" & 
			    CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[Type] ), 'Prod Order Capacity Need'[Type], "|" ) & "'" & " AND 'Prod. Order Capacity Need'.'Date' IS " & [Ranged]
			            &  " AND 'Prod. Order Capacity Need'.'Requested Only' IS 'No'",
			    baseLink
			    )
			```
		isHidden
		lineageTag: 260ab712-b2d0-481a-b1d1-9ddf9ed984a1

		changedProperty = IsHidden

	measure 'Capacity Ledger Entries Back Link' = ```
			
			VAR Endpoint = "&page=5832&"
			VAR baseLink = [Base Link] & Endpoint
			
			// Project the URL length from the raw filter values without building the (possibly huge) URL string
			VAR ProjectedLength =
			    LEN ( baseLink )
			    + LEN ( "filter='Capacity Ledger Entry'.'Order No.' IS ''" )
			    + SUMX ( VALUES ( 'Prod Order Capacity Need'[Prod. Order No.] ), LEN ( 'Prod Order Capacity Need'[Prod. Order No.] ) + 1 )
			RETURN
			    // Fall back to the unfiltered page if the URL exceeds the 2000 character limit
			    IF (
			        ProjectedLength <= 2000,
			        baseLink
			            & "filter='Capacity Ledger Entry'.'Order No.' IS " & "'" & 
			    CONCATENATEX(VALUES ( 'Prod Order Capacity Need'[Prod. Order No.] ), 'Prod Order Capacity Need'[Prod. Order No.], "|" ) & "'",
			    baseLink
			    )
			```
		isHidden
		lineageTag: 5b769c7e-3d21-40ae-922e-ffbc42a4bc3a

		changedProperty = IsHidden

	column Column1
		dataType: string
		isHidden
		lineageTag: 87207e88-c30e-4ed7-8a04-50591e53b160
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Back Links' = m
		mode: import
		queryGroup: 'Parameters and Functions'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

