table 'Company Encoding'
	isHidden
	lineageTag: 595fb95c-0edb-4fa6-9999-90c4cc77fb92

	column ParameterValue
		dataType: string
		isHidden
		lineageTag: 0b87d89b-497d-4684-90c3-bce538e6c6b7
		summarizeBy: none
		sourceColumn: ParameterValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Encoded Company Name'
		dataType: string
		isHidden
		lineageTag: 1e269faf-2b83-41db-b3fa-65bb44931871
		summarizeBy: none
		sourceColumn: Encoded Company Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Company Encoding' = m
		mode: import
		source =
				let
				    Source = #table(
				        {"ParameterValue"},
				        {{COMPANY}}
				    ),
				    #"Added Encoded Column" = Table.AddColumn(Source, "Encoded Company Name", each Uri.EscapeDataString(COMPANY), type text)
				in
				    #"Added Encoded Column"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

