table Item
	lineageTag: 15e037bf-2c91-4a8e-8264-65fb7172d679

	column 'Item No. & Description'
		dataType: string
		lineageTag: 7f576aa0-bece-4d63-a336-8865d2a88e79
		summarizeBy: none
		sourceColumn: Item No. & Description

		annotation SummarizationSetBy = Automatic

	column 'Item No.'
		dataType: string
		isKey
		lineageTag: 43269098-0a62-455b-a4ea-96aac55ce085
		summarizeBy: none
		sourceColumn: Item No.

		annotation SummarizationSetBy = Automatic

	column 'Item Description'
		dataType: string
		lineageTag: d7164614-9624-4262-ad0b-2dbaf3c99005
		summarizeBy: none
		sourceColumn: Item Description

		annotation SummarizationSetBy = Automatic

	column 'Item Unit Cost (LCY)'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 19e28380-9aba-4ce5-8448-b5560e460e66
		summarizeBy: none
		sourceColumn: Item Unit Cost (LCY)

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-AU"}

	column 'Item Inventory Posting Group'
		dataType: string
		lineageTag: 83eb9ecb-bcfe-41b2-8a32-0b64163b5471
		summarizeBy: none
		sourceColumn: Item Inventory Posting Group

		annotation SummarizationSetBy = Automatic

	column 'Item Category Code'
		dataType: string
		isHidden
		lineageTag: 6652c1de-8cf4-4cc7-a03a-3c521679f12d
		summarizeBy: none
		sourceColumn: Item Category Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Category Description'
		dataType: string
		isHidden
		lineageTag: 3b9d016b-cf47-4ad2-8869-b76494c77b7f
		summarizeBy: none
		sourceColumn: Item Category Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Routing No.'
		dataType: string
		lineageTag: 6b483bfb-c114-485d-8cec-32a325bae6d1
		summarizeBy: none
		sourceColumn: Item Routing No.

		annotation SummarizationSetBy = Automatic

	column 'Item Production BOM No.'
		dataType: string
		lineageTag: a2a14486-e561-4d10-b027-7ee674a2b353
		summarizeBy: none
		sourceColumn: Item Production BOM No.

		annotation SummarizationSetBy = Automatic

	column 'Item Replenishment System'
		dataType: string
		lineageTag: e3140e91-9c48-4cde-8941-46ca9bc592f1
		summarizeBy: none
		sourceColumn: Item Replenishment System

		annotation SummarizationSetBy = Automatic

	column 'Item Single-Level Cap. Ovhd Cost'
		dataType: double
		lineageTag: 1bb5857d-4b8c-405a-9c72-58d7f4d060c2
		summarizeBy: none
		sourceColumn: Item Single-Level Cap. Ovhd Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Capacity Cost'
		dataType: double
		lineageTag: 6b914bcc-0173-4986-becd-da687f6f4bb4
		summarizeBy: none
		sourceColumn: Item Single-Level Capacity Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Material Cost'
		dataType: double
		lineageTag: daee483a-6074-4523-848c-6e14cfff7306
		summarizeBy: none
		sourceColumn: Item Single-Level Material Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Mfg. Ovhd Cost'
		dataType: double
		lineageTag: 8612df39-dee5-4000-9f6c-65c2415d4ad0
		summarizeBy: none
		sourceColumn: Item Single-Level Mfg. Ovhd Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Subcontrd. Cost'
		dataType: double
		lineageTag: baabb4a4-e472-423f-b425-e2071d820e3f
		summarizeBy: none
		sourceColumn: Item Single-Level Subcontrd. Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Base Unit of Measure'
		dataType: string
		lineageTag: e9d3bcef-d5df-49c5-9309-1c70ff9456b5
		summarizeBy: none
		sourceColumn: Item Base Unit of Measure

		annotation SummarizationSetBy = Automatic

	column 'Item Rolled-up Cap. Overhead Cost'
		dataType: double
		lineageTag: e63a3315-91ef-4add-aeac-26c66290e1f7
		summarizeBy: sum
		sourceColumn: Item Rolled-up Cap. Overhead Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Capacity Cost'
		dataType: double
		lineageTag: e0976f28-f9c1-4b02-a6c7-567a444c7b7f
		summarizeBy: sum
		sourceColumn: Item Rolled-up Capacity Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Material Cost'
		dataType: double
		lineageTag: ad2edf87-2410-4eac-b373-c9fc426085f9
		summarizeBy: sum
		sourceColumn: Item Rolled-up Material Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mfg. Ovhd Cost'
		dataType: double
		lineageTag: a16048b7-296f-4781-88e1-50efcedaf77b
		summarizeBy: sum
		sourceColumn: Item Rolled-up Mfg. Ovhd Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Subcontracted Cost'
		dataType: double
		lineageTag: fd5249a2-7f63-432f-b86e-1153ad735033
		summarizeBy: sum
		sourceColumn: Item Rolled-up Subcontracted Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Scrap %'
		dataType: double
		lineageTag: 08d4fc8b-8cc2-4090-802c-f6dedc0fe048
		summarizeBy: sum
		sourceColumn: Item Scrap %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Lvl Mat. Non-Invt. Cost'
		dataType: double
		lineageTag: 6527fd8e-a8c1-48f5-999c-119904a5075d
		summarizeBy: sum
		sourceColumn: Item Single-Lvl Mat. Non-Invt. Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mat. Non-Invt. Cost'
		dataType: double
		lineageTag: dd15c431-5d41-4589-a0d6-4106c4c2c57b
		summarizeBy: sum
		sourceColumn: Item Rolled-up Mat. Non-Invt. Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Item-239072cc-c802-4b3e-8de9-e5402e6d7b52 = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY, API_ENDPOINT, []),
				    TableData = Source{[Name = "items", Signature = "table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(
				        TableData,
				        {
				            {"itemNo", "Item No."},
				            {"unitCost", "Item Unit Cost (LCY)"},
				            {"itemCategoryCode", "Item Category Code"},
				            {"itemCategoryDescription", "Item Category Description"},
				            {"baseUnitofMeasure", "Item Base Unit of Measure"},
				            {"itemDescription", "Item Description"},
				            {"inventoryPostingGroup", "Item Inventory Posting Group"},
				            {"routingNo", "Item Routing No."},
				            {"productionBomNo", "Item Production BOM No."},
				            {"replenishmentSystem", "Item Replenishment System"},
				            {"singleLevelCapOvhdCost", "Item Single-Level Cap. Ovhd Cost"},
				            {"singleLevelCapacityCost", "Item Single-Level Capacity Cost"},
				            {"singleLevelMaterialCost", "Item Single-Level Material Cost"},
				            {"singleLevelMfgOvhdCost", "Item Single-Level Mfg. Ovhd Cost"},
				            {"singleLevelSubcontrdCost", "Item Single-Level Subcontrd. Cost"},
				            {"singleLvlMatNonInvtCost", "Item Single-Lvl Mat. Non-Invt. Cost"},
				            {"rolledUpCapacityCost", "Item Rolled-up Capacity Cost"},
				            {"rolledUpCapOverheadCost", "Item Rolled-up Cap. Overhead Cost"},
				            {"rolledUpMatNonInvtCost", "Item Rolled-up Mat. Non-Invt. Cost"},
				            {"rolledUpMaterialCost", "Item Rolled-up Material Cost"},
				            {"rolledUpMfgOvhdCost", "Item Rolled-up Mfg. Ovhd Cost"},
				            {"rolledUpSubcontractedCost", "Item Rolled-up Subcontracted Cost"},
				            {"scrapPrc", "Item Scrap %"}
				        }
				    ),
				    #"Added Custom" = Table.AddColumn(
				        #"Renamed Columns", "Item No. & Description", each [#"Item No."] & " " & [Item Description], type text
				    ),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom", {"ETag"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns", {{"Item Unit Cost (LCY)", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

