table 'Dimension Sets'
	lineageTag: e3e30143-4bf4-463c-8fd1-5eeb9f47fc01

	column dimensionSetID
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: cf9779e0-d471-45cc-9bf4-c9c8db7ad6e6
		summarizeBy: none
		sourceColumn: dimensionSetID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column valueCount
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2300acf4-3cf8-4563-9400-9cead37ed3af
		summarizeBy: none
		sourceColumn: valueCount

		annotation SummarizationSetBy = Automatic

	column 'Global Dimension 1'
		dataType: string
		lineageTag: d853332b-5fe5-41dd-84f3-9ddfc3ad4fc7
		summarizeBy: none
		sourceColumn: Global Dimension 1

		annotation SummarizationSetBy = Automatic

	column dimension1ValueName
		dataType: string
		isHidden
		lineageTag: df8dc870-a2a4-4987-915a-a52721abfd20
		summarizeBy: none
		sourceColumn: dimension1ValueName

		annotation SummarizationSetBy = Automatic

	column 'Global Dimension 2'
		dataType: string
		lineageTag: c3535d52-c3d9-460d-8d6f-e53affeb9259
		summarizeBy: none
		sourceColumn: Global Dimension 2

		annotation SummarizationSetBy = Automatic

	column dimension2ValueName
		dataType: string
		isHidden
		lineageTag: 7b259dc2-a325-481b-8ac6-2d2a4ef56215
		summarizeBy: none
		sourceColumn: dimension2ValueName

		annotation SummarizationSetBy = Automatic

	column 'Shortcut Dimension 3'
		dataType: string
		lineageTag: 244f6e8c-35d2-4116-8be7-0a9a29c95f18
		summarizeBy: none
		sourceColumn: Shortcut Dimension 3

		annotation SummarizationSetBy = Automatic

	column dimension3ValueName
		dataType: string
		isHidden
		lineageTag: 37898913-55ce-469e-8542-52121d0f4cf3
		summarizeBy: none
		sourceColumn: dimension3ValueName

		annotation SummarizationSetBy = Automatic

	column 'Shortcut Dimension 4'
		dataType: string
		lineageTag: d3443ed4-2249-4b3e-8065-27ed2716c743
		summarizeBy: none
		sourceColumn: Shortcut Dimension 4

		annotation SummarizationSetBy = Automatic

	column dimension4ValueName
		dataType: string
		isHidden
		lineageTag: 3f16c2b4-1d7b-42e4-8f9f-8c960decbc44
		summarizeBy: none
		sourceColumn: dimension4ValueName

		annotation SummarizationSetBy = Automatic

	column 'Shortcut Dimension 5'
		dataType: string
		lineageTag: f42370f7-f2db-4b94-ab79-81148076e4b5
		summarizeBy: none
		sourceColumn: Shortcut Dimension 5

		annotation SummarizationSetBy = Automatic

	column dimension5ValueName
		dataType: string
		isHidden
		lineageTag: 911ef1b4-3a59-45f0-97a2-ca837b662ae8
		summarizeBy: none
		sourceColumn: dimension5ValueName

		annotation SummarizationSetBy = Automatic

	column 'Shortcut Dimension 6'
		dataType: string
		lineageTag: bbe89889-fd63-4f3b-b6c3-c3d16d544a9d
		summarizeBy: none
		sourceColumn: Shortcut Dimension 6

		annotation SummarizationSetBy = Automatic

	column dimension6ValueName
		dataType: string
		isHidden
		lineageTag: 0017e2c2-200e-47a6-a2e0-19a26affb385
		summarizeBy: none
		sourceColumn: dimension6ValueName

		annotation SummarizationSetBy = Automatic

	column 'Shortcut Dimension 7'
		dataType: string
		lineageTag: 404d9552-4bba-4a8d-a437-5a48204a1e3d
		summarizeBy: none
		sourceColumn: Shortcut Dimension 7

		annotation SummarizationSetBy = Automatic

	column dimension7ValueName
		dataType: string
		isHidden
		lineageTag: 222f8a3d-1c50-4751-a6b7-da71e6eeda4d
		summarizeBy: none
		sourceColumn: dimension7ValueName

		annotation SummarizationSetBy = Automatic

	column 'Shortcut Dimension 8'
		dataType: string
		lineageTag: 34627f19-5b26-44da-8c1c-c08828ecf4e2
		summarizeBy: none
		sourceColumn: Shortcut Dimension 8

		annotation SummarizationSetBy = Automatic

	column dimension8ValueName
		dataType: string
		isHidden
		lineageTag: 1af08e53-60b0-4725-b0fa-0109636649b3
		summarizeBy: none
		sourceColumn: dimension8ValueName

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		isHidden
		lineageTag: 99221efe-aa3a-468b-9516-a9afdeeacdcf
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Dimension Sets' = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = DimensionSets_DataSource,
				    #"Changed Type" = Table.TransformColumnTypes(
				        Source,
				        {
				            {"dimensionSetID", Int64.Type},
				            {"dimension1ValueCode", type text},
				            {"dimension2ValueCode", type text},
				            {"dimension3ValueCode", type text},
				            {"dimension4ValueCode", type text},
				            {"dimension5ValueCode", type text},
				            {"dimension6ValueCode", type text},
				            {"dimension7ValueCode", type text},
				            {"dimension8ValueCode", type text}
				        }
				    ),
				    #"Renamed Columns" = Table.RenameColumns(
				        #"Changed Type",
				        {
				            {"dimension1ValueCode", "Global Dimension 1"},
				            {"dimension2ValueCode", "Global Dimension 2"},
				            {"dimension3ValueCode", "Shortcut Dimension 3"},
				            {"dimension4ValueCode", "Shortcut Dimension 4"},
				            {"dimension5ValueCode", "Shortcut Dimension 5"},
				            {"dimension6ValueCode", "Shortcut Dimension 6"},
				            {"dimension7ValueCode", "Shortcut Dimension 7"},
				            {"dimension8ValueCode", "Shortcut Dimension 8"}
				        }
				    )
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

