table Item
	lineageTag: 5da64649-f155-4cb5-a110-43dacd41b0e6

	column 'Item No. & Description'
		dataType: string
		lineageTag: 5656dac9-f4ca-4023-aff0-2e4830192c07
		summarizeBy: none
		sourceColumn: Item No. & Description

		annotation SummarizationSetBy = Automatic

	column 'Item No.'
		dataType: string
		isKey
		lineageTag: 20ef9aeb-b3c0-408e-b877-46d3850c8f2e
		summarizeBy: none
		sourceColumn: Item No.

		annotation SummarizationSetBy = Automatic

	column 'Item Description'
		dataType: string
		lineageTag: afd52416-5b40-4cc5-8842-d81d4ac487ce
		summarizeBy: none
		sourceColumn: Item Description

		annotation SummarizationSetBy = Automatic

	column 'Item Base Unit of Measure'
		dataType: string
		lineageTag: 02c4b8bf-66d8-45ac-bcae-b0855f1f4185
		summarizeBy: none
		sourceColumn: Item Base Unit of Measure

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Unit Cost (LCY)'
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 71cd8f0f-212c-4537-a692-9cafe0ad92f4
		summarizeBy: sum
		sourceColumn: Item Unit Cost (LCY)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-AU"}

	column 'Item Inventory Posting Group'
		dataType: string
		lineageTag: eecaa41f-295f-4501-890e-a32765d93e8f
		summarizeBy: none
		sourceColumn: Item Inventory Posting Group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Category Code'
		dataType: string
		isHidden
		lineageTag: b372e673-8a06-488f-951d-a29f8f92084f
		summarizeBy: none
		sourceColumn: Item Category Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Category Description'
		dataType: string
		isHidden
		lineageTag: 863da02c-78e2-40db-a9da-24f8936afc59
		summarizeBy: none
		sourceColumn: Item Category Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ETag
		dataType: string
		isHidden
		lineageTag: 180e22fe-cf15-4bf9-9e5b-2f063d6f2a34
		summarizeBy: none
		sourceColumn: ETag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Routing No.'
		dataType: string
		lineageTag: c24302d5-7972-4f74-8e55-874d4f707d78
		summarizeBy: none
		sourceColumn: Item Routing No.

		annotation SummarizationSetBy = Automatic

	column 'Item Production BOM No.'
		dataType: string
		lineageTag: 8743b79c-8583-4ec2-9901-6e6ea960fe59
		summarizeBy: none
		sourceColumn: Item Production BOM No.

		annotation SummarizationSetBy = Automatic

	column 'Item Replenishment System'
		dataType: string
		lineageTag: 0befc772-735c-4c28-aa31-8db003660911
		summarizeBy: none
		sourceColumn: Item Replenishment System

		annotation SummarizationSetBy = Automatic

	column 'Item Single-Level Cap. Ovhd Cost'
		dataType: double
		lineageTag: 28f5d160-ac70-43b2-a10b-b2e91c62e2c2
		summarizeBy: none
		sourceColumn: Item Single-Level Cap. Ovhd Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Capacity Cost'
		dataType: double
		lineageTag: 98390536-11e4-482a-ac0a-906243b14400
		summarizeBy: none
		sourceColumn: Item Single-Level Capacity Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Material Cost'
		dataType: double
		lineageTag: b3407160-b83b-417a-a932-4cc57e1b575e
		summarizeBy: none
		sourceColumn: Item Single-Level Material Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Mfg. Ovhd Cost'
		dataType: double
		lineageTag: ef2c8689-ff33-4ba2-aa2b-00459474ec83
		summarizeBy: none
		sourceColumn: Item Single-Level Mfg. Ovhd Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Subcontrd. Cost'
		dataType: double
		lineageTag: bc386578-fb89-486b-a19f-4fe02e91af4e
		summarizeBy: none
		sourceColumn: Item Single-Level Subcontrd. Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Lvl Mat. Non-Invt. Cost'
		dataType: double
		lineageTag: ae4f3278-7d30-4ffc-ba49-3cd9d17d77b7
		summarizeBy: none
		sourceColumn: Item Single-Lvl Mat. Non-Invt. Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Cap. Overhead Cost'
		dataType: double
		lineageTag: 852f716b-7d35-4e3a-aa76-a9efd2693792
		summarizeBy: none
		sourceColumn: Item Rolled-up Cap. Overhead Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Capacity Cost'
		dataType: double
		lineageTag: d0ff0d91-d8c2-4e36-83cb-cdfec66585f9
		summarizeBy: none
		sourceColumn: Item Rolled-up Capacity Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mat. Non-Invt. Cost'
		dataType: double
		lineageTag: 9c90be21-1ae1-40c7-a57a-b629afe600d5
		summarizeBy: none
		sourceColumn: Item Rolled-up Mat. Non-Invt. Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Material Cost'
		dataType: double
		lineageTag: 4c03ff40-0f33-49e9-84c7-07a4d33be490
		summarizeBy: none
		sourceColumn: Item Rolled-up Material Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mfg. Ovhd Cost'
		dataType: double
		lineageTag: 3f76a68a-534a-4864-bf9f-552f960eedfa
		summarizeBy: none
		sourceColumn: Item Rolled-up Mfg. Ovhd Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Subcontracted Cost'
		dataType: double
		lineageTag: 5d9cf4cf-6fec-4a1e-a3a3-bcb0ea115eac
		summarizeBy: none
		sourceColumn: Item Rolled-up Subcontracted Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Scrap %'
		dataType: double
		lineageTag: 339d3a30-f857-46b7-ad92-6ab83edeaa16
		summarizeBy: none
		sourceColumn: Item Scrap %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Item-239072cc-c802-4b3e-8de9-e5402e6d7b52 = m
		mode: import
		queryGroup: 'Dimension Tables'
		source = ```
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY, API_ENDPOINT, []),
				    TableData = Source{[Name = "items", Signature = "table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(
				        TableData,
				        {
				            {"itemNo", type text},
				            {"itemDescription", type text},
				            {"itemCategoryCode", type text},
				            {"itemCategoryDescription", type text},
				            {"unitCost", Currency.Type},
				            {"baseUnitofMeasure", type text}
				        }
				    ),
				    #"Renamed Columns" = Table.RenameColumns(
				        #"Changed Type",
				        {
				            {"itemNo", "Item No."},
				            {"unitCost", "Item Unit Cost (LCY)"},
				            {"itemCategoryCode", "Item Category Code"},
				            {"itemCategoryDescription", "Item Category Description"},
				            {"baseUnitofMeasure", "Item Base Unit of Measure"},
				            {"itemDescription", "Item Description"},
				            {"inventoryPostingGroup", "Item Inventory Posting Group"},
				            {"routingNo", "Item Routing No."},
				            {"productionBomNo", "Item Production BOM No."},
				            {"replenishmentSystem", "Item Replenishment System"},
				            {"singleLevelCapOvhdCost", "Item Single-Level Cap. Ovhd Cost"},
				            {"singleLevelCapacityCost", "Item Single-Level Capacity Cost"},
				            {"singleLevelMaterialCost", "Item Single-Level Material Cost"},
				            {"singleLevelMfgOvhdCost", "Item Single-Level Mfg. Ovhd Cost"},
				            {"singleLevelSubcontrdCost", "Item Single-Level Subcontrd. Cost"},
				            {"singleLvlMatNonInvtCost", "Item Single-Lvl Mat. Non-Invt. Cost"},
				            {"rolledUpCapacityCost", "Item Rolled-up Capacity Cost"},
				            {"rolledUpCapOverheadCost", "Item Rolled-up Cap. Overhead Cost"},
				            {"rolledUpMatNonInvtCost", "Item Rolled-up Mat. Non-Invt. Cost"},
				            {"rolledUpMaterialCost", "Item Rolled-up Material Cost"},
				            {"rolledUpMfgOvhdCost", "Item Rolled-up Mfg. Ovhd Cost"},
				            {"rolledUpSubcontractedCost", "Item Rolled-up Subcontracted Cost"},
				            {"scrapPrc", "Item Scrap %"}
				        }
				    ),
				    #"Added Column" = Table.AddColumn(
				        #"Renamed Columns", 
				        "Item No. & Description", each [#"Item No."] & " " & [Item Description],
				        type text
				    )
				in
				    #"Added Column"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

