table Item
	lineageTag: 5a9bd65b-6f5f-459e-aa78-812cb31cc047

	column 'Item No. & Description'
		dataType: string
		lineageTag: a761988c-3afd-49cf-ac59-6eecbbffc257
		summarizeBy: none
		sourceColumn: Item No. & Description

		annotation SummarizationSetBy = Automatic

	column 'Item No.'
		dataType: string
		isKey
		lineageTag: bedf723b-8ea2-4c37-85e7-96da43875a0c
		summarizeBy: none
		sourceColumn: Item No.

		annotation SummarizationSetBy = Automatic

	column 'Item Description'
		dataType: string
		lineageTag: 006058ff-cf79-4211-a138-b79e68cdb715
		summarizeBy: none
		sourceColumn: Item Description

		annotation SummarizationSetBy = Automatic

	column 'Item Base Unit of Measure'
		dataType: string
		isHidden
		lineageTag: d629e2cf-c6f2-4ba7-bf48-c4cc96004322
		summarizeBy: none
		sourceColumn: Item Base Unit of Measure

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Unit Cost (LCY)'
		dataType: decimal
		formatString: #,0.00
		lineageTag: abe83ad7-42d1-4d37-a6bc-7674c942a73a
		summarizeBy: none
		sourceColumn: Item Unit Cost (LCY)

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-AU"}

	column 'Item Inventory Posting Group'
		dataType: string
		isHidden
		lineageTag: 68010b08-92ed-4a63-ab43-2ebf5a9d1550
		summarizeBy: none
		sourceColumn: Item Inventory Posting Group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Category Code'
		dataType: string
		isHidden
		lineageTag: 58847eb1-b3d4-4131-9073-e177d4ffc7cb
		summarizeBy: none
		sourceColumn: Item Category Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Category Description'
		dataType: string
		lineageTag: 59c1f724-8fd2-4ae2-8c9c-efd84737d0e0
		summarizeBy: none
		sourceColumn: Item Category Description

		annotation SummarizationSetBy = Automatic

	column 'Item Routing No.'
		dataType: string
		isHidden
		lineageTag: 64d9f4e3-5494-4e53-80b8-48cd543f917f
		summarizeBy: none
		sourceColumn: Item Routing No.

		annotation SummarizationSetBy = Automatic

	column 'Item Production BOM No.'
		dataType: string
		isHidden
		lineageTag: b4f65516-8a9d-46db-bc0d-f39b34bf447f
		summarizeBy: none
		sourceColumn: Item Production BOM No.

		annotation SummarizationSetBy = Automatic

	column 'Item Replenishment System'
		dataType: string
		isHidden
		lineageTag: c1131e5e-5203-4527-bb0e-196be9168b83
		summarizeBy: none
		sourceColumn: Item Replenishment System

		annotation SummarizationSetBy = Automatic

	column 'Item Single-Level Cap. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 7cad0b8e-ef32-4902-bde4-90a0c616c480
		summarizeBy: none
		sourceColumn: Item Single-Level Cap. Ovhd Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Capacity Cost'
		dataType: double
		isHidden
		lineageTag: 3df7b4d2-c88d-4722-8fc4-3e1b277bf339
		summarizeBy: none
		sourceColumn: Item Single-Level Capacity Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Material Cost'
		dataType: double
		isHidden
		lineageTag: 2244d3bb-f54d-45d1-8cc9-d3d0cac3703d
		summarizeBy: none
		sourceColumn: Item Single-Level Material Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Mfg. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 5e64c067-cee1-4511-9c92-b22e4603a64e
		summarizeBy: none
		sourceColumn: Item Single-Level Mfg. Ovhd Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Subcontrd. Cost'
		dataType: double
		isHidden
		lineageTag: 365552a3-1651-4256-b140-7d2041b6dae1
		summarizeBy: none
		sourceColumn: Item Single-Level Subcontrd. Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Lvl Mat. Non-Invt. Cost'
		dataType: double
		isHidden
		lineageTag: 3c87ca91-0232-4330-9348-548cf5cb5286
		summarizeBy: none
		sourceColumn: Item Single-Lvl Mat. Non-Invt. Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Cap. Overhead Cost'
		dataType: double
		isHidden
		lineageTag: d1fea419-d54c-40cd-8bbc-f2f459f5702d
		summarizeBy: none
		sourceColumn: Item Rolled-up Cap. Overhead Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Capacity Cost'
		dataType: double
		isHidden
		lineageTag: 2f4be64f-a4a6-4087-8693-bb57cff99884
		summarizeBy: none
		sourceColumn: Item Rolled-up Capacity Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mat. Non-Invt. Cost'
		dataType: double
		isHidden
		lineageTag: 94f4e216-5acf-4183-83d1-ad5239d46dbb
		summarizeBy: none
		sourceColumn: Item Rolled-up Mat. Non-Invt. Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Material Cost'
		dataType: double
		isHidden
		lineageTag: 592e815e-35a4-45e2-a827-9dd3ef9db103
		summarizeBy: none
		sourceColumn: Item Rolled-up Material Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mfg. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 078fa689-3083-4529-8d59-b9d0ce20c2ad
		summarizeBy: none
		sourceColumn: Item Rolled-up Mfg. Ovhd Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Subcontracted Cost'
		dataType: double
		isHidden
		lineageTag: cd3fa838-b2bb-4491-87dd-8a9829ad1506
		summarizeBy: none
		sourceColumn: Item Rolled-up Subcontracted Cost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Scrap %'
		dataType: double
		isHidden
		lineageTag: 05a18104-015f-43cb-9883-e76948b404e2
		summarizeBy: none
		sourceColumn: Item Scrap %

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Type Key'
		dataType: string
		isHidden
		lineageTag: 0b004070-c449-4616-b9b2-f666df8a3e9e
		summarizeBy: none
		sourceColumn: Type Key

		annotation SummarizationSetBy = Automatic

	partition Item-239072cc-c802-4b3e-8de9-e5402e6d7b52 = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY, API_ENDPOINT, []),
				    TableData = Source{[Name = "items", Signature = "table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(
				        TableData,
				        {
				            {"itemNo", "Item No."},
				            {"unitCost", "Item Unit Cost (LCY)"},
				            {"itemCategoryCode", "Item Category Code"},
				            {"itemCategoryDescription", "Item Category Description"},
				            {"baseUnitofMeasure", "Item Base Unit of Measure"},
				            {"itemDescription", "Item Description"},
				            {"inventoryPostingGroup", "Item Inventory Posting Group"},
				            {"routingNo", "Item Routing No."},
				            {"productionBomNo", "Item Production BOM No."},
				            {"replenishmentSystem", "Item Replenishment System"},
				            {"singleLevelCapOvhdCost", "Item Single-Level Cap. Ovhd Cost"},
				            {"singleLevelCapacityCost", "Item Single-Level Capacity Cost"},
				            {"singleLevelMaterialCost", "Item Single-Level Material Cost"},
				            {"singleLevelMfgOvhdCost", "Item Single-Level Mfg. Ovhd Cost"},
				            {"singleLevelSubcontrdCost", "Item Single-Level Subcontrd. Cost"},
				            {"singleLvlMatNonInvtCost", "Item Single-Lvl Mat. Non-Invt. Cost"},
				            {"rolledUpCapacityCost", "Item Rolled-up Capacity Cost"},
				            {"rolledUpCapOverheadCost", "Item Rolled-up Cap. Overhead Cost"},
				            {"rolledUpMatNonInvtCost", "Item Rolled-up Mat. Non-Invt. Cost"},
				            {"rolledUpMaterialCost", "Item Rolled-up Material Cost"},
				            {"rolledUpMfgOvhdCost", "Item Rolled-up Mfg. Ovhd Cost"},
				            {"rolledUpSubcontractedCost", "Item Rolled-up Subcontracted Cost"},
				            {"scrapPrc", "Item Scrap %"}
				        }
				    ),
				    #"Added Custom" = Table.AddColumn(
				        #"Renamed Columns", "Item No. & Description", each [#"Item No."] & " " & [Item Description], type text
				    ),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom", {"ETag"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns", {{"Item Unit Cost (LCY)", Currency.Type}}),
				    #"Added Type Key" = Table.AddColumn(#"Changed Type", "Type Key", each "Item" & " " & [#"Item No."], type text)
				in
				    #"Added Type Key"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

