// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.Finance.Analysis;

codeunit 689 "Payment Practices"
{
    var
        PaymentPracticeMath: Codeunit "Payment Practice Math";

    procedure Generate(var PaymentPracticeHeader: Record "Payment Practice Header") DataIsNotEmpty: Boolean
    var
        PaymentPracticeData: Record "Payment Practice Data";
    begin
        PaymentPracticeHeader.TestField("Starting Date");
        PaymentPracticeHeader.TestField("Ending Date");
        PaymentPracticeData.Reset();
        PaymentPracticeData.SetRange("Header No.", PaymentPracticeHeader."No.");
        PaymentPracticeData.DeleteAll();
        GenerateData(PaymentPracticeData, PaymentPracticeHeader, PaymentPracticeHeader."Header Type");
        DataIsNotEmpty := not PaymentPracticeData.IsEmpty();
        PaymentPracticeHeader."Generated On" := CurrentDateTime();
        PaymentPracticeHeader."Generated By" := CopyStr(UserId(), 1, MaxStrLen(PaymentPracticeHeader."Generated By"));
        GenerateTotals(PaymentPracticeData, PaymentPracticeHeader);
        GenerateLines(PaymentPracticeHeader."Aggregation Type", PaymentPracticeData, PaymentPracticeHeader);
        PaymentPracticeHeader."Modified Manually" := false;
        PaymentPracticeHeader.Modify(false);
    end;

    local procedure GenerateTotals(var PaymentPracticeData: Record "Payment Practice Data"; var PaymentPracticeHeader: Record "Payment Practice Header")
    begin
        PaymentPracticeHeader."Average Actual Payment Period" := PaymentPracticeMath.GetAverageActualPaymentTime(PaymentPracticeData);
        PaymentPracticeHeader."Average Agreed Payment Period" := PaymentPracticeMath.GetAverageAgreedPaymentTime(PaymentPracticeData);
        PaymentPracticeHeader."Pct Paid on Time" := PaymentPracticeMath.GetPercentOfOnTimePayments(PaymentPracticeData);
        PaymentPracticeHeader."Mode Payment Time" := PaymentPracticeMath.GetModePaymentTime(PaymentPracticeData);

        PaymentPracticeHeader."Mode Payment Time Min." := 0;
        PaymentPracticeHeader."Mode Payment Time Max." := 0;
        PaymentPracticeHeader."Median Payment Time" := 0;
        PaymentPracticeHeader."80th Percentile Payment Time" := 0;
        PaymentPracticeHeader."95th Percentile Payment Time" := 0;
        PaymentPracticeHeader."Pct Peppol Enabled" := 0;
        PaymentPracticeHeader."Pct Small Business Payments" := 0;

        if PaymentPracticeHeader."Reporting Scheme" = PaymentPracticeHeader."Reporting Scheme"::"Percentiles; Modes; Pct Peppol Enabled; Pct Small Business Payments" then begin
            PaymentPracticeHeader."Mode Payment Time Min." := PaymentPracticeMath.GetModePaymentTimeMin(PaymentPracticeData);
            PaymentPracticeHeader."Mode Payment Time Max." := PaymentPracticeMath.GetModePaymentTimeMax(PaymentPracticeData);
            PaymentPracticeHeader."Median Payment Time" := PaymentPracticeMath.GetMedianPaymentTime(PaymentPracticeData);
            PaymentPracticeHeader."80th Percentile Payment Time" := PaymentPracticeMath.Get80thPercentilePaymentTime(PaymentPracticeData);
            PaymentPracticeHeader."95th Percentile Payment Time" := PaymentPracticeMath.Get95thPercentilePaymentTime(PaymentPracticeData);
            PaymentPracticeHeader."Pct Peppol Enabled" := PaymentPracticeMath.GetPctPeppolEnabled(PaymentPracticeData);

            if PaymentPracticeHeader."Only Small Businesses" then
                PaymentPracticeHeader."Pct Small Business Payments" := PaymentPracticeMath.GetPctSmallBusinessPayments(PaymentPracticeData, PaymentPracticeHeader);
        end;
    end;

    local procedure GenerateData(var PaymentPracticeData: Record "Payment Practice Data"; PaymentPracticeHeader: Record "Payment Practice Header"; PaymentPracticeDataGenerator: Interface PaymentPracticeDataGenerator)
    begin
        PaymentPracticeDataGenerator.GenerateData(PaymentPracticeData, PaymentPracticeHeader);
    end;

    local procedure GenerateLines(PaymentPracticeLinesAggregator: Interface PaymentPracticeLinesAggregator; var PaymentPracticeData: Record "Payment Practice Data"; PaymentPracticeHeader: Record "Payment Practice Header")
    begin
        PaymentPracticeLinesAggregator.GenerateLines(PaymentPracticeData, PaymentPracticeHeader);
    end;
}
