// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------

namespace Microsoft.DataMigration.BC14;

using Microsoft.Finance.Dimension;

codeunit 50187 "BC14 Dim. Value Migrator" implements "ISetupMigrator"
{
    var
        MigratorNameLbl: Label 'Dimension Value Migrator';
        DimensionDoesNotExistErr: Label 'Dimension %1 does not exist. Please ensure Dimension table is migrated first.', Comment = '%1 = Dimension Code';

    procedure GetName(): Text[250]
    begin
        exit(MigratorNameLbl);
    end;

    procedure IsEnabled(): Boolean
    begin
        exit(HasDataToMigrate());
    end;

    procedure Migrate(StopOnFirstError: Boolean): Boolean
    var
        BC14DimensionValue: Record "BC14 Dimension Value";
        BC14MigrationErrorHandler: Codeunit "BC14 Migration Error Handler";
        Success: Boolean;
    begin
        Success := true;

        if not HasDataToMigrate() then
            exit(true);

        if BC14DimensionValue.FindSet() then
            repeat
                if not TryMigrateDimensionValue(BC14DimensionValue) then begin
                    BC14MigrationErrorHandler.LogError(GetName(), Database::"BC14 Dimension Value", 'BC14 Dimension Value', BC14DimensionValue."Dimension Code" + '-' + BC14DimensionValue.Code, Database::"Dimension Value", GetLastErrorText(), BC14DimensionValue.RecordId);
                    Success := false;
                    if StopOnFirstError then
                        exit(false);
                    ClearLastError();
                end;
            until BC14DimensionValue.Next() = 0;

        exit(Success);
    end;

    local procedure HasDataToMigrate(): Boolean
    var
        BC14DimensionValue: Record "BC14 Dimension Value";
    begin
        exit(not BC14DimensionValue.IsEmpty());
    end;

    [TryFunction]
    local procedure TryMigrateDimensionValue(BC14DimensionValue: Record "BC14 Dimension Value")
    var
        DimensionValue: Record "Dimension Value";
        Dimension: Record Dimension;
    begin
        // Check if dimension exists
        if not Dimension.Get(BC14DimensionValue."Dimension Code") then
            Error(DimensionDoesNotExistErr, BC14DimensionValue."Dimension Code");

        // Check if dimension value already exists
        if DimensionValue.Get(BC14DimensionValue."Dimension Code", BC14DimensionValue.Code) then begin
            // Update existing record
            TransferFields(BC14DimensionValue, DimensionValue);
            DimensionValue.Modify(true);
        end else begin
            // Insert new record - BC Online will auto-generate "Dimension Value ID"
            DimensionValue.Init();
            DimensionValue."Dimension Code" := BC14DimensionValue."Dimension Code";
            DimensionValue.Code := BC14DimensionValue.Code;
            TransferFields(BC14DimensionValue, DimensionValue);
            DimensionValue.Insert(true);
        end;
    end;

    local procedure TransferFields(BC14DimensionValue: Record "BC14 Dimension Value"; var DimensionValue: Record "Dimension Value")
    begin
        DimensionValue.Name := BC14DimensionValue.Name;
        DimensionValue."Dimension Value Type" := BC14DimensionValue."Value Type";
        DimensionValue.Totaling := BC14DimensionValue.Totaling;
        DimensionValue.Blocked := BC14DimensionValue.Blocked;
        DimensionValue."Consolidation Code" := BC14DimensionValue."Consolidation Code";
        DimensionValue.Indentation := BC14DimensionValue.Indentation;
        DimensionValue."Global Dimension No." := BC14DimensionValue."Global Dimension No.";
        DimensionValue."Map-to IC Dimension Code" := BC14DimensionValue."Map-to IC Dimension Code";
        DimensionValue."Map-to IC Dimension Value Code" := BC14DimensionValue."Map-to IC Dimension Value Code";
        // Note: "Dimension Value ID" is NOT transferred - it's auto-generated by BC Online

        // Allow extensions to map custom fields
        OnTransferDimensionValueCustomFields(BC14DimensionValue, DimensionValue);
    end;

    /// <summary>
    /// Integration event raised during dimension value migration to allow mapping of custom fields.
    /// Subscribe to this event to transfer TableExtension fields from BC14 Dimension Value to Dimension Value.
    /// </summary>
    [IntegrationEvent(false, false)]
    local procedure OnTransferDimensionValueCustomFields(BC14DimensionValue: Record "BC14 Dimension Value"; var DimensionValue: Record "Dimension Value")
    begin
    end;
}
