table 'Date Table Setup'
	isHidden
	lineageTag: 1f8ffa9a-61f9-4fc5-9dcc-6d36520cc60b

	measure 'Last Refresh Label' = ```
			
			VAR LastRefreshLabel = [Last Refreshed Label] & ": "
			
			VAR LastRefreshDate =
			    FORMAT (
			        VALUES ( 'Date Table Setup'[Today] ),
			        BLANK(),
			        USERCULTURE ()
			    )
			VAR LastRefreshTime =
			    FORMAT (
			        VALUES ( 'Date Table Setup'[Last Refresh Time] ),
			        "hh:nn AMPM",
			        USERCULTURE ()
			    )
			VAR CompanyName = [Company Name Label] & ": "
			
			RETURN
			    CompanyName & COMPANY[Company Label] & " - " & LastRefreshLabel & LastRefreshDate & " " & LastRefreshTime 
			
			```
		isHidden
		lineageTag: b02b1ea1-16a6-40bb-a6dd-ec2e6b288b3d

		changedProperty = IsHidden

	column 'First Day of Week'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 368bd7d3-07e4-4b02-97e5-5e5ebb7536bf
		summarizeBy: sum
		sourceColumn: First Day of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Today
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 5efb189b-347f-4cf1-98cf-7ed7a30cd39e
		summarizeBy: none
		sourceColumn: Today

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fiscalCalendarFirstMonth
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: db45a844-eac8-4495-91c0-cd857488bae3
		summarizeBy: sum
		sourceColumn: fiscalCalendarFirstMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column firstDayOfWeek
		dataType: string
		isHidden
		lineageTag: fa9fa751-3319-471c-8190-3c1a63be7ac6
		summarizeBy: none
		sourceColumn: firstDayOfWeek

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column isoCountryHolidays
		dataType: string
		isHidden
		lineageTag: 8e6d8c14-64e9-4c66-aefe-23554703237e
		summarizeBy: none
		sourceColumn: isoCountryHolidays

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column weeklyType
		dataType: string
		isHidden
		lineageTag: 702ff07d-6872-4742-b4f0-2699a7d96ebc
		summarizeBy: none
		sourceColumn: weeklyType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quarterWeekType
		dataType: string
		isHidden
		lineageTag: 0630456f-b17e-423a-93fc-3afe435e7670
		summarizeBy: none
		sourceColumn: quarterWeekType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column calendarRange
		dataType: string
		isHidden
		lineageTag: df50959e-89fb-40f1-afe5-fda0c17f3012
		summarizeBy: none
		sourceColumn: calendarRange

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column calendarPrefix
		dataType: string
		isHidden
		lineageTag: 86128744-54ea-4585-b7ac-f7212b0cb714
		summarizeBy: none
		sourceColumn: calendarPrefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fiscalGregorianPrefix
		dataType: string
		isHidden
		lineageTag: 3b0dc5d1-4d19-468b-8289-97f3dcef1de1
		summarizeBy: none
		sourceColumn: fiscalGregorianPrefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fiscalWeeklyPrefix
		dataType: string
		isHidden
		lineageTag: 1d241752-896f-45a8-95ff-10766ec4447a
		summarizeBy: none
		sourceColumn: fiscalWeeklyPrefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column useCustomFisclPeriods
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 59a48404-1acb-4e02-af63-fe246b9999a0
		summarizeBy: none
		sourceColumn: useCustomFisclPeriods

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ignoreWeeklyPeriods
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9fcb2e4f-9919-490a-abbd-c5849f8c8f18
		summarizeBy: none
		sourceColumn: ignoreWeeklyPeriods

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dateTblStart
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 8067ab8d-6c71-4d36-a4ab-762f7c638b98
		summarizeBy: none
		sourceColumn: dateTblStart

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dateTblEnd
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 557edfa0-ad0b-4ce2-83b5-b7d225678b4c
		summarizeBy: none
		sourceColumn: dateTblEnd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column timeZone
		dataType: string
		isHidden
		lineageTag: dd7d9341-9b55-4418-964a-ea8ea3c2e24d
		summarizeBy: none
		sourceColumn: timeZone

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column timeZoneDisplayName
		dataType: string
		isHidden
		lineageTag: 9e4ed7ec-ffeb-49a1-ac66-10f597730018
		summarizeBy: none
		sourceColumn: timeZoneDisplayName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entryNo
		dataType: string
		isHidden
		lineageTag: a50b7895-45dd-4406-a316-04d242d710a1
		summarizeBy: none
		sourceColumn: entryNo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		isHidden
		lineageTag: 7b1f3371-4a8b-41aa-a86a-87b62799cb4a
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh Time'
		dataType: dateTime
		isHidden
		formatString: Long Time
		lineageTag: be3ee4fe-e54c-47a8-9bd2-23e3b26aca50
		summarizeBy: none
		sourceColumn: Last Refresh Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column tenantID
		dataType: string
		lineageTag: 93d6a5db-1c7c-4f86-bda7-ffa12b2e2df7
		summarizeBy: none
		sourceColumn: tenantID

		annotation SummarizationSetBy = Automatic

	column 'UTC Hours'
		dataType: int64
		formatString: 0
		lineageTag: 07bf4237-5362-4b52-823d-3fe98ba779ea
		summarizeBy: sum
		sourceColumn: UTC Hours

		annotation SummarizationSetBy = Automatic

	column 'UTC Minutes'
		dataType: int64
		formatString: 0
		lineageTag: e3c13e52-b72c-454a-b3bb-204ddd8bcff4
		summarizeBy: sum
		sourceColumn: UTC Minutes

		annotation SummarizationSetBy = Automatic

	partition 'Date Table Setup-e674a110-5b5f-4e78-b7ad-43d0c53bac17' = m
		mode: import
		queryGroup: 'Date Table'
		source =
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY, API_ENDPOINT, []),
				    TableData = Source{[Name = "dateSetups", Signature = "table"]}[Data],
				    CheckTenantIDColumnExists = if Table.HasColumns(TableData, "tenantID") then TableData else Table.AddColumn(TableData, "tenantID", each null, type text),
				    #"Convert UTC to Local" = ConvertUTC(CheckTenantIDColumnExists),
				    #"Removed Columns" = Table.RemoveColumns(#"Convert UTC to Local", {"ETag"}),
				    #"Added Conditional Column" = Table.AddColumn(
				        #"Removed Columns",
				        "First Day of Week",
				        each
				            if [firstDayOfWeek] = "Sunday" then
				                0
				            else if [firstDayOfWeek] = "Monday" then
				                1
				            else if [firstDayOfWeek] = "Tuesday" then
				                2
				            else if [firstDayOfWeek] = "Wednesday" then
				                3
				            else if [firstDayOfWeek] = "Thursday" then
				                4
				            else if [firstDayOfWeek] = "Friday" then
				                5
				            else if [firstDayOfWeek] = "Saturday" then
				                6
				            else
				                1
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column", {{"First Day of Week", Int64.Type}}),
				    #"Replaced Calendar Range" = Table.ReplaceValue(
				        #"Changed Type",
				        each [calendarRange],
				        each
				            if [calendarRange] = "Weekly" then
				                "FiscalWeekly"
				            else if [calendarRange] = "Fiscal Calendar" then
				                "FiscalGregorian"
				            else
				                "Calendar",
				        Replacer.ReplaceText,
				        {"calendarRange"}
				    ),
				    #"Replaced Fiscal Gregorian Prefix" = Table.ReplaceValue(
				        #"Replaced Calendar Range", "", "F", Replacer.ReplaceValue, {"fiscalGregorianPrefix"}
				    ),
				    #"Replaced Fiscal Weekly Prefix" = Table.ReplaceValue(
				        #"Replaced Fiscal Gregorian Prefix", "", "FW", Replacer.ReplaceValue, {"fiscalWeeklyPrefix"}
				    ),
				    #"Changed Type3" = Table.TransformColumnTypes(
				        #"Replaced Fiscal Weekly Prefix",
				        {
				            {"fiscalCalendarFirstMonth", Int64.Type},
				            {"firstDayOfWeek", type text},
				            {"isoCountryHolidays", type text},
				            {"weeklyType", type text},
				            {"quarterWeekType", type text},
				            {"calendarRange", type text},
				            {"calendarPrefix", type text},
				            {"fiscalGregorianPrefix", type text},
				            {"fiscalWeeklyPrefix", type text},
				            {"useCustomFisclPeriods", type logical},
				            {"ignoreWeeklyPeriods", type logical},
				            {"timeZone", type text},
				            {"timeZoneDisplayName", type text},
				            {"dateTblStart", type date},
				            {"dateTblEnd", type date}
				        }
				    )
				in
				    #"Changed Type3"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

