table Item
	lineageTag: c40a40e9-d278-4fd2-b077-3918c6213a0d

	column 'Item No. & Description'
		dataType: string
		lineageTag: eeb89ffc-5a5a-4e05-a540-63b5f453e2d8
		summarizeBy: none
		sourceColumn: Item No. & Description

		annotation SummarizationSetBy = Automatic

	column 'Item No.'
		dataType: string
		isKey
		lineageTag: cc676ed5-3d83-4de6-985c-7cefb883b39a
		summarizeBy: none
		sourceColumn: Item No.

		annotation SummarizationSetBy = Automatic

	column 'Item Description'
		dataType: string
		lineageTag: e79021b1-e46a-4327-b842-e5173a818dd3
		summarizeBy: none
		sourceColumn: Item Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Base Unit of Measure'
		dataType: string
		lineageTag: d6cd68fc-ef5a-4d4e-b06b-594317d76155
		summarizeBy: none
		sourceColumn: Item Base Unit of Measure

		annotation SummarizationSetBy = Automatic

	column 'Item Unit Cost (LCY)'
		dataType: decimal
		formatString: #,0.00
		lineageTag: f06b8e0c-5176-4cee-a752-c2cea34cc48f
		summarizeBy: none
		sourceColumn: Item Unit Cost (LCY)

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-AU"}

	column 'Item Inventory Posting Group'
		dataType: string
		lineageTag: a2bc423f-a4b2-4183-8810-26598d8def2d
		summarizeBy: none
		sourceColumn: Item Inventory Posting Group

		annotation SummarizationSetBy = Automatic

	column 'Item Category Code'
		dataType: string
		isHidden
		lineageTag: a0cedea3-b6d1-459e-8778-9ce6409fe496
		summarizeBy: none
		sourceColumn: Item Category Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Category Description'
		dataType: string
		isHidden
		lineageTag: 47581cca-cd17-4404-a350-3db7b05fb429
		summarizeBy: none
		sourceColumn: Item Category Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Routing No.'
		dataType: string
		isHidden
		lineageTag: defb9c37-a706-4716-a40a-e628145e3516
		summarizeBy: none
		sourceColumn: Item Routing No.

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Production BOM No.'
		dataType: string
		isHidden
		lineageTag: b7013b57-5705-47c9-9ed6-d290616c3840
		summarizeBy: none
		sourceColumn: Item Production BOM No.

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Replenishment System'
		dataType: string
		isHidden
		lineageTag: 4ddffb8d-9a30-4aed-83a1-07c5fea25516
		summarizeBy: none
		sourceColumn: Item Replenishment System

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Item Single-Level Cap. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 1e45c658-8ed0-4cf5-963e-8f530a01058f
		summarizeBy: sum
		sourceColumn: Item Single-Level Cap. Ovhd Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Capacity Cost'
		dataType: double
		isHidden
		lineageTag: d3ee5898-f190-4236-a018-52223fab801a
		summarizeBy: sum
		sourceColumn: Item Single-Level Capacity Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Material Cost'
		dataType: double
		isHidden
		lineageTag: a6301b57-fbfd-4646-91cb-81a393384674
		summarizeBy: sum
		sourceColumn: Item Single-Level Material Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Mfg. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 6abb5928-091f-4874-a5d3-cd6c231a39f1
		summarizeBy: sum
		sourceColumn: Item Single-Level Mfg. Ovhd Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Level Subcontrd. Cost'
		dataType: double
		isHidden
		lineageTag: 17ad40fa-5dae-4f57-8e3c-9b5de7a12092
		summarizeBy: sum
		sourceColumn: Item Single-Level Subcontrd. Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Single-Lvl Mat. Non-Invt. Cost'
		dataType: double
		isHidden
		lineageTag: bce0798b-92d2-4548-afd8-002c5a8721e7
		summarizeBy: sum
		sourceColumn: Item Single-Lvl Mat. Non-Invt. Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Cap. Overhead Cost'
		dataType: double
		isHidden
		lineageTag: 42ca3000-97dd-48d5-b6b2-d359c133d123
		summarizeBy: none
		sourceColumn: Item Rolled-up Cap. Overhead Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Capacity Cost'
		dataType: double
		isHidden
		lineageTag: 9b8fc25f-ccf5-4531-8718-3a3e3359e83b
		summarizeBy: sum
		sourceColumn: Item Rolled-up Capacity Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mat. Non-Invt. Cost'
		dataType: double
		isHidden
		lineageTag: 421d74a5-ce22-4336-8c2e-16a808c49cb4
		summarizeBy: sum
		sourceColumn: Item Rolled-up Mat. Non-Invt. Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Material Cost'
		dataType: double
		isHidden
		lineageTag: 56adf0f3-2dde-4c10-a3a7-625446f58d0a
		summarizeBy: sum
		sourceColumn: Item Rolled-up Material Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Mfg. Ovhd Cost'
		dataType: double
		isHidden
		lineageTag: 24ff8135-8185-4143-8244-b0672094e419
		summarizeBy: sum
		sourceColumn: Item Rolled-up Mfg. Ovhd Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Rolled-up Subcontracted Cost'
		dataType: double
		isHidden
		lineageTag: 3c0e9220-c2a4-4e1c-89e1-0417200bc09e
		summarizeBy: sum
		sourceColumn: Item Rolled-up Subcontracted Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Scrap %'
		dataType: double
		isHidden
		lineageTag: b99bb910-07d1-44fc-a451-4fda7d91e383
		summarizeBy: sum
		sourceColumn: Item Scrap %

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Type Key'
		dataType: string
		isHidden
		lineageTag: 2b456b16-acaf-4352-a044-6491bdcd80d0
		summarizeBy: none
		sourceColumn: Type Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Item-239072cc-c802-4b3e-8de9-e5402e6d7b52 = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(ENVIRONMENT, COMPANY, API_ENDPOINT, []),
				    TableData = Source{[Name = "items", Signature = "table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(
				        TableData,
				        {
				            {"itemNo", type text},
				            {"itemDescription", type text},
				            {"itemCategoryCode", type text},
				            {"itemCategoryDescription", type text},
				            {"unitCost", Currency.Type},
				            {"baseUnitofMeasure", type text}
				        }
				    ),
				    #"Renamed Columns" = Table.RenameColumns(
				        #"Changed Type",
				        {
				            {"itemNo", "Item No."},
				            {"unitCost", "Item Unit Cost (LCY)"},
				            {"itemCategoryCode", "Item Category Code"},
				            {"itemCategoryDescription", "Item Category Description"},
				            {"baseUnitofMeasure", "Item Base Unit of Measure"},
				            {"itemDescription", "Item Description"},
				            {"inventoryPostingGroup", "Item Inventory Posting Group"},
				            {"routingNo", "Item Routing No."},
				            {"productionBomNo", "Item Production BOM No."},
				            {"replenishmentSystem", "Item Replenishment System"},
				            {"singleLevelCapOvhdCost", "Item Single-Level Cap. Ovhd Cost"},
				            {"singleLevelCapacityCost", "Item Single-Level Capacity Cost"},
				            {"singleLevelMaterialCost", "Item Single-Level Material Cost"},
				            {"singleLevelMfgOvhdCost", "Item Single-Level Mfg. Ovhd Cost"},
				            {"singleLevelSubcontrdCost", "Item Single-Level Subcontrd. Cost"},
				            {"singleLvlMatNonInvtCost", "Item Single-Lvl Mat. Non-Invt. Cost"},
				            {"rolledUpCapacityCost", "Item Rolled-up Capacity Cost"},
				            {"rolledUpCapOverheadCost", "Item Rolled-up Cap. Overhead Cost"},
				            {"rolledUpMatNonInvtCost", "Item Rolled-up Mat. Non-Invt. Cost"},
				            {"rolledUpMaterialCost", "Item Rolled-up Material Cost"},
				            {"rolledUpMfgOvhdCost", "Item Rolled-up Mfg. Ovhd Cost"},
				            {"rolledUpSubcontractedCost", "Item Rolled-up Subcontracted Cost"},
				            {"scrapPrc", "Item Scrap %"}
				        }
				    ),
				    #"Added Custom" = Table.AddColumn(
				        #"Renamed Columns", "Item No. & Description", each [#"Item No."] & " " & [Item Description], type text
				    ),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom", {"ETag"}),
				    #"Added Type Key" = Table.AddColumn(#"Removed Columns", "Type Key", each "Item" & " " & [#"Item No."], type text)
				in
				    #"Added Type Key"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

