table 'Translated Localized Labels'
	isHidden
	lineageTag: 93479982-1377-4891-99f9-b02ea8b1234c

	measure 'My Report Title Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Título del informe",
			   "de-DE", "Titel meines Berichts",
			   "fr-FR", "Titre de l’état",
			   "cs-CZ", "Můj nadpis sestavy",
			   "da-DK", "Min rapporttitel",
			   "de-AT", "Titel meines Berichts",
			   "de-CH", "Titel meines Berichts",
			   "en-AU", "My Report Title",
			   "en-CA", "My Report Title",
			   "en-GB", "My Report Title",
			   "en-NZ", "My Report Title",
			   "es-MX", "Título del informe",
			   "fi-FI", "Oman raportin otsikko",
			   "fr-BE", "Titre de l’état",
			   "fr-CA", "Titre du rapport",
			   "fr-CH", "Titre de l’état",
			   "is-IS", "Skýrslutitillinn minn",
			   "it-CH", "Titolo report personale",
			   "it-IT", "Titolo report personale",
			   "nb-NO", "Min rapporttittel",
			   "nl-BE", "Mijn rapporttitel",
			   "nl-NL", "Mijn rapporttitel",
			   "sv-SE", "Min rapportrubrik",
			   "My Report Title"
			)
		isHidden
		lineageTag: 5f874db8-6c18-4367-872d-86545a590753

	measure 'My Button Caption Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Título de botón",
			   "de-DE", "Beschriftung Meine Schaltfläche",
			   "fr-FR", "Légende de mon bouton",
			   "cs-CZ", "Popisek mého tlačítka",
			   "da-DK", "Min knaptitel",
			   "de-AT", "Beschriftung Meine Schaltfläche",
			   "de-CH", "Beschriftung Meine Schaltfläche",
			   "en-AU", "My Button Caption",
			   "en-CA", "My Button Caption",
			   "en-GB", "My Button Caption",
			   "en-NZ", "My Button Caption",
			   "es-MX", "Título de botón",
			   "fi-FI", "Oma painikkeen otsikko",
			   "fr-BE", "Légende de mon bouton",
			   "fr-CA", "Légende de mon bouton",
			   "fr-CH", "Légende de mon bouton",
			   "is-IS", "Texti hnappsins míns",
			   "it-CH", "Didascalia pulsante personale",
			   "it-IT", "Didascalia pulsante personale",
			   "nb-NO", "Min knappetittel",
			   "nl-BE", "Bijschrift van mijn knop",
			   "nl-NL", "Bijschrift van mijn knop",
			   "sv-SE", "Min knapprubrik",
			   "My Button Caption"
			)
		isHidden
		lineageTag: 339f334d-4c46-49e3-bcd7-e92742123677

	measure 'My Visual Title Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Título visual",
			   "de-DE", "Titel meines Visuals",
			   "fr-FR", "Mon titre visuel",
			   "cs-CZ", "Název mého vizuálu",
			   "da-DK", "Min visuelle titel",
			   "de-AT", "Titel meines Visuals",
			   "de-CH", "Titel meines Visuals",
			   "en-AU", "My Visual Title",
			   "en-CA", "My Visual Title",
			   "en-GB", "My Visual Title",
			   "en-NZ", "My Visual Title",
			   "es-MX", "Título visual",
			   "fi-FI", "Oma visuaalinen otsikko",
			   "fr-BE", "Mon titre visuel",
			   "fr-CA", "Mon titre visuel",
			   "fr-CH", "Mon titre visuel",
			   "is-IS", "Sjónræni titillinn minn",
			   "it-CH", "Titolo visivo personale",
			   "it-IT", "Titolo visivo personale",
			   "nb-NO", "Min visuelle tittel",
			   "nl-BE", "Mijn visuele titel",
			   "nl-NL", "Mijn visuele titel",
			   "sv-SE", "Min visuella rubrik",
			   "My Visual Title"
			)
		isHidden
		lineageTag: 6b7700b2-10fa-41dd-9905-3cb12c99ba1d

	measure 'Top 5 Items Gross Profit Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Las 5 principales partidas de beneficio bruto",
			   "de-DE", "Top 5-Artikel Bruttogewinn",
			   "fr-FR", "Bénéfice brut 5 premiers articles",
			   "cs-CZ", "Hrubý zisk předních 5 zboží",
			   "da-DK", "Top 5 varers bruttofortjeneste",
			   "de-AT", "Top 5-Artikel Bruttogewinn",
			   "de-CH", "Top 5-Artikel Bruttogewinn",
			   "en-AU", "Top 5 Items Gross Profit",
			   "en-CA", "Top 5 Items Gross Profit",
			   "en-GB", "Top 5 Items Gross Profit",
			   "en-NZ", "Top 5 Items Gross Profit",
			   "es-MX", "Las 5 principales partidas de beneficio bruto",
			   "fi-FI", "5 parasta nimikettä bruttovoiton mukaan",
			   "fr-BE", "Bénéfice brut 5 premiers articles",
			   "fr-CA", "Profit brut 5 premiers articles",
			   "fr-CH", "Bénéfice brut 5 premiers articles",
			   "is-IS", "Brúttóhagnaður af 5 söluhæstu vörunum",
			   "it-CH", "Profitto lordo primi 5 articoli",
			   "it-IT", "Profitto lordo primi 5 articoli",
			   "nb-NO", "Topp fem varer etter bruttofortjeneste",
			   "nl-BE", "Top 5 artikelen brutowinst",
			   "nl-NL", "Top 5 artikelen brutowinst",
			   "sv-SE", "5 bästa artiklar per bruttovinst",
			   "Top 5 Items Gross Profit"
			)
		isHidden
		lineageTag: 6f055949-cc01-4830-9f03-1de6beb12d1e

	measure 'Top 5 Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Los 5 mejores vendedores",
			   "de-DE", "Top 5-Verkäufer",
			   "fr-FR", "5 premiers vendeurs",
			   "cs-CZ", "Předních 5 prodejců",
			   "da-DK", "Top 5 sælgere",
			   "de-AT", "Top 5-Verkäufer",
			   "de-CH", "Top 5-Verkäufer",
			   "en-AU", "Top 5 Salesperson",
			   "en-CA", "Top 5 Salesperson",
			   "en-GB", "Top 5 Salesperson",
			   "en-NZ", "Top 5 Salesperson",
			   "es-MX", "Los 5 mejores vendedores",
			   "fi-FI", "5 parasta myyjää",
			   "fr-BE", "5 premiers vendeurs",
			   "fr-CA", "5 premiers représentants",
			   "fr-CH", "5 premiers vendeurs",
			   "is-IS", "Efstu 5 sölumenn",
			   "it-CH", "Primi 5 venditori",
			   "it-IT", "Primi 5 venditori",
			   "nb-NO", "Topp fem selgere",
			   "nl-BE", "Top 5 verkopers",
			   "nl-NL", "Top 5 verkopers",
			   "sv-SE", "5 bästa säljare",
			   "Top 5 Salesperson"
			)
		isHidden
		lineageTag: 5a43bfeb-f997-437e-853a-f95b7fde2d92

	measure 'Top 5 Customers Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Los 5 mejores clientes",
			   "de-DE", "Top 5-Debitoren",
			   "fr-FR", "5 premiers clients",
			   "cs-CZ", "Předních 5 zákazníků",
			   "da-DK", "Top 5 debitorer",
			   "de-AT", "Top 5-Debitoren",
			   "de-CH", "Top 5-Debitoren",
			   "en-AU", "Top 5 Customers",
			   "en-CA", "Top 5 Customers",
			   "en-GB", "Top 5 Customers",
			   "en-NZ", "Top 5 Customers",
			   "es-MX", "Los 5 mejores clientes",
			   "fi-FI", "5 suurinta asiakasta",
			   "fr-BE", "5 premiers clients",
			   "fr-CA", "5 premiers clients",
			   "fr-CH", "5 premiers clients",
			   "is-IS", "Efstu 5 viðskiptavinir",
			   "it-CH", "Primi 5 clienti",
			   "it-IT", "Primi 5 clienti",
			   "nb-NO", "Topp fem kunder",
			   "nl-BE", "Top 5 klanten",
			   "nl-NL", "Top 5 klanten",
			   "sv-SE", "5 bästa kunder",
			   "Top 5 Customers"
			)
		isHidden
		lineageTag: 1c1790f7-a08a-44ce-bb49-e3545ef38060

	measure 'Document Value Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor del documento",
			   "de-DE", "Belegwert",
			   "fr-FR", "Valeur de document",
			   "cs-CZ", "Hodnota dokladu",
			   "da-DK", "Dokumentværdi",
			   "de-AT", "Belegwert",
			   "de-CH", "Belegwert",
			   "en-AU", "Document Value",
			   "en-CA", "Document Value",
			   "en-GB", "Document Value",
			   "en-NZ", "Document Value",
			   "es-MX", "Valor del documento",
			   "fi-FI", "Asiakirjan arvo",
			   "fr-BE", "Valeur de document",
			   "fr-CA", "Valeur de document",
			   "fr-CH", "Valeur de document",
			   "is-IS", "Gildi skjals",
			   "it-CH", "Valore documento",
			   "it-IT", "Valore documento",
			   "nb-NO", "Dokumentverdi",
			   "nl-BE", "Documentwaarde",
			   "nl-NL", "Documentwaarde",
			   "sv-SE", "Dokumentvärde",
			   "Document Value"
			)
		isHidden
		lineageTag: 8c059739-1800-438e-bc14-3abb44d468c5

	measure 'Document Count Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Número de documentos",
			   "de-DE", "Anzahl der Belege",
			   "fr-FR", "Nombre de documents",
			   "cs-CZ", "Počet dokladů",
			   "da-DK", "Dokumentantal",
			   "de-AT", "Anzahl der Belege",
			   "de-CH", "Anzahl der Belege",
			   "en-AU", "Document Count",
			   "en-CA", "Document Count",
			   "en-GB", "Document Count",
			   "en-NZ", "Document Count",
			   "es-MX", "Número de documentos",
			   "fi-FI", "Asiakirjamäärä",
			   "fr-BE", "Nombre de documents",
			   "fr-CA", "Nombre de documents",
			   "fr-CH", "Nombre de documents",
			   "is-IS", "Skjalatalning",
			   "it-CH", "Numero documenti",
			   "it-IT", "Numero documenti",
			   "nb-NO", "Dokumentantall",
			   "nl-BE", "Aantal documenten",
			   "nl-NL", "Aantal documenten",
			   "sv-SE", "Antal dokument",
			   "Document Count"
			)
		isHidden
		lineageTag: 09f61d17-6c6f-47f9-8664-05236f313118

	measure 'Sales Amount and Sales Amount AVG 30D (Fiscal) by Fiscal Month Year Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de ventas e importe medio de ventas 30 días (fiscal) por mes año fiscal",
			   "de-DE", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftlich Monat Jahr",
			   "fr-FR", "Montant vente et montant de ventes moyen 30 jours (fiscal) par mois d’exercice",
			   "cs-CZ", "Částka prodeje a průměrná částka prodeje za 30 dní (fiskální) podle fiskálního měsíce a roku",
			   "da-DK", "Salgsbeløb og salgsbeløb i gennemsnit 30 dage (regnskab) pr. regnskabsmåned år",
			   "de-AT", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftlich Monat Jahr",
			   "de-CH", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftlich Monat Jahr",
			   "en-AU", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year",
			   "en-CA", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year",
			   "en-GB", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year",
			   "en-NZ", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year",
			   "es-MX", "Importe de ventas e importe medio de ventas 30 días (fiscal) por mes año fiscal",
			   "fi-FI", "Myyntisumma ja Myyntisumman keskiarvo 30 päivän ajalta (kirjanpito) kirjanpitokuukauden vuoden mukaan",
			   "fr-BE", "Montant vente et montant de ventes moyen 30 jours (fiscal) par mois d’exercice",
			   "fr-CA", "Montant vente et montant de ventes moyen 30 jours (fiscal) par mois d’exercice",
			   "fr-CH", "Montant vente et montant de ventes moyen 30 jours (fiscal) par mois d’exercice",
			   "is-IS", "Söluupphæð og söluupphæð 30 daga meðaltal (fjárhagur) eftir fjárhagsmánuði Ári",
			   "it-CH", "Importo vendite e media importo vendite 30 giorni (fiscale) per mese e anno fiscale",
			   "it-IT", "Importo vendite e media importo vendite 30 giorni (fiscale) per mese e anno fiscale",
			   "nb-NO", "Salgsbeløp og salgsbeløpgjennomsnitt 30 dager (regnskap) etter Regnskap Måned År",
			   "nl-BE", "Verkoopbedrag en gemiddeld verkoopbedrag 30 dagen (fiscaal) op fiscale maand/jaar",
			   "nl-NL", "Verkoopbedrag en gemiddeld verkoopbedrag 30 dagen (fiscaal) op fiscale maand/jaar",
			   "sv-SE", "Försäljningsbelopp och Försäljningsbelopp genomsnitt 30 dagar (räkenskapskalender) per Räkenskapskalender Månad År",
			   "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year"
			)
		isHidden
		lineageTag: 8a979bba-b616-4fe3-8ddc-2863db69d30d

	measure 'Sales Overview Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Información general de ventas",
			   "de-DE", "Verkauf – Übersicht",
			   "fr-FR", "Vue d’ensemble des ventes",
			   "cs-CZ", "Přehled prodeje",
			   "da-DK", "Salgsoversigt",
			   "de-AT", "Verkauf – Übersicht",
			   "de-CH", "Verkauf – Übersicht",
			   "en-AU", "Sales Overview",
			   "en-CA", "Sales Overview",
			   "en-GB", "Sales Overview",
			   "en-NZ", "Sales Overview",
			   "es-MX", "Información general de ventas",
			   "fi-FI", "Myynnin yleiskatsaus",
			   "fr-BE", "Vue d’ensemble des ventes",
			   "fr-CA", "Vue d’ensemble des ventes",
			   "fr-CH", "Vue d’ensemble des ventes",
			   "is-IS", "Söluyfirlit",
			   "it-CH", "Panoramica delle vendite",
			   "it-IT", "Panoramica delle vendite",
			   "nb-NO", "Oversikt over salg",
			   "nl-BE", "Verkoopoverzicht",
			   "nl-NL", "Verkoopoverzicht",
			   "sv-SE", "Försäljningsöversikt",
			   "Sales Overview"
			)
		isHidden
		lineageTag: e9b48a8f-eb89-43e4-a020-0c5e76028399

	measure 'Daily Sales Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas diarias",
			   "de-DE", "Tägliche Verkäufe",
			   "fr-FR", "Ventes quotidiennes",
			   "cs-CZ", "Denní prodej",
			   "da-DK", "Dagligt salg",
			   "de-AT", "Tägliche Verkäufe",
			   "de-CH", "Tägliche Verkäufe",
			   "en-AU", "Daily Sales",
			   "en-CA", "Daily Sales",
			   "en-GB", "Daily Sales",
			   "en-NZ", "Daily Sales",
			   "es-MX", "Ventas diarias",
			   "fi-FI", "Päivittäinen myynti",
			   "fr-BE", "Ventes quotidiennes",
			   "fr-CA", "Ventes quotidiennes",
			   "fr-CH", "Ventes quotidiennes",
			   "is-IS", "Dagleg sala",
			   "it-CH", "Vendite giornaliere",
			   "it-IT", "Vendite giornaliere",
			   "nb-NO", "Daglig salg",
			   "nl-BE", "Dagelijkse verkoop",
			   "nl-NL", "Dagelijkse verkoop",
			   "sv-SE", "Daglig försäljning",
			   "Daily Sales"
			)
		isHidden
		lineageTag: 92d84a2a-2a28-42e4-8f1c-d8e6464199d6

	measure 'Moving Averages Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Medias móviles",
			   "de-DE", "Gleitender Durchschnitt",
			   "fr-FR", "Moyennes mobiles",
			   "cs-CZ", "Klouzavé průměry",
			   "da-DK", "Glidende gennemsnit",
			   "de-AT", "Gleitender Durchschnitt",
			   "de-CH", "Gleitender Durchschnitt",
			   "en-AU", "Moving Averages",
			   "en-CA", "Moving Averages",
			   "en-GB", "Moving Averages",
			   "en-NZ", "Moving Averages",
			   "es-MX", "Medias móviles",
			   "fi-FI", "Liukuvat keskiarvot",
			   "fr-BE", "Moyennes mobiles",
			   "fr-CA", "Moyennes mobiles",
			   "fr-CH", "Moyennes mobiles",
			   "is-IS", "Hlaupandi meðaltal",
			   "it-CH", "Medie mobili",
			   "it-IT", "Medie mobili",
			   "nb-NO", "Glidende gjennomsnitt",
			   "nl-BE", "Voortschrijdende gemiddelden",
			   "nl-NL", "Voortschrijdende gemiddelden",
			   "sv-SE", "Glidande medelvärde",
			   "Moving Averages"
			)
		isHidden
		lineageTag: 08ccc637-27ee-44da-9cb8-85dd8af58e46

	measure 'Moving Annual Total Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Total anual móvil",
			   "de-DE", "Gleitend Jahr Gesamt",
			   "fr-FR", "Total annuel mobile",
			   "cs-CZ", "Roční pohyblivý součet",
			   "da-DK", "Flytning af årligt total",
			   "de-AT", "Gleitend Jahr Gesamt",
			   "de-CH", "Gleitend Jahr Gesamt",
			   "en-AU", "Moving Annual Total",
			   "en-CA", "Moving Annual Total",
			   "en-GB", "Moving Annual Total",
			   "en-NZ", "Moving Annual Total",
			   "es-MX", "Total anual móvil",
			   "fi-FI", "Liukuva vuosittainen kokonaissumma",
			   "fr-BE", "Total annuel mobile",
			   "fr-CA", "Total annuel mobile",
			   "fr-CH", "Total annuel mobile",
			   "is-IS", "Hlaupandi alls yfir árið",
			   "it-CH", "Totale annuo mobile",
			   "it-IT", "Totale annuo mobile",
			   "nb-NO", "Glidende årssum",
			   "nl-BE", "Voortschrijdend jaarlijks totaal",
			   "nl-NL", "Voortschrijdend jaarlijks totaal",
			   "sv-SE", "Glidande årssumma",
			   "Moving Annual Total"
			)
		isHidden
		lineageTag: b326446f-3d61-4f3d-86ce-b3f990ded45e

	measure 'Previous Year MAT and MAT by Fiscal Month Year Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Año anterior TAM y TAM por mes año fiscal",
			   "de-DE", "Vorjahres-GJG und GJG nach Geschäftlich Monat Jahr",
			   "fr-FR", "TAM de l’année précédente et TAM par mois d’exercice",
			   "cs-CZ", "RPS předchozího roku a RPS podle fiskálního měsíce a roku",
			   "da-DK", "Forrige år GÅT og GÅT efter regnskabsmåned år",
			   "de-AT", "Vorjahres-GJG und GJG nach Geschäftlich Monat Jahr",
			   "de-CH", "Vorjahres-GJG und GJG nach Geschäftlich Monat Jahr",
			   "en-AU", "Previous Year MAT and MAT by Fiscal Month Year",
			   "en-CA", "Previous Year MAT and MAT by Fiscal Month Year",
			   "en-GB", "Previous Year MAT and MAT by Fiscal Month Year",
			   "en-NZ", "Previous Year MAT and MAT by Fiscal Month Year",
			   "es-MX", "Año anterior TAM y TAM por mes año fiscal",
			   "fi-FI", "Edellisen vuoden LVK ja LVK kirjanpidon kuukauden vuoden mukaan",
			   "fr-BE", "TAM de l’année précédente et TAM par mois d’exercice",
			   "fr-CA", "TAM de l’année précédente et TAM par mois d’exercice",
			   "fr-CH", "TAM de l’année précédente et TAM par mois d’exercice",
			   "is-IS", "Hlaupandi alls yfir fyrra ár og Hlaupandi alls yfir árið eftir fjárhagsmánuði Ári",
			   "it-CH", "MAT anno precedente e MAT per mese e anno fiscale",
			   "it-IT", "MAT anno precedente e MAT per mese e anno fiscale",
			   "nb-NO", "Forrige år MAT og MAT etter Regnskap Måned År",
			   "nl-BE", "Vorig jaar VJT en VJT per fiscale maand/jaar",
			   "nl-NL", "Vorig jaar VJT en VJT per fiscale maand/jaar",
			   "sv-SE", "Föregående år GÅS och GÅS per Räkenskapskalender Månad År",
			   "Previous Year MAT and MAT by Fiscal Month Year"
			)
		isHidden
		lineageTag: 6009a366-a842-4ca7-bba8-4caeed0d12b8

	measure 'Period-Over-Period Growth Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Crecimiento periodo tras periodo",
			   "de-DE", "Wachstum im Periodenvergleich",
			   "fr-FR", "Croissance d’une période à l’autre",
			   "cs-CZ", "Růst mezi obdobími",
			   "da-DK", "Periode-til-periode vækst",
			   "de-AT", "Wachstum im Periodenvergleich",
			   "de-CH", "Wachstum im Periodenvergleich",
			   "en-AU", "Period-Over-Period Growth",
			   "en-CA", "Period-Over-Period Growth",
			   "en-GB", "Period-Over-Period Growth",
			   "en-NZ", "Period-Over-Period Growth",
			   "es-MX", "Crecimiento periodo tras periodo",
			   "fi-FI", "Kasku kaudesta toiseen",
			   "fr-BE", "Croissance d’une période à l’autre",
			   "fr-CA", "Croissance d’une période à l’autre",
			   "fr-CH", "Croissance d’une période à l’autre",
			   "is-IS", "Vöxtur milli tímabila",
			   "it-CH", "Confronto crescita su periodi",
			   "it-IT", "Confronto crescita su periodi",
			   "nb-NO", "Vekst periode for periode",
			   "nl-BE", "Groei van periode-tot-periode",
			   "nl-NL", "Groei van periode-tot-periode",
			   "sv-SE", "Tillväxt period-för-period",
			   "Period-Over-Period Growth"
			)
		isHidden
		lineageTag: c200d8c4-a21f-43bd-b56d-6a1e74e450d8

	measure 'Month-To-Date Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Mes hasta la fecha",
			   "de-DE", "Monat-bis-heute",
			   "fr-FR", "Cumul mensuel jusqu’à ce jour",
			   "cs-CZ", "Od začátku měsíce k dnešnímu dni",
			   "da-DK", "Måned-til-dato",
			   "de-AT", "Monat-bis-heute",
			   "de-CH", "Monat-bis-heute",
			   "en-AU", "Month-To-Date",
			   "en-CA", "Month-To-Date",
			   "en-GB", "Month-To-Date",
			   "en-NZ", "Month-To-Date",
			   "es-MX", "Mes hasta la fecha",
			   "fi-FI", "Kuukausi päivämäärään",
			   "fr-BE", "Cumul mensuel jusqu’à ce jour",
			   "fr-CA", "Cumul mensuel jusqu’à ce jour",
			   "fr-CH", "Cumul mensuel jusqu’à ce jour",
			   "is-IS", "Mánuður dagsetningar",
			   "it-CH", "Da inizio mese a oggi",
			   "it-IT", "Da inizio mese a oggi",
			   "nb-NO", "Måned hittil",
			   "nl-BE", "Maand-tot-heden",
			   "nl-NL", "Maand-tot-heden",
			   "sv-SE", "Månad-till-datum",
			   "Month-To-Date"
			)
		isHidden
		lineageTag: c2730c79-1736-47a3-8be3-95afe439fdcb

	measure '% Share of Sales Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "% cuota de ventas",
			   "de-DE", "% Anteil der Verkäufe",
			   "fr-FR", "% part des ventes",
			   "cs-CZ", "% podíl z prodeje",
			   "da-DK", "Procent af del af salget",
			   "de-AT", "% Anteil der Verkäufe",
			   "de-CH", "% Anteil der Verkäufe",
			   "en-AU", "% Share of Sales",
			   "en-CA", "% Share of Sales",
			   "en-GB", "% Share of Sales",
			   "en-NZ", "% Share of Sales",
			   "es-MX", "% cuota de ventas",
			   "fi-FI", "Prosenttiosuus myynnistä",
			   "fr-BE", "% participation des ventes",
			   "fr-CA", "% action des ventes",
			   "fr-CH", "% part des ventes",
			   "is-IS", "% hlutfall af sölu",
			   "it-CH", "% quota delle vendite",
			   "it-IT", "% quota delle vendite",
			   "nb-NO", "Prosentandel av salg",
			   "nl-BE", "% aandeel in omzet",
			   "nl-NL", "% aandeel in omzet",
			   "sv-SE", "% av försäljningskostnaden",
			   "% Share of Sales"
			)
		isHidden
		lineageTag: 69a956fc-bae9-4cb6-901f-0ec098fde823

	measure 'Sales Amount, Sales Quantity and Gross Profit by Item Category Code Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe ventas, cantidad venta y beneficio bruto por código de categoría de producto",
			   "de-DE", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Artikelkategoriencode",
			   "fr-FR", "Montant vente, quantité vente et bénéfice brut par code catégorie article",
			   "cs-CZ", "Částka prodeje, množství prodeje a hrubý zisk podle kódu kategorie zboží",
			   "da-DK", "Salgsbeløb, salgsantal og bruttoavance efter varekategorikode",
			   "de-AT", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Artikelkategoriencode",
			   "de-CH", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Artikelkategoriencode",
			   "en-AU", "Sales Amount, Sales Quantity and Gross Profit by Item Category Code",
			   "en-CA", "Sales Amount, Sales Quantity and Gross Profit by Item Category Code",
			   "en-GB", "Sales Amount, Sales Quantity and Gross Profit by Item Category Code",
			   "en-NZ", "Sales Amount, Sales Quantity and Gross Profit by Item Category Code",
			   "es-MX", "Importe ventas, cantidad venta y beneficio bruto por código de categoría de producto",
			   "fi-FI", "Myyntisumma, myyntimäärä ja bruttovoitto nimikeluokan koodin mukaan",
			   "fr-BE", "Montant vente, quantité vente et bénéfice brut par code catégorie article",
			   "fr-CA", "Montant vente, quantité vente et profit brut par code catégorie article",
			   "fr-CH", "Montant vente, quantité vente et bénéfice brut par code catégorie article",
			   "is-IS", "Söluupphæð, sölumagn og brúttóframlegð eftir vöruflokkakóða",
			   "it-CH", "Importo vendite, quantità vendite e profitto lordo per codice categoria articolo",
			   "it-IT", "Importo vendite, quantità vendite e profitto lordo per codice categoria articolo",
			   "nb-NO", "Salgsbeløp, salgsantall og bruttofortjeneste etter varekategorikode",
			   "nl-BE", "Verkoopbedrag, verkoopaantal en brutowinst op artikelcategoriecode",
			   "nl-NL", "Verkoopbedrag, verkoopaantal en brutowinst op artikelcategoriecode",
			   "sv-SE", "Försäljningsbelopp, Försäljningsantal och Bruttovinst per Artikelkategorinamn",
			   "Sales Amount, Sales Quantity and Gross Profit by Item Category Code"
			)
		isHidden
		lineageTag: 00dbac6a-4c9f-498b-b7bb-ff25028f886f

	measure 'Sales by Item Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas por producto",
			   "de-DE", "Verkauf nach Artikel",
			   "fr-FR", "Ventes par article",
			   "cs-CZ", "Prodej podle zboží",
			   "da-DK", "Salg efter vare",
			   "de-AT", "Verkauf nach Artikel",
			   "de-CH", "Verkauf nach Artikel",
			   "en-AU", "Sales by Item",
			   "en-CA", "Sales by Item",
			   "en-GB", "Sales by Item",
			   "en-NZ", "Sales by Item",
			   "es-MX", "Ventas por producto",
			   "fi-FI", "Nimikekohtainen myynti",
			   "fr-BE", "Ventes par article",
			   "fr-CA", "Ventes par article",
			   "fr-CH", "Ventes par article",
			   "is-IS", "Sala eftir vöru",
			   "it-CH", "Vendite per articolo",
			   "it-IT", "Vendite per articolo",
			   "nb-NO", "Salg etter vare",
			   "nl-BE", "Verkopen op artikel",
			   "nl-NL", "Verkopen op artikel",
			   "sv-SE", "Försäljning per artikel",
			   "Sales by Item"
			)
		isHidden
		lineageTag: 356a5cb4-3e5f-4a71-ab33-648d66114f57

	measure 'Sales by Customer Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas por cliente",
			   "de-DE", "Umsatz nach Debitor",
			   "fr-FR", "Ventes par client",
			   "cs-CZ", "Prodej podle zákazníka",
			   "da-DK", "Salg pr. debitor",
			   "de-AT", "Umsatz nach Debitor",
			   "de-CH", "Umsatz nach Debitor",
			   "en-AU", "Sales by Customer",
			   "en-CA", "Sales by Customer",
			   "en-GB", "Sales by Customer",
			   "en-NZ", "Sales by Customer",
			   "es-MX", "Ventas por cliente",
			   "fi-FI", "Asiakaskohtainen myynti",
			   "fr-BE", "Ventes par client",
			   "fr-CA", "Ventes par client",
			   "fr-CH", "Ventes par client",
			   "is-IS", "Sala eftir viðskiptavini",
			   "it-CH", "Vendite per cliente",
			   "it-IT", "Vendite per cliente",
			   "nb-NO", "Salg etter kunde",
			   "nl-BE", "Verkopen op klant",
			   "nl-NL", "Verkopen op klant",
			   "sv-SE", "Försäljning per kund",
			   "Sales by Customer"
			)
		isHidden
		lineageTag: 8596cf15-88ad-450f-84d2-cdce3d9ba25b

	measure 'Sales Amount, Sales Quantity and Gross Profit by Customer Name Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe ventas, cantidad venta y beneficio bruto por nombre de cliente",
			   "de-DE", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Debitorname",
			   "fr-FR", "Montant vente, quantité vente et bénéfice brut par nom de client",
			   "cs-CZ", "Částka prodeje, množství prodeje a hrubý zisk podle jména zákazníka",
			   "da-DK", "Salgsbeløb, salgsantal og bruttoavance efter debitornavn",
			   "de-AT", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Debitorname",
			   "de-CH", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Debitorname",
			   "en-AU", "Sales Amount, Sales Quantity and Gross Profit by Customer Name",
			   "en-CA", "Sales Amount, Sales Quantity and Gross Profit by Customer Name",
			   "en-GB", "Sales Amount, Sales Quantity and Gross Profit by Customer Name",
			   "en-NZ", "Sales Amount, Sales Quantity and Gross Profit by Customer Name",
			   "es-MX", "Importe ventas, cantidad venta y beneficio bruto por nombre de cliente",
			   "fi-FI", "Myyntisumma, myyntimäärä ja bruttovoitto asiakkaan nimen mukaan",
			   "fr-BE", "Montant vente, quantité vente et bénéfice brut par nom de client",
			   "fr-CA", "Montant vente, quantité vente et profit brut par nom de client",
			   "fr-CH", "Montant vente, quantité vente et bénéfice brut par nom de client",
			   "is-IS", "Söluupphæð, sölumagn og brúttóframlegð eftir nafni viðskiptavinar",
			   "it-CH", "Importo vendite, quantità vendite e profitto lordo per nome cliente",
			   "it-IT", "Importo vendite, quantità vendite e profitto lordo per nome cliente",
			   "nb-NO", "Salgsbeløp, salgsantall og bruttofortjeneste etter kundenavn",
			   "nl-BE", "Verkoopbedrag, verkoopaantal en brutowinst op klantnaam",
			   "nl-NL", "Verkoopbedrag, verkoopaantal en brutowinst op klantnaam",
			   "sv-SE", "Försäljningsbelopp, Försäljningsantal och Bruttovinst efter Kundnamn",
			   "Sales Amount, Sales Quantity and Gross Profit by Customer Name"
			)
		isHidden
		lineageTag: 7452e6c0-dbed-4cf0-8191-df5fac579967

	measure 'Sales by Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Equipos por vendedor",
			   "de-DE", "Verkäufe nach Verkäufer",
			   "fr-FR", "Ventes par vendeur",
			   "cs-CZ", "Prodej podle prodejce",
			   "da-DK", "Salg efter sælger",
			   "de-AT", "Verkäufe nach Verkäufer",
			   "de-CH", "Verkäufe nach Verkäufer",
			   "en-AU", "Sales by Salesperson",
			   "en-CA", "Sales by Salesperson",
			   "en-GB", "Sales by Salesperson",
			   "en-NZ", "Sales by Salesperson",
			   "es-MX", "Equipos por vendedor",
			   "fi-FI", "Myynti myyjän mukaan",
			   "fr-BE", "Ventes par vendeur",
			   "fr-CA", "Ventes par représentant",
			   "fr-CH", "Ventes par vendeur",
			   "is-IS", "Sala eftir sölumanni",
			   "it-CH", "Vendite per venditore",
			   "it-IT", "Vendite per venditore",
			   "nb-NO", "Salg etter selger",
			   "nl-BE", "Verkoop per verkoper",
			   "nl-NL", "Verkoop per verkoper",
			   "sv-SE", "Försäljning per säljare",
			   "Sales by Salesperson"
			)
		isHidden
		lineageTag: 31175767-d476-4820-8a9b-515283517dc2

	measure 'Sales Amount, Sales Quantity and Gross Profit by Salesperson Code Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe ventas, cantidad venta y beneficio bruto por código de vendedor",
			   "de-DE", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Verkäufercode",
			   "fr-FR", "Montant vente, quantité vente et bénéfice brut par code vendeur",
			   "cs-CZ", "Částka prodeje, množství prodeje a hrubý zisk podle kódu prodejce",
			   "da-DK", "Salgsbeløb, salgsantal og bruttoavance efter sælgerkode",
			   "de-AT", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Verkäufercode",
			   "de-CH", "Verkaufsbetrag, Verkaufsmenge und Bruttogewinn nach Verkäufercode",
			   "en-AU", "Sales Amount, Sales Quantity and Gross Profit by Salesperson Code",
			   "en-CA", "Sales Amount, Sales Quantity and Gross Profit by Salesperson Code",
			   "en-GB", "Sales Amount, Sales Quantity and Gross Profit by Salesperson Code",
			   "en-NZ", "Sales Amount, Sales Quantity and Gross Profit by Salesperson Code",
			   "es-MX", "Importe ventas, cantidad venta y beneficio bruto por código de vendedor",
			   "fi-FI", "Myyntisumma, myyntimäärä ja bruttovoitto myyjäkoodin mukaan",
			   "fr-BE", "Montant vente, quantité vente et bénéfice brut par code vendeur",
			   "fr-CA", "Montant vente, quantité vente et profit brut par code représentant",
			   "fr-CH", "Montant vente, quantité vente et bénéfice brut par code vendeur",
			   "is-IS", "Söluupphæð, sölumagn og brúttóframlegð eftir kóða sölumanns",
			   "it-CH", "Importo vendite, quantità vendite e profitto lordo per codice venditore",
			   "it-IT", "Importo vendite, quantità vendite e profitto lordo per codice venditore",
			   "nb-NO", "Salgsbeløp, salgsantall og bruttofortjeneste etter selgerkode",
			   "nl-BE", "Verkoopbedrag, verkoopaantal en brutowinst op verkoperscode",
			   "nl-NL", "Verkoopbedrag, verkoopaantal en brutowinst op verkoperscode",
			   "sv-SE", "Försäljningsbelopp, Försäljningsantal och Bruttovinst per Säljarkod",
			   "Sales Amount, Sales Quantity and Gross Profit by Salesperson Code"
			)
		isHidden
		lineageTag: af8afa25-d266-4975-82de-4df5828cf317

	measure 'Actual vs Budget Quantity Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Cantidad real vs. ppto",
			   "de-DE", "Budgetvergleich",
			   "fr-FR", "Quantité réelle/budgétaire",
			   "cs-CZ", "Skutečné vs. rozpočtové množství",
			   "da-DK", "Faktisk vs. budgetantal",
			   "de-AT", "Budgetvergleich",
			   "de-CH", "Budgetvergleich",
			   "en-AU", "Actual vs Budget Quantity",
			   "en-CA", "Actual vs Budget Quantity",
			   "en-GB", "Actual vs Budget Quantity",
			   "en-NZ", "Actual vs Budget Quantity",
			   "es-MX", "Cantidad real vs. ppto",
			   "fi-FI", "Toteutunut vs. budjetoitu määrä",
			   "fr-BE", "Quantité réelle/budgétaire",
			   "fr-CA", "Quantité réelle/budgétaire",
			   "fr-CH", "Quantité réelle/budgétaire",
			   "is-IS", "Raunverulegt magn sb. v. áætlað magn",
			   "it-CH", "Quantità - Effettiva/in budget",
			   "it-IT", "Quantità - Effettiva/in budget",
			   "nb-NO", "Faktisk antall kontra budsjettantall",
			   "nl-BE", "Werkelijk versus budgetaantal",
			   "nl-NL", "Werkelijk versus budgetaantal",
			   "sv-SE", "Faktiskt vs. budgeterat antal",
			   "Actual vs Budget Quantity"
			)
		isHidden
		lineageTag: 90c6c4eb-b09a-4ab6-9e85-5f48ae1c8c67

	measure 'Actual vs Budget Amount Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe real vs. ppto",
			   "de-DE", "Tatsächlicher vs Budgetbetrag",
			   "fr-FR", "Montant réel/budgétaire",
			   "cs-CZ", "Skutečná vs. rozpočtovaná částka",
			   "da-DK", "Faktisk vs. budgetbeløb",
			   "de-AT", "Tatsächlicher vs Budgetbetrag",
			   "de-CH", "Tatsächlicher vs Budgetbetrag",
			   "en-AU", "Actual vs Budget Amount",
			   "en-CA", "Actual vs Budget Amount",
			   "en-GB", "Actual vs Budget Amount",
			   "en-NZ", "Actual vs Budget Amount",
			   "es-MX", "Importe real vs. ppto",
			   "fi-FI", "Toteutunut vs. budjetoitu summa",
			   "fr-BE", "Montant réel/budgétaire",
			   "fr-CA", "Montant réel/budgétaire",
			   "fr-CH", "Montant réel/budgétaire",
			   "is-IS", "Raunveruleg upphæð sb. v. áætlaða upphæð",
			   "it-CH", "Importo - Effettivo/in budget",
			   "it-IT", "Importo - Effettivo/in budget",
			   "nb-NO", "Faktisk beløp kontra budsjettbeløp",
			   "nl-BE", "Werkelijk versus budgetbedrag",
			   "nl-NL", "Werkelijk versus budgetbedrag",
			   "sv-SE", "Faktiskt vs. budgeterat belopp",
			   "Actual vs Budget Amount"
			)
		isHidden
		lineageTag: a1397aac-7415-44c0-9eac-969cc54eeb2a

	measure 'Sales Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas",
			   "de-DE", "VERKAUF",
			   "fr-FR", "Ventes",
			   "cs-CZ", "Prodej",
			   "da-DK", "Salg",
			   "de-AT", "VERKAUF",
			   "de-CH", "VERKAUF",
			   "en-AU", "Sales",
			   "en-CA", "Sales",
			   "en-GB", "Sales",
			   "en-NZ", "Sales",
			   "es-MX", "Ventas",
			   "fi-FI", "Myynti",
			   "fr-BE", "Ventes",
			   "fr-CA", "Ventes",
			   "fr-CH", "Ventes",
			   "is-IS", "Sala",
			   "it-CH", "Vendite",
			   "it-IT", "Vendite",
			   "nb-NO", "Salg",
			   "nl-BE", "Verkopen",
			   "nl-NL", "Verkopen",
			   "sv-SE", "Försäljning",
			   "Sales"
			)
		isHidden
		lineageTag: f5d5b444-f6c2-4250-a836-d8aec0eccdff

	measure 'for Business Central Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "para Business Central",
			   "de-DE", "für Business Central",
			   "fr-FR", "pour Business Central",
			   "cs-CZ", "pro Business Central",
			   "da-DK", "til Business Central",
			   "de-AT", "für Business Central",
			   "de-CH", "für Business Central",
			   "en-AU", "for Business Central",
			   "en-CA", "for Business Central",
			   "en-GB", "for Business Central",
			   "en-NZ", "for Business Central",
			   "es-MX", "para Business Central",
			   "fi-FI", "Business Centralille",
			   "fr-BE", "pour Business Central",
			   "fr-CA", "pour Business Central",
			   "fr-CH", "pour Business Central",
			   "is-IS", "fyrir Business Central",
			   "it-CH", "per Business Central",
			   "it-IT", "per Business Central",
			   "nb-NO", "for Business Central",
			   "nl-BE", "voor Business Central",
			   "nl-NL", "voor Business Central",
			   "sv-SE", "för Business Central",
			   "for Business Central"
			)
		isHidden
		lineageTag: cf8527ca-4eff-4df7-b12a-9e963a7489df

	measure 'USE, EDIT AND BUILD YOUR OWN REPORTS Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "USAR, EDITAR Y CREAR SUS PROPIOS INFORMES",
			   "de-DE", "EIGENE BERICHTE VERWENDEN, BEARBEITEN UND ERSTELLEN",
			   "fr-FR", "UTILISEZ, MODIFIEZ ET CRÉEZ VOS PROPRES ÉTATS",
			   "cs-CZ", "POUŽÍVÁNÍ, ÚPRAVA A TVORBA VLASTNÍCH SESTAV",
			   "da-DK", "BRUG, REDIGER OG OPRET DINE EGNE RAPPORTER",
			   "de-AT", "EIGENE BERICHTE VERWENDEN, BEARBEITEN UND ERSTELLEN",
			   "de-CH", "EIGENE BERICHTE VERWENDEN, BEARBEITEN UND ERSTELLEN",
			   "en-AU", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "en-CA", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "en-GB", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "en-NZ", "USE, EDIT AND BUILD YOUR OWN REPORTS",
			   "es-MX", "USAR, EDITAR Y CREAR SUS PROPIOS INFORMES",
			   "fi-FI", "KÄYTÄ, MUOKKAA JA LUO OMIA RAPORTTEJA",
			   "fr-BE", "UTILISEZ, MODIFIEZ ET CRÉEZ VOS PROPRES ÉTATS",
			   "fr-CA", "UTILISEZ, MODIFIEZ ET CRÉEZ VOS PROPRES RAPPORTS",
			   "fr-CH", "UTILISEZ, MODIFIEZ ET CRÉEZ VOS PROPRES ÉTATS",
			   "is-IS", "NOTAÐU, BREYTTU OG GERÐU ÞÍNAR EIGIN SKÝRSLUR",
			   "it-CH", "USA, MODIFICA E CREA I TUOI REPORT",
			   "it-IT", "USA, MODIFICA E CREA I TUOI REPORT",
			   "nb-NO", "BRUK, REDIGER OG BYGG DINE EGNE RAPPORTER",
			   "nl-BE", "UW EIGEN RAPPORTEN GEBRUIKEN, BEWERKEN EN MAKEN",
			   "nl-NL", "UW EIGEN RAPPORTEN GEBRUIKEN, BEWERKEN EN MAKEN",
			   "sv-SE", "ANVÄND, REDIGERA OCH SKAPA EGNA RAPPORTER",
			   "USE, EDIT AND BUILD YOUR OWN REPORTS"
			)
		isHidden
		lineageTag: 171d9506-4920-45c2-ba90-fae024e518f4

	measure 'Sales includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch. Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas incluye una variedad de informes prediseñados para ayudarlo a ver sus datos de inmediato. Puede editar estos informes o crear su propio informe desde cero.",
			   "de-DE", "Verkäufe enthält eine Vielzahl vordefinierter Berichte, mit denen Sie Ihre Daten unmittelbar ansehen können. Sie können diese Berichte bearbeiten oder Ihren eigenen Bericht von Grund auf neu erstellen.",
			   "fr-FR", "Ventes inclut une variété d’états prédéfinis pour vous aider à voir vos données immédiatement. Vous pouvez modifier ces états ou créer votre propre état à partir de zéro.",
			   "cs-CZ", "Prodej obsahuje řadu předpřipravených sestav, které vám pomohou okamžitě zobrazit vaše data. Tyto sestavy můžete upravovat nebo si vytvořit vlastní sestavu od základu.",
			   "da-DK", "Salg indeholder en række færdigbyggede rapporter, der hjælper dig med at få vist dine data med det samme. Du kan redigere disse rapporter eller oprette din egen rapport fra bunden.",
			   "de-AT", "Verkäufe enthält eine Vielzahl vordefinierter Berichte, mit denen Sie Ihre Daten unmittelbar ansehen können. Sie können diese Berichte bearbeiten oder Ihren eigenen Bericht von Grund auf neu erstellen.",
			   "de-CH", "Verkäufe enthält eine Vielzahl vordefinierter Berichte, mit denen Sie Ihre Daten unmittelbar ansehen können. Sie können diese Berichte bearbeiten oder Ihren eigenen Bericht von Grund auf neu erstellen.",
			   "en-AU", "Sales includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "en-CA", "Sales includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "en-GB", "Sales includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "en-NZ", "Sales includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch.",
			   "es-MX", "Ventas incluye una variedad de informes prediseñados para ayudarlo a ver sus datos de inmediato. Puede editar estos informes o crear su propio informe desde cero.",
			   "fi-FI", "Myynti sisältää erilaisia esimääritettyjä raportteja, joiden avulla voit tarkastella tietojasi välittömästi. Voit muokata näitä raportteja tai luoda oman raportin alusta alkaen.",
			   "fr-BE", "Ventes inclut une variété d’états prédéfinis pour vous aider à voir vos données immédiatement. Vous pouvez modifier ces états ou créer votre propre état à partir de zéro.",
			   "fr-CA", "Ventes inclut une variété de rapports prédéfinis pour vous aider à voir vos données immédiatement. Vous pouvez modifier ces rapports ou créer votre propre rapport à partir de zéro.",
			   "fr-CH", "Ventes inclut une variété d’états prédéfinis pour vous aider à voir vos données immédiatement. Vous pouvez modifier ces états ou créer votre propre état à partir de zéro.",
			   "is-IS", "Sala býður upp á innbyggðar skýrslur til að skoða gögn samstundis. Hægt er að breyta skýrslunum eða búa til eigin skýrslur frá grunni.",
			   "it-CH", "Le vendite includono una serie di report predefiniti che consentono di visualizzare immediatamente i dati. È possibile modificare questi report o creare il proprio report da zero.",
			   "it-IT", "Le vendite includono una serie di report predefiniti che consentono di visualizzare immediatamente i dati. È possibile modificare questi report o creare il proprio report da zero.",
			   "nb-NO", "Salg inneholder en rekke forhåndsbygde rapporter som hjelper deg med å se dataene umiddelbart. Du kan redigere disse rapportene eller lage din egen rapport fra bunnen av.",
			   "nl-BE", "Verkopen bevatten een verscheidenheid aan vooraf gemaakte rapporten om u te helpen uw gegevens direct te bekijken. U kunt deze rapporten bewerken of uw eigen rapport helemaal opnieuw maken.",
			   "nl-NL", "Verkopen bevatten een verscheidenheid aan vooraf gemaakte rapporten om u te helpen uw gegevens direct te bekijken. U kunt deze rapporten bewerken of uw eigen rapport helemaal opnieuw maken.",
			   "sv-SE", "Försäljning omfattar en mängd olika färdiga rapporter som gör det enkelt att se data direkt. Du kan redigera dessa rapporter eller skapa en egen rapport från grunden.",
			   "Sales includes a variety of pre-built reports to help you see your data immediately. You are able to edit these reports or build your own report from scratch."
			)
		isHidden
		lineageTag: 7f16985e-9513-4ed5-b0bf-2c17c382bf45

	measure 'CONNECT YOUR DATA Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "CONECTAR LOS DATOS",
			   "de-DE", "MIT EIGENEN DATEN VERBINDEN",
			   "fr-FR", "CONNECTER VOS DONNÉES",
			   "cs-CZ", "PŘIPOJENÍ DAT",
			   "da-DK", "FORBIND DINE DATA",
			   "de-AT", "MIT EIGENEN DATEN VERBINDEN",
			   "de-CH", "MIT EIGENEN DATEN VERBINDEN",
			   "en-AU", "CONNECT YOUR DATA",
			   "en-CA", "CONNECT YOUR DATA",
			   "en-GB", "CONNECT YOUR DATA",
			   "en-NZ", "CONNECT YOUR DATA",
			   "es-MX", "CONECTAR LOS DATOS",
			   "fi-FI", "YHDISTÄ TIETOSI",
			   "fr-BE", "CONNECTER VOS DONNÉES",
			   "fr-CA", "CONNECTER VOS DONNÉES",
			   "fr-CH", "CONNECTER VOS DONNÉES",
			   "is-IS", "TENGDU GÖGNIN ÞÍN",
			   "it-CH", "CONNETTI I DATI",
			   "it-IT", "CONNETTI I DATI",
			   "nb-NO", "KOBLE TIL DATAENE",
			   "nl-BE", "UW GEGEVENS VERBINDEN",
			   "nl-NL", "UW GEGEVENS VERBINDEN",
			   "sv-SE", "ANSLUT DINA DATA",
			   "CONNECT YOUR DATA"
			)
		isHidden
		lineageTag: 434ce231-c4ce-48c3-9d03-04fae06bc699

	measure '1. Download the Sales Connector for Power BI Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "1. Descargar Sales Connector for Power BI",
			   "de-DE", "1. Sales Connector for Power BI herunterladen",
			   "fr-FR", "1. Téléchargez Sales Connector for Power BI",
			   "cs-CZ", "1. Stažení řešení Sales Connector for Power BI",
			   "da-DK", "1. Download Sales Connector for Power BI",
			   "de-AT", "1. Sales Connector for Power BI herunterladen",
			   "de-CH", "1. Sales Connector for Power BI herunterladen",
			   "en-AU", "1. Download the Sales Connector for Power BI",
			   "en-CA", "1. Download the Sales Connector for Power BI",
			   "en-GB", "1. Download the Sales Connector for Power BI",
			   "en-NZ", "1. Download the Sales Connector for Power BI",
			   "es-MX", "1. Descargar Sales Connector for Power BI",
			   "fi-FI", "1. Lataa Sales Connector for Power BI",
			   "fr-BE", "1. Téléchargez Sales Connector for Power BI",
			   "fr-CA", "1. Téléchargez Sales Connector for Power BI",
			   "fr-CH", "1. Téléchargez Sales Connector for Power BI",
			   "is-IS", "1. Sækja Sales Connector for Power BI",
			   "it-CH", "1. Scaricare Sales Connector for Power BI",
			   "it-IT", "1. Scaricare Sales Connector for Power BI",
			   "nb-NO", "1. Last ned Sales Connector for Power BI",
			   "nl-BE", "1. Download de Sales Connector for Power BI",
			   "nl-NL", "1. Download de Sales Connector for Power BI",
			   "sv-SE", "1. Ladda ned Sales Connector for Power BI",
			   "1. Download the Sales Connector for Power BI"
			)
		isHidden
		lineageTag: 5c531cea-f51a-4167-8f9c-20e077b72c7a

	measure '2. Configure Dynamics 365 Business Central Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "2. Configurar Dynamics 365 Business Central",
			   "de-DE", "2. Dynamics 365 Business Central konfigurieren",
			   "fr-FR", "2. Configurez Dynamics 365 Business Central",
			   "cs-CZ", "2. Konfigurace Dynamics 365 Business Central",
			   "da-DK", "2. Konfigurer Dynamics 365 Business Central",
			   "de-AT", "2. Dynamics 365 Business Central konfigurieren",
			   "de-CH", "2. Dynamics 365 Business Central konfigurieren",
			   "en-AU", "2. Configure Dynamics 365 Business Central",
			   "en-CA", "2. Configure Dynamics 365 Business Central",
			   "en-GB", "2. Configure Dynamics 365 Business Central",
			   "en-NZ", "2. Configure Dynamics 365 Business Central",
			   "es-MX", "2. Configurar Dynamics 365 Business Central",
			   "fi-FI", "2. Määritä Dynamics 365 Business Central",
			   "fr-BE", "2. Configurez Dynamics 365 Business Central",
			   "fr-CA", "2. Configurez Dynamics 365 Business Central",
			   "fr-CH", "2. Configurez Dynamics 365 Business Central",
			   "is-IS", "2. Stilla Dynamics 365 Business Central",
			   "it-CH", "2. Configurare Dynamics 365 Business Central",
			   "it-IT", "2. Configurare Dynamics 365 Business Central",
			   "nb-NO", "2. Konfigurer Dynamics 365 Business Central",
			   "nl-BE", "2. Dynamics 365 Business Central configureren",
			   "nl-NL", "2. Dynamics 365 Business Central configureren",
			   "sv-SE", "2. Konfigurera Dynamics 365 Business Central",
			   "2. Configure Dynamics 365 Business Central"
			)
		isHidden
		lineageTag: 55568433-1340-4583-a5a5-4b7330b600c8

	measure 'HELP AND SUPPORT Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "AYUDA Y SOPORTE",
			   "de-DE", "HILFE UND SUPPORT",
			   "fr-FR", "AIDE ET SUPPORT",
			   "cs-CZ", "POMOC A PODPORA",
			   "da-DK", "HJÆLP OG SUPPORT",
			   "de-AT", "HILFE UND SUPPORT",
			   "de-CH", "HILFE UND SUPPORT",
			   "en-AU", "HELP AND SUPPORT",
			   "en-CA", "HELP AND SUPPORT",
			   "en-GB", "HELP AND SUPPORT",
			   "en-NZ", "HELP AND SUPPORT",
			   "es-MX", "AYUDA Y SOPORTE",
			   "fi-FI", "OHJE JA TUKI",
			   "fr-BE", "AIDE ET SUPPORT",
			   "fr-CA", "AIDE ET SUPPORT",
			   "fr-CH", "AIDE ET SUPPORT",
			   "is-IS", "HJÁLP OG STUÐNINGUR",
			   "it-CH", "GUIDA E SUPPORTO",
			   "it-IT", "GUIDA E SUPPORTO",
			   "nb-NO", "HJELP OG KUNDESTØTTE",
			   "nl-BE", "HELP EN ONDERSTEUNING",
			   "nl-NL", "HELP EN ONDERSTEUNING",
			   "sv-SE", "HJÄLP OCH SUPPORT",
			   "HELP AND SUPPORT"
			)
		isHidden
		lineageTag: 0ec97384-b7e6-44d0-acfd-f7abacba7e9a

	measure 'For help and support with your new report please visit the Analytics overview documentation. Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Para obtener ayuda y soporte técnico con su nuevo informe, visite la documentación de información general de Analytics.",
			   "de-DE", "Hilfe und Unterstützung für Ihren neuen Bericht finden Sie in der Dokumentation Analysen – Übersicht.",
			   "fr-FR", "Pour obtenir de l’aide et de l’assistance concernant votre nouvel état, consultez la documentation de vue d’ensemble de l’analyse.",
			   "cs-CZ", "Nápovědu a podporu k nové sestavě naleznete v dokumentaci k přehledu Analytics.",
			   "da-DK", "Du kan få hjælp og support til din nye rapport i dokumentationen til analyseoversigten.",
			   "de-AT", "Hilfe und Unterstützung für Ihren neuen Bericht finden Sie in der Dokumentation Analysen – Übersicht.",
			   "de-CH", "Hilfe und Unterstützung für Ihren neuen Bericht finden Sie in der Dokumentation Analysen – Übersicht.",
			   "en-AU", "For help and support with your new report please visit the Analytics overview documentation.",
			   "en-CA", "For help and support with your new report please visit the Analytics overview documentation.",
			   "en-GB", "For help and support with your new report please visit the Analytics overview documentation.",
			   "en-NZ", "For help and support with your new report please visit the Analytics overview documentation.",
			   "es-MX", "Para obtener ayuda y soporte técnico con su nuevo informe, visite la documentación de información general de Analytics.",
			   "fi-FI", "Lisätietoja ja tukea uudelle raportillesi löydät analytiikan yleiskuvauksesta.",
			   "fr-BE", "Pour obtenir de l’aide et de l’assistance concernant votre nouvel état, consultez la documentation de vue d’ensemble de l’analyse.",
			   "fr-CA", "Pour obtenir de l’aide et de l’assistance concernant votre nouveau rapport, consultez la documentation de vue d’ensemble de l’analyse.",
			   "fr-CH", "Pour obtenir de l’aide et de l’assistance concernant votre nouvel état, consultez la documentation de vue d’ensemble de l’analyse.",
			   "is-IS", "Kynntu þér fylgigögn greiningaryfirlitsins til að fá hjálp og aðstoð varðandi nýju skýrsluna þína.",
			   "it-CH", "Per assistenza e supporto per il nuovo report, vedere la documentazione generale di analisi.",
			   "it-IT", "Per assistenza e supporto per il nuovo report, vedere la documentazione generale di analisi.",
			   "nb-NO", "Hvis du vil ha hjelp og støtte med den nye rapporten, kan du gå til dokumentasjonen for analyseoversikten.",
			   "nl-BE", "Ga voor hulp en ondersteuning met uw nieuwe rapport naar de Analytics-overzichtsdocumentatie.",
			   "nl-NL", "Ga voor hulp en ondersteuning met uw nieuwe rapport naar de Analytics-overzichtsdocumentatie.",
			   "sv-SE", "Hjälp och support med den nya rapporten finns i översiktsdokumentationen för Analys.",
			   "For help and support with your new report please visit the Analytics overview documentation."
			)
		isHidden
		lineageTag: 64013763-ae0f-4653-bc1c-ce13c10dfc90

	measure 'OTHER POWER BI REPORTS Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "OTROS INFORMES DE POWER BI",
			   "de-DE", "SONSTIGE POWER BI-BERICHTE",
			   "fr-FR", "AUTRES ÉTATS POWER BI",
			   "cs-CZ", "DALŠÍ SESTAVY POWER BI",
			   "da-DK", "ANDRE POWER BI-RAPPORTER",
			   "de-AT", "SONSTIGE POWER BI-BERICHTE",
			   "de-CH", "SONSTIGE POWER BI-BERICHTE",
			   "en-AU", "OTHER POWER BI REPORTS",
			   "en-CA", "OTHER POWER BI REPORTS",
			   "en-GB", "OTHER POWER BI REPORTS",
			   "en-NZ", "OTHER POWER BI REPORTS",
			   "es-MX", "OTROS INFORMES DE POWER BI",
			   "fi-FI", "MUUT POWER BI -RAPORTIT",
			   "fr-BE", "AUTRES ÉTATS POWER BI",
			   "fr-CA", "AUTRES RAPPORTS POWER BI",
			   "fr-CH", "AUTRES ÉTATS POWER BI",
			   "is-IS", "AÐRAR POWER BI SKÝRSLUR",
			   "it-CH", "ALTRI REPORT DI POWER BI",
			   "it-IT", "ALTRI REPORT DI POWER BI",
			   "nb-NO", "ANDRE POWER BI-RAPPORTER",
			   "nl-BE", "OVERIGE POWER BI-RAPPORTEN",
			   "nl-NL", "OVERIGE POWER BI-RAPPORTEN",
			   "sv-SE", "ÖVRIGA POWER BI-RAPPORTER",
			   "OTHER POWER BI REPORTS"
			)
		isHidden
		lineageTag: 25356582-b767-449f-8d76-fa85f292993a

	measure 'PURCHASE Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "COMPRA",
			   "de-DE", "EINKAUF",
			   "fr-FR", "ACHATS",
			   "cs-CZ", "NÁKUP",
			   "da-DK", "INDKØB",
			   "de-AT", "EINKAUF",
			   "de-CH", "EINKAUF",
			   "en-AU", "PURCHASE",
			   "en-CA", "PURCHASE",
			   "en-GB", "PURCHASE",
			   "en-NZ", "PURCHASE",
			   "es-MX", "COMPRA",
			   "fi-FI", "OSTO",
			   "fr-BE", "ACHATS",
			   "fr-CA", "ACHATS",
			   "fr-CH", "ACHATS",
			   "is-IS", "INNKAUP",
			   "it-CH", "ACQUISTI",
			   "it-IT", "ACQUISTI",
			   "nb-NO", "INNKJØP",
			   "nl-BE", "INKOOP",
			   "nl-NL", "INKOOP",
			   "sv-SE", "INKÖP",
			   "PURCHASE"
			)
		isHidden
		lineageTag: 747c1a18-19a6-499e-aad6-150175bb27b9

	measure 'FINANCE Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "FINANZAS",
			   "de-DE", "FINANZEN",
			   "fr-FR", "FINANCE",
			   "cs-CZ", "FINANCE",
			   "da-DK", "FINANS",
			   "de-AT", "FINANZEN",
			   "de-CH", "FINANZEN",
			   "en-AU", "FINANCE",
			   "en-CA", "FINANCE",
			   "en-GB", "FINANCE",
			   "en-NZ", "FINANCE",
			   "es-MX", "FINANZAS",
			   "fi-FI", "TALOUSHALLINTO",
			   "fr-BE", "FINANCE",
			   "fr-CA", "FINANCE",
			   "fr-CH", "FINANCE",
			   "is-IS", "FJÁRMÁL",
			   "it-CH", "DATI FINANZIARI",
			   "it-IT", "DATI FINANZIARI",
			   "nb-NO", "FINANS",
			   "nl-BE", "FINANCIËN",
			   "nl-NL", "FINANCIËN",
			   "sv-SE", "EKONOMI",
			   "FINANCE"
			)
		isHidden
		lineageTag: b4d8e6c6-c3ab-4ed1-b2a4-d0c1d09020a7

	measure 'REBATES Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "DEVOLUCIONES",
			   "de-DE", "RÜCKVERGÜTUNGEN",
			   "fr-FR", "REMISES",
			   "cs-CZ", "RABATY",
			   "da-DK", "RABATTER",
			   "de-AT", "RÜCKVERGÜTUNGEN",
			   "de-CH", "RÜCKVERGÜTUNGEN",
			   "en-AU", "REBATES",
			   "en-CA", "REBATES",
			   "en-GB", "REBATES",
			   "en-NZ", "REBATES",
			   "es-MX", "DEVOLUCIONES",
			   "fi-FI", "HYVITYKSET",
			   "fr-BE", "REMISES",
			   "fr-CA", "REMISES",
			   "fr-CH", "REMISES",
			   "is-IS", "EFTIRÁGREIDDIR AFSLÆTTIR",
			   "it-CH", "SCONTI",
			   "it-IT", "SCONTI",
			   "nb-NO", "RABATTER",
			   "nl-BE", "KORTINGEN",
			   "nl-NL", "KORTINGEN",
			   "sv-SE", "RABATTER",
			   "REBATES"
			)
		isHidden
		lineageTag: 8770de2b-94ce-4636-b078-2049b44cbf12

	measure 'INVENTORY Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "INVENTARIO",
			   "de-DE", "LAGERBESTAND",
			   "fr-FR", "STOCK",
			   "cs-CZ", "ZÁSOBY",
			   "da-DK", "LAGERBEHOLDNING",
			   "de-AT", "LAGERBESTAND",
			   "de-CH", "LAGERBESTAND",
			   "en-AU", "INVENTORY",
			   "en-CA", "INVENTORY",
			   "en-GB", "INVENTORY",
			   "en-NZ", "INVENTORY",
			   "es-MX", "INVENTARIO",
			   "fi-FI", "VARASTO",
			   "fr-BE", "STOCK",
			   "fr-CA", "INVENTAIRE",
			   "fr-CH", "STOCK",
			   "is-IS", "BIRGÐIR",
			   "it-CH", "INVENTARIO",
			   "it-IT", "INVENTARIO",
			   "nb-NO", "BEHOLDNING",
			   "nl-BE", "VOORRAAD",
			   "nl-NL", "VOORRAAD",
			   "sv-SE", "LAGER",
			   "INVENTORY"
			)
		isHidden
		lineageTag: ae00d423-a7bd-4177-9865-032b1dc646d0

	measure 'JOBS Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "PROYECTOS",
			   "de-DE", "PROJEKTE",
			   "fr-FR", "PROJETS",
			   "cs-CZ", "ÚLOHY",
			   "da-DK", "JOB",
			   "de-AT", "PROJEKTE",
			   "de-CH", "PROJEKTE",
			   "en-AU", "JOBS",
			   "en-CA", "JOBS",
			   "en-GB", "JOBS",
			   "en-NZ", "JOBS",
			   "es-MX", "PROYECTOS",
			   "fi-FI", "PROJEKTIT",
			   "fr-BE", "PROJETS",
			   "fr-CA", "PROJETS",
			   "fr-CH", "PROJETS",
			   "is-IS", "VERK",
			   "it-CH", "COMMESSE",
			   "it-IT", "COMMESSE",
			   "nb-NO", "PROSJEKTER",
			   "nl-BE", "PROJECTEN",
			   "nl-NL", "PROJECTEN",
			   "sv-SE", "PROJEKT",
			   "JOBS"
			)
		isHidden
		lineageTag: f4c150e1-c1b5-4ac5-8c91-273fb7bd265d

	measure 'SALES  Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "VENTAS ",
			   "de-DE", "VERKAUF",
			   "fr-FR", "VENTES ",
			   "cs-CZ", "PRODEJ ",
			   "da-DK", "SALG ",
			   "de-AT", "VERKAUF",
			   "de-CH", "VERKAUF",
			   "en-AU", "SALES ",
			   "en-CA", "SALES ",
			   "en-GB", "SALES ",
			   "en-NZ", "SALES ",
			   "es-MX", "VENTAS ",
			   "fi-FI", "MYYNTI ",
			   "fr-BE", "VENTES ",
			   "fr-CA", "VENTES ",
			   "fr-CH", "VENTES ",
			   "is-IS", "SALA ",
			   "it-CH", "VENDITE",
			   "it-IT", "VENDITE",
			   "nb-NO", "SALG ",
			   "nl-BE", "VERKOPEN ",
			   "nl-NL", "VERKOPEN ",
			   "sv-SE", "FÖRSÄLJNING ",
			   "SALES "
			)
		isHidden
		lineageTag: a48b9882-3b1e-43f2-9830-59d4d9d6d0b7

	measure 'Sales Amount  Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe ventas ",
			   "de-DE", "Verkaufsbetrag",
			   "fr-FR", "Montant vente ",
			   "cs-CZ", "Částka prodeje ",
			   "da-DK", "Salgsbeløb ",
			   "de-AT", "Verkaufsbetrag",
			   "de-CH", "Verkaufsbetrag",
			   "en-AU", "Sales Amount ",
			   "en-CA", "Sales Amount ",
			   "en-GB", "Sales Amount ",
			   "en-NZ", "Sales Amount ",
			   "es-MX", "Importe ventas ",
			   "fi-FI", "Myyntisumma ",
			   "fr-BE", "Montant vente ",
			   "fr-CA", "Montant vente ",
			   "fr-CH", "Montant vente ",
			   "is-IS", "Söluupphæð ",
			   "it-CH", "Importo vendite",
			   "it-IT", "Importo vendite",
			   "nb-NO", "Salgsbeløp ",
			   "nl-BE", "Verkoopbedrag ",
			   "nl-NL", "Verkoopbedrag ",
			   "sv-SE", "Försäljningsbelopp ",
			   "Sales Amount "
			)
		isHidden
		lineageTag: 59cfd50c-9546-4162-8ec5-47672418acbd

	measure 'Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de ventas e importe medio de ventas 30 días (fiscal) por mes año fiscal",
			   "de-DE", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftlich Monat Jahr",
			   "fr-FR", "Montant vente et montant de ventes moyen 30 jours (fiscal) par mois d’exercice",
			   "cs-CZ", "Částka prodeje a průměrná částka prodeje za 30 dní (fiskální) podle fiskálního měsíce a roku",
			   "da-DK", "Salgsbeløb og salgsbeløb i gennemsnit 30 dage (regnskab) pr. regnskabsmåned år",
			   "de-AT", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftlich Monat Jahr",
			   "de-CH", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftlich Monat Jahr",
			   "en-AU", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year",
			   "en-CA", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year",
			   "en-GB", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year",
			   "en-NZ", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year",
			   "es-MX", "Importe de ventas e importe medio de ventas 30 días (fiscal) por mes año fiscal",
			   "fi-FI", "Myyntisumma ja Myyntisumman keskiarvo 30 päivän ajalta (kirjanpito) kirjanpitokuukauden vuoden mukaan",
			   "fr-BE", "Montant vente et montant de ventes moyen 30 jours (fiscal) par mois d’exercice",
			   "fr-CA", "Montant vente et montant de ventes moyen 30 jours (fiscal) par mois d’exercice",
			   "fr-CH", "Montant vente et montant de ventes moyen 30 jours (fiscal) par mois d’exercice",
			   "is-IS", "Upphæð sölu og meðalupphæð sölu yfir 30 daga (fjárhagstímabil) eftir mánuði fjárhagsárs",
			   "it-CH", "Importo vendite e media importo vendite 30 giorni (fiscale) per mese e anno fiscale",
			   "it-IT", "Importo vendite e media importo vendite 30 giorni (fiscale) per mese e anno fiscale",
			   "nb-NO", "Salgsbeløp og salgsbeløpgjennomsnitt 30 dager (regnskap) etter Regnskap Måned År",
			   "nl-BE", "Verkoopbedrag en gemiddeld verkoopbedrag 30 dagen (fiscaal) op fiscale maand/jaar",
			   "nl-NL", "Verkoopbedrag en gemiddeld verkoopbedrag 30 dagen (fiscaal) op fiscale maand/jaar",
			   "sv-SE", "Försäljningsbelopp och Försäljningsbelopp genomsnitt 30 dagar (räkenskapskalender) per Räkenskapskalender Månad År",
			   "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Month Year"
			)
		isHidden
		lineageTag: 6e21ad02-129d-42e6-a437-346f66ecc322

	measure 'Previous Year and Current Moving Annual Total by Fiscal Month Year Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Total anual móvil actual y año anterior por mes año fiscal",
			   "de-DE", "Gleitend Jahr Gesamt des Vorjahres und aktuell nach Geschäftlich Monat Jahr",
			   "fr-FR", "Année précédente et mobile actuel, total annuel par mois d’exercice",
			   "cs-CZ", "Předchozí rok a aktuální pohyblivý součet podle fiskálního měsíce a roku",
			   "da-DK", "Forrige år og nuværende glidende årlige total efter regnskabsmåned år",
			   "de-AT", "Gleitend Jahr Gesamt des Vorjahres und aktuell nach Geschäftlich Monat Jahr",
			   "de-CH", "Gleitend Jahr Gesamt des Vorjahres und aktuell nach Geschäftlich Monat Jahr",
			   "en-AU", "Previous Year and Current Moving Annual Total by Fiscal Month Year",
			   "en-CA", "Previous Year and Current Moving Annual Total by Fiscal Month Year",
			   "en-GB", "Previous Year and Current Moving Annual Total by Fiscal Month Year",
			   "en-NZ", "Previous Year and Current Moving Annual Total by Fiscal Month Year",
			   "es-MX", "Total anual móvil actual y año anterior por mes año fiscal",
			   "fi-FI", "Edellinen vuosi ja nykyinen liukuva vuosittainen kokonaissumma kirjanpitokuukauden vuoden mukaan",
			   "fr-BE", "Année précédente et mobile actuel, total annuel par mois d’exercice",
			   "fr-CA", "Année précédente et mobile actuel, total annuel par mois d’exercice",
			   "fr-CH", "Année précédente et mobile actuel, total annuel par mois d’exercice",
			   "is-IS", "Hlaupandi alls yfir fyrra og núverandi ár eftir mánuði fjárhagsárs",
			   "it-CH", "Totale annuo mobile anno precedente e corrente per mese e anno fiscale",
			   "it-IT", "Totale annuo mobile anno precedente e corrente per mese e anno fiscale",
			   "nb-NO", "Forrige år og inneværende glidende årssum etter Regnskap Måned År",
			   "nl-BE", "Voortschrijdend jaarlijks totaal vorig jaar en huidig jaar op fiscale maand/jaar",
			   "nl-NL", "Voortschrijdend jaarlijks totaal vorig jaar en huidig jaar op fiscale maand/jaar",
			   "sv-SE", "Föregående år och aktuell glidande årssumma per Räkenskapskalender Månad År",
			   "Previous Year and Current Moving Annual Total by Fiscal Month Year"
			)
		isHidden
		lineageTag: ff01f65d-d5b5-405c-9d01-f465796469c9

	measure 'Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Month Year Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Periodo tras periodo (fiscal) de importe de ventas e importe de ventas por mes año fiscal",
			   "de-DE", "Verkaufsbetrag Zeitraum-gegenüber-Zeitraum (Geschäftlich) und Verkaufsbetrag nach Geschäftlich Monat Jahr",
			   "fr-FR", "Montant vente période sur période (fiscal) et montant vente par mois d’exercice",
			   "cs-CZ", "Částka prodeje mezi dvěma obdobími (fiskální) a částka prodeje podle fiskálního měsíce a roku",
			   "da-DK", "Salgsbeløb periode for periode (regnskab) og salgsbeløb pr. regnskabsmåned år",
			   "de-AT", "Verkaufsbetrag Zeitraum-gegenüber-Zeitraum (Geschäftlich) und Verkaufsbetrag nach Geschäftlich Monat Jahr",
			   "de-CH", "Verkaufsbetrag Zeitraum-gegenüber-Zeitraum (Geschäftlich) und Verkaufsbetrag nach Geschäftlich Monat Jahr",
			   "en-AU", "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Month Year",
			   "en-CA", "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Month Year",
			   "en-GB", "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Month Year",
			   "en-NZ", "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Month Year",
			   "es-MX", "Periodo tras periodo (fiscal) de importe de ventas e importe de ventas por mes año fiscal",
			   "fi-FI", "Myyntisumma kaudesta toiseen (kirjanpito) ja Myyntisumma kirjanpitokuukauden vuoden mukaan",
			   "fr-BE", "Montant vente période sur période (fiscal) et montant vente par mois d’exercice",
			   "fr-CA", "Montant vente période sur période (fiscal) et montant vente par mois d’exercice",
			   "fr-CH", "Montant vente période sur période (fiscal) et montant vente par mois d’exercice",
			   "is-IS", "Samanburður á upphæð sölu milli tímabila (fjárhagstímabil) og upphæð sölu eftir mánuði fjárhagsárs",
			   "it-CH", "Confronto importo vendite su periodi (fiscale) e importo vendite per mese e anno fiscale",
			   "it-IT", "Confronto importo vendite su periodi (fiscale) e importo vendite per mese e anno fiscale",
			   "nb-NO", "Salgsbeløp periode for periode (regnskap) og salgsbeløp etter Regnskap Måned År",
			   "nl-BE", "Verkoopbedrag periode tot periode (fiscaal) en verkoopbedrag op fiscale maand/jaar",
			   "nl-NL", "Verkoopbedrag periode tot periode (fiscaal) en verkoopbedrag op fiscale maand/jaar",
			   "sv-SE", "Försäljningsbelopp period för period (räkenskapskalender) Försäljningsbelopp per Räkenskapskalender Månad År",
			   "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Month Year"
			)
		isHidden
		lineageTag: 252370f6-a42a-49a1-bb36-ea58c0dfd1ec

	measure 'Sales Amount Month-to-Date (Fiscal) by Date Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe ventas mes hasta la fecha (fiscal) por fecha",
			   "de-DE", "Verkaufsbetrag seit Monatsbeginn (Geschäftlich) nach Datum",
			   "fr-FR", "Montant des ventes - Cumul mensuel jusqu’à ce jour (fiscal) par date",
			   "cs-CZ", "Částka prodeje od začátku měsíce k dnešnímu dni (fiskální) podle data",
			   "da-DK", "Salgsbeløb måned-til-dato (regnskab) efter dato",
			   "de-AT", "Verkaufsbetrag seit Monatsbeginn (Geschäftlich) nach Datum",
			   "de-CH", "Verkaufsbetrag seit Monatsbeginn (Geschäftlich) nach Datum",
			   "en-AU", "Sales Amount Month-to-Date (Fiscal) by Date",
			   "en-CA", "Sales Amount Month-to-Date (Fiscal) by Date",
			   "en-GB", "Sales Amount Month-to-Date (Fiscal) by Date",
			   "en-NZ", "Sales Amount Month-to-Date (Fiscal) by Date",
			   "es-MX", "Importe ventas mes hasta la fecha (fiscal) por fecha",
			   "fi-FI", "Myyntisumma – kuukausi pvm:ään asti (kirjanpito) pvm:n mukaan",
			   "fr-BE", "Montant des ventes - Cumul mensuel jusqu’à ce jour (fiscal) par date",
			   "fr-CA", "Montant des ventes - Cumul mensuel jusqu’à ce jour (fiscal) par date",
			   "fr-CH", "Montant des ventes - Cumul mensuel jusqu’à ce jour (fiscal) par date",
			   "is-IS", "Upphæð sölu þennan mánuð til dagsins í dag (fjárhagstímabil) eftir dagsetningu",
			   "it-CH", "Importo vendite mese in corso (fiscale) per data",
			   "it-IT", "Importo vendite mese in corso (fiscale) per data",
			   "nb-NO", "Salgsbeløp hittil i måneden (regnskap) etter dato",
			   "nl-BE", "Verkoopbedrag maand-tot-heden (fiscaal) op datum",
			   "nl-NL", "Verkoopbedrag maand-tot-heden (fiscaal) op datum",
			   "sv-SE", "Försäljningsbelopp Månad-till-datum (räkenskapskalender) per Datum",
			   "Sales Amount Month-to-Date (Fiscal) by Date"
			)
		isHidden
		lineageTag: bfafaa2e-d84c-4847-ba6c-810944bcab22

	measure 'Last Refreshed Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Última actualización",
			   "de-DE", "Zuletzt aktualisiert",
			   "fr-FR", "Dernière actualisation",
			   "cs-CZ", "Naposledy aktualizováno",
			   "da-DK", "Sidst opdateret",
			   "de-AT", "Zuletzt aktualisiert",
			   "de-CH", "Zuletzt aktualisiert",
			   "en-AU", "Last Refreshed",
			   "en-CA", "Last Refreshed",
			   "en-GB", "Last Refreshed",
			   "en-NZ", "Last Refreshed",
			   "es-MX", "Última actualización",
			   "fi-FI", "Päivitetty viimeksi",
			   "fr-BE", "Dernière actualisation",
			   "fr-CA", "Dernière actualisation",
			   "fr-CH", "Dernière actualisation",
			   "is-IS", "Síðast uppfært",
			   "it-CH", "Ultimo aggiornamento",
			   "it-IT", "Ultimo aggiornamento",
			   "nb-NO", "Sist oppdatert",
			   "nl-BE", "Laatst vernieuwd",
			   "nl-NL", "Laatst vernieuwd",
			   "sv-SE", "Uppdaterades senast",
			   "Last Refreshed"
			)
		isHidden
		lineageTag: e4392d68-9ead-42ea-862a-b000b5b136e3

	measure 'Company Name Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Nombre empresa",
			   "de-DE", "Mandantenname",
			   "fr-FR", "Nom de la société",
			   "cs-CZ", "Název společnosti",
			   "da-DK", "Virksomhedsnavn",
			   "de-AT", "Mandantenname",
			   "de-CH", "Mandantenname",
			   "en-AU", "Company Name",
			   "en-CA", "Company Name",
			   "en-GB", "Company Name",
			   "en-NZ", "Company Name",
			   "es-MX", "Nombre empresa",
			   "fi-FI", "Yrityksen nimi",
			   "fr-BE", "Nom de la société",
			   "fr-CA", "Nom de la compagnie",
			   "fr-CH", "Nom de la société",
			   "is-IS", "Heiti fyrirtækis",
			   "it-CH", "Nome società",
			   "it-IT", "Nome società",
			   "nb-NO", "Selskapsnavn",
			   "nl-BE", "Bedrijfsnaam",
			   "nl-NL", "Bedrijfsnaam",
			   "sv-SE", "Företagsnamn",
			   "Company Name"
			)
		isHidden
		lineageTag: 4186a71c-af46-4663-a4b9-4a1ebe4dabf5

	measure 'Sales Amount by Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de ventas por vendedor",
			   "de-DE", "Verkaufsbetrag nach Verkäufer",
			   "fr-FR", "Montant vente par vendeur",
			   "cs-CZ", "Částka prodeje podle prodejce",
			   "da-DK", "Salgsbeløb efter sælger",
			   "de-AT", "Verkaufsbetrag nach Verkäufer",
			   "de-CH", "Verkaufsbetrag nach Verkäufer",
			   "en-AU", "Sales Amount by Salesperson",
			   "en-CA", "Sales Amount by Salesperson",
			   "en-GB", "Sales Amount by Salesperson",
			   "en-NZ", "Sales Amount by Salesperson",
			   "es-MX", "Importe de ventas por vendedor",
			   "fi-FI", "Myyntisumma myyjän mukaan",
			   "fr-BE", "Montant vente par vendeur",
			   "fr-CA", "Montant vente par représentant",
			   "fr-CH", "Montant vente par vendeur",
			   "is-IS", "Upphæð sölu eftir sölumanni",
			   "it-CH", "Importo vendite per venditore",
			   "it-IT", "Importo vendite per venditore",
			   "nb-NO", "Salgsbeløp etter selger",
			   "nl-BE", "Verkoopbedrag per verkoper",
			   "nl-NL", "Verkoopbedrag per verkoper",
			   "sv-SE", "Försäljningsbelopp per säljare",
			   "Sales Amount by Salesperson"
			)
		isHidden
		lineageTag: 2d8e8c74-7422-47a8-a23b-51c4b3bd11d0

	measure 'Gross Profit by Item Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Beneficio bruto por producto",
			   "de-DE", "Bruttogewinn nach Artikel",
			   "fr-FR", "Bénéfice brut par article",
			   "cs-CZ", "Hrubý zisk podle zboží",
			   "da-DK", "Bruttofortjeneste efter vare",
			   "de-AT", "Bruttogewinn nach Artikel",
			   "de-CH", "Bruttogewinn nach Artikel",
			   "en-AU", "Gross Profit by Item",
			   "en-CA", "Gross Profit by Item",
			   "en-GB", "Gross Profit by Item",
			   "en-NZ", "Gross Profit by Item",
			   "es-MX", "Beneficio bruto por producto",
			   "fi-FI", "Bruttovoitto nimikkeen mukaan",
			   "fr-BE", "Bénéfice brut par article",
			   "fr-CA", "Profit brut par article",
			   "fr-CH", "Bénéfice brut par article",
			   "is-IS", "Brúttóhagnaður eftir vöru",
			   "it-CH", "Profitto lordo per articolo",
			   "it-IT", "Profitto lordo per articolo",
			   "nb-NO", "Bruttofortjeneste etter vare",
			   "nl-BE", "Brutowinst per artikel",
			   "nl-NL", "Brutowinst per artikel",
			   "sv-SE", "Bruttovinst per artikel",
			   "Gross Profit by Item"
			)
		isHidden
		lineageTag: d7b2cf4a-a059-42a6-9f77-2968067b6848

	measure 'Sales Amount by Customer Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de ventas por cliente",
			   "de-DE", "Verkaufsbetrag nach Debitor",
			   "fr-FR", "Montant vente par client",
			   "cs-CZ", "Částka prodeje podle zákazníka",
			   "da-DK", "Salgsbeløb efter debitor",
			   "de-AT", "Verkaufsbetrag nach Debitor",
			   "de-CH", "Verkaufsbetrag nach Debitor",
			   "en-AU", "Sales Amount by Customer",
			   "en-CA", "Sales Amount by Customer",
			   "en-GB", "Sales Amount by Customer",
			   "en-NZ", "Sales Amount by Customer",
			   "es-MX", "Importe de ventas por cliente",
			   "fi-FI", "Myyntisumma asiakkaan mukaan",
			   "fr-BE", "Montant vente par client",
			   "fr-CA", "Montant vente par client",
			   "fr-CH", "Montant vente par client",
			   "is-IS", "Upphæð sölu eftir viðskiptavini",
			   "it-CH", "Importo vendite per cliente",
			   "it-IT", "Importo vendite per cliente",
			   "nb-NO", "Salgsbeløp etter kunde",
			   "nl-BE", "Verkoopbedrag per klant",
			   "nl-NL", "Verkoopbedrag per klant",
			   "sv-SE", "Försäljningsbelopp per kund",
			   "Sales Amount by Customer"
			)
		isHidden
		lineageTag: a8db3828-07db-42c1-ba1c-ff92d7f0f652

	measure 'Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Year Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de ventas e importe medio de ventas 30 días (fiscal) por año fiscal",
			   "de-DE", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftsjahr",
			   "fr-FR", "Montant vente et montant de ventes moyen 30 jours (fiscal) par exercice",
			   "cs-CZ", "Částka prodeje a průměrná částka prodeje za 30 dní (fiskální) podle fiskálního roku",
			   "da-DK", "Salgsbeløb og salgsbeløb i gennemsnit 30 dage (regnskab) pr. regnskabsår",
			   "de-AT", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftsjahr",
			   "de-CH", "Verkaufsbetrag und Verkaufsbetragsdurchschnitt 30 Tage (Geschäftlich) nach Geschäftsjahr",
			   "en-AU", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Year",
			   "en-CA", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Year",
			   "en-GB", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Year",
			   "en-NZ", "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Year",
			   "es-MX", "Importe de ventas e importe medio de ventas 30 días (fiscal) por año fiscal",
			   "fi-FI", "Myyntisumma ja Myyntisumman keskiarvo 30 päivän ajalta (kirjanpito) kirjanpitovuoden mukaan",
			   "fr-BE", "Montant vente et montant de ventes moyen 30 jours (fiscal) par exercice",
			   "fr-CA", "Montant vente et montant vente moyen 30 jours (fiscal) par exercice financier",
			   "fr-CH", "Montant vente et montant de ventes moyen 30 jours (fiscal) par exercice",
			   "is-IS", "Upphæð sölu og meðalupphæð sölu yfir 30 daga (fjárhagstímabil) eftir fjárhagsári",
			   "it-CH", "Importo vendite e media importo vendite 30 giorni (fiscale) per anno fiscale",
			   "it-IT", "Importo vendite e media importo vendite 30 giorni (fiscale) per anno fiscale",
			   "nb-NO", "Salgsbeløp og salgsbeløpgjennomsnitt 30 dager (regnskap) etter regnskapsår",
			   "nl-BE", "Verkoopbedrag en gemiddeld verkoopbedrag 30 dagen (fiscaal) op fiscaal jaar",
			   "nl-NL", "Verkoopbedrag en gemiddeld verkoopbedrag 30 dagen (fiscaal) op fiscaal jaar",
			   "sv-SE", "Försäljningsbelopp och Försäljningsbelopp genomsnitt 30 dagar (räkenskapskalender) per räkenskapsår",
			   "Sales Amount and Sales Amount Average 30 Days (Fiscal) by Fiscal Year"
			)
		isHidden
		lineageTag: 174a7865-2c04-41a4-b149-a2614c9d4229

	measure 'Monthly Comparison of Previous Year and Current Year Moving Annual Totals Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Comparación mensual del total anual móvil año actual y año anterior",
			   "de-DE", "Monatlicher Vergleich des Vorjahres und Moving Annual Total des aktuellen Jahres",
			   "fr-FR", "Comparaison mensuelle totaux annuels mobiles année précédente et année en cours",
			   "cs-CZ", "Měsíční srovnání předchozích let a běžného roku – roční pohyblivé součty",
			   "da-DK", "Månedlig sammenligning af glidende årlige totaler for forrige år og indeværende år",
			   "de-AT", "Monatlicher Vergleich des Vorjahres und Moving Annual Total des aktuellen Jahres",
			   "de-CH", "Monatlicher Vergleich des Vorjahres und Moving Annual Total des aktuellen Jahres",
			   "en-AU", "Monthly Comparison of Previous Year and Current Year Moving Annual Totals",
			   "en-CA", "Monthly Comparison of Previous Year and Current Year Moving Annual Totals",
			   "en-GB", "Monthly Comparison of Previous Year and Current Year Moving Annual Totals",
			   "en-NZ", "Monthly Comparison of Previous Year and Current Year Moving Annual Totals",
			   "es-MX", "Comparación mensual del total anual móvil año actual y año anterior",
			   "fi-FI", "Edellisen vuoden ja kuluvan vuoden liukuvien vuosittaisten kokonaissummien kuukausivertailu",
			   "fr-BE", "Comparaison mensuelle totaux annuels mobiles année précédente et année en cours",
			   "fr-CA", "Comparaison mensuelle totaux annuels mobiles année précédente et année en cours",
			   "fr-CH", "Comparaison mensuelle totaux annuels mobiles année précédente et année en cours",
			   "is-IS", "Mánaðarlegur samanburður á hlaupandi alls yfir fyrra og núverandi ár",
			   "it-CH", "Confronto mensile totali annui mobili anno precedente e corrente",
			   "it-IT", "Confronto mensile totali annui mobili anno precedente e corrente",
			   "nb-NO", "Månedlig sammenligning av glidende årssum for forrige år og inneværende år",
			   "nl-BE", "Maandelijkse vergelijking van voortschrijdend jaarlijks totaal vorig jaar en huidig jaar",
			   "nl-NL", "Maandelijkse vergelijking van voortschrijdend jaarlijks totaal vorig jaar en huidig jaar",
			   "sv-SE", "Månadsjämförelse av glidande årssumma för föregående år och innevarande år",
			   "Monthly Comparison of Previous Year and Current Year Moving Annual Totals"
			)
		isHidden
		lineageTag: b9dfe150-1c21-4857-89a1-d31f2d09288f

	measure 'Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Year Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Periodo tras periodo (fiscal) de importe de ventas e importe de ventas por año fiscal",
			   "de-DE", "Verkaufsbetrag Zeitraum-gegenüber-Zeitraum (Geschäftlich) und Verkaufsbetrag nach Geschäftsjahr",
			   "fr-FR", "Montant vente période sur période (fiscal) et montant vente par exercice",
			   "cs-CZ", "Částka prodeje mezi dvěma obdobími (fiskální) a částka prodeje podle fiskálního roku",
			   "da-DK", "Salgsbeløb periode for periode (regnskab) og salgsbeløb efter regnskabsår",
			   "de-AT", "Verkaufsbetrag Zeitraum-gegenüber-Zeitraum (Geschäftlich) und Verkaufsbetrag nach Geschäftsjahr",
			   "de-CH", "Verkaufsbetrag Zeitraum-gegenüber-Zeitraum (Geschäftlich) und Verkaufsbetrag nach Geschäftsjahr",
			   "en-AU", "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Year",
			   "en-CA", "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Year",
			   "en-GB", "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Year",
			   "en-NZ", "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Year",
			   "es-MX", "Periodo tras periodo (fiscal) de importe de ventas e importe de ventas por año fiscal",
			   "fi-FI", "Myyntisumma kaudesta toiseen (kirjanpito) ja Myyntisumma kirjanpitovuoden mukaan",
			   "fr-BE", "Montant vente période sur période (fiscal) et montant vente par exercice",
			   "fr-CA", "Montant vente période sur période (fiscal) et montant vente par exercice financier",
			   "fr-CH", "Montant vente période sur période (fiscal) et montant vente par exercice",
			   "is-IS", "Samanburður á upphæð sölu milli tímabila (fjárhagstímabil) og upphæð sölu eftir fjárhagsári",
			   "it-CH", "Confronto importo vendite su periodi (fiscale) e importo vendite per anno fiscale",
			   "it-IT", "Confronto importo vendite su periodi (fiscale) e importo vendite per anno fiscale",
			   "nb-NO", "Salgsbeløp periode for periode (regnskap) og salgsbeløp etter regnskapsår",
			   "nl-BE", "Verkoopbedrag periode tot periode (fiscaal) en verkoopbedrag op fiscaal jaar",
			   "nl-NL", "Verkoopbedrag periode tot periode (fiscaal) en verkoopbedrag op fiscaal jaar",
			   "sv-SE", "Försäljningsbelopp period för period (räkenskapskalender) Försäljningsbelopp per räkenskapsår",
			   "Sales Amount Period-over-Period (Fiscal) and Sales Amount by Fiscal Year"
			)
		isHidden
		lineageTag: d6eaa2b9-2211-4730-8c99-f55354317112

	measure 'Sales Amount by Item Category Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de ventas por categoría de producto",
			   "de-DE", "Verkaufsbetrag nach Artikelkategorie",
			   "fr-FR", "Montant vente par catégorie d’article",
			   "cs-CZ", "Částka prodeje podle kategorie zboží",
			   "da-DK", "Salgsbeløb efter varekategori",
			   "de-AT", "Verkaufsbetrag nach Artikelkategorie",
			   "de-CH", "Verkaufsbetrag nach Artikelkategorie",
			   "en-AU", "Sales Amount by Item Category",
			   "en-CA", "Sales Amount by Item Category",
			   "en-GB", "Sales Amount by Item Category",
			   "en-NZ", "Sales Amount by Item Category",
			   "es-MX", "Importe de ventas por categoría de producto",
			   "fi-FI", "Myyntisumma nimikeluokan mukaan",
			   "fr-BE", "Montant vente par catégorie d’article",
			   "fr-CA", "Montant vente par catégorie d’article",
			   "fr-CH", "Montant vente par catégorie d’article",
			   "is-IS", "Upphæð sölu eftir vöruflokki",
			   "it-CH", "Importo vendite per categoria articolo",
			   "it-IT", "Importo vendite per categoria articolo",
			   "nb-NO", "Salgsbeløp etter varekategori",
			   "nl-BE", "Verkoopbedrag per artikelcategorie",
			   "nl-NL", "Verkoopbedrag per artikelcategorie",
			   "sv-SE", "Försäljningsbelopp per artikelkategori",
			   "Sales Amount by Item Category"
			)
		isHidden
		lineageTag: cc40e53e-b9da-4e22-a084-5afdfb915b43

	measure 'Sales Metrics by Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Métricas de ventas por vendedor",
			   "de-DE", "Verkaufskennzahlen nach Verkäufer",
			   "fr-FR", "Mesures ventes par vendeur",
			   "cs-CZ", "Metriky prodeje podle prodejce",
			   "da-DK", "Salgsmålepunkter efter sælger",
			   "de-AT", "Verkaufskennzahlen nach Verkäufer",
			   "de-CH", "Verkaufskennzahlen nach Verkäufer",
			   "en-AU", "Sales Metrics by Salesperson",
			   "en-CA", "Sales Metrics by Salesperson",
			   "en-GB", "Sales Metrics by Salesperson",
			   "en-NZ", "Sales Metrics by Salesperson",
			   "es-MX", "Métricas de ventas por vendedor",
			   "fi-FI", "Myyntimittarit myyjän mukaan",
			   "fr-BE", "Mesures ventes par vendeur",
			   "fr-CA", "Mesures ventes par représentant",
			   "fr-CH", "Mesures ventes par vendeur",
			   "is-IS", "Mælingar á sölu eftir sölumanni",
			   "it-CH", "Metriche vendite per venditore",
			   "it-IT", "Metriche vendite per venditore",
			   "nb-NO", "Salgsmåleverdier etter selger",
			   "nl-BE", "Verkoopmeetgegevens per verkoper",
			   "nl-NL", "Verkoopmeetgegevens per verkoper",
			   "sv-SE", "Försäljningsmått per säljare",
			   "Sales Metrics by Salesperson"
			)
		isHidden
		lineageTag: 62967707-3252-4ccc-a9ef-d53dde4d8674

	measure 'Sales by Location Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas por almacén",
			   "de-DE", "Verkauf nach Lagerort",
			   "fr-FR", "Ventes par magasin",
			   "cs-CZ", "Prodej podle lokace",
			   "da-DK", "Salg efter placering",
			   "de-AT", "Verkauf nach Lagerort",
			   "de-CH", "Verkauf nach Lagerort",
			   "en-AU", "Sales by Location",
			   "en-CA", "Sales by Location",
			   "en-GB", "Sales by Location",
			   "en-NZ", "Sales by Location",
			   "es-MX", "Ventas por almacén",
			   "fi-FI", "Myynti sijainnin mukaan",
			   "fr-BE", "Ventes par magasin",
			   "fr-CA", "Ventes par emplacement",
			   "fr-CH", "Ventes par magasin",
			   "is-IS", "Sala eftir staðsetningu",
			   "it-CH", "Vendite per ubicazione",
			   "it-IT", "Vendite per ubicazione",
			   "nb-NO", "Salg etter lokasjon",
			   "nl-BE", "Verkoop per locatie",
			   "nl-NL", "Verkoop per locatie",
			   "sv-SE", "Försäljning per lagerställe",
			   "Sales by Location"
			)
		isHidden
		lineageTag: 884ac8c7-c66f-4830-acdb-4767f8437721

	measure 'Sales Amount by Location Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe ventas por almacén",
			   "de-DE", "Verkaufsbetrag nach Lagerort",
			   "fr-FR", "Montant vente par magasin",
			   "cs-CZ", "Částka prodeje podle lokace",
			   "da-DK", "Salgsbeløb efter placering",
			   "de-AT", "Verkaufsbetrag nach Lagerort",
			   "de-CH", "Verkaufsbetrag nach Lagerort",
			   "en-AU", "Sales Amount by Location",
			   "en-CA", "Sales Amount by Location",
			   "en-GB", "Sales Amount by Location",
			   "en-NZ", "Sales Amount by Location",
			   "es-MX", "Importe ventas por almacén",
			   "fi-FI", "Myyntisumma sijainnin mukaan",
			   "fr-BE", "Montant vente par magasin",
			   "fr-CA", "Montant vente par emplacement",
			   "fr-CH", "Montant vente par magasin",
			   "is-IS", "Upphæð sölu eftir staðsetningu",
			   "it-CH", "Importo vendite per ubicazione",
			   "it-IT", "Importo vendite per ubicazione",
			   "nb-NO", "Salgsbeløp etter lokasjon",
			   "nl-BE", "Verkoopbedrag per locatie",
			   "nl-NL", "Verkoopbedrag per locatie",
			   "sv-SE", "Försäljningsbelopp per lagerställe",
			   "Sales Amount by Location"
			)
		isHidden
		lineageTag: 3b88e09d-2df5-4332-a259-f02522f3f2d2

	measure 'Actual vs Budget Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor real frente a presupuesto",
			   "de-DE", "Istwert vs. Budget",
			   "fr-FR", "Comparatif Réel/Budget",
			   "cs-CZ", "Skutečnost vs. rozpočet",
			   "da-DK", "Faktisk i forhold til budget",
			   "de-AT", "Istwert vs. Budget",
			   "de-CH", "Istwert vs. Budget",
			   "en-AU", "Actual vs Budget",
			   "en-CA", "Actual vs Budget",
			   "en-GB", "Actual vs Budget",
			   "en-NZ", "Actual vs Budget",
			   "es-MX", "Valor real frente a presupuesto",
			   "fi-FI", "Toteutunut vrt. budjetoitu",
			   "fr-BE", "Comparatif Réel/Budget",
			   "fr-CA", "Comparatif Réel/Budget",
			   "fr-CH", "Comparatif Réel/Budget",
			   "is-IS", "Raunverulegt samanb. v. áætlun",
			   "it-CH", "Effettivo rispetto al budget",
			   "it-IT", "Effettivo rispetto al budget",
			   "nb-NO", "Faktisk i forhold til budsjett",
			   "nl-BE", "Werkelijk vs. budget",
			   "nl-NL", "Werkelijk vs. budget",
			   "sv-SE", "Utfall kontra budget",
			   "Actual vs Budget"
			)
		isHidden
		lineageTag: 1fd67658-7776-4a94-9432-9eee731a21f5

	measure 'Actual vs Budget Purchase Analysis by Item Category Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis de compras reales frente a presupuestadas por categoría de producto",
			   "de-DE", "Istwert vs. Budget – Einkaufsanalyse nach Artikelkategorie",
			   "fr-FR", "Analyse des achats réels par rapport au budget par catégorie d’article",
			   "cs-CZ", "Analýza skutečného a rozpočtového nákupu podle kategorie zboží",
			   "da-DK", "Faktisk i forhold til budgetkøbsanalyse efter varekategori",
			   "de-AT", "Istwert vs. Budget – Einkaufsanalyse nach Artikelkategorie",
			   "de-CH", "Istwert vs. Budget – Einkaufsanalyse nach Artikelkategorie",
			   "en-AU", "Actual vs Budget Purchase Analysis by Item Category",
			   "en-CA", "Actual vs Budget Purchase Analysis by Item Category",
			   "en-GB", "Actual vs Budget Purchase Analysis by Item Category",
			   "en-NZ", "Actual vs Budget Purchase Analysis by Item Category",
			   "es-MX", "Análisis de compras reales frente a presupuestadas por categoría de producto",
			   "fi-FI", "Toteutunut vrt. budjetin oston analyysi nimikeluokan mukaan",
			   "fr-BE", "Analyse des achats réels par rapport au budget par catégorie d’article",
			   "fr-CA", "Analyse des achats réels par rapport au budget par catégorie d’article",
			   "fr-CH", "Analyse des achats réels par rapport au budget par catégorie d’article",
			   "is-IS", "Innkaupagreining á rauntölum samanbornum við fjárhagsáætlun eftir vöruflokki",
			   "it-CH", "Analisi degli acquisti effettivi rispetto al budget per categoria articolo",
			   "it-IT", "Analisi degli acquisti effettivi rispetto al budget per categoria articolo",
			   "nb-NO", "Kjøpsanalyse av faktisk i forhold til budsjett etter varekategori",
			   "nl-BE", "Analyse van werkelijke inkoop versus budgetinkoop per artikelcategorie",
			   "nl-NL", "Analyse van werkelijke inkoop versus budgetinkoop per artikelcategorie",
			   "sv-SE", "Analys av faktiska kontra budgeterade inköp per artikelkategori",
			   "Actual vs Budget Purchase Analysis by Item Category"
			)
		isHidden
		lineageTag: a5331b82-44a3-4af6-ad11-24e2a057549e

	measure 'Sales Drillthrough Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis detallado de ventas",
			   "de-DE", "Verkaufs-Drillthrough",
			   "fr-FR", "Extraction ventes",
			   "cs-CZ", "Podrobné procházení prodeje",
			   "da-DK", "Detaljeudledning for salg",
			   "de-AT", "Verkaufs-Drillthrough",
			   "de-CH", "Verkaufs-Drillthrough",
			   "en-AU", "Sales Drillthrough",
			   "en-CA", "Sales Drillthrough",
			   "en-GB", "Sales Drillthrough",
			   "en-NZ", "Sales Drillthrough",
			   "es-MX", "Análisis detallado de ventas",
			   "fi-FI", "Myyntiin porautuminen",
			   "fr-BE", "Extraction ventes",
			   "fr-CA", "Extraction ventes",
			   "fr-CH", "Extraction ventes",
			   "is-IS", "Köfun í sölu",
			   "it-CH", "Drill-through vendite",
			   "it-IT", "Drill-through vendite",
			   "nb-NO", "Gjennomgang av salg",
			   "nl-BE", "Detailanalyse verkoop",
			   "nl-NL", "Detailanalyse verkoop",
			   "sv-SE", "Detaljerad analys av försäljning",
			   "Sales Drillthrough"
			)
		isHidden
		lineageTag: 2a037db4-1b8d-43d7-a56b-775909ff8167

	measure 'Detailed Sales Ledger Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Movimientos detallados de ventas",
			   "de-DE", "Detaillierter Verkaufsposten",
			   "fr-FR", "Écritures comptables vente détaillées",
			   "cs-CZ", "Podrobná položka prodeje",
			   "da-DK", "Detaljeret salgsfinanskonto",
			   "de-AT", "Detaillierter Verkaufsposten",
			   "de-CH", "Detaillierter Verkaufsposten",
			   "en-AU", "Detailed Sales Ledger",
			   "en-CA", "Detailed Sales Ledger",
			   "en-GB", "Detailed Sales Ledger",
			   "en-NZ", "Detailed Sales Ledger",
			   "es-MX", "Movimientos detallados de ventas",
			   "fi-FI", "Yksityiskohtainen myyntikirjanpito",
			   "fr-BE", "Écritures comptables vente détaillées",
			   "fr-CA", "Écritures comptables vente détaillées",
			   "fr-CH", "Écritures comptables vente détaillées",
			   "is-IS", "Ítarlegt söluyfirlit",
			   "it-CH", "Movimenti contabili vendite dettagliati",
			   "it-IT", "Movimenti contabili vendite dettagliati",
			   "nb-NO", "Detaljerte salgsposter",
			   "nl-BE", "Gedetailleerd verkoopboek",
			   "nl-NL", "Gedetailleerd verkoopboek",
			   "sv-SE", "Detaljerad försäljningsredovisning",
			   "Detailed Sales Ledger"
			)
		isHidden
		lineageTag: f2505f15-3669-4355-8876-fe207b48fe10

	measure 'Sales Amount by Month Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe ventas por mes",
			   "de-DE", "Verkaufsbetrag nach Monat",
			   "fr-FR", "Montant vente par mois",
			   "cs-CZ", "Částka prodeje podle měsíce",
			   "da-DK", "Salgsbeløb efter måned",
			   "de-AT", "Verkaufsbetrag nach Monat",
			   "de-CH", "Verkaufsbetrag nach Monat",
			   "en-AU", "Sales Amount by Month",
			   "en-CA", "Sales Amount by Month",
			   "en-GB", "Sales Amount by Month",
			   "en-NZ", "Sales Amount by Month",
			   "es-MX", "Importe ventas por mes",
			   "fi-FI", "Myyntisumma kuukauden mukaan",
			   "fr-BE", "Montant vente par mois",
			   "fr-CA", "Montant vente par mois",
			   "fr-CH", "Montant vente par mois",
			   "is-IS", "Upphæð sölu eftir mánuði",
			   "it-CH", "Importo vendite per mese",
			   "it-IT", "Importo vendite per mese",
			   "nb-NO", "Salgsbeløp etter måned",
			   "nl-BE", "Verkoopbedrag per maand",
			   "nl-NL", "Verkoopbedrag per maand",
			   "sv-SE", "Försäljningsbelopp per månad",
			   "Sales Amount by Month"
			)
		isHidden
		lineageTag: 91c936ee-8d89-4a6e-9b04-f729b315d169

	measure 'PROJECTS Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "PROYECTOS",
			   "de-DE", "PROJEKTE",
			   "fr-FR", "PROJETS",
			   "cs-CZ", "PROJEKTY",
			   "da-DK", "PROJEKTER",
			   "de-AT", "PROJEKTE",
			   "de-CH", "PROJEKTE",
			   "en-AU", "PROJECTS",
			   "en-CA", "PROJECTS",
			   "en-GB", "PROJECTS",
			   "en-NZ", "PROJECTS",
			   "es-MX", "PROYECTOS",
			   "fi-FI", "PROJEKTIT",
			   "fr-BE", "PROJETS",
			   "fr-CA", "PROJETS",
			   "fr-CH", "PROJETS",
			   "is-IS", "VERKEFNI",
			   "it-CH", "PROGETTI",
			   "it-IT", "PROGETTI",
			   "nb-NO", "PROSJEKTER",
			   "nl-BE", "PROJECTEN",
			   "nl-NL", "PROJECTEN",
			   "sv-SE", "PROJEKT",
			   "PROJECTS"
			)
		isHidden
		lineageTag: 1733a7cf-a57b-448d-a2f6-c8709d28c487

	measure 'MANUFACTURING Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "FABRICACIÓN",
			   "de-DE", "PRODUKTION",
			   "fr-FR", "FABRICATION",
			   "cs-CZ", "VÝROBA",
			   "da-DK", "PRODUKTION",
			   "de-AT", "PRODUKTION",
			   "de-CH", "PRODUKTION",
			   "en-AU", "MANUFACTURING",
			   "en-CA", "MANUFACTURING",
			   "en-GB", "MANUFACTURING",
			   "en-NZ", "MANUFACTURING",
			   "es-MX", "FABRICACIÓN",
			   "fi-FI", "TUOTANTO",
			   "fr-BE", "FABRICATION",
			   "fr-CA", "FABRICATION",
			   "fr-CH", "FABRICATION",
			   "is-IS", "FRAMLEIÐSLA",
			   "it-CH", "PRODUZIONE",
			   "it-IT", "PRODUZIONE",
			   "nb-NO", "PRODUKSJON",
			   "nl-BE", "PRODUCTIE",
			   "nl-NL", "PRODUCTIE",
			   "sv-SE", "PRODUKTION",
			   "MANUFACTURING"
			)
		isHidden
		lineageTag: ffc28ded-1263-489a-abfc-25618d4a077f

	measure 'Month-To-Date Sales Performance Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Rendimiento de ventas mes hasta la fecha",
			   "de-DE", "Verkaufsleistung seit Monatsbeginn",
			   "fr-FR", "Performances vente - Cumul mensuel jusqu’à ce jour",
			   "cs-CZ", "Prodejní výsledky od začátku měsíce k dnešnímu dni",
			   "da-DK", "Salgsresultater måned til dato",
			   "de-AT", "Verkaufsleistung seit Monatsbeginn",
			   "de-CH", "Verkaufsleistung seit Monatsbeginn",
			   "en-AU", "Month-To-Date Sales Performance",
			   "en-CA", "Month-To-Date Sales Performance",
			   "en-GB", "Month-To-Date Sales Performance",
			   "en-NZ", "Month-To-Date Sales Performance",
			   "es-MX", "Rendimiento de ventas mes hasta la fecha",
			   "fi-FI", "Kuukausi pvm:ään asti – myynnin suorituskyky",
			   "fr-BE", "Performances vente - Cumul mensuel jusqu’à ce jour",
			   "fr-CA", "Performances vente - Cumul mensuel jusqu’à ce jour",
			   "fr-CH", "Performances vente - Cumul mensuel jusqu’à ce jour",
			   "is-IS", "Söluárangur þennan mánuð til dagsins í dag",
			   "it-CH", "Prestazioni vendite mese in corso",
			   "it-IT", "Prestazioni vendite mese in corso",
			   "nb-NO", "Salgsresultater hittil denne måneden",
			   "nl-BE", "Verkoopprestaties maand-tot-heden",
			   "nl-NL", "Verkoopprestaties maand-tot-heden",
			   "sv-SE", "Försäljningsresultat hittills till månad",
			   "Month-To-Date Sales Performance"
			)
		isHidden
		lineageTag: f4c08787-2f8b-47dd-9f85-66b1311d936d

	measure 'Top Customer Sales Contributions Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Principales contribuciones de ventas de los clientes",
			   "de-DE", "Top-Debitorenverkaufsbeiträge",
			   "fr-FR", "Principales contributions des ventes des clients",
			   "cs-CZ", "Přední příspěvky prodeje zákazníků",
			   "da-DK", "De vigtigste debitorers bidrag til salg",
			   "de-AT", "Top-Debitorenverkaufsbeiträge",
			   "de-CH", "Top-Debitorenverkaufsbeiträge",
			   "en-AU", "Top Customer Sales Contributions",
			   "en-CA", "Top Customer Sales Contributions",
			   "en-GB", "Top Customer Sales Contributions",
			   "en-NZ", "Top Customer Sales Contributions",
			   "es-MX", "Principales contribuciones de ventas de los clientes",
			   "fi-FI", "Parhaan asiakkaan myyntikontribuutiot",
			   "fr-BE", "Principales contributions des ventes des clients",
			   "fr-CA", "Principales contributions des ventes des clients",
			   "fr-CH", "Principales contributions des ventes des clients",
			   "is-IS", "Söluframlög helstu viðskiptavina",
			   "it-CH", "Contributi alle vendite dei clienti principali",
			   "it-IT", "Contributi alle vendite dei clienti principali",
			   "nb-NO", "Beste kundesalgsbidrag",
			   "nl-BE", "Verkoopbijdragen van topklanten",
			   "nl-NL", "Verkoopbijdragen van topklanten",
			   "sv-SE", "Försäljningsbidrag från främsta kunder",
			   "Top Customer Sales Contributions"
			)
		isHidden
		lineageTag: e8997d17-33cd-4a2a-a1b2-11671ff80c8e

	measure 'Daily Sales by Date Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas diarias por fecha",
			   "de-DE", "Tägliche Verkäufe nach Datum",
			   "fr-FR", "Ventes quotidiennes par date",
			   "cs-CZ", "Denní prodeje podle data",
			   "da-DK", "Dagligt salg efter dato",
			   "de-AT", "Tägliche Verkäufe nach Datum",
			   "de-CH", "Tägliche Verkäufe nach Datum",
			   "en-AU", "Daily Sales by Date",
			   "en-CA", "Daily Sales by Date",
			   "en-GB", "Daily Sales by Date",
			   "en-NZ", "Daily Sales by Date",
			   "es-MX", "Ventas diarias por fecha",
			   "fi-FI", "Päivittäinen myynti päivämäärittäin",
			   "fr-BE", "Ventes quotidiennes par date",
			   "fr-CA", "Ventes quotidiennes par date",
			   "fr-CH", "Ventes quotidiennes par date",
			   "is-IS", "Dagleg sala eftir dagsetningu",
			   "it-CH", "Vendite giornaliere per data",
			   "it-IT", "Vendite giornaliere per data",
			   "nb-NO", "Daglig salg etter dato",
			   "nl-BE", "Dagelijkse verkoop per datum",
			   "nl-NL", "Dagelijkse verkoop per datum",
			   "sv-SE", "Daglig försäljning per datum",
			   "Daily Sales by Date"
			)
		isHidden
		lineageTag: b31df422-892c-4655-a106-25b8e1e55c6c

	measure 'Daily Sales by Entry No Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas diarias por n.º de movimiento",
			   "de-DE", "Tägliche Verkäufe nach Postennr.",
			   "fr-FR", "Ventes quotidiennes par n° écriture",
			   "cs-CZ", "Denní prodej podle č. položky",
			   "da-DK", "Dagligt salg efter løbenr",
			   "de-AT", "Tägliche Verkäufe nach Postennr.",
			   "de-CH", "Tägliche Verkäufe nach Postennr.",
			   "en-AU", "Daily Sales by Entry No",
			   "en-CA", "Daily Sales by Entry No",
			   "en-GB", "Daily Sales by Entry No",
			   "en-NZ", "Daily Sales by Entry No",
			   "es-MX", "Ventas diarias por n.º de movimiento",
			   "fi-FI", "Päivittäinen myynti tapahtumanumeroittain",
			   "fr-BE", "Ventes quotidiennes par n° écriture",
			   "fr-CA", "Ventes quotidiennes par n° écriture",
			   "fr-CH", "Ventes quotidiennes par n° écriture",
			   "is-IS", "Dagleg sala eftir færslunr.",
			   "it-CH", "Vendite giornaliere per nr. movimento",
			   "it-IT", "Vendite giornaliere per nr. movimento",
			   "nb-NO", "Daglig salg etter oppføringsnr.",
			   "nl-BE", "Dagelijkse verkoop per postnr",
			   "nl-NL", "Dagelijkse verkoop per postnr",
			   "sv-SE", "Daglig försäljning per transaktionsnummer",
			   "Daily Sales by Entry No"
			)
		isHidden
		lineageTag: c205fd4b-69fd-4719-a144-2eca686bf2a1

	measure 'Daily Sales Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles de venta diarias",
			   "de-DE", "Tägliche Verkaufszahlen",
			   "fr-FR", "Détails ventes quotidiennes",
			   "cs-CZ", "Denní prodej – podrobnosti",
			   "da-DK", "Detaljer om dagligt salg",
			   "de-AT", "Tägliche Verkaufszahlen",
			   "de-CH", "Tägliche Verkaufszahlen",
			   "en-AU", "Daily Sales Details",
			   "en-CA", "Daily Sales Details",
			   "en-GB", "Daily Sales Details",
			   "en-NZ", "Daily Sales Details",
			   "es-MX", "Detalles de venta diarias",
			   "fi-FI", "Päivittäinen myynti – Tiedot",
			   "fr-BE", "Détails ventes quotidiennes",
			   "fr-CA", "Détails ventes quotidiennes",
			   "fr-CH", "Détails ventes quotidiennes",
			   "is-IS", "Upplýsingar um daglega sölu",
			   "it-CH", "Dettagli vendite giornaliere",
			   "it-IT", "Dettagli vendite giornaliere",
			   "nb-NO", "Daglige salgsdetaljer",
			   "nl-BE", "Details van dagelijkse verkoop",
			   "nl-NL", "Details van dagelijkse verkoop",
			   "sv-SE", "Daglig försäljningsinformation",
			   "Daily Sales Details"
			)
		isHidden
		lineageTag: be5e46e2-0648-4c71-80aa-a2703f1f801b

	measure 'Moving Annual Total Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles totales anuales móviles",
			   "de-DE", "Gleitend Jahr Gesamt – Details",
			   "fr-FR", "Détails total annuel mobile",
			   "cs-CZ", "Roční pohyblivý součet – podrobnosti",
			   "da-DK", "Detaljer om glidende årlig total",
			   "de-AT", "Gleitend Jahr Gesamt – Details",
			   "de-CH", "Gleitend Jahr Gesamt – Details",
			   "en-AU", "Moving Annual Total Details",
			   "en-CA", "Moving Annual Total Details",
			   "en-GB", "Moving Annual Total Details",
			   "en-NZ", "Moving Annual Total Details",
			   "es-MX", "Detalles totales anuales móviles",
			   "fi-FI", "Liukuva vuosittainen kokonaissumma – Tiedot",
			   "fr-BE", "Détails total annuel mobile",
			   "fr-CA", "Détails total annuel mobile",
			   "fr-CH", "Détails total annuel mobile",
			   "is-IS", "Upplýsingar um hlaupandi alls yfir árið",
			   "it-CH", "Dettagli totale annuo mobile",
			   "it-IT", "Dettagli totale annuo mobile",
			   "nb-NO", "Detaljer om glidende årssum",
			   "nl-BE", "Details van voortschrijdend jaarlijks totaal",
			   "nl-NL", "Details van voortschrijdend jaarlijks totaal",
			   "sv-SE", "Information om glidande årssumma",
			   "Moving Annual Total Details"
			)
		isHidden
		lineageTag: ef6ce5e9-d9be-490e-a366-5314cd5413bc

	measure 'Period-Over-Period Growth Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles crecimiento periodo tras periodo",
			   "de-DE", "Wachstum im Periodenvergleich – Details",
			   "fr-FR", "Détails croissance d’une période à l’autre",
			   "cs-CZ", "Růst mezi obdobími – podrobnosti",
			   "da-DK", "Detaljer om periode-til-periode vækst",
			   "de-AT", "Wachstum im Periodenvergleich – Details",
			   "de-CH", "Wachstum im Periodenvergleich – Details",
			   "en-AU", "Period-Over-Period Growth Details",
			   "en-CA", "Period-Over-Period Growth Details",
			   "en-GB", "Period-Over-Period Growth Details",
			   "en-NZ", "Period-Over-Period Growth Details",
			   "es-MX", "Detalles crecimiento periodo tras periodo",
			   "fi-FI", "Kasvu kaudesta toiseen – Tiedot",
			   "fr-BE", "Détails croissance d’une période à l’autre",
			   "fr-CA", "Détails croissance d’une période à l’autre",
			   "fr-CH", "Détails croissance d’une période à l’autre",
			   "is-IS", "Upplýsingar um vöxt milli tímabila",
			   "it-CH", "Dettagli crescita su periodi",
			   "it-IT", "Dettagli crescita su periodi",
			   "nb-NO", "Detaljer om vekst periode for periode",
			   "nl-BE", "Details van groei van periode-tot-periode",
			   "nl-NL", "Details van groei van periode-tot-periode",
			   "sv-SE", "Information om tillväxt period-för-period",
			   "Period-Over-Period Growth Details"
			)
		isHidden
		lineageTag: 24eb74c5-7009-49e3-a087-af66e18853f6

	measure 'Month-To-Date Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles mes hasta la fecha",
			   "de-DE", "Monat-bis-heute – Details",
			   "fr-FR", "Détails cumul mensuel jusqu’à ce jour",
			   "cs-CZ", "Od začátku měsíce k dnešnímu dni – podrobnosti",
			   "da-DK", "Detaljer om måned til dato",
			   "de-AT", "Monat-bis-heute – Details",
			   "de-CH", "Monat-bis-heute – Details",
			   "en-AU", "Month-To-Date Details",
			   "en-CA", "Month-To-Date Details",
			   "en-GB", "Month-To-Date Details",
			   "en-NZ", "Month-To-Date Details",
			   "es-MX", "Detalles mes hasta la fecha",
			   "fi-FI", "Kuukausi pvm:ään asti – Tiedot",
			   "fr-BE", "Détails cumul mensuel jusqu’à ce jour",
			   "fr-CA", "Détails cumul mensuel jusqu’à ce jour",
			   "fr-CH", "Détails cumul mensuel jusqu’à ce jour",
			   "is-IS", "Upplýsingar um samanburð milli mánaða",
			   "it-CH", "Dettagli mese in corso",
			   "it-IT", "Dettagli mese in corso",
			   "nb-NO", "Detaljer om hittil denne måneden",
			   "nl-BE", "Details van verkoop van maand-tot-heden",
			   "nl-NL", "Details van verkoop van maand-tot-heden",
			   "sv-SE", "Information om hittills till månad",
			   "Month-To-Date Details"
			)
		isHidden
		lineageTag: 7415e02b-2e2f-4217-832f-f09acf32f5d0

	measure 'Sales by Item Category Over Time Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas por categoría de producto a lo largo del tiempo",
			   "de-DE", "Verkauf nach Artikelkategorie im Zeitverlauf",
			   "fr-FR", "Vente par catégorie d’article dans le temps",
			   "cs-CZ", "Prodeje podle kategorie zboží v průběhu času",
			   "da-DK", "Salgsbeløb efter varekategori over tid",
			   "de-AT", "Verkauf nach Artikelkategorie im Zeitverlauf",
			   "de-CH", "Verkauf nach Artikelkategorie im Zeitverlauf",
			   "en-AU", "Sales by Item Category Over Time",
			   "en-CA", "Sales by Item Category Over Time",
			   "en-GB", "Sales by Item Category Over Time",
			   "en-NZ", "Sales by Item Category Over Time",
			   "es-MX", "Ventas por categoría de producto a lo largo del tiempo",
			   "fi-FI", "Myynti nimikeluokittain ajan kuluessa",
			   "fr-BE", "Vente par catégorie d’article dans le temps",
			   "fr-CA", "Vente par catégorie d’article dans le temps",
			   "fr-CH", "Vente par catégorie d’article dans le temps",
			   "is-IS", "Sala eftir vöruflokkum yfir tíma",
			   "it-CH", "Vendite per categoria articolo nel tempo",
			   "it-IT", "Vendite per categoria articolo nel tempo",
			   "nb-NO", "Salg etter varekategori over tid",
			   "nl-BE", "Verkoop per artikelcategorie in loop van tijd",
			   "nl-NL", "Verkoop per artikelcategorie in loop van tijd",
			   "sv-SE", "Försäljning per artikelkategori över tid",
			   "Sales by Item Category Over Time"
			)
		isHidden
		lineageTag: f0656528-5ec3-4009-814f-407859f0a8c9

	measure 'Sales by Item Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles de ventas por producto",
			   "de-DE", "Verkauf nach Artikeldetails",
			   "fr-FR", "Détails ventes par article",
			   "cs-CZ", "Prodej podle zboží – podrobnosti",
			   "da-DK", "Detaljer om salg efter vare",
			   "de-AT", "Verkauf nach Artikeldetails",
			   "de-CH", "Verkauf nach Artikeldetails",
			   "en-AU", "Sales by Item Details",
			   "en-CA", "Sales by Item Details",
			   "en-GB", "Sales by Item Details",
			   "en-NZ", "Sales by Item Details",
			   "es-MX", "Detalles de ventas por producto",
			   "fi-FI", "Myynti nimikkeittäin – Tiedot",
			   "fr-BE", "Détails ventes par article",
			   "fr-CA", "Détails ventes par article",
			   "fr-CH", "Détails ventes par article",
			   "is-IS", "Sala eftir vöruupplýsingum",
			   "it-CH", "Dettagli vendite per articolo",
			   "it-IT", "Dettagli vendite per articolo",
			   "nb-NO", "Detaljer om salg etter vare",
			   "nl-BE", "Verkopen per artikeldetails",
			   "nl-NL", "Verkopen per artikeldetails",
			   "sv-SE", "Information om försäljning per artikel",
			   "Sales by Item Details"
			)
		isHidden
		lineageTag: d41e2c26-7b28-4f49-ba9a-37dc24cf104e

	measure 'Profitability by Item Category Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Rentabilidad por categoría de producto",
			   "de-DE", "Rentabilität nach Artikelkategorie",
			   "fr-FR", "Rentabilité par catégorie d’article",
			   "cs-CZ", "Ziskovost podle kategorie zboží",
			   "da-DK", "Rentabilitet efter varekategori",
			   "de-AT", "Rentabilität nach Artikelkategorie",
			   "de-CH", "Rentabilität nach Artikelkategorie",
			   "en-AU", "Profitability by Item Category",
			   "en-CA", "Profitability by Item Category",
			   "en-GB", "Profitability by Item Category",
			   "en-NZ", "Profitability by Item Category",
			   "es-MX", "Rentabilidad por categoría de producto",
			   "fi-FI", "Kannattavuus nimikeluokittain",
			   "fr-BE", "Rentabilité par catégorie d’article",
			   "fr-CA", "Rentabilité par catégorie d’article",
			   "fr-CH", "Rentabilité par catégorie d’article",
			   "is-IS", "Arðsemi eftir vöruflokki",
			   "it-CH", "Redditività per categoria articolo",
			   "it-IT", "Redditività per categoria articolo",
			   "nb-NO", "Lønnsomhet etter varekategori",
			   "nl-BE", "Winstgevendheid per artikelcategorie",
			   "nl-NL", "Winstgevendheid per artikelcategorie",
			   "sv-SE", "Lönsamhet per artikelkategori",
			   "Profitability by Item Category"
			)
		isHidden
		lineageTag: cf6f6925-9771-4d56-90d3-fb8e0d50f994

	measure 'Gross Profit Pareto Analysis by Customer Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis de Pareto por cliente de beneficio bruto",
			   "de-DE", "Bruttogewinn-Pareto-Analyse nach Debitor",
			   "fr-FR", "Analyse de Pareto marge brute par client",
			   "cs-CZ", "Paretova analýza hrubého zisku podle zákazníka",
			   "da-DK", "Pareto-bruttoavanceanalyse efter debitor",
			   "de-AT", "Bruttogewinn-Pareto-Analyse nach Debitor",
			   "de-CH", "Bruttogewinn-Pareto-Analyse nach Debitor",
			   "en-AU", "Gross Profit Pareto Analysis by Customer",
			   "en-CA", "Gross Profit Pareto Analysis by Customer",
			   "en-GB", "Gross Profit Pareto Analysis by Customer",
			   "en-NZ", "Gross Profit Pareto Analysis by Customer",
			   "es-MX", "Análisis de Pareto por cliente de beneficio bruto",
			   "fi-FI", "Bruttovoiton Pareto-analyysi asiakkaittain",
			   "fr-BE", "Analyse de Pareto marge brute par client",
			   "fr-CA", "Analyse de Pareto du bénéfice brut par client",
			   "fr-CH", "Analyse de Pareto marge brute par client",
			   "is-IS", "Pareto-greining brúttóhagnaðar eftir viðskiptavini",
			   "it-CH", "Analisi di Pareto del profitto lordo per cliente",
			   "it-IT", "Analisi di Pareto del profitto lordo per cliente",
			   "nb-NO", "Bruttofortjeneste – Pareto-analyse etter kunde",
			   "nl-BE", "Pareto-analyse brutowinst per klant",
			   "nl-NL", "Pareto-analyse brutowinst per klant",
			   "sv-SE", "Bruttovinst – Pareto-diagram per kund",
			   "Gross Profit Pareto Analysis by Customer"
			)
		isHidden
		lineageTag: 8a25e0da-8e90-4999-a7f2-2d49f7356478

	measure 'Sales by Customer Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles de ventas por cliente",
			   "de-DE", "Verkauf nach Debitor – Details",
			   "fr-FR", "Détails vente par client",
			   "cs-CZ", "Prodeje podle zákazníka – podrobnosti",
			   "da-DK", "Detaljer om salg efter debitor",
			   "de-AT", "Verkauf nach Debitor – Details",
			   "de-CH", "Verkauf nach Debitor – Details",
			   "en-AU", "Sales by Customer Details",
			   "en-CA", "Sales by Customer Details",
			   "en-GB", "Sales by Customer Details",
			   "en-NZ", "Sales by Customer Details",
			   "es-MX", "Detalles de ventas por cliente",
			   "fi-FI", "Myynti asiakkaittain – Tiedot",
			   "fr-BE", "Détails vente par client",
			   "fr-CA", "Détails vente par client",
			   "fr-CH", "Détails vente par client",
			   "is-IS", "Upplýsingar um sölu eftir viðskiptavini",
			   "it-CH", "Dettagli vendite per cliente",
			   "it-IT", "Dettagli vendite per cliente",
			   "nb-NO", "Detaljer om salg etter kunde",
			   "nl-BE", "Details van verkoop per klant",
			   "nl-NL", "Details van verkoop per klant",
			   "sv-SE", "Information om försäljning per kund",
			   "Sales by Customer Details"
			)
		isHidden
		lineageTag: 36581b5d-a1b1-4855-a3cc-a52f1f648484

	measure 'Estimated Opportunity Value Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor de oportunidad estimado",
			   "de-DE", "Geschätzter Verkaufschancenwert",
			   "fr-FR", "Valeur opportunité estimée",
			   "cs-CZ", "Odhadované hodnota příležitosti",
			   "da-DK", "Anslået værdi af lead",
			   "de-AT", "Geschätzter Verkaufschancenwert",
			   "de-CH", "Geschätzter Verkaufschancenwert",
			   "en-AU", "Estimated Opportunity Value",
			   "en-CA", "Estimated Opportunity Value",
			   "en-GB", "Estimated Opportunity Value",
			   "en-NZ", "Estimated Opportunity Value",
			   "es-MX", "Valor de oportunidad estimado",
			   "fi-FI", "Arvioitu mahdollisuuden arvo",
			   "fr-BE", "Valeur opportunité estimée",
			   "fr-CA", "Valeur opportunité estimée",
			   "fr-CH", "Valeur opportunité estimée",
			   "is-IS", "Áætlað gildi tækifæris",
			   "it-CH", "Valore opportunità previsto",
			   "it-IT", "Valore opportunità previsto",
			   "nb-NO", "Anslått verdi på salgsmulighet",
			   "nl-BE", "Geschatte opportuniteitwaarde",
			   "nl-NL", "Geschatte verkoopkanswaarde",
			   "sv-SE", "Uppskattat affärsmöjlighetsvärde",
			   "Estimated Opportunity Value"
			)
		isHidden
		lineageTag: cc95bd56-b8b7-40cf-9990-4370abecba10

	measure 'Sales by Salesperson Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles de ventas por vendedor",
			   "de-DE", "Verkauf nach Verkäufer – Details",
			   "fr-FR", "Détails ventes par vendeur",
			   "cs-CZ", "Prodeje podle prodejce – podrobnosti",
			   "da-DK", "Detaljer om salg efter sælger",
			   "de-AT", "Verkauf nach Verkäufer – Details",
			   "de-CH", "Verkauf nach Verkäufer – Details",
			   "en-AU", "Sales by Salesperson Details",
			   "en-CA", "Sales by Salesperson Details",
			   "en-GB", "Sales by Salesperson Details",
			   "en-NZ", "Sales by Salesperson Details",
			   "es-MX", "Detalles de ventas por vendedor",
			   "fi-FI", "Myynti myyjittäin – Tiedot",
			   "fr-BE", "Détails ventes par vendeur",
			   "fr-CA", "Détails des ventes par représentant commercial",
			   "fr-CH", "Détails ventes par vendeur",
			   "is-IS", "Upplýsingar um sölu eftir sölumanni",
			   "it-CH", "Dettagli vendite per venditore",
			   "it-IT", "Dettagli vendite per venditore",
			   "nb-NO", "Detaljer om salg etter selger",
			   "nl-BE", "Details van verkoop per verkoper",
			   "nl-NL", "Details van verkoop per verkoper",
			   "sv-SE", "Information om försäljning per säljare",
			   "Sales by Salesperson Details"
			)
		isHidden
		lineageTag: 4b70c28e-8e3c-4af0-8c64-a852fff35663

	measure 'Profitability by Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Rentabilidad por vendedor",
			   "de-DE", "Rentabilität nach Verkäufer",
			   "fr-FR", "Rentabilité par vendeur",
			   "cs-CZ", "Ziskovost podle prodejce",
			   "da-DK", "Rentabilitet efter sælger",
			   "de-AT", "Rentabilität nach Verkäufer",
			   "de-CH", "Rentabilität nach Verkäufer",
			   "en-AU", "Profitability by Salesperson",
			   "en-CA", "Profitability by Salesperson",
			   "en-GB", "Profitability by Salesperson",
			   "en-NZ", "Profitability by Salesperson",
			   "es-MX", "Rentabilidad por vendedor",
			   "fi-FI", "Kannattavuus myyjittäin",
			   "fr-BE", "Rentabilité par vendeur",
			   "fr-CA", "Rentabilité par représentant commercial",
			   "fr-CH", "Rentabilité par vendeur",
			   "is-IS", "Arðsemi eftir sölumanni",
			   "it-CH", "Redditività per venditore",
			   "it-IT", "Redditività per venditore",
			   "nb-NO", "Lønnsomhet etter selger",
			   "nl-BE", "Winstgevendheid per verkoper",
			   "nl-NL", "Winstgevendheid per verkoper",
			   "sv-SE", "Lönsamhet per säljare",
			   "Profitability by Salesperson"
			)
		isHidden
		lineageTag: 45f87f90-f208-4aa4-afc1-a32fc95fee3d

	measure 'Sales Amount by Customer Location Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe ventas por almacén de cliente",
			   "de-DE", "Verkaufsbetrag nach Debitorelagerort",
			   "fr-FR", "Montant ventes par magasin client",
			   "cs-CZ", "Částka prodeje podle lokace zákazníka",
			   "da-DK", "Salgsbeløb efter debitors placering",
			   "de-AT", "Verkaufsbetrag nach Debitorelagerort",
			   "de-CH", "Verkaufsbetrag nach Debitorelagerort",
			   "en-AU", "Sales Amount by Customer Location",
			   "en-CA", "Sales Amount by Customer Location",
			   "en-GB", "Sales Amount by Customer Location",
			   "en-NZ", "Sales Amount by Customer Location",
			   "es-MX", "Importe ventas por almacén de cliente",
			   "fi-FI", "Myyntisumma asiakkaan sijainnin mukaan",
			   "fr-BE", "Montant ventes par magasin client",
			   "fr-CA", "Montant des ventes par emplacement client",
			   "fr-CH", "Montant ventes par magasin client",
			   "is-IS", "Upphæð sölu eftir staðsetningu viðskiptavinar",
			   "it-CH", "Importo vendite per ubicazione cliente",
			   "it-IT", "Importo vendite per ubicazione cliente",
			   "nb-NO", "Salgsbeløp etter kundelokasjon",
			   "nl-BE", "Verkoopbedrag per klantlocatie",
			   "nl-NL", "Verkoopbedrag per klantlocatie",
			   "sv-SE", "Försäljningsbelopp per kundlagerställe",
			   "Sales Amount by Customer Location"
			)
		isHidden
		lineageTag: 3e002d13-066c-4220-bd82-75122b58582f

	measure 'Sales by Location Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles de ventas por almacén",
			   "de-DE", "Verkauf nach Lagerort – Details",
			   "fr-FR", "Détails ventes par magasin",
			   "cs-CZ", "Prodeje podle lokace – podrobnosti",
			   "da-DK", "Detaljer om salg efter placering",
			   "de-AT", "Verkauf nach Lagerort – Details",
			   "de-CH", "Verkauf nach Lagerort – Details",
			   "en-AU", "Sales by Location Details",
			   "en-CA", "Sales by Location Details",
			   "en-GB", "Sales by Location Details",
			   "en-NZ", "Sales by Location Details",
			   "es-MX", "Detalles de ventas por almacén",
			   "fi-FI", "Myynti sijainneittain – Tiedot",
			   "fr-BE", "Détails ventes par magasin",
			   "fr-CA", "Détails des ventes par emplacement",
			   "fr-CH", "Détails ventes par magasin",
			   "is-IS", "Upplýsingar um sölu eftir staðsetningu",
			   "it-CH", "Dettagli vendite per ubicazione",
			   "it-IT", "Dettagli vendite per ubicazione",
			   "nb-NO", "Detaljer om salg etter lokasjon",
			   "nl-BE", "Details van verkoop per locatie",
			   "nl-NL", "Details van verkoop per locatie",
			   "sv-SE", "Information om försäljning per lagerställe",
			   "Sales by Location Details"
			)
		isHidden
		lineageTag: 7a110838-9fb8-4a6b-b9a5-0cc3ae00b8ef

	measure 'Sales Demographics Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Datos demográficos de ventas",
			   "de-DE", "Verkaufsdemografie",
			   "fr-FR", "Démographie de vente",
			   "cs-CZ", "Demografické údaje prodeje",
			   "da-DK", "Demografiske oplysninger om salg",
			   "de-AT", "Verkaufsdemografie",
			   "de-CH", "Verkaufsdemografie",
			   "en-AU", "Sales Demographics",
			   "en-CA", "Sales Demographics",
			   "en-GB", "Sales Demographics",
			   "en-NZ", "Sales Demographics",
			   "es-MX", "Datos demográficos de ventas",
			   "fi-FI", "Myynnin demografia",
			   "fr-BE", "Démographie de vente",
			   "fr-CA", "Démographie de vente",
			   "fr-CH", "Démographie de vente",
			   "is-IS", "Lýðfræði sölu",
			   "it-CH", "Dati demografici vendite",
			   "it-IT", "Dati demografici vendite",
			   "nb-NO", "Salgsdemografi",
			   "nl-BE", "Demografische verkoopgegevens",
			   "nl-NL", "Demografische verkoopgegevens",
			   "sv-SE", "Försäljningsdemografi",
			   "Sales Demographics"
			)
		isHidden
		lineageTag: 761048c9-f4de-49a3-9886-fbf76b8c9131

	measure 'Sales Metrics by Item Category Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Métricas de ventas por categoría de producto",
			   "de-DE", "Verkaufskennzahlen nach Artikelkategorie",
			   "fr-FR", "Mesures ventes par catégorie d’article",
			   "cs-CZ", "Metriky prodeje podle kategorie zboží",
			   "da-DK", "Salgsmålinger efter varekategori",
			   "de-AT", "Verkaufskennzahlen nach Artikelkategorie",
			   "de-CH", "Verkaufskennzahlen nach Artikelkategorie",
			   "en-AU", "Sales Metrics by Item Category",
			   "en-CA", "Sales Metrics by Item Category",
			   "en-GB", "Sales Metrics by Item Category",
			   "en-NZ", "Sales Metrics by Item Category",
			   "es-MX", "Métricas de ventas por categoría de producto",
			   "fi-FI", "Myyntimittarit nimekeluokittain",
			   "fr-BE", "Mesures ventes par catégorie d’article",
			   "fr-CA", "Mesures ventes par catégorie d’article",
			   "fr-CH", "Mesures ventes par catégorie d’article",
			   "is-IS", "Söluupplýsingar eftir vöruflokkum",
			   "it-CH", "Metriche vendite per categoria articolo",
			   "it-IT", "Metriche vendite per categoria articolo",
			   "nb-NO", "Salgsmåleverdier etter varekategori",
			   "nl-BE", "Verkoopmeetgegevens per artikelcategorie",
			   "nl-NL", "Verkoopmeetgegevens per artikelcategorie",
			   "sv-SE", "Försäljningsmått per artikelkategori",
			   "Sales Metrics by Item Category"
			)
		isHidden
		lineageTag: 079dcc4c-c323-4cd1-a015-b61f5e5f9702

	measure 'Sales by Customer Posting Group Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Grupo contable ventas por cliente",
			   "de-DE", "Verkauf nach Debitorenbuchungsgruppe",
			   "fr-FR", "Ventes par groupe comptabilisation client",
			   "cs-CZ", "Prodej podle účto skupiny zákazníků",
			   "da-DK", "Salg efter debitorbogføringsgruppe",
			   "de-AT", "Verkauf nach Debitorenbuchungsgruppe",
			   "de-CH", "Verkauf nach Debitorenbuchungsgruppe",
			   "en-AU", "Sales by Customer Posting Group",
			   "en-CA", "Sales by Customer Posting Group",
			   "en-GB", "Sales by Customer Posting Group",
			   "en-NZ", "Sales by Customer Posting Group",
			   "es-MX", "Grupo contable ventas por cliente",
			   "fi-FI", "Myynti asiakkaan kirjausryhmän mukaan",
			   "fr-BE", "Ventes par groupe comptabilisation client",
			   "fr-CA", "Ventes par groupe de comptabilisation du client",
			   "fr-CH", "Ventes par groupe comptabilisation client",
			   "is-IS", "Sala eftir bókunarflokki viðskiptavinar",
			   "it-CH", "Vendite per categoria registrazione cliente",
			   "it-IT", "Vendite per categoria registrazione cliente",
			   "nb-NO", "Salg etter kundebokføringsgruppe",
			   "nl-BE", "Verkoop per klantboekingsgroep",
			   "nl-NL", "Verkoop per klantboekingsgroep",
			   "sv-SE", "Försäljning per kundbokföringsmall",
			   "Sales by Customer Posting Group"
			)
		isHidden
		lineageTag: 25ac162b-8ad9-4e63-90b0-7b3780544513

	measure 'Sales by Document Type Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Ventas por tipo de documento",
			   "de-DE", "Verkauf nach Belegart",
			   "fr-FR", "Ventes par type document",
			   "cs-CZ", "Prodej podle typu dokladu",
			   "da-DK", "Salg efter dokumenttype",
			   "de-AT", "Verkauf nach Belegart",
			   "de-CH", "Verkauf nach Belegart",
			   "en-AU", "Sales by Document Type",
			   "en-CA", "Sales by Document Type",
			   "en-GB", "Sales by Document Type",
			   "en-NZ", "Sales by Document Type",
			   "es-MX", "Ventas por tipo de documento",
			   "fi-FI", "Myynti asiakirjatyypeittäin",
			   "fr-BE", "Ventes par type document",
			   "fr-CA", "Ventes par type document",
			   "fr-CH", "Ventes par type document",
			   "is-IS", "Sala eftir skjalagerð",
			   "it-CH", "Vendite per tipo di documento",
			   "it-IT", "Vendite per tipo di documento",
			   "nb-NO", "Salg etter dokumenttype",
			   "nl-BE", "Verkoop per documenttype",
			   "nl-NL", "Verkoop per documenttype",
			   "sv-SE", "Försäljning per dokumenttyp",
			   "Sales by Document Type"
			)
		isHidden
		lineageTag: 16c97c0f-bc32-4883-9ed4-8b62f6fe6588

	measure 'No. of Customers by Location Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "N.º de clientes por almacén",
			   "de-DE", "Anzahl der Debitoren nach Lagerort",
			   "fr-FR", "Nbre de clients par magasin",
			   "cs-CZ", "Počet zákazníků podle lokality",
			   "da-DK", "Antal debitorer efter placering",
			   "de-AT", "Anzahl der Debitoren nach Lagerort",
			   "de-CH", "Anzahl der Debitoren nach Lagerort",
			   "en-AU", "No. of Customers by Location",
			   "en-CA", "No. of Customers by Location",
			   "en-GB", "No. of Customers by Location",
			   "en-NZ", "No. of Customers by Location",
			   "es-MX", "N.º de clientes por almacén",
			   "fi-FI", "Asiakkaiden määrä sijainneittain",
			   "fr-BE", "Nbre de clients par magasin",
			   "fr-CA", "Nombre de clients par emplacement",
			   "fr-CH", "Nbre de clients par magasin",
			   "is-IS", "Fjöldi viðskiptavina eftir staðsetningu",
			   "it-CH", "Nr. di clienti per ubicazione",
			   "it-IT", "Nr. di clienti per ubicazione",
			   "nb-NO", "Antall kunder etter lokasjon",
			   "nl-BE", "Aantal klanten per locatie",
			   "nl-NL", "Aantal klanten per locatie",
			   "sv-SE", "Antal kunder per lagerställe",
			   "No. of Customers by Location"
			)
		isHidden
		lineageTag: ab984096-2d99-4094-b7c6-515faa16008c

	measure 'Sales Decomposition Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Descomposición de ventas",
			   "de-DE", "Verkaufsaufschlüsselung",
			   "fr-FR", "Décomposition des ventes",
			   "cs-CZ", "Dekompozice prodeje",
			   "da-DK", "Nedbrydning af salg",
			   "de-AT", "Verkaufsaufschlüsselung",
			   "de-CH", "Verkaufsaufschlüsselung",
			   "en-AU", "Sales Decomposition",
			   "en-CA", "Sales Decomposition",
			   "en-GB", "Sales Decomposition",
			   "en-NZ", "Sales Decomposition",
			   "es-MX", "Descomposición de ventas",
			   "fi-FI", "Myynnin purkaminen",
			   "fr-BE", "Décomposition des ventes",
			   "fr-CA", "Décomposition des ventes",
			   "fr-CH", "Décomposition des ventes",
			   "is-IS", "Sundurliðun sölu",
			   "it-CH", "Scomposizione vendite",
			   "it-IT", "Scomposizione vendite",
			   "nb-NO", "Nedbryting av salg",
			   "nl-BE", "Uitsplitsing verkoop",
			   "nl-NL", "Uitsplitsing verkoop",
			   "sv-SE", "Försäljningsuppdelning",
			   "Sales Decomposition"
			)
		isHidden
		lineageTag: 6bac4b63-7837-4f0b-954b-071f5a8b2e4d

	measure 'Sales Amount by Item Category Description Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Descripción de importe de ventas por categoría de producto",
			   "de-DE", "Verkaufsbetrag nach Artikelkategorie – Beschreibung",
			   "fr-FR", "Désignation Montant ventes par catégorie d’article",
			   "cs-CZ", "Částka prodeje podle kategorie zboží – popis",
			   "da-DK", "Salgsbeløb efter varekategoribeskrivelse",
			   "de-AT", "Verkaufsbetrag nach Artikelkategorie – Beschreibung",
			   "de-CH", "Verkaufsbetrag nach Artikelkategorie – Beschreibung",
			   "en-AU", "Sales Amount by Item Category Description",
			   "en-CA", "Sales Amount by Item Category Description",
			   "en-GB", "Sales Amount by Item Category Description",
			   "en-NZ", "Sales Amount by Item Category Description",
			   "es-MX", "Descripción de importe de ventas por categoría de producto",
			   "fi-FI", "Myyntisumma nimikeluokittain – Kuvaus",
			   "fr-BE", "Désignation Montant ventes par catégorie d’article",
			   "fr-CA", "Montant des ventes par catégorie d’article",
			   "fr-CH", "Désignation Montant ventes par catégorie d’article",
			   "is-IS", "Lýsing á upphæð sölu eftir vöruflokki",
			   "it-CH", "Importo vendite per descrizione categoria articolo",
			   "it-IT", "Importo vendite per descrizione categoria articolo",
			   "nb-NO", "Beskrivelse av salgsbeløp etter varekategori",
			   "nl-BE", "Verkoopbedrag per omschrijving van artikelcategorie",
			   "nl-NL", "Verkoopbedrag per omschrijving van artikelcategorie",
			   "sv-SE", "Beskrivning av försäljningsbelopp per artikelkategori",
			   "Sales Amount by Item Category Description"
			)
		isHidden
		lineageTag: cce2a2ac-489a-4a63-ae10-731cdeb247a0

	measure 'Sales Quantity by Salesperson Name Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Cantidad de ventas por nombre de vendedor",
			   "de-DE", "Verkaufsmenge nach Verkäufername",
			   "fr-FR", "Quantité ventes par nom de vendeur",
			   "cs-CZ", "Množství prodeje podle jména prodejce",
			   "da-DK", "Antal salg efter sælgers navn",
			   "de-AT", "Verkaufsmenge nach Verkäufername",
			   "de-CH", "Verkaufsmenge nach Verkäufername",
			   "en-AU", "Sales Quantity by Salesperson Name",
			   "en-CA", "Sales Quantity by Salesperson Name",
			   "en-GB", "Sales Quantity by Salesperson Name",
			   "en-NZ", "Sales Quantity by Salesperson Name",
			   "es-MX", "Cantidad de ventas por nombre de vendedor",
			   "fi-FI", "Myyntimäärä myyjän nimen mukaan",
			   "fr-BE", "Quantité ventes par nom de vendeur",
			   "fr-CA", "Quantité vendue par nom de représentant commercial",
			   "fr-CH", "Quantité ventes par nom de vendeur",
			   "is-IS", "Sölumagn eftir nafni sölumanns",
			   "it-CH", "Quantità vendite per nome venditore",
			   "it-IT", "Quantità vendite per nome venditore",
			   "nb-NO", "Salgsantall etter selgernavn",
			   "nl-BE", "Verkoophoeveelheid per naam van verkoper",
			   "nl-NL", "Verkoophoeveelheid per naam van verkoper",
			   "sv-SE", "Försäljningskvantitet per säljares namn",
			   "Sales Quantity by Salesperson Name"
			)
		isHidden
		lineageTag: f9eafac0-0091-44c7-8fc4-0d5b979f645f

	measure 'Key Sales Influencers Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Personas con influencia de ventas clave",
			   "de-DE", "Wichtige Verkaufseinflussfaktoren",
			   "fr-FR", "Influenceurs des ventes clés",
			   "cs-CZ", "Klíčové ovlivňující faktory prodeje",
			   "da-DK", "Vigtige salgsinfluencere",
			   "de-AT", "Wichtige Verkaufseinflussfaktoren",
			   "de-CH", "Wichtige Verkaufseinflussfaktoren",
			   "en-AU", "Key Sales Influencers",
			   "en-CA", "Key Sales Influencers",
			   "en-GB", "Key Sales Influencers",
			   "en-NZ", "Key Sales Influencers",
			   "es-MX", "Personas con influencia de ventas clave",
			   "fi-FI", "Tärkeimmät myynnin vaikuttajat",
			   "fr-BE", "Influenceurs des ventes clés",
			   "fr-CA", "Influenceurs des ventes clés",
			   "fr-CH", "Influenceurs des ventes clés",
			   "is-IS", "Helstu áhrifavaldar sölu",
			   "it-CH", "Fattori chiave che influenzano le vendite",
			   "it-IT", "Fattori chiave che influenzano le vendite",
			   "nb-NO", "Viktige salgspåvirkere",
			   "nl-BE", "Belangrijkste verkoopbeïnvloeders",
			   "nl-NL", "Belangrijkste verkoopbeïnvloeders",
			   "sv-SE", "Viktiga försäljningsinfluerare",
			   "Key Sales Influencers"
			)
		isHidden
		lineageTag: 06ff817c-b50f-4ed8-917f-db4b5e22c9ad

	measure 'Sales Amount by Item Category Code Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de ventas por código de categoría de producto",
			   "de-DE", "Verkaufsbetrag nach Artikelkategoriencode",
			   "fr-FR", "Code montant ventes par catégorie d’article",
			   "cs-CZ", "Částka prodeje podle kódu kategorie zboží",
			   "da-DK", "Salgsbeløb efter varekategorikode",
			   "de-AT", "Verkaufsbetrag nach Artikelkategoriencode",
			   "de-CH", "Verkaufsbetrag nach Artikelkategoriencode",
			   "en-AU", "Sales Amount by Item Category Code",
			   "en-CA", "Sales Amount by Item Category Code",
			   "en-GB", "Sales Amount by Item Category Code",
			   "en-NZ", "Sales Amount by Item Category Code",
			   "es-MX", "Importe de ventas por código de categoría de producto",
			   "fi-FI", "Myyntisumma nimikeluokan koodin mukaan",
			   "fr-BE", "Code montant ventes par catégorie d’article",
			   "fr-CA", "Code montant ventes par catégorie d’article",
			   "fr-CH", "Code montant ventes par catégorie d’article",
			   "is-IS", "Kóði upphæðar sölu eftir vöruflokki",
			   "it-CH", "Importo vendite per codice categoria articolo",
			   "it-IT", "Importo vendite per codice categoria articolo",
			   "nb-NO", "Salgsbeløp etter varekategorikode",
			   "nl-BE", "Verkoopbedrag per artikelcategoriecode",
			   "nl-NL", "Verkoopbedrag per artikelcategoriecode",
			   "sv-SE", "Försäljningsbelopp per artikelkategorikod",
			   "Sales Amount by Item Category Code"
			)
		isHidden
		lineageTag: ad5b8a9e-3af2-4550-9f50-2bb2e147b820

	measure 'Opportunity Overview Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Información general de oportunidad",
			   "de-DE", "Verkaufschancenübersicht",
			   "fr-FR", "Vue d’ensemble de l’opportunité",
			   "cs-CZ", "Přehled příležitostí",
			   "da-DK", "Oversigt over leads",
			   "de-AT", "Verkaufschancenübersicht",
			   "de-CH", "Verkaufschancenübersicht",
			   "en-AU", "Opportunity Overview",
			   "en-CA", "Opportunity Overview",
			   "en-GB", "Opportunity Overview",
			   "en-NZ", "Opportunity Overview",
			   "es-MX", "Información general de oportunidad",
			   "fi-FI", "Mahdollisuudet – Yleiskatsaus",
			   "fr-BE", "Vue d’ensemble de l’opportunité",
			   "fr-CA", "Vue d’ensemble de l’opportunité",
			   "fr-CH", "Vue d’ensemble de l’opportunité",
			   "is-IS", "Yfirlit yfir tækifæri",
			   "it-CH", "Panoramica opportunità",
			   "it-IT", "Panoramica opportunità",
			   "nb-NO", "Oversikt over salgsmulighet",
			   "nl-BE", "Overzicht van opportuniteiten",
			   "nl-NL", "Overzicht van verkoopkansen",
			   "sv-SE", "Översikt över affärsmöjligheten",
			   "Opportunity Overview"
			)
		isHidden
		lineageTag: 3eccc2ac-63b0-47b2-8a23-a9f78a964a5b

	measure 'Opportunity Value by Status Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor de oportunidad por estado",
			   "de-DE", "Verkaufschancenwert nach Status",
			   "fr-FR", "Valeur opportunité par statut",
			   "cs-CZ", "Hodnota příležitosti podle stavu",
			   "da-DK", "Værdi af leads efter status",
			   "de-AT", "Verkaufschancenwert nach Status",
			   "de-CH", "Verkaufschancenwert nach Status",
			   "en-AU", "Opportunity Value by Status",
			   "en-CA", "Opportunity Value by Status",
			   "en-GB", "Opportunity Value by Status",
			   "en-NZ", "Opportunity Value by Status",
			   "es-MX", "Valor de oportunidad por estado",
			   "fi-FI", "Mahdollisuuden arvo tiloittain",
			   "fr-BE", "Valeur opportunité par statut",
			   "fr-CA", "Valeur de l’opportunité par état",
			   "fr-CH", "Valeur opportunité par statut",
			   "is-IS", "Gildi tækifæris eftir stöðu",
			   "it-CH", "Valore opportunità per stato",
			   "it-IT", "Valore opportunità per stato",
			   "nb-NO", "Salgsmulighetsverdi etter status",
			   "nl-BE", "Opportuniteitwaarde per status",
			   "nl-NL", "Verkoopkanswaarde per status",
			   "sv-SE", "Affärsmöjlighetsvärde per status",
			   "Opportunity Value by Status"
			)
		isHidden
		lineageTag: e12db723-d90f-4509-b17e-133f0760a81b

	measure 'Open Opportunities by Sales Cycle Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Oportunidades abiertas por ciclo de ventas",
			   "de-DE", "Offene Verkaufschancen nach Verkaufsprozess",
			   "fr-FR", "Opportunités ouvertes par cycle de vente",
			   "cs-CZ", "Otevřené příležitosti podle prodejního cyklu",
			   "da-DK", "Åbne leads efter salgsproces",
			   "de-AT", "Offene Verkaufschancen nach Verkaufsprozess",
			   "de-CH", "Offene Verkaufschancen nach Verkaufsprozess",
			   "en-AU", "Open Opportunities by Sales Cycle",
			   "en-CA", "Open Opportunities by Sales Cycle",
			   "en-GB", "Open Opportunities by Sales Cycle",
			   "en-NZ", "Open Opportunities by Sales Cycle",
			   "es-MX", "Oportunidades abiertas por ciclo de ventas",
			   "fi-FI", "Avoimet mahdollisuudet myyntisykleittäin",
			   "fr-BE", "Opportunités ouvertes par cycle de vente",
			   "fr-CA", "Opportunités ouvertes par cycle de vente",
			   "fr-CH", "Opportunités ouvertes par cycle de vente",
			   "is-IS", "Opin tækifæri eftir söluferli",
			   "it-CH", "Opportunità aperte per ciclo di vendita",
			   "it-IT", "Opportunità aperte per ciclo di vendita",
			   "nb-NO", "Åpne salgsmuligheter etter salgssyklus",
			   "nl-BE", "Open opportuniteiten per verkoopcyclus",
			   "nl-NL", "Open verkoopkansen per verkoopcyclus",
			   "sv-SE", "Öppna affärsmöjligheter per försäljningscykel",
			   "Open Opportunities by Sales Cycle"
			)
		isHidden
		lineageTag: 09487d3a-fc02-4072-aa64-8903dbcb9f57

	measure 'Open Opportunities by Sales Cycle Stage Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Etapa de oportunidades abiertas por ciclo de ventas",
			   "de-DE", "Offene Verkaufschancen nach Verkaufsprozess-Stufe",
			   "fr-FR", "Opportunités ouvertes par étape cycle de vente",
			   "cs-CZ", "Otevřené příležitosti podle fáze prodejního cyklu",
			   "da-DK", "Åbne leads efter salgsprocesfase",
			   "de-AT", "Offene Verkaufschancen nach Verkaufsprozess-Stufe",
			   "de-CH", "Offene Verkaufschancen nach Verkaufsprozess-Stufe",
			   "en-AU", "Open Opportunities by Sales Cycle Stage",
			   "en-CA", "Open Opportunities by Sales Cycle Stage",
			   "en-GB", "Open Opportunities by Sales Cycle Stage",
			   "en-NZ", "Open Opportunities by Sales Cycle Stage",
			   "es-MX", "Oportunidades abiertas por etapa de ciclo de ventas",
			   "fi-FI", "Avoimet mahdollisuudet myyntisyklin vaiheen mukaan",
			   "fr-BE", "Opportunités ouvertes par étape cycle de vente",
			   "fr-CA", "Opportunités ouvertes par étape du cycle de vente",
			   "fr-CH", "Opportunités ouvertes par étape cycle de vente",
			   "is-IS", "Opin tækifæri eftir stigi söluferlis",
			   "it-CH", "Opportunità aperte per fase ciclo di vendita",
			   "it-IT", "Opportunità aperte per fase ciclo di vendita",
			   "nb-NO", "Åpne salgsmuligheter etter salgssyklusfase",
			   "nl-BE", "Open opportuniteiten per verkoopcyclusfase",
			   "nl-NL", "Open verkoopkansen per verkoopcyclusfase",
			   "sv-SE", "Öppna affärsmöjligheter per stadium i försäljningscykel",
			   "Open Opportunities by Sales Cycle Stage"
			)
		isHidden
		lineageTag: fec02479-9489-41f9-8324-3f29a64a2bfc

	measure 'Estimated Value by Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor estimado por vendedor",
			   "de-DE", "Geschätzter Wert nach Verkäufer",
			   "fr-FR", "Valeur estimée par vendeur",
			   "cs-CZ", "Odhadovaná hodnota podle prodejce",
			   "da-DK", "Anslået værdi efter sælger",
			   "de-AT", "Geschätzter Wert nach Verkäufer",
			   "de-CH", "Geschätzter Wert nach Verkäufer",
			   "en-AU", "Estimated Value by Salesperson",
			   "en-CA", "Estimated Value by Salesperson",
			   "en-GB", "Estimated Value by Salesperson",
			   "en-NZ", "Estimated Value by Salesperson",
			   "es-MX", "Valor estimado por vendedor",
			   "fi-FI", "Arvioitu arvo myyjittäin",
			   "fr-BE", "Valeur estimée par vendeur",
			   "fr-CA", "Valeur estimée par représentant commercial",
			   "fr-CH", "Valeur estimée par vendeur",
			   "is-IS", "Áætlað gildi eftir sölumanni",
			   "it-CH", "Valore previsto per venditore",
			   "it-IT", "Valore previsto per venditore",
			   "nb-NO", "Anslått verdi etter selger",
			   "nl-BE", "Geschatte waarde per verkoper",
			   "nl-NL", "Geschatte waarde per verkoper",
			   "sv-SE", "Uppskattat värde per säljare",
			   "Estimated Value by Salesperson"
			)
		isHidden
		lineageTag: 94d70804-c71a-441f-aa0d-887b6e7dbcfa

	measure 'Estimated Value by Contact Location Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor estimado por almacén de contacto",
			   "de-DE", "Geschätzter Wert nach Kontaktstandort",
			   "fr-FR", "Valeur estimée par magasin du contact",
			   "cs-CZ", "Odhadovaná hodnota podle lokace kontaktu",
			   "da-DK", "Anslået værdi efter kontakts placering",
			   "de-AT", "Geschätzter Wert nach Kontaktstandort",
			   "de-CH", "Geschätzter Wert nach Kontaktstandort",
			   "en-AU", "Estimated Value by Contact Location",
			   "en-CA", "Estimated Value by Contact Location",
			   "en-GB", "Estimated Value by Contact Location",
			   "en-NZ", "Estimated Value by Contact Location",
			   "es-MX", "Valor estimado por almacén de contacto",
			   "fi-FI", "Arvioitu arvo kontaktin sijainnin mukaan",
			   "fr-BE", "Valeur estimée par magasin du contact",
			   "fr-CA", "Valeur estimée par emplacement du contact",
			   "fr-CH", "Valeur estimée par magasin du contact",
			   "is-IS", "Áætlað gildi eftir staðsetningu tengiliðar",
			   "it-CH", "Valore previsto per ubicazione contatto",
			   "it-IT", "Valore previsto per ubicazione contatto",
			   "nb-NO", "Anslått verdi etter kontaktlokasjon",
			   "nl-BE", "Geschatte waarde per contactlocatie",
			   "nl-NL", "Geschatte waarde per contactlocatie",
			   "sv-SE", "Uppskattat värde per kontaktlagerställe",
			   "Estimated Value by Contact Location"
			)
		isHidden
		lineageTag: 80fdaa58-6914-45bb-8a4b-cdbd083f889d

	measure 'Sales Quote Overview Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Información general de oferta de venta",
			   "de-DE", "Verkaufsangebot – Übersicht",
			   "fr-FR", "Vue d’ensemble devis",
			   "cs-CZ", "Přehled prodejní nabídky",
			   "da-DK", "Oversigt over salgstilbud",
			   "de-AT", "Verkaufsangebot – Übersicht",
			   "de-CH", "Verkaufsofferte – Übersicht",
			   "en-AU", "Sales Quote Overview",
			   "en-CA", "Sales Quote Overview",
			   "en-GB", "Sales Quote Overview",
			   "en-NZ", "Sales Quote Overview",
			   "es-MX", "Información general de cotización de venta",
			   "fi-FI", "Myyntitarjous – Yleiskatsaus",
			   "fr-BE", "Vue d’ensemble devis",
			   "fr-CA", "Vue d’ensemble devis",
			   "fr-CH", "Vue d’ensemble devis",
			   "is-IS", "Yfirlit sölutilboðs",
			   "it-CH", "Panoramica offerte di vendita",
			   "it-IT", "Panoramica offerte di vendita",
			   "nb-NO", "Oversikt over tilbud",
			   "nl-BE", "Overzicht van verkoopoffertes",
			   "nl-NL", "Overzicht van verkoopoffertes",
			   "sv-SE", "Översikt över försäljningsoffert",
			   "Sales Quote Overview"
			)
		isHidden
		lineageTag: 2e62a07b-1c8a-4a0c-91f5-e616924327a8

	measure 'Sales Quotes by Customer Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles de ofertas de venta por cliente",
			   "de-DE", "Verkaufsangebote nach Debitor – Details",
			   "fr-FR", "Détails devis par client",
			   "cs-CZ", "Prodejní nabídky podle zákazníka – podrobnosti",
			   "da-DK", "Detaljer om salgstilbud efter debitor",
			   "de-AT", "Verkaufsangebote nach Debitor – Details",
			   "de-CH", "Verkaufsofferten nach Debitor – Details",
			   "en-AU", "Sales Quotes by Customer Details",
			   "en-CA", "Sales Quotes by Customer Details",
			   "en-GB", "Sales Quotes by Customer Details",
			   "en-NZ", "Sales Quotes by Customer Details",
			   "es-MX", "Detalles de cotizaciones de vta. por cliente",
			   "fi-FI", "Myyntitarjous asiakkaittain – Tiedot",
			   "fr-BE", "Détails devis par client",
			   "fr-CA", "Détails devis par client",
			   "fr-CH", "Détails devis par client",
			   "is-IS", "Sölutilboð eftir upplýsingum um viðskiptavin",
			   "it-CH", "Dettagli offerte di vendita per cliente",
			   "it-IT", "Dettagli offerte di vendita per cliente",
			   "nb-NO", "Detaljer om tilbud etter kunde",
			   "nl-BE", "Details van verkoopoffertes per klant",
			   "nl-NL", "Details van verkoopoffertes per klant",
			   "sv-SE", "Information om försäljningsofferter per kund",
			   "Sales Quotes by Customer Details"
			)
		isHidden
		lineageTag: 77d81fdf-392c-41b7-8266-1840a7a85bd2

	measure 'Sales Quote Amount by Salesperson Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de oferta de venta por vendedor",
			   "de-DE", "Verkaufsangebotsbetrag nach Verkäufer",
			   "fr-FR", "Montant devis par vendeur",
			   "cs-CZ", "Částka prodejní nabídky podle prodejce",
			   "da-DK", "Salgstilbudsbeløb efter sælger",
			   "de-AT", "Verkaufsangebotsbetrag nach Verkäufer",
			   "de-CH", "Verkaufsoffertenbetrag nach Verkäufer",
			   "en-AU", "Sales Quote Amount by Salesperson",
			   "en-CA", "Sales Quote Amount by Salesperson",
			   "en-GB", "Sales Quote Amount by Salesperson",
			   "en-NZ", "Sales Quote Amount by Salesperson",
			   "es-MX", "Importe de cotiz. de venta por vendedor",
			   "fi-FI", "Myyntitarjoussumma myyjittäin",
			   "fr-BE", "Montant devis par vendeur",
			   "fr-CA", "Montant du devis par représentant commercial",
			   "fr-CH", "Montant devis par vendeur",
			   "is-IS", "Upphæð sölutilboðs eftir sölumanni",
			   "it-CH", "Importo offerte di vendita per venditore",
			   "it-IT", "Importo offerte di vendita per venditore",
			   "nb-NO", "Tilbudsbeløp etter selger",
			   "nl-BE", "Verkoopoffertebedrag per verkoper",
			   "nl-NL", "Verkoopoffertebedrag per verkoper",
			   "sv-SE", "Försäljningsoffertbelopp per säljare",
			   "Sales Quote Amount by Salesperson"
			)
		isHidden
		lineageTag: c0b9b3f8-6512-4c7b-b984-847f5a7e438e

	measure 'Sales Quote Amount Over Time Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de oferta de venta a lo largo del tiempo",
			   "de-DE", "Verkaufsangebotsbetrag im Zeitverlauf",
			   "fr-FR", "Montant devis dans le temps",
			   "cs-CZ", "Částka prodejní nabídky v průběhu času",
			   "da-DK", "Salgstilbudsbeløb over tid",
			   "de-AT", "Verkaufsangebotsbetrag im Zeitverlauf",
			   "de-CH", "Verkaufsoffertenbetrag im Zeitverlauf",
			   "en-AU", "Sales Quote Amount Over Time",
			   "en-CA", "Sales Quote Amount Over Time",
			   "en-GB", "Sales Quote Amount Over Time",
			   "en-NZ", "Sales Quote Amount Over Time",
			   "es-MX", "Importe de cotiz. de venta a lo largo del tiempo",
			   "fi-FI", "Myyntitarjoussumma ajan kuluessa",
			   "fr-BE", "Montant devis dans le temps",
			   "fr-CA", "Montant devis dans le temps",
			   "fr-CH", "Montant devis dans le temps",
			   "is-IS", "Upphæð sölutilboðs yfir tíma",
			   "it-CH", "Importo offerte di vendita nel tempo",
			   "it-IT", "Importo offerte di vendita nel tempo",
			   "nb-NO", "Tilbudsbeløp over tid",
			   "nl-BE", "Verkoopoffertebedrag in loop van tijd",
			   "nl-NL", "Verkoopoffertebedrag in loop van tijd",
			   "sv-SE", "Försäljningsoffertbelopp över tid",
			   "Sales Quote Amount Over Time"
			)
		isHidden
		lineageTag: d8bc4a45-3207-4520-b87a-6d771dc38d49

	measure 'Sales Quote Amount by Item Category Code Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de oferta de venta por código de categoría de producto",
			   "de-DE", "Verkaufsangebotsbetrag nach Artikelkategoriencode",
			   "fr-FR", "Code montant devis par catégorie d’article",
			   "cs-CZ", "Částka prodejní nabídky podle kódu kategorie zboží",
			   "da-DK", "Salgstilbudsbeløb efter varekategorikode",
			   "de-AT", "Verkaufsangebotsbetrag nach Artikelkategoriencode",
			   "de-CH", "Verkaufsoffertenbetrag nach Artikelkategoriencode",
			   "en-AU", "Sales Quote Amount by Item Category Code",
			   "en-CA", "Sales Quote Amount by Item Category Code",
			   "en-GB", "Sales Quote Amount by Item Category Code",
			   "en-NZ", "Sales Quote Amount by Item Category Code",
			   "es-MX", "Importe de cotiz. de venta por código de categ. de prod.",
			   "fi-FI", "Myyntitarjoussumma nimikeluokan koodin mukaan",
			   "fr-BE", "Code montant devis par catégorie d’article",
			   "fr-CA", "Code montant devis par catégorie d’article",
			   "fr-CH", "Code montant devis par catégorie d’article",
			   "is-IS", "Upphæð sölutilboðs eftir vöruflokkskóða",
			   "it-CH", "Importo offerte di vendita per codice categoria articolo",
			   "it-IT", "Importo offerte di vendita per codice categoria articolo",
			   "nb-NO", "Tilbudsbeløp etter varekategorikode",
			   "nl-BE", "Verkoopoffertebedrag per artikelcategoriecode",
			   "nl-NL", "Verkoopoffertebedrag per artikelcategoriecode",
			   "sv-SE", "Försäljningsoffertbelopp per artikelkategorikod",
			   "Sales Quote Amount by Item Category Code"
			)
		isHidden
		lineageTag: 597dd2e9-22b4-41ae-ba2a-50ed1e237fcc

	measure 'Sales Returns Overview Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Inf. general de devoluciones de ventas",
			   "de-DE", "Retouren – Überblick",
			   "fr-FR", "Vue d’ensemble retours vente",
			   "cs-CZ", "Přehled prodejních vratek",
			   "da-DK", "Oversigt over salgsreturneringer",
			   "de-AT", "Retouren – Überblick",
			   "de-CH", "Retouren – Überblick",
			   "en-AU", "Sales Returns Overview",
			   "en-CA", "Sales Returns Overview",
			   "en-GB", "Sales Returns Overview",
			   "en-NZ", "Sales Returns Overview",
			   "es-MX", "Inf. general de devoluciones de ventas",
			   "fi-FI", "Myyntipalautukset – Yleiskatsaus",
			   "fr-BE", "Vue d’ensemble retours vente",
			   "fr-CA", "Vue d’ensemble retours vente",
			   "fr-CH", "Vue d’ensemble retours vente",
			   "is-IS", "Yfirlit söluvöruskila",
			   "it-CH", "Panoramica resi di vendita",
			   "it-IT", "Panoramica resi di vendita",
			   "nb-NO", "Oversikt over salgsreturer",
			   "nl-BE", "Overzicht verkoopretouren",
			   "nl-NL", "Overzicht verkoopretouren",
			   "sv-SE", "Översikt över försäljningsreturer",
			   "Sales Returns Overview"
			)
		isHidden
		lineageTag: 7a291d56-53d8-48d8-8664-f6679971316d

	measure 'Sales Returns by Customer Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Devoluciones de ventas por cliente",
			   "de-DE", "Retouren nach Debitor",
			   "fr-FR", "Retours vente par client",
			   "cs-CZ", "Prodejní vratky podle zákazníka",
			   "da-DK", "Salgsreturneringer efter debitor",
			   "de-AT", "Retouren nach Debitor",
			   "de-CH", "Retouren nach Debitor",
			   "en-AU", "Sales Returns by Customer",
			   "en-CA", "Sales Returns by Customer",
			   "en-GB", "Sales Returns by Customer",
			   "en-NZ", "Sales Returns by Customer",
			   "es-MX", "Devoluciones de ventas por cliente",
			   "fi-FI", "Myyntipalautukset asiakkaittain",
			   "fr-BE", "Retours vente par client",
			   "fr-CA", "Retours vente par client",
			   "fr-CH", "Retours vente par client",
			   "is-IS", "Söluvöruskil eftir viðskiptavini",
			   "it-CH", "Resi di vendita per cliente",
			   "it-IT", "Resi di vendita per cliente",
			   "nb-NO", "Salgsreturer etter kunde",
			   "nl-BE", "Verkoopretouren per klant",
			   "nl-NL", "Verkoopretouren per klant",
			   "sv-SE", "Försäljningsreturer per kund",
			   "Sales Returns by Customer"
			)
		isHidden
		lineageTag: 41777028-9068-46b8-b8e9-6ab2db56ad71

	measure 'Sales Return Amount by Reason Code Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de devolución de venta por código de auditoría",
			   "de-DE", "Retourenbetrag nach Ursachencode",
			   "fr-FR", "Montant retour vente par code motif",
			   "cs-CZ", "Částka prodejní vratky podle kódu příčiny",
			   "da-DK", "Salgsreturbeløb efter årsagskode",
			   "de-AT", "Retourenbetrag nach Ursachencode",
			   "de-CH", "Retourenbetrag nach Ursachencode",
			   "en-AU", "Sales Return Amount by Reason Code",
			   "en-CA", "Sales Return Amount by Reason Code",
			   "en-GB", "Sales Return Amount by Reason Code",
			   "en-NZ", "Sales Return Amount by Reason Code",
			   "es-MX", "Importe de devolución de venta por código de auditoría",
			   "fi-FI", "Myyntipalautussumma syykoodeittain",
			   "fr-BE", "Montant retour vente par code motif",
			   "fr-CA", "Montant retour vente par code motif",
			   "fr-CH", "Montant retour vente par code motif",
			   "is-IS", "Upphæð söluskila eftir ástæðukóða",
			   "it-CH", "Importo resi di vendita per codice causale",
			   "it-IT", "Importo resi di vendita per codice causale",
			   "nb-NO", "Salgsreturbeløp etter årsaksspor",
			   "nl-BE", "Verkoopretourbedrag per redencode",
			   "nl-NL", "Verkoopretourbedrag per redencode",
			   "sv-SE", "Försäljningsreturbelopp per uppföljningskod",
			   "Sales Return Amount by Reason Code"
			)
		isHidden
		lineageTag: e450f32e-1a7a-4a33-aa00-fab7e3c2d336

	measure 'Sales Return Amount Over Time Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de devolución de venta a lo largo del tiempo",
			   "de-DE", "Retourenbetrag im Zeitverlauf",
			   "fr-FR", "Montant retour vente dans le temps",
			   "cs-CZ", "Částka prodejní vratky v průběhu času",
			   "da-DK", "Salgsretursbeløb over tid",
			   "de-AT", "Retourenbetrag im Zeitverlauf",
			   "de-CH", "Retourenbetrag im Zeitverlauf",
			   "en-AU", "Sales Return Amount Over Time",
			   "en-CA", "Sales Return Amount Over Time",
			   "en-GB", "Sales Return Amount Over Time",
			   "en-NZ", "Sales Return Amount Over Time",
			   "es-MX", "Importe de devolución de venta a lo largo del tiempo",
			   "fi-FI", "Myyntipalautussumma ajan kuluessa",
			   "fr-BE", "Montant retour vente dans le temps",
			   "fr-CA", "Montant retour vente dans le temps",
			   "fr-CH", "Montant retour vente dans le temps",
			   "is-IS", "Upphæð söluskila yfir tíma",
			   "it-CH", "Importo resi di vendita nel tempo",
			   "it-IT", "Importo resi di vendita nel tempo",
			   "nb-NO", "Salgsreturbeløp over tid",
			   "nl-BE", "Verkoopretourbedrag in loop van tijd",
			   "nl-NL", "Verkoopretourbedrag in loop van tijd",
			   "sv-SE", "Försäljningsreturbelopp över tid",
			   "Sales Return Amount Over Time"
			)
		isHidden
		lineageTag: 34bf34f8-962b-46c8-8f20-f59c50a1ed93

	measure 'Sales Return Amount by Item Category Code Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Importe de devolución de venta por código de categoría de producto",
			   "de-DE", "Retourenbetrag nach Artikelkategoriencode",
			   "fr-FR", "Code montant retour vente par catégorie d’article",
			   "cs-CZ", "Částka prodejní vratky podle kódu kategorie zboží",
			   "da-DK", "Salgsreturbeløb efter varekategorikode",
			   "de-AT", "Retourenbetrag nach Artikelkategoriencode",
			   "de-CH", "Retourenbetrag nach Artikelkategoriencode",
			   "en-AU", "Sales Return Amount by Item Category Code",
			   "en-CA", "Sales Return Amount by Item Category Code",
			   "en-GB", "Sales Return Amount by Item Category Code",
			   "en-NZ", "Sales Return Amount by Item Category Code",
			   "es-MX", "Importe de devolución de venta por código de categoría de producto",
			   "fi-FI", "Myyntipalautussumma nimikeluokan koodin mukaan",
			   "fr-BE", "Code montant retour vente par catégorie d’article",
			   "fr-CA", "Code montant retour vente par catégorie d’article",
			   "fr-CH", "Code montant retour vente par catégorie d’article",
			   "is-IS", "Upphæð söluskila eftir vöruflokkskóða",
			   "it-CH", "Importo resi di vendita per codice categoria articolo",
			   "it-IT", "Importo resi di vendita per codice categoria articolo",
			   "nb-NO", "Salgsreturbeløp etter varekategorikode",
			   "nl-BE", "Verkoopretourbedrag per artikelcategoriecode",
			   "nl-NL", "Verkoopretourbedrag per artikelcategoriecode",
			   "sv-SE", "Försäljningsreturbelopp per artikelkategorikod",
			   "Sales Return Amount by Item Category Code"
			)
		isHidden
		lineageTag: 327d2876-de1c-4837-ad72-d738edfcc6f6

	measure 'Sales Opportunity Analysis Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Análisis de oportunidad de venta",
			   "de-DE", "Verkaufschancenanalyse",
			   "fr-FR", "Analyse des opportunités de vente",
			   "cs-CZ", "Analýza prodejních příležitostí",
			   "da-DK", "Analyse af lead",
			   "de-AT", "Verkaufschancenanalyse",
			   "de-CH", "Verkaufschancenanalyse",
			   "en-AU", "Sales Opportunity Analysis",
			   "en-CA", "Sales Opportunity Analysis",
			   "en-GB", "Sales Opportunity Analysis",
			   "en-NZ", "Sales Opportunity Analysis",
			   "es-MX", "Análisis de oportunidad de venta",
			   "fi-FI", "Myyntimahdollisuusanalyysi",
			   "fr-BE", "Analyse des opportunités de vente",
			   "fr-CA", "Analyse des opportunités de vente",
			   "fr-CH", "Analyse des opportunités de vente",
			   "is-IS", "Greining sölutækifæra",
			   "it-CH", "Analisi opportunità vendite",
			   "it-IT", "Analisi opportunità vendite",
			   "nb-NO", "Salgsmulighetsanalyse",
			   "nl-BE", "Verkoopopportuniteitanalyse",
			   "nl-NL", "Verkoopkansanalyse",
			   "sv-SE", "Analys av försäljningsmöjligheter",
			   "Sales Opportunity Analysis"
			)
		isHidden
		lineageTag: 82b6e68e-54a6-4b6c-96cc-1e0cef43d3ea

	measure 'Estimated Value by Opportunity Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Valor estimado por oportunidad",
			   "de-DE", "Geschätzter Wert nach Verkaufschance",
			   "fr-FR", "Valeur estimée par opportunité",
			   "cs-CZ", "Odhadované hodnota podle příležitosti",
			   "da-DK", "Anslået værdi efter leads",
			   "de-AT", "Geschätzter Wert nach Verkaufschance",
			   "de-CH", "Geschätzter Wert nach Verkaufschance",
			   "en-AU", "Estimated Value by Opportunity",
			   "en-CA", "Estimated Value by Opportunity",
			   "en-GB", "Estimated Value by Opportunity",
			   "en-NZ", "Estimated Value by Opportunity",
			   "es-MX", "Valor estimado por oportunidad",
			   "fi-FI", "Arvioitu arvo mahdollisuuksittain",
			   "fr-BE", "Valeur estimée par opportunité",
			   "fr-CA", "Valeur estimée par opportunité",
			   "fr-CH", "Valeur estimée par opportunité",
			   "is-IS", "Metið gildi eftir tækifæri",
			   "it-CH", "Valore previsto per opportunità",
			   "it-IT", "Valore previsto per opportunità",
			   "nb-NO", "Anslått verdi etter salgsmulighet",
			   "nl-BE", "Geschatte waarde per opportuniteit",
			   "nl-NL", "Geschatte waarde per verkoopkans",
			   "sv-SE", "Uppskattat per affärsmöjlighet",
			   "Estimated Value by Opportunity"
			)
		isHidden
		lineageTag: fb7038df-cc22-43e0-b7bc-436b1d19cc55

	measure 'Opportunities by Closed Opportunity Code Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Oportunidades por código de oportunidad cerrado",
			   "de-DE", "Verkaufschancen nach abgeschlossenem Verkaufschancencode",
			   "fr-FR", "Opportunités par code opportunité clôturée",
			   "cs-CZ", "Příležitosti podle kódu uzavřené příležitosti",
			   "da-DK", "Leads efter lukket leadskode",
			   "de-AT", "Verkaufschancen nach abgeschlossenem Verkaufschancencode",
			   "de-CH", "Verkaufschancen nach abgeschlossenem Verkaufschancencode",
			   "en-AU", "Opportunities by Closed Opportunity Code",
			   "en-CA", "Opportunities by Closed Opportunity Code",
			   "en-GB", "Opportunities by Closed Opportunity Code",
			   "en-NZ", "Opportunities by Closed Opportunity Code",
			   "es-MX", "Oportunidades por código de oportunidad cerrado",
			   "fi-FI", "Mahdollisuudet suljetun mahdollisuuden koodin mukaan",
			   "fr-BE", "Opportunités par code opportunité clôturée",
			   "fr-CA", "Opportunités par code d’opportunité fermée",
			   "fr-CH", "Opportunités par code opportunité clôturée",
			   "is-IS", "Tækifæri eftir kóða lokunar tækifæris",
			   "it-CH", "Opportunità per codice opportunità chiuse",
			   "it-IT", "Opportunità per codice opportunità chiuse",
			   "nb-NO", "Salgsmuligheter etter lukket salgsmulighetskode",
			   "nl-BE", "Opportuniteiten per code van gesloten opportuniteit",
			   "nl-NL", "Verkoopkansen per code van gesloten verkoopkans",
			   "sv-SE", "Affärsmöjligheter per kod för avslutade affärsmöjligheter",
			   "Opportunities by Closed Opportunity Code"
			)
		isHidden
		lineageTag: 0f7f69b3-c122-44c0-82bd-7354cbe887d8

	measure 'Opportunities by Salesperson Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles de oportunidad por vendedor",
			   "de-DE", "Verkaufschancen nach Verkäufer – Details",
			   "fr-FR", "Détails opportunités par vendeur",
			   "cs-CZ", "Příležitosti podle prodejce – podrobnosti",
			   "da-DK", "Detaljer om leads efter sælger",
			   "de-AT", "Verkaufschancen nach Verkäufer – Details",
			   "de-CH", "Verkaufschancen nach Verkäufer – Details",
			   "en-AU", "Opportunities by Salesperson Details",
			   "en-CA", "Opportunities by Salesperson Details",
			   "en-GB", "Opportunities by Salesperson Details",
			   "en-NZ", "Opportunities by Salesperson Details",
			   "es-MX", "Detalles de oportunidad por vendedor",
			   "fi-FI", "Mahdollisuudet myyjittäin – Tiedot",
			   "fr-BE", "Détails opportunités par vendeur",
			   "fr-CA", "Détails des opportunités par représentant",
			   "fr-CH", "Détails opportunités par vendeur",
			   "is-IS", "Tækifæri eftir upplýsingum um sölumann",
			   "it-CH", "Dettagli opportunità per venditore",
			   "it-IT", "Dettagli opportunità per venditore",
			   "nb-NO", "Detaljer om salgsmuligheter etter selger",
			   "nl-BE", "Opportuniteiten per details van verkoper",
			   "nl-NL", "Verkoopkansen per details van verkoper",
			   "sv-SE", "Information om affärsmöjligheter per säljare",
			   "Opportunities by Salesperson Details"
			)
		isHidden
		lineageTag: e8ad6ef0-d4fc-447f-8cbf-d7ac595993ea

	measure 'Opportunities by Closed Status Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Oportunidades por estado cerrado",
			   "de-DE", "Verkaufschancen nach abgschlossenem Status",
			   "fr-FR", "Opportunités par statut Clôturé",
			   "da-DK", "Leads efter lukket status",
			   "de-AT", "Verkaufschancen nach abgschlossenem Status",
			   "de-CH", "Verkaufschancen nach abgschlossenem Status",
			   "en-AU", "Opportunities by Closed Status",
			   "en-CA", "Opportunities by Closed Status",
			   "en-GB", "Opportunities by Closed Status",
			   "en-NZ", "Opportunities by Closed Status",
			   "es-MX", "Oportunidades por estado cerrado",
			   "fi-FI", "Mahdollisuudet suljetun tilan mukaan",
			   "fr-BE", "Opportunités par statut Clôturé",
			   "fr-CA", "Opportunités par état fermé",
			   "fr-CH", "Opportunités par statut Clôturé",
			   "is-IS", "Tækifæri eftir lokaðri stöðu",
			   "it-CH", "Opportunità per stato chiuso",
			   "it-IT", "Opportunità per stato chiuso",
			   "nb-NO", "Salgsmuligheter etter lukket status",
			   "nl-BE", "Opportuniteiten per gesloten status",
			   "nl-NL", "Verkoopkansen per gesloten status",
			   "sv-SE", "Affärsmöjligheter per avslutad status",
			   "Opportunities by Closed Status"
			)
		isHidden
		lineageTag: 46e11cca-1450-4670-ba35-c022a1bce8f1

	measure 'Sales Drillthrough Details Label' =
			SWITCH(USERCULTURE(),
			   "es-ES", "Detalles de análisis detallado de ventas",
			   "de-DE", "Verkaufs-Drillthrough – Details",
			   "fr-FR", "Détails extraction ventes",
			   "cs-CZ", "Podrobné procházení prodeje – podrobnosti",
			   "da-DK", "Detaljeudledninger for salg",
			   "de-AT", "Verkaufs-Drillthrough – Details",
			   "de-CH", "Verkaufs-Drillthrough – Details",
			   "en-AU", "Sales Drillthrough Details",
			   "en-CA", "Sales Drillthrough Details",
			   "en-GB", "Sales Drillthrough Details",
			   "en-NZ", "Sales Drillthrough Details",
			   "es-MX", "Detalles de análisis detallado de ventas",
			   "fi-FI", "Myyntiin porautuminen – Tiedot",
			   "fr-BE", "Détails extraction ventes",
			   "fr-CA", "Détails extraction ventes",
			   "fr-CH", "Détails extraction ventes",
			   "is-IS", "Upplýsingar um köfun í sölu",
			   "it-CH", "Dettagli drill-through vendite",
			   "it-IT", "Dettagli drill-through vendite",
			   "nb-NO", "Detaljer om gjennomgang av salg",
			   "nl-BE", "Details van detailanalyse verkoop",
			   "nl-NL", "Details van detailanalyse verkoop",
			   "sv-SE", "Information om detaljerad analys av försäljning",
			   "Sales Drillthrough Details"
			)
		isHidden
		lineageTag: d22fbebe-4ba1-45b7-8118-52834da7e3c6

	measure 'Actual vs Budget Sales Analysis by Item Category Label' = "Actual vs Budget Sales Analysis by Item Category"
		isHidden
		lineageTag: 98b547c2-3f61-4fa6-9e1e-e7962e4c0c5f

	measure 'Adjusted Profit Pareto Analysis by Customer Label' = "Adjusted Profit Pareto Analysis by Customer"
		isHidden
		lineageTag: 32c17c77-58e4-4d72-936c-856bc71f2626

	measure 'Sales Quantity Text Label' = "Sales Quantity Text"
		isHidden
		lineageTag: 05a223bf-bf29-4004-8624-624e53d856ed

	measure 'Sales (LCY) Text Label' = "Sales (LCY)"
		isHidden
		lineageTag: 6b25dfe2-16f4-4f52-9c07-87cd2262e5de

	measure 'Actual vs Budget Over Period Label' = "Actual vs Budget Over Period"
		isHidden
		lineageTag: 909c3081-8559-4a7f-8293-951fb2c2a022

	measure 'Sales Forecasting Label' = "Sales Forecasting"
		isHidden
		lineageTag: af801fcb-282b-4ca1-b6c4-3ce0edf659eb

	measure 'Sales Amount Forecast Label' = "Sales Amount Forecast"
		isHidden
		lineageTag: caa38196-2075-4e46-85bc-4f0203454262

	measure 'Sales Amount by Document Type Label' = "Sales Amount by Document Type"
		isHidden
		lineageTag: 0d0b59f3-8a26-4485-b09f-801d06ede00a

	measure 'Sales by Projects Label' = "Sales by Projects"
		isHidden
		lineageTag: 40905a24-6ea5-447e-934e-b9e072a6bc12

	measure 'Project Sales by Status Label' = "Project Sales by Status"
		isHidden
		lineageTag: 85f5059f-2795-4c8b-9042-8ad2090cf523

	measure 'Project Sales by Type Label' = "Project Sales by Type"
		isHidden
		lineageTag: 29516b9f-7bff-4017-8143-318aa5321a09

	measure 'Project Sales by Project Label' = "Project Sales by Project"
		isHidden
		lineageTag: a23ce41e-789c-461f-936f-cb1b3480ad53

	measure 'Sales by Project Details Label' = "Sales by Project Details"
		isHidden
		lineageTag: f3a7f07e-35c0-440c-890a-5c9ef49a15f0

	measure 'Project Sales by Customer Label' = "Project Sales by Customer"
		isHidden
		lineageTag: 732a6438-7c6f-4614-9766-c9149a774cc0

	measure 'Return Rate (Amount) by Customer Label' = "Return Rate (Amount) by Customer"
		isHidden
		lineageTag: 33b5bd0c-a2c4-49c4-a8ae-5cc71e9b7e20

	measure 'Total Credit (Amount) by Type and No Label' = "Total Credit (Amount) by Type and No"
		isHidden
		lineageTag: 313535a5-6678-4221-b7d3-78fcd32d03be

	measure 'Total Credit (Amount) Over Time Label' = "Total Credit (Amount) Over Time"
		isHidden
		lineageTag: 73545c9e-0722-40e0-b87f-1c01caf2c72a

	measure 'Total Credit (Amount) by Return Reason Code Label' = "Total Credit (Amount) by Return Reason Code"
		isHidden
		lineageTag: e78bdafd-4ea8-462d-b0aa-246c27103e58

	measure 'Sales % by Category Label' = "Sales % by Category"
		isHidden
		lineageTag: 356f4ffa-8df6-4c2a-89fc-37ad354c61b4

	measure 'Sales (LCY) by Dimension  Label' = "Sales (LCY) by Dimension "
		isHidden
		lineageTag: a0858e04-c77a-46f7-96bb-ca6b0a8eaf42

	measure 'Actual vs. Budget Sales (LCY) by Item Label' = "Actual vs. Budget Sales (LCY) by Item"
		isHidden
		lineageTag: 91818d4c-a7ba-4816-880b-7647c4d82c2f

	measure 'Year-To-Date Sales (LCY) Over Time Label' = "Year-To-Date Sales (LCY) Over Time"
		isHidden
		lineageTag: 52e03e74-ad20-4604-9ad1-95991eb93c83

	column unused
		isHidden
		displayFolder: unused
		lineageTag: bda4affe-2b95-4f61-adfd-a051615fc07b
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

