// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.ExpenseAgent;

using Microsoft.Foundation.Attachment;
using System.Utilities;

#pragma warning disable AL0679
codeunit 6913 "No Receipt Declaration Mgt."
#pragma warning restore AL0679
{
    Access = Internal;

    procedure CreateDeclaration(var Expense: Record Expense; Reason: Text; AttestationConfirmed: Boolean)
    var
        ExpenseAgentSetup: Record "Expense Agent Setup";
        DocumentAttachment: Record "Document Attachment";
        TempBlob: Codeunit "Temp Blob";
        ExpenseRecordRef: RecordRef;
        DeclarationInStream: InStream;
        DeclarationOutStream: OutStream;
        FileName: Text[250];
    begin
        Expense.LockTable();
        Expense.Get(Expense."No.");
        Expense.TestField(Status, Expense.Status::Open);
        Expense.TestField("Expense Report No.", '');
        Expense.TestField("Expense User No.");
        Expense.TestField("Expense Date");
        Expense.TestField(Description);
        Expense.TestField(Amount);

        ExpenseAgentSetup.GetRecordOnce();
        if not ExpenseAgentSetup."Allow No Receipt" then
            Error(NoReceiptNotAllowedErr);
        if Reason.Trim() = '' then
            Error(ReasonRequiredErr);
        if not AttestationConfirmed then
            Error(AttestationRequiredErr);
        if HasOriginalReceipt(Expense) then
            Error(OriginalReceiptExistsErr, Expense."No.");

        DeleteExistingDeclaration(Expense);

        Expense."No Receipt Type" := Expense."No Receipt Type"::"Lost Receipt";
        Expense."No Receipt Reason" := CopyStr(Reason.Trim(), 1, MaxStrLen(Expense."No Receipt Reason"));
        Clear(Expense."No Receipt Declaration ID");
        Expense."No Receipt Decl. Current" := false;
        Expense."Compliance Status" := Expense."Compliance Status"::"Non-Compliant";
        Expense."Compliance Reason" := CopyStr(LostReceiptComplianceReasonLbl, 1, MaxStrLen(Expense."Compliance Reason"));
        Expense."No Receipt Generated At" := CurrentDateTime();
        Expense."No Receipt Generated By" := CopyStr(UserId(), 1, MaxStrLen(Expense."No Receipt Generated By"));
        Expense.Modify(true);

        Expense.SetRecFilter();
        ExpenseRecordRef.GetTable(Expense);
        TempBlob.CreateOutStream(DeclarationOutStream);
        if not Report.SaveAs(Report::"No Receipt Declaration", '', ReportFormat::Pdf, DeclarationOutStream, ExpenseRecordRef) then
            Error(DeclarationGenerationFailedErr);

        DocumentAttachment.InitFieldsFromRecRef(ExpenseRecordRef);
        FileName := DocumentAttachment.FindUniqueFileName(StrSubstNo(DeclarationFileNameLbl, Expense."No."), 'pdf');
        TempBlob.CreateInStream(DeclarationInStream);
        DocumentAttachment.SaveAttachmentFromStream(DeclarationInStream, ExpenseRecordRef, FileName);
        DocumentAttachment."No Receipt Declaration" := true;
        DocumentAttachment."System Generated" := true;
        DocumentAttachment.Modify(true);

        Expense.Get(Expense."No.");
        Expense."No Receipt Declaration ID" := DocumentAttachment.SystemId;
        Expense."No Receipt Decl. Current" := true;
        Expense.Modify(true);
        Expense.ApplyRule(false, true);
    end;

    procedure HasOriginalReceipt(Expense: Record Expense): Boolean
    var
        DocumentAttachment: Record "Document Attachment";
    begin
        SetExpenseAttachmentFilters(DocumentAttachment, Expense."No.");
        DocumentAttachment.SetRange("No Receipt Declaration", false);
        exit(not DocumentAttachment.IsEmpty());
    end;

    procedure CancelDeclaration(var Expense: Record Expense)
    begin
        Expense.LockTable();
        Expense.Get(Expense."No.");
        Expense.TestField(Status, Expense.Status::Open);
        Expense.TestField("Expense Report No.", '');

        DeleteExistingDeclaration(Expense);
        Clear(Expense."No Receipt Type");
        Clear(Expense."No Receipt Reason");
        Clear(Expense."No Receipt Declaration ID");
        Expense."No Receipt Decl. Current" := false;
        Clear(Expense."Compliance Status");
        Clear(Expense."Compliance Reason");
        Clear(Expense."No Receipt Generated At");
        Clear(Expense."No Receipt Generated By");
        Expense.Modify(true);
        Expense.ApplyRule(false, true);
    end;

    procedure HasOriginalReceipt(ExpenseReportLine: Record "Expense Report Line"): Boolean
    var
        DocumentAttachment: Record "Document Attachment";
    begin
        DocumentAttachment.SetRange("Document Type", DocumentAttachment."Document Type"::Expense);
        DocumentAttachment.SetRange("Table ID", Database::"Expense Report Line");
        DocumentAttachment.SetRange("No.", ExpenseReportLine."Document No.");
        DocumentAttachment.SetRange("Line No.", ExpenseReportLine."Line No.");
        DocumentAttachment.SetRange("No Receipt Declaration", false);
        exit(not DocumentAttachment.IsEmpty());
    end;

    procedure HasCurrentDeclaration(Expense: Record Expense): Boolean
    var
        DocumentAttachment: Record "Document Attachment";
    begin
        if not Expense."No Receipt Decl. Current" or IsNullGuid(Expense."No Receipt Declaration ID") then
            exit(false);

        if not DocumentAttachment.GetBySystemId(Expense."No Receipt Declaration ID") then
            exit(false);

        exit(
            (DocumentAttachment."Table ID" = Database::Expense) and
            (DocumentAttachment."No." = Expense."No.") and
            DocumentAttachment."No Receipt Declaration" and
            DocumentAttachment."System Generated" and
            DocumentAttachment.HasContent());
    end;

    procedure HasDeclaration(ExpenseReportLine: Record "Expense Report Line"): Boolean
    var
        DocumentAttachment: Record "Document Attachment";
    begin
        DocumentAttachment.SetRange("Document Type", DocumentAttachment."Document Type"::Expense);
        DocumentAttachment.SetRange("Table ID", Database::"Expense Report Line");
        DocumentAttachment.SetRange("No.", ExpenseReportLine."Document No.");
        DocumentAttachment.SetRange("Line No.", ExpenseReportLine."Line No.");
        DocumentAttachment.SetRange("No Receipt Declaration", true);
        DocumentAttachment.SetRange("System Generated", true);
        if not DocumentAttachment.FindFirst() then
            exit(false);

        exit(DocumentAttachment.HasContent());
    end;

    procedure MarkDeclarationOutdated(var Expense: Record Expense)
    begin
        if Expense."No Receipt Type" = Expense."No Receipt Type"::" " then
            exit;

        Expense."No Receipt Decl. Current" := false;
    end;

    local procedure DeleteExistingDeclaration(Expense: Record Expense)
    var
        DocumentAttachment: Record "Document Attachment";
    begin
        if IsNullGuid(Expense."No Receipt Declaration ID") then
            exit;

        if DocumentAttachment.GetBySystemId(Expense."No Receipt Declaration ID") then
            DocumentAttachment.Delete(true);
    end;

    local procedure SetExpenseAttachmentFilters(var DocumentAttachment: Record "Document Attachment"; ExpenseNo: Code[20])
    begin
        DocumentAttachment.SetRange("Document Type", DocumentAttachment."Document Type"::Expense);
        DocumentAttachment.SetRange("Table ID", Database::Expense);
        DocumentAttachment.SetRange("No.", ExpenseNo);
        DocumentAttachment.SetRange("Line No.", 0);
    end;

    var
        NoReceiptNotAllowedErr: Label 'No receipt declarations are not allowed by the current expense policy.';
        ReasonRequiredErr: Label 'Enter the reason the original receipt is unavailable.';
        AttestationRequiredErr: Label 'Confirm the declaration before creating the no receipt document.';
        OriginalReceiptExistsErr: Label 'Expense %1 already has an original receipt.', Comment = '%1 = Expense No.';
        DeclarationGenerationFailedErr: Label 'The no receipt declaration could not be generated.';
        LostReceiptComplianceReasonLbl: Label 'Original receipt unavailable; a no receipt declaration was submitted.';
        DeclarationFileNameLbl: Label 'NO-RECEIPT-DECLARATION-%1', Comment = '%1 = Expense No.';
}
