codeunit 135161 "Cloud Mig Country Tables"
{
    procedure GetTablesThatShouldBeCloudMigrated(var ListOfTablesToMigrate: List of [Integer])
    begin
        ListOfTablesToMigrate.Add(Database::"Account Identifier");
        ListOfTablesToMigrate.Add(Database::"ACH Cecoban Detail");
        ListOfTablesToMigrate.Add(Database::"ACH Cecoban Footer");
        ListOfTablesToMigrate.Add(Database::"ACH Cecoban Header");
        ListOfTablesToMigrate.Add(Database::"ACH RB Detail");
        ListOfTablesToMigrate.Add(Database::"ACH RB Footer");
        ListOfTablesToMigrate.Add(Database::"ACH RB Header");
        ListOfTablesToMigrate.Add(Database::"ACH US Detail");
        ListOfTablesToMigrate.Add(Database::"ACH US Footer");
        ListOfTablesToMigrate.Add(Database::"ACH US Header");
        ListOfTablesToMigrate.Add(Database::"B10 Adjustment");
        ListOfTablesToMigrate.Add(Database::"Bank Comment Line");
        ListOfTablesToMigrate.Add(Database::"CFDI Cancellation Reason");
        ListOfTablesToMigrate.Add(Database::"CFDI Documents");
        ListOfTablesToMigrate.Add(Database::"CFDI Export Code");
        ListOfTablesToMigrate.Add(Database::"CFDI Relation Document");
        ListOfTablesToMigrate.Add(Database::"CFDI Transport Operator");
        ListOfTablesToMigrate.Add(Database::"Credit Manager Cue");
        ListOfTablesToMigrate.Add(Database::"Data Dictionary Info");
        ListOfTablesToMigrate.Add(Database::"Data Type Buffer NA");
        ListOfTablesToMigrate.Add(Database::"Document Header");
        ListOfTablesToMigrate.Add(Database::"Document Line");
        ListOfTablesToMigrate.Add(Database::"EFT Export Workset");
        ListOfTablesToMigrate.Add(Database::"EFT Export");
        ListOfTablesToMigrate.Add(Database::"GIFI Code");
#if not CLEANSCHEMA28
        ListOfTablesToMigrate.Add(10016); //Database::"IRS 1099 Adjustment"
        ListOfTablesToMigrate.Add(10010); //Database::"IRS 1099 Form-Box"
#endif
        ListOfTablesToMigrate.Add(Database::"Item Location Variant Buffer");
        ListOfTablesToMigrate.Add(Database::"MX Electronic Invoicing Setup");
        ListOfTablesToMigrate.Add(Database::"PAC Web Service Detail");
        ListOfTablesToMigrate.Add(Database::"PAC Web Service");
        ListOfTablesToMigrate.Add(Database::"Posted Bank Rec. Header");
        ListOfTablesToMigrate.Add(Database::"Posted Bank Rec. Line");
        ListOfTablesToMigrate.Add(Database::"Posted Deposit Header");
        ListOfTablesToMigrate.Add(Database::"Posted Deposit Line");
        ListOfTablesToMigrate.Add(Database::"Sales Tax Amount Difference");
        ListOfTablesToMigrate.Add(Database::"Sales Tax Amount Line");
        ListOfTablesToMigrate.Add(Database::"Sales Tax Setup Wizard");
        ListOfTablesToMigrate.Add(Database::"SAT Account Code");
        ListOfTablesToMigrate.Add(Database::"SAT Payment Method Code");
        ListOfTablesToMigrate.Add(Database::"Vendor Location");
        ListOfTablesToMigrate.Add(Database::"Account Identifier");
        ListOfTablesToMigrate.Add(Database::"ACH Cecoban Detail");
        ListOfTablesToMigrate.Add(Database::"ACH Cecoban Footer");
        ListOfTablesToMigrate.Add(Database::"ACH Cecoban Header");
        ListOfTablesToMigrate.Add(Database::"ACH RB Detail");
        ListOfTablesToMigrate.Add(Database::"ACH RB Footer");
        ListOfTablesToMigrate.Add(Database::"ACH RB Header");
        ListOfTablesToMigrate.Add(Database::"ACH US Detail");
        ListOfTablesToMigrate.Add(Database::"ACH US Footer");
        ListOfTablesToMigrate.Add(Database::"ACH US Header");
        ListOfTablesToMigrate.Add(Database::"B10 Adjustment");
        ListOfTablesToMigrate.Add(Database::"Bank Comment Line");
        ListOfTablesToMigrate.Add(Database::"CFDI Cancellation Reason");
        ListOfTablesToMigrate.Add(Database::"CFDI Documents");
        ListOfTablesToMigrate.Add(Database::"CFDI Export Code");
        ListOfTablesToMigrate.Add(Database::"CFDI Subject to Tax");
        ListOfTablesToMigrate.Add(Database::"CFDI Relation Document");
        ListOfTablesToMigrate.Add(Database::"CFDI Transport Operator");
        ListOfTablesToMigrate.Add(Database::"Credit Manager Cue");
        ListOfTablesToMigrate.Add(Database::"Data Dictionary Info");
        ListOfTablesToMigrate.Add(Database::"Data Type Buffer NA");
        ListOfTablesToMigrate.Add(Database::"Document Header");
        ListOfTablesToMigrate.Add(Database::"Document Line");
        ListOfTablesToMigrate.Add(Database::"EFT Export Workset");
        ListOfTablesToMigrate.Add(Database::"EFT Export");
        ListOfTablesToMigrate.Add(Database::"GIFI Code");
        ListOfTablesToMigrate.Add(Database::"Item Location Variant Buffer");
        ListOfTablesToMigrate.Add(Database::"MX Electronic Invoicing Setup");
        ListOfTablesToMigrate.Add(Database::"PAC Web Service Detail");
        ListOfTablesToMigrate.Add(Database::"PAC Web Service");
        ListOfTablesToMigrate.Add(Database::"Posted Bank Rec. Header");
        ListOfTablesToMigrate.Add(Database::"Posted Bank Rec. Line");
        ListOfTablesToMigrate.Add(Database::"Posted Deposit Header");
        ListOfTablesToMigrate.Add(Database::"Posted Deposit Line");
        ListOfTablesToMigrate.Add(Database::"Sales Tax Amount Difference");
        ListOfTablesToMigrate.Add(Database::"Sales Tax Amount Line");
        ListOfTablesToMigrate.Add(Database::"Sales Tax Setup Wizard");
        ListOfTablesToMigrate.Add(Database::"SAT Account Code");
        ListOfTablesToMigrate.Add(Database::"SAT Payment Method Code");
        ListOfTablesToMigrate.Add(Database::"Vendor Location");
        ListOfTablesToMigrate.Add(Database::"SAT Classification");
        ListOfTablesToMigrate.Add(Database::"SAT Country Code");
        ListOfTablesToMigrate.Add(Database::"SAT Address");
        ListOfTablesToMigrate.Add(Database::"SAT Federal Motor Transport");
        ListOfTablesToMigrate.Add(Database::"SAT Hazardous Material");
        ListOfTablesToMigrate.Add(Database::"SAT Locality");
        ListOfTablesToMigrate.Add(Database::"SAT Municipality");
        ListOfTablesToMigrate.Add(Database::"SAT MX Resources");
        ListOfTablesToMigrate.Add(Database::"SAT Packaging Type");
        ListOfTablesToMigrate.Add(Database::"SAT Payment Method");
        ListOfTablesToMigrate.Add(Database::"SAT Payment Term");
        ListOfTablesToMigrate.Add(Database::"SAT Permission Type");
        ListOfTablesToMigrate.Add(Database::"SAT Relationship Type");
        ListOfTablesToMigrate.Add(Database::"SAT State");
        ListOfTablesToMigrate.Add(Database::"SAT Suburb");
        ListOfTablesToMigrate.Add(Database::"SAT Tax Scheme");
        ListOfTablesToMigrate.Add(Database::"SAT Trailer Type");
        ListOfTablesToMigrate.Add(Database::"SAT Unit of Measure");
        ListOfTablesToMigrate.Add(Database::"SAT Use Code");
        ListOfTablesToMigrate.Add(Database::"SAT Weight Unit of Measure");
        ListOfTablesToMigrate.Add(Database::"SAT International Trade Term");
        ListOfTablesToMigrate.Add(Database::"SAT Customs Unit");
        ListOfTablesToMigrate.Add(Database::"SAT Transfer Reason");
        ListOfTablesToMigrate.Add(Database::"SAT Material Type");
        ListOfTablesToMigrate.Add(Database::"SAT Customs Regime");
        ListOfTablesToMigrate.Add(Database::"SAT Customs Document Type");
    end;
}
