name: 'PowerShell'

on:
  push:
    branches: [ "main", "releases/*" ]
    paths: ["**.ps1", "**.psm1", "**.psd1", ".github/workflows/powershell.yaml" ]
  pull_request:
    branches: [ "main", "releases/*" ]
    paths: ["**.ps1", "**.psm1", "**.psd1", ".github/workflows/powershell.yaml" ]

permissions:
  contents: read

jobs:
  PSScriptAnalyzer:
    # https://github.com/microsoft/psscriptanalyzer-action
    # For more information on PSScriptAnalyzer in general, see
    # https://github.com/PowerShell/PSScriptAnalyzer
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f # v1.1
        with:
          path: .\
          recurse: true
          excludeRule: '"PSAvoidUsingInvokeExpression", "PSUseShouldProcessForStateChangingFunctions", "PSAvoidUsingWriteHost", "PSAvoidUsingCmdletAliases", "PSUseSingularNouns", "PSUseApprovedVerbs"'
          output: results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@3cf0a529d8434171b6af190714e8d5b7abb83927 # v3.30.8
        with:
          sarif_file: results.sarif

  RunTests:
    name: Run PS Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run PS Tests
        run: |
          . (Join-Path "." "build/scripts/tests/runTests.ps1")
