name: Pull request Labeler
on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write
  issues: write

defaults:
  run:
    shell: pwsh

jobs:
  Label:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'microsoft'
    steps:
      - name: Label pull request
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
            repo-token: '${{ secrets.GITHUB_TOKEN }}'
            sync-labels: true

      - name: Label community contribution
        if: github.event.pull_request.head.repo.full_name != github.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels  -f "labels[]=From Fork" -H "Accept: application/vnd.github.v3+json" -H "X-GitHub-Api-Version: 2022-11-28"
