name: Scorecard analysis
on:
  workflow_dispatch:
  schedule:
    # Weekly on Monday at 08:00 UTC
    - cron: "0 8 * * 1"

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    if: github.repository_owner == 'microsoft'
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed for Code scanning upload
      id-token: write # Needed for GitHub OIDC token if publish_results is true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@5d3eb98e4a780bfe1a53f57fbdc278ea5da1274b # v3.30.8
        with:
          sarif_file: results.sarif
