name: 'Troubleshooting'

on:
  workflow_dispatch:
    inputs:
      displayNameOfSecrets:
        description: Display the name (not the value) of secrets available to the repository
        type: boolean
        default: false

permissions:
  actions: read
  contents: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true

      - name: Troubleshooting
        uses: microsoft/AL-Go/Actions/Troubleshooting@b97c03d40c6f3d32a1e12a54a316c9a0d68c6261
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          displayNameOfSecrets: ${{ github.event.inputs.displayNameOfSecrets }}
