name: 'Troubleshooting'

on:
  workflow_dispatch:
    inputs:
      displayNameOfSecrets:
        description: Display the name (not the value) of secrets available to the repository
        type: boolean
        default: false

permissions:
  actions: read
  contents: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          lfs: true

      - name: Troubleshooting
        uses: microsoft/AL-Go/Actions/Troubleshooting@17d656a4fde5f320c4496f80198ce5269f0e296e
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          displayNameOfSecrets: ${{ github.event.inputs.displayNameOfSecrets }}
