name: 'Verify App Changes'

on:
  pull_request:
    branches: [ 'main', 'releases/*']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  VerifyAppChanges:
    runs-on: windows-latest
    name: Verify App Changes
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.sha }}

      - uses: microsoft/BCApps/.github/actions/TestPreprocessorSymbols@main

      - uses: microsoft/BCApps/.github/actions/TestObjectIdsAndManifests@main
